#!/usr/bin/env python3
"""Validate and document Arauna's staged quality-of-life package."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REPORT = ROOT / "docs/arauna/ARAUNA_QOL_AUDIT.md"


class AuditError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AuditError(message)


def macro(path: str, name: str) -> str:
    text = (ROOT / path).read_text(encoding="utf-8")
    match = re.search(rf"^#define\s+{re.escape(name)}\s+([^\s/]+)", text, flags=re.MULTILINE)
    require(match is not None, f"missing config {name}")
    return match.group(1)


def render() -> str:
    return """# Arauna quality-of-life audit

This report is generated by `tools/arauna/audit_arauna_qol.py`.
Arauna introduces convenience in stages so testing can still reveal real progression and balance problems.

## Foundation package — active now

| Feature | State | Balance effect |
|---|---|---|
| Running indoors | Active | Navigation only |
| Faster HP and EXP bars | Active | Animation time only |
| Bag sorting | Active | Navigation only |
| Repel/lure renewal menu | Active | Removes repeated menuing |
| Reusable TMs | Active | Encourages team experimentation without granting new moves |
| IV/EV grades in Summary | Active | Reveals existing data; exact values remain hidden |
| Alphabetical move-relearner lists | Active | Navigation only |
| Pre-evolution moves in the relearner | Active | Evolution cannot permanently delete family options |
| Rename from Summary | Active | Cosmetic convenience |

Reusable TMs do not change which Fakemon can learn a move. Arauna's 386-species compatibility overlay remains
the authority, and field HMs still obey story progression.

## Vertical-slice package — after the second badge is playable

The next QoL pass should be tested together with the opening campaign rather than enabled blindly:

- optional party-wide EXP Share with a visible toggle;
- reliable DexNav or habitat search, only after the regional-Dex crash path is fully retested;
- clearly placed Move Reminder, nature and ability services;
- explicit level-target messages at story milestones;
- healing immediately before long mandatory gauntlets;
- early access to common evolution items without giving late combat items early.

## World package — after maps and story gates are stable

- Fly from the PokéNav or another fast-travel interface;
- repeatable trainer battles and optional high-difficulty rematches;
- late-game IV correction and EV reset tools;
- bulk item services and improved capture supplies;
- optional follower support only after its sprite and save-memory cost is measured.

## Deliberately deferred

DexNav search-level storage, first-time item-description storage, portable PC access and universal move-service
flags remain disabled. Some alter the save layout; others can hide pacing, healing or resource problems during
development. They require a clean-save migration decision and a complete vertical-slice test first.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify the committed report without rewriting it")
    args = parser.parse_args()

    active = {
        ("include/config/item.h", "I_REUSABLE_TMS"): "TRUE",
        ("include/config/item.h", "I_REPEL_LURE_MENU"): "TRUE",
        ("include/config/overworld.h", "OW_RUNNING_INDOORS"): "GEN_LATEST",
        ("include/config/overworld.h", "OW_CHOOSE_FROM_PC_AND_PARTY"): "TRUE",
        ("include/config/summary_screen.h", "P_SUMMARY_SCREEN_IV_EV_INFO"): "TRUE",
        ("include/config/summary_screen.h", "P_SUMMARY_SCREEN_IV_EV_VALUES"): "FALSE",
        ("include/config/summary_screen.h", "P_SORT_MOVES"): "TRUE",
        ("include/config/summary_screen.h", "P_PRE_EVO_MOVES"): "TRUE",
        ("include/config/summary_screen.h", "P_SUMMARY_SCREEN_RENAME"): "TRUE",
        ("include/config/battle.h", "B_FAST_HP_DRAIN"): "TRUE",
        ("include/config/battle.h", "B_FAST_EXP_GROW"): "TRUE",
    }
    for (path, name), expected in active.items():
        value = macro(path, name)
        require(value == expected, f"{name} must be {expected}, found {value}")

    deferred = {
        ("include/config/item.h", "I_EXP_SHARE_FLAG"): "0",
        ("include/config/dexnav.h", "DEXNAV_ENABLED"): "FALSE",
        ("include/config/dexnav.h", "USE_DEXNAV_SEARCH_LEVELS"): "FALSE",
        ("include/config/overworld.h", "OW_SHOW_ITEM_DESCRIPTIONS"): "OW_ITEM_DESCRIPTIONS_OFF",
        ("include/config/overworld.h", "OW_FLAG_POKE_RIDER"): "0",
        ("include/config/overworld.h", "OW_FOLLOWERS_ENABLED"): "FALSE",
        ("include/config/summary_screen.h", "P_ENABLE_MOVE_RELEARNERS"): "FALSE",
        ("include/config/summary_screen.h", "P_TM_MOVES_RELEARNER"): "FALSE",
        ("include/config/summary_screen.h", "P_ENABLE_ALL_TM_MOVES"): "FALSE",
    }
    for (path, name), expected in deferred.items():
        value = macro(path, name)
        require(value == expected, f"deferred {name} must remain {expected}, found {value}")

    item_menu = (ROOT / "src/item_menu.c").read_text(encoding="utf-8")
    require("ItemMenu_SortByName" in item_menu and "ItemMenu_SortByType" in item_menu,
            "bag sorting implementation is missing")

    report = render()
    if args.check:
        require(REPORT.is_file(), "QoL audit report is missing")
        require(REPORT.read_text(encoding="utf-8") == report,
                "QoL audit report is stale; regenerate it")
    else:
        REPORT.write_text(report, encoding="utf-8")
    print("Arauna QoL audit passed: 11 safe configs active, 9 progression/save-sensitive configs deferred")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, AuditError) as exc:
        print(f"Arauna QoL audit failed: {exc}")
        raise SystemExit(1)
