#!/usr/bin/env python3
"""Validate and document Arauna's fair difficulty framework."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REPORT = ROOT / "docs/arauna/ARAUNA_DIFFICULTY_AUDIT.md"

SINGLE_BOSSES = (
    "TRAINER_ROXANNE_1",
    "TRAINER_BRAWLY_1",
    "TRAINER_WATTSON_1",
    "TRAINER_FLANNERY_1",
    "TRAINER_NORMAN_1",
    "TRAINER_WINONA_1",
    "TRAINER_JUAN_1",
    "TRAINER_SIDNEY",
    "TRAINER_PHOEBE",
    "TRAINER_GLACIA",
    "TRAINER_DRAKE",
    "TRAINER_WALLACE",
)
DOUBLE_BOSSES = ("TRAINER_TATE_AND_LIZA_1",)
EXPECTED_CAPS = (
    ("Before badge 1", 15),
    ("Before badge 2", 19),
    ("Before badge 3", 24),
    ("Before badge 4", 29),
    ("Before badge 5", 31),
    ("Before badge 6", 33),
    ("Before badge 7", 42),
    ("Before badge 8", 46),
    ("Pokémon League", 58),
)


class AuditError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AuditError(message)


def trainer_blocks(text: str) -> dict[str, str]:
    matches = list(re.finditer(r"^=== (TRAINER_[A-Z0-9_]+) ===$", text, flags=re.MULTILINE))
    blocks = {}
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        blocks[match.group(1)] = text[match.start():end].rstrip()
    return blocks


def party_chunks(block: str) -> list[str]:
    chunks = [chunk.strip() for chunk in re.split(r"\n\s*\n", block) if chunk.strip()]
    require(chunks and chunks[0].startswith("=== TRAINER_"), "malformed trainer block")
    return chunks[1:]


def describe_boss(trainer_id: str, block: str, expected_ai: str) -> dict[str, str]:
    ai = re.search(r"^AI:\s*(.+)$", block, flags=re.MULTILINE)
    require(ai is not None, f"{trainer_id} has no AI tier")
    require(ai.group(1).strip() == expected_ai,
            f"{trainer_id} must use '{expected_ai}'")

    party = party_chunks(block)
    require(3 <= len(party) <= 6,
            f"{trainer_id} must have a readable 3-6 member boss party")
    levels = [int(value) for value in re.findall(r"^Level:\s*(\d+)$", block, flags=re.MULTILINE)]
    require(len(levels) == len(party), f"{trainer_id} has missing party levels")
    held_items = sum(" @ " in chunk.splitlines()[0] for chunk in party)
    require(held_items >= 1, f"{trainer_id} must telegraph an ace with a held item")
    require(" @ " in party[-1].splitlines()[0], f"{trainer_id}'s ace must be last and hold an item")
    return {
        "trainer": trainer_id.removeprefix("TRAINER_").replace("_1", "").replace("_", " ").title(),
        "ai": ai.group(1).strip(),
        "party": str(len(party)),
        "levels": f"{min(levels)}-{max(levels)}" if min(levels) != max(levels) else str(min(levels)),
        "held": str(held_items),
    }


def render(rows: list[dict[str, str]]) -> str:
    lines = [
        "# Arauna difficulty audit",
        "",
        "This report is generated by `tools/arauna/audit_arauna_difficulty.py`.",
        "The framework borrows Emerald Imperium's use of level caps, curated bosses and stronger AI,",
        "but Arauna's first pass is intentionally less punitive: caps are soft, the player keeps Bag access,",
        "battle style is not forced to Set, and boss AI cannot read the player's complete moves, items or abilities.",
        "",
        "## Soft level targets",
        "",
        "| Milestone | Target level |",
        "|---|---:|",
    ]
    lines.extend(f"| {label} | {level} |" for label, level in EXPECTED_CAPS)
    lines.extend((
        "",
        "A Pokémon at or above the target still gains experience, but at a reduced rate. This discourages",
        "brute-force overlevelling without trapping a player who wants to continue the story.",
        "",
        "## Main campaign bosses",
        "",
        "| Boss | AI tier | Party | Levels | Held items |",
        "|---|---|---:|---:|---:|",
    ))
    for row in rows:
        lines.append(f"| {row['trainer']} | {row['ai']} | {row['party']} | {row['levels']} | {row['held']} |")
    lines.extend((
        "",
        "Bosses preserve the current team data in this checkpoint. Their final species, moves and item synergy",
        "will be curated after the story order and biome encounter curve are locked.",
        "",
        "## Fair-play guardrails",
        "",
        "- ordinary trainers remain simpler and faster than bosses;",
        "- bosses understand HP, STAB, status moves, switching and their visible win condition;",
        "- boss AI does not use omniscience, full move prediction or knowledge of the player's unseen party data;",
        "- every principal boss has a visible ace in the last party slot with a held item;",
        "- no ROM build is required for this data checkpoint.",
        "",
    ))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify the committed report without rewriting it")
    args = parser.parse_args()

    caps = (ROOT / "include/config/caps.h").read_text(encoding="utf-8")
    cap_source = (ROOT / "src/caps.c").read_text(encoding="utf-8")
    ai_source = (ROOT / "include/constants/battle_ai.h").read_text(encoding="utf-8")
    trainers = (ROOT / "src/data/trainers.party").read_text(encoding="utf-8")

    require("#define B_EXP_CAP_TYPE                  EXP_CAP_SOFT" in caps,
            "Arauna must use soft experience caps")
    require("#define B_LEVEL_CAP_TYPE                LEVEL_CAP_FLAG_LIST" in caps,
            "Arauna must derive caps from story milestones")
    cap_values = [int(value) for value in re.findall(r"\{FLAG_(?:BADGE\d+_GET|IS_CHAMPION),\s*(\d+)\}", cap_source)]
    require(cap_values == [level for _, level in EXPECTED_CAPS],
            f"unexpected badge cap curve: {cap_values}")

    macro_lines = {
        name: body
        for name, body in re.findall(r"^#define (AI_FLAG_ARAUNA_[A-Z_]+)\s+(.+)$", ai_source, flags=re.MULTILINE)
    }
    require(set(macro_lines) == {
        "AI_FLAG_ARAUNA_TRAINER", "AI_FLAG_ARAUNA_MINIBOSS",
        "AI_FLAG_ARAUNA_BOSS", "AI_FLAG_ARAUNA_DOUBLE_BOSS",
    }, "Arauna AI tiers are incomplete")
    forbidden = ("AI_FLAG_OMNISCIENT", "AI_FLAG_PREDICTION", "AI_FLAG_KNOW_OPPONENT_PARTY")
    require(not any(flag in body for body in macro_lines.values() for flag in forbidden),
            "Arauna AI tiers contain hidden-information flags")

    blocks = trainer_blocks(trainers)
    rows = []
    for trainer_id in SINGLE_BOSSES:
        require(trainer_id in blocks, f"missing boss {trainer_id}")
        rows.append(describe_boss(trainer_id, blocks[trainer_id], "Arauna Boss"))
    for trainer_id in DOUBLE_BOSSES:
        require(trainer_id in blocks, f"missing boss {trainer_id}")
        rows.append(describe_boss(trainer_id, blocks[trainer_id], "Arauna Double Boss"))

    report = render(rows)
    if args.check:
        require(REPORT.is_file(), "difficulty audit report is missing")
        require(REPORT.read_text(encoding="utf-8") == report,
                "difficulty audit report is stale; regenerate it")
    else:
        REPORT.write_text(report, encoding="utf-8")
    print(f"Arauna difficulty audit passed: {len(rows)} bosses, 9 soft caps, non-omniscient AI tiers")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, AuditError) as exc:
        print(f"Arauna difficulty audit failed: {exc}")
        raise SystemExit(1)
