#!/usr/bin/env python3
"""Audit trainer parties and replace protected Arauna slots with safe peers."""

from __future__ import annotations

import argparse
import csv
import json
import re
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEX_SIZE = 386
ADDITIONAL_STORY_RESERVED_IDS = {256}


def normalize(value: str) -> str:
    value = value.upper().removeprefix("SPECIES_")
    return re.sub(r"[^A-Z0-9]", "", value)


def species_span(line: str) -> tuple[int, int, str] | None:
    stripped = line.strip()
    if (not stripped or ":" in stripped or stripped.startswith(("===", "/*", "*", "//", "-"))
            or stripped.endswith("*/")):
        return None
    leading = len(line) - len(line.lstrip())
    held_item = stripped.find(" @ ")
    core = stripped if held_item < 0 else stripped[:held_item]
    parentheses = list(re.finditer(r"\(([^()]*)\)", core))
    species_paren = next((match for match in parentheses if match.group(1) not in {"M", "F"}), None)
    if species_paren:
        return leading + species_paren.start(1), leading + species_paren.end(1), species_paren.group(1)
    core = re.sub(r"\s+\([MF]\)$", "", core).rstrip()
    return leading, leading + len(core), core


def stage_by_id(entries: list[dict]) -> dict[int, int]:
    parent = {}
    for entry in entries:
        for evolution in entry.get("evolvesTo") or []:
            parent[int(evolution["id"])] = int(entry["id"])

    def stage(number: int) -> int:
        value = 0
        seen = set()
        while number in parent and number not in seen:
            seen.add(number)
            number = parent[number]
            value += 1
        return value

    return {int(entry["id"]): stage(int(entry["id"])) for entry in entries}


def protected_reasons(entries: list[dict], story: dict) -> dict[int, set[str]]:
    result: dict[int, set[str]] = {}

    def add(number: int, reason: str) -> None:
        result.setdefault(number, set()).add(reason)

    for entry in entries:
        number = int(entry["id"])
        if entry.get("legendary"):
            add(number, "legendary")
        if entry.get("mythical"):
            add(number, "mythical")
    for entry in story.get("nonCapturable", []):
        add(int(entry["id"]), "non-capturable")
    for number in story.get("fadedStorySpecies", []):
        add(int(number), "story-reserved")
    for number in story.get("sensitivityReviewRequired", []):
        add(int(number), "sensitivity-review")
    for number in ADDITIONAL_STORY_RESERVED_IDS:
        add(number, "story-reserved")
    return result


def best_replacement(number: int, entries: dict[int, dict], stages: dict[int, int], safe_ids: set[int]) -> int:
    source = entries[number]
    source_types = set(source.get("types") or ["normal"])
    source_bst = sum(int(value) for value in source["stats"].values())

    def score(candidate_id: int) -> tuple[int, int, int, int]:
        candidate = entries[candidate_id]
        candidate_types = set(candidate.get("types") or ["normal"])
        candidate_bst = sum(int(value) for value in candidate["stats"].values())
        exact = int(candidate_types == source_types)
        overlap = len(candidate_types & source_types)
        stage_distance = abs(stages[candidate_id] - stages[number])
        return (exact, overlap, -stage_distance, -abs(candidate_bst - source_bst))

    return max(safe_ids, key=score)


def render_audit(rows: list[dict[str, str]], trainer_count: int, party_count: int) -> str:
    total = sum(int(row["occurrences"]) for row in rows)
    lines = [
        "# Arauna trainer-party audit",
        "",
        "This report is generated by `tools/arauna/audit_arauna_trainers.py`.",
        "It does not redesign story teams; it only prevents protected Census slots from appearing in ordinary trainer data.",
        "",
        f"- Trainer definitions checked: **{trainer_count}**",
        f"- Party members checked: **{party_count}**",
        f"- Protected slot occurrences remapped: **{total}**",
        f"- Protected engine slots involved: **{len(rows)}**",
        "",
        "| Arauna slot | Protected species | Engine slot | Safe replacement | Replacement engine slot | Occurrences | Reason |",
        "|---:|---|---|---|---|---:|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['id']} | {row['name']} | `{row['engine_species']}` | "
            f"#{row['replacement_id']} {row['replacement_name']} | `{row['replacement_species']}` | "
            f"{row['occurrences']} | {row['reason']} |"
        )
    lines.extend((
        "",
        "Levels, held items, natures and explicit moves are preserved. Species without explicit moves continue to use the last four moves from their new Arauna level-up learnset.",
        "",
    ))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dex", type=Path, default=ROOT / "docs/arauna/source/pokedex.json")
    parser.add_argument("--story-roles", type=Path, default=ROOT / "docs/arauna/source/story_roles.json")
    parser.add_argument("--profiles", type=Path, default=ROOT / "docs/arauna/ARAUNA_BATTLE_PROFILES.csv")
    parser.add_argument("--trainers", type=Path, default=ROOT / "src/data/trainers.party")
    parser.add_argument("--report", type=Path, default=ROOT / "docs/arauna/ARAUNA_TRAINER_AUDIT.md")
    parser.add_argument("--no-apply", action="store_true")
    args = parser.parse_args()

    entries_list = json.loads(args.dex.read_text(encoding="utf-8"))["pokemon"]
    entries = {int(entry["id"]): entry for entry in entries_list}
    story = json.loads(args.story_roles.read_text(encoding="utf-8"))
    with args.profiles.open(encoding="utf-8", newline="") as source:
        profiles = {int(row["id"]): row for row in csv.DictReader(source)}
    if set(entries) != set(range(1, DEX_SIZE + 1)) or set(profiles) != set(entries):
        raise ValueError("Dex and battle profiles must cover IDs 001-386")

    reasons = protected_reasons(entries_list, story)
    stages = stage_by_id(entries_list)
    safe_ids = set(entries) - set(reasons) - set(range(1, 10))
    replacements = {
        number: best_replacement(number, entries, stages, safe_ids)
        for number in reasons
    }
    by_normalized_slot = {
        normalize(row["engine_species"]): number
        for number, row in profiles.items()
    }

    original = args.trainers.read_text(encoding="utf-8")
    result_lines = []
    occurrences: Counter[int] = Counter()
    party_count = 0
    in_block_comment = False
    for line in original.splitlines(keepends=True):
        ending = "\n" if line.endswith("\n") else ""
        body = line[:-1] if ending else line
        if in_block_comment:
            if "*/" in body:
                in_block_comment = False
            result_lines.append(body + ending)
            continue
        if "/*" in body:
            if "*/" not in body.split("/*", 1)[1]:
                in_block_comment = True
            result_lines.append(body + ending)
            continue
        span = species_span(body)
        if span is not None:
            start, end, token = span
            number = by_normalized_slot.get(normalize(token))
            if number is not None:
                party_count += 1
                if number in reasons:
                    replacement = profiles[replacements[number]]["engine_species"]
                    body = body[:start] + replacement + body[end:]
                    occurrences[number] += 1
        result_lines.append(body + ending)
    updated = "".join(result_lines)

    # A second parse must find no protected slot after the replacements.
    trainer_code = re.sub(r"/\*.*?\*/", "", updated, flags=re.DOTALL)
    for line in trainer_code.splitlines():
        span = species_span(line)
        if span is None:
            continue
        number = by_normalized_slot.get(normalize(span[2]))
        if number in reasons:
            raise ValueError(f"protected slot #{number:03d} remains in trainer data")

    rows = []
    for number in sorted(occurrences):
        replacement = replacements[number]
        rows.append({
            "id": f"{number:03d}", "name": entries[number]["name"],
            "engine_species": profiles[number]["engine_species"],
            "replacement_id": f"{replacement:03d}", "replacement_name": entries[replacement]["name"],
            "replacement_species": profiles[replacement]["engine_species"],
            "occurrences": str(occurrences[number]), "reason": ", ".join(sorted(reasons[number])),
        })
    if not args.no_apply:
        args.trainers.write_text(updated, encoding="utf-8")
    trainer_count = len(re.findall(r"^=== TRAINER_", original, flags=re.MULTILINE))
    args.report.parent.mkdir(parents=True, exist_ok=True)
    # Keep the historical remap report on idempotent re-runs.  A new report is
    # emitted whenever fresh protected occurrences are actually discovered.
    if rows or not args.report.exists():
        args.report.write_text(render_audit(rows, trainer_count, party_count), encoding="utf-8")
    print(f"audited {trainer_count} trainers / {party_count} party members; remapped {sum(occurrences.values())} protected occurrences")


if __name__ == "__main__":
    main()
