#!/usr/bin/env python3
"""Validate Arauna's wild ecology and pre-boss counterplay."""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path

import build_arauna_encounters as encounter_builder


ROOT = Path(__file__).resolve().parents[2]
REPORT = ROOT / "docs/arauna/ARAUNA_ENCOUNTER_AUDIT.md"

CORE_LAND_MAPS = (
    "MAP_ROUTE101", "MAP_ROUTE102", "MAP_ROUTE103", "MAP_ROUTE104",
    "MAP_PETALBURG_WOODS", "MAP_ROUTE110", "MAP_ROUTE111", "MAP_ROUTE112",
    "MAP_ROUTE113", "MAP_ROUTE114", "MAP_ROUTE116", "MAP_ROUTE117",
    "MAP_ROUTE118", "MAP_ROUTE119", "MAP_ROUTE120", "MAP_ROUTE121",
    "MAP_ROUTE123", "MAP_RUSTURF_TUNNEL", "MAP_GRANITE_CAVE_1F",
    "MAP_GRANITE_CAVE_B1F", "MAP_GRANITE_CAVE_B2F", "MAP_FIERY_PATH",
    "MAP_JAGGED_PASS",
)

PROGRESSION = (
    ("Badge 1", (
        "MAP_ROUTE101", "MAP_ROUTE102", "MAP_ROUTE103", "MAP_ROUTE104",
        "MAP_PETALBURG_WOODS", "MAP_ROUTE116", "MAP_RUSTURF_TUNNEL",
    ), {"water", "grass", "fighting", "ground", "steel"}),
    ("Badge 2", (
        "MAP_GRANITE_CAVE_1F", "MAP_GRANITE_CAVE_B1F", "MAP_GRANITE_CAVE_B2F",
    ), {"flying", "psychic", "fairy"}),
    ("Badge 3", (
        "MAP_ROUTE110", "MAP_ROUTE117",
    ), {"ground"}),
    ("Badge 4", (
        "MAP_ROUTE111", "MAP_ROUTE112", "MAP_FIERY_PATH", "MAP_ROUTE113",
        "MAP_ROUTE114", "MAP_JAGGED_PASS",
    ), {"water", "rock", "ground"}),
    ("Badge 5", (), {"fighting"}),
    ("Badge 6", (
        "MAP_ROUTE118", "MAP_ROUTE119", "MAP_ROUTE120",
    ), {"electric", "ice", "rock"}),
    ("Badge 7", (
        "MAP_ROUTE121", "MAP_MT_PYRE_1F", "MAP_MT_PYRE_EXTERIOR",
        "MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM",
    ), {"bug", "ghost", "dark"}),
    ("Badge 8", (
        "MAP_SEAFLOOR_CAVERN_ROOM1", "MAP_SEAFLOOR_CAVERN_ROOM2",
        "MAP_SEAFLOOR_CAVERN_ROOM3", "MAP_SEAFLOOR_CAVERN_ROOM4",
        "MAP_SEAFLOOR_CAVERN_ROOM5", "MAP_SEAFLOOR_CAVERN_ROOM6",
        "MAP_SEAFLOOR_CAVERN_ROOM7", "MAP_SEAFLOOR_CAVERN_ROOM8",
    ), {"electric", "grass"}),
)


class AuditError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AuditError(message)


def encounter_index(data: dict) -> tuple[Counter, dict[str, set[str]], list[dict]]:
    counts = Counter()
    land_by_map: dict[str, set[str]] = defaultdict(set)
    tables = []
    for group in data["wild_encounter_groups"]:
        for encounter in group.get("encounters", []):
            map_name = encounter.get("map", group["label"])
            for field in encounter_builder.FIELD_METHOD:
                table = encounter.get(field)
                if not table:
                    continue
                species = [mon["species"] for mon in table["mons"]]
                counts.update(species)
                if field == "land_mons":
                    land_by_map[map_name].update(species)
                tables.append({
                    "map": map_name,
                    "field": field,
                    "slots": len(species),
                    "unique": len(set(species)),
                })
    return counts, land_by_map, tables


def render(
    profiles: list[dict],
    wild_count: int,
    table_count: int,
    core_tables: list[dict],
    milestones: list[dict],
) -> str:
    lines = [
        "# Arauna encounter audit",
        "",
        "This report is generated by `tools/arauna/audit_arauna_encounters.py`.",
        "Its guardrails adapt Emerald Imperium's broad route choices and pre-boss counterplay",
        "to Arauna's smaller 386-species regional Census.",
        "",
        "## Global safeguards",
        "",
        f"- **{len(profiles)}** Census entries classified;",
        f"- **{wild_count}** wild-eligible species placed at least once;",
        "- **0** starter, legendary, mythical, story-reserved or sensitivity-review species in random encounters;",
        f"- **{table_count}** encounter tables checked;",
        f"- core land tables expose **{min(row['unique'] for row in core_tables)}-"
        f"{max(row['unique'] for row in core_tables)}** distinct species each.",
        "",
        "The generator prefers a different species for every slot when the biome and level curve allow it.",
        "The audit permits a minimum of eight distinct choices in a 12-slot core land table so later",
        "story-specific areas can still use deliberate repetition.",
        "",
        "## Counterplay available before each badge",
        "",
        "Only land encounters are counted here. This deliberately ignores Surf and late fishing rods,",
        "so the result does not promise a counter the player cannot actually reach yet.",
        "",
        "| Milestone | Cumulative land species | Direct type answers | Accepted answer types | Examples |",
        "|---|---:|---:|---|---|",
    ]
    for row in milestones:
        lines.append(
            f"| {row['milestone']} | {row['available']} | {row['answers']} | "
            f"{row['types']} | {row['examples']} |"
        )
    lines.extend((
        "",
        "These are choices, not guaranteed wins: boss coverage moves, stats, evolutions and team roles",
        "still matter. The final boss pass must keep at least two practical answers after those details",
        "are considered, while optional challenge fights may demand narrower solutions.",
        "",
    ))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify the committed report without rewriting it")
    args = parser.parse_args()

    source = json.loads((ROOT / "docs/arauna/source/pokedex.json").read_text(encoding="utf-8"))
    story = json.loads((ROOT / "docs/arauna/source/story_roles.json").read_text(encoding="utf-8"))
    profiles = encounter_builder.build_profiles(
        source,
        encounter_builder.species_constants(ROOT / "src/data/pokemon/species_info/arauna_dex.h"),
        story,
    )
    by_species = {profile["species"]: profile for profile in profiles}
    data = json.loads((ROOT / "src/data/wild_encounters.json").read_text(encoding="utf-8"))
    counts, land_by_map, tables = encounter_index(data)

    protected = [
        profile for profile in profiles
        if profile["availability"] != "wild" and counts[profile["species"]]
    ]
    require(not protected, "protected species remain in wild encounters: " + ", ".join(
        f"#{profile['id']:03d} {profile['name']}" for profile in protected
    ))

    wild_profiles = [profile for profile in profiles if profile["availability"] == "wild"]
    missing = [profile for profile in wild_profiles if not counts[profile["species"]]]
    require(not missing, "wild-eligible species without an encounter: " + ", ".join(
        f"#{profile['id']:03d} {profile['name']}" for profile in missing
    ))

    core_tables = [
        table for table in tables
        if table["field"] == "land_mons" and table["map"] in CORE_LAND_MAPS
    ]
    require(len(core_tables) == len(CORE_LAND_MAPS), "one or more core land maps have no encounter table")
    for table in core_tables:
        minimum = min(8, table["slots"])
        require(table["unique"] >= minimum,
                f"{table['map']} has only {table['unique']} distinct land species; expected {minimum}")

    milestones = []
    cumulative = set()
    for label, maps, answer_types in PROGRESSION:
        for map_name in maps:
            require(map_name in land_by_map, f"progression map has no land encounters: {map_name}")
            cumulative.update(land_by_map[map_name])
        answers = sorted(
            (by_species[species] for species in cumulative
             if answer_types & set(by_species[species]["types"])),
            key=lambda profile: profile["id"],
        )
        require(len(answers) >= 3,
                f"{label} has only {len(answers)} direct land counter choices")
        milestones.append({
            "milestone": label,
            "available": len(cumulative),
            "answers": len(answers),
            "types": "/".join(sorted(answer_types)).title(),
            "examples": ", ".join(profile["name"] for profile in answers[:3]),
        })

    report = render(profiles, len(wild_profiles), len(tables), core_tables, milestones)
    if args.check:
        require(REPORT.is_file(), "encounter audit report is missing")
        require(REPORT.read_text(encoding="utf-8") == report,
                "encounter audit report is stale; regenerate it")
    else:
        REPORT.write_text(report, encoding="utf-8")
    print(
        f"Arauna encounter audit passed: {len(wild_profiles)} wild species, "
        f"{len(tables)} tables, 0 protected encounters, 8 counterplay milestones"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, AuditError) as exc:
        print(f"Arauna encounter audit failed: {exc}")
        raise SystemExit(1)
