SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "As aguas carregam lembrancas\nque nao pertencem a quem as\p"
	.string "recebe. Pessoas reconhecem\nnomes que nunca ouviram e\p"
	.string "esquecem rostos que amam.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "My big brother used to study the sea.$"

