SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "The waters carry memories that do not\n"
	.string "belong to whoever receives them. People\l"
	.string "recognize names they have never heard\l"
	.string "and forget faces they love.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "My big brother used to study the sea.$"

