#ifndef GUARD_CONSTANTS_ABILITIES_H
#define GUARD_CONSTANTS_ABILITIES_H

#define ABILITY_NONE 0
#define ABILITY_STENCH 1
#define ABILITY_DRIZZLE 2
#define ABILITY_SPEED_BOOST 3
#define ABILITY_BATTLE_ARMOR 4
#define ABILITY_STURDY 5
#define ABILITY_DAMP 6
#define ABILITY_LIMBER 7
#define ABILITY_SAND_VEIL 8
#define ABILITY_STATIC 9
#define ABILITY_VOLT_ABSORB 10
#define ABILITY_WATER_ABSORB 11
#define ABILITY_OBLIVIOUS 12
#define ABILITY_CLOUD_NINE 13
#define ABILITY_COMPOUND_EYES 14
#define ABILITY_INSOMNIA 15
#define ABILITY_COLOR_CHANGE 16
#define ABILITY_IMMUNITY 17
#define ABILITY_FLASH_FIRE 18
#define ABILITY_SHIELD_DUST 19
#define ABILITY_OWN_TEMPO 20
#define ABILITY_SUCTION_CUPS 21
#define ABILITY_INTIMIDATE 22
#define ABILITY_SHADOW_TAG 23
#define ABILITY_ROUGH_SKIN 24
#define ABILITY_WONDER_GUARD 25
#define ABILITY_LEVITATE 26
#define ABILITY_EFFECT_SPORE 27
#define ABILITY_SYNCHRONIZE 28
#define ABILITY_CLEAR_BODY 29
#define ABILITY_NATURAL_CURE 30
#define ABILITY_LIGHTNING_ROD 31
#define ABILITY_SERENE_GRACE 32
#define ABILITY_SWIFT_SWIM 33
#define ABILITY_CHLOROPHYLL 34
#define ABILITY_ILLUMINATE 35
#define ABILITY_TRACE 36
#define ABILITY_HUGE_POWER 37
#define ABILITY_POISON_POINT 38
#define ABILITY_INNER_FOCUS 39
#define ABILITY_MAGMA_ARMOR 40
#define ABILITY_WATER_VEIL 41
#define ABILITY_MAGNET_PULL 42
#define ABILITY_SOUNDPROOF 43
#define ABILITY_RAIN_DISH 44
#define ABILITY_SAND_STREAM 45
#define ABILITY_PRESSURE 46
#define ABILITY_THICK_FAT 47
#define ABILITY_EARLY_BIRD 48
#define ABILITY_FLAME_BODY 49
#define ABILITY_RUN_AWAY 50
#define ABILITY_KEEN_EYE 51
#define ABILITY_HYPER_CUTTER 52
#define ABILITY_PICKUP 53
#define ABILITY_TRUANT 54
#define ABILITY_HUSTLE 55
#define ABILITY_CUTE_CHARM 56
#define ABILITY_PLUS 57
#define ABILITY_MINUS 58
#define ABILITY_FORECAST 59
#define ABILITY_STICKY_HOLD 60
#define ABILITY_SHED_SKIN 61
#define ABILITY_GUTS 62
#define ABILITY_MARVEL_SCALE 63
#define ABILITY_LIQUID_OOZE 64
#define ABILITY_OVERGROW 65
#define ABILITY_BLAZE 66
#define ABILITY_TORRENT 67
#define ABILITY_SWARM 68
#define ABILITY_ROCK_HEAD 69
#define ABILITY_DROUGHT 70
#define ABILITY_ARENA_TRAP 71
#define ABILITY_VITAL_SPIRIT 72
#define ABILITY_WHITE_SMOKE 73
#define ABILITY_PURE_POWER 74
#define ABILITY_SHELL_ARMOR 75
#define ABILITY_CACOPHONY 76
#define ABILITY_AIR_LOCK 77

// The Arauna abilities. One per species, and the same one in both slots of
// that species: Gen III stores only a single "which of the two" bit on the
// Pokemon, chosen at random, so a species with two different abilities cannot
// be relied on to have either. Putting the same ability in both slots is the
// only way to guarantee the one that was designed for it.
//
// The constants keep the Portuguese spelling the design package uses, so the
// package's ids and assignments still line up with the code; the names the
// player reads are English, the same split the signature moves already use.
#define ABILITY_FOGO_LEAL 78
#define ABILITY_VIGIA_ALADO 79
#define ABILITY_BICO_GRANITO 80
#define ABILITY_COBRA_GRANDE 81
#define ABILITY_COROA_SOLAR 82
#define ABILITY_VEU_LUNAR 83
#define ABILITY_VOZ_DE_TUPA 84
#define ABILITY_CANTO_RIO 85
#define ABILITY_SOL_PRIMEIRO 86
#define ABILITY_LUA_PRIMEVA 87
#define ABILITY_LACO_ETERNO 88
#define ABILITY_MIL_RIOS 89
#define ABILITY_GUARDIAO 90
#define ABILITY_MATA_RENOVA 91
#define ABILITY_TEMPESTADE 92
#define ABILITY_SECA_BRAVA 93
#define ABILITY_VENTO_SUL 94
#define ABILITY_SOLO_VIVO 95
#define ABILITY_FOGO_ANTIGO 96
#define ABILITY_MARE_MESTRA 97
#define ABILITY_PRIMEIRA_LUZ 98
#define ABILITY_ULTIMA_LUZ 99
#define ABILITY_DESEJO_VIVO 100
#define ABILITY_JURAMENTO 101
#define ABILITY_FOGO_VIGIA 102
#define ABILITY_REI_DO_RIO 103
#define ABILITY_CASCO_ANTIGO 104
#define ABILITY_SOL_ABSOLUTO 105
#define ABILITY_NOITE_ETERNA 106
#define ABILITY_RESISTENCIA 107
#define ABILITY_MAR_SAGRADO 108
#define ABILITY_ARCO_VIVO 109
#define ABILITY_PE_INVERSO 110
#define ABILITY_REDEMOINHO 111
#define ABILITY_ESSENCIA 112

#define ABILITIES_COUNT 113

#endif  // GUARD_CONSTANTS_ABILITIES_H
