#ifndef GUARD_CONSTANTS_FLAGS_H
#define GUARD_CONSTANTS_FLAGS_H

#include "constants/trainers.h"
#include "constants/opponents.h"
#include "constants/rematches.h"


// Temporary Flags
// These temporary flags are are cleared every time a map is loaded. They are used
// for things like shortening an NPCs introduction text if the player already spoke
// to them once.
#define TEMP_FLAGS_START 0x0
#define FLAG_TEMP_1      (TEMP_FLAGS_START + 0x1)
#define FLAG_TEMP_2      (TEMP_FLAGS_START + 0x2)
#define FLAG_TEMP_3      (TEMP_FLAGS_START + 0x3)
#define FLAG_TEMP_4      (TEMP_FLAGS_START + 0x4)
#define FLAG_TEMP_5      (TEMP_FLAGS_START + 0x5)  // Unused Flag
#define FLAG_TEMP_6      (TEMP_FLAGS_START + 0x6)  // Unused Flag
#define FLAG_TEMP_7      (TEMP_FLAGS_START + 0x7)  // Unused Flag
#define FLAG_TEMP_8      (TEMP_FLAGS_START + 0x8)  // Unused Flag
#define FLAG_TEMP_9      (TEMP_FLAGS_START + 0x9)  // Unused Flag
#define FLAG_TEMP_A      (TEMP_FLAGS_START + 0xA)  // Unused Flag
#define FLAG_TEMP_B      (TEMP_FLAGS_START + 0xB)  // Unused Flag
#define FLAG_TEMP_C      (TEMP_FLAGS_START + 0xC)  // Unused Flag
#define FLAG_TEMP_D      (TEMP_FLAGS_START + 0xD)  // Unused Flag
#define FLAG_TEMP_E      (TEMP_FLAGS_START + 0xE)  // When set, follower Pokémon won't be spawned
#define FLAG_TEMP_F      (TEMP_FLAGS_START + 0xF)  // Unused Flag
#define FLAG_TEMP_10     (TEMP_FLAGS_START + 0x10) // Unused Flag
#define FLAG_TEMP_11     (TEMP_FLAGS_START + 0x11)
#define FLAG_TEMP_12     (TEMP_FLAGS_START + 0x12)
#define FLAG_TEMP_13     (TEMP_FLAGS_START + 0x13)
#define FLAG_TEMP_14     (TEMP_FLAGS_START + 0x14)
#define FLAG_TEMP_15     (TEMP_FLAGS_START + 0x15)
#define FLAG_TEMP_16     (TEMP_FLAGS_START + 0x16)
#define FLAG_TEMP_17     (TEMP_FLAGS_START + 0x17)
#define FLAG_TEMP_18     (TEMP_FLAGS_START + 0x18)
#define FLAG_TEMP_19     (TEMP_FLAGS_START + 0x19)
#define FLAG_TEMP_1A     (TEMP_FLAGS_START + 0x1A)
#define FLAG_TEMP_1B     (TEMP_FLAGS_START + 0x1B)
#define FLAG_TEMP_1C     (TEMP_FLAGS_START + 0x1C)
#define FLAG_TEMP_1D     (TEMP_FLAGS_START + 0x1D)
#define FLAG_TEMP_1E     (TEMP_FLAGS_START + 0x1E)
#define FLAG_TEMP_1F     (TEMP_FLAGS_START + 0x1F)
#define TEMP_FLAGS_END   FLAG_TEMP_1F
#define NUM_TEMP_FLAGS   (TEMP_FLAGS_END - TEMP_FLAGS_START + 1)

#if IS_FRLG

#include "constants/flags_frlg.h"

#else

#define FLAG_ARAUNA_MAP_LAB_VISITED          0x20
#define FLAG_ARAUNA_MAP_LAB_GUIDE_MET        0x21
#define FLAG_ARAUNA_MAP_LAB_FIELD_KIT_TAKEN  0x22
#define FLAG_ARAUNA_MIST_ROUTE_AFFECTED_MON_CLEARED  0x23
#define FLAG_ARAUNA_MIST_ROUTE_NOTEBOOK_TAKEN        0x24
#define FLAG_ARAUNA_FIRST_LINK_RESCUE_COMPLETE      0x25
#define FLAG_ARAUNA_FIRST_LINK_MEMORY_SEEN           0x26
#define FLAG_ARAUNA_FIRST_LINK_CHAMBER_COMPLETE      0x27
#define FLAG_ARAUNA_PORTO_ARRIVED                    0x28
#define FLAG_ARAUNA_PORTO_CELINA_MET                 0x29
#define FLAG_ARAUNA_PORTO_IARACO_SEEN                0x2A
#define FLAG_ARAUNA_PORTO_IARACO_RESTORED            0x2B
#define FLAG_ARAUNA_TESTIMONY_IARA_MAE               0x2C
#define FLAG_ARAUNA_BADGE_MARE                       0x2D
#define FLAG_ARAUNA_SERRA_ARRIVED                     0x2E
#define FLAG_ARAUNA_LIBRAS_LEARNED                    0x2F
#define FLAG_ARAUNA_SERRA_HERMIT_UNDERSTOOD           0x30
#define FLAG_ARAUNA_SERRA_LOBISOMEM_CALMED            0x31
#define FLAG_ARAUNA_BADGE_UIVO                        0x32
#define FLAG_ARAUNA_SERRA_CHAPTER_RECEIVED            0x33
#define FLAG_ARAUNA_SECOND_TEST_CANDIES_RECEIVED     0x34
#define FLAG_ARAUNA_MARE_TRIAL_COMPLETE             0x35
#define FLAG_ARAUNA_UIVO_TRIAL_COMPLETE             0x36
#define FLAG_ARAUNA_PROLOGUE_FED_PIMPAU              0x37
#define FLAG_ARAUNA_PROLOGUE_FED_CARAMELO            0x38
#define FLAG_ARAUNA_PROLOGUE_FED_QUERO               0x39
#define FLAG_ARAUNA_CIRO_STARTER_PIMPAU              0x3A
#define FLAG_ARAUNA_CIRO_STARTER_CARAMELO            0x3B
#define FLAG_ARAUNA_CIRO_STARTER_QUERO               0x3C
#define FLAG_ARAUNA_ANAHI_STARTER_PIMPAU             0x3D
#define FLAG_ARAUNA_ANAHI_STARTER_CARAMELO            0x3E
#define FLAG_ARAUNA_ANAHI_STARTER_QUERO              0x3F
#define FLAG_ARAUNA_PROLOGUE_NIGHT_PIMPAU             0x40
#define FLAG_ARAUNA_PROLOGUE_NIGHT_CARAMELO           0x41
#define FLAG_ARAUNA_PROLOGUE_NIGHT_QUERO              0x42
#define FLAG_ARAUNA_PROLOGUE_TALKED_ZILA_AT_NIGHT     0x43
#define FLAG_ARAUNA_PROLOGUE_TALKED_ANAHI_AT_NIGHT    0x44
#define FLAG_ARAUNA_PROLOGUE_NIGHT_COMPLETE           0x45
#define FLAG_ARAUNA_PORTO_MEMORIAL_HEARD             0x46
#define FLAG_ARAUNA_PORTO_PERMIT_FOUND                0x47
#define FLAG_ARAUNA_PORTO_DOCK_SONG_HEARD             0x48
#define FLAG_ARAUNA_PORTO_NET_FOUND                   0x49
#define FLAG_ARAUNA_PORTO_AGENT_DEFEATED              0x4A
#define FLAG_ARAUNA_COAST_ROAD_ENTERED                0x4B
#define FLAG_ARAUNA_PORTO_IDENTITY_SEEN               0x4C
#define FLAG_ARAUNA_BOARD_RECEIVED                    0x4D
#define FLAG_ARAUNA_BOARD_FIELD_UNLOCKED              0x4E
#define FLAG_ARAUNA_NORTH_ROAD_REOPENED               0x4F

// Scripts
#define FLAG_HIDE_SKY_PILLAR_TOP_RAYQUAZA_STILL  0x50
#define FLAG_SET_WALL_CLOCK                      0x51
#define FLAG_RESCUED_BIRCH                       0x52
#define FLAG_LEGENDARIES_IN_SOOTOPOLIS           0x53

#define FLAG_UNUSED_0x054                    0x54  // Unused Flag
#define FLAG_UNUSED_0x055                    0x55  // Unused Flag

#define FLAG_HIDE_CONTEST_POKE_BALL          0x56  // Always set after new game, object it hides is added directly
#define FLAG_MET_RIVAL_MOM                   0x57
#define FLAG_BIRCH_AIDE_MET                  0x58
#define FLAG_DECLINED_BIKE                   0x59
#define FLAG_RECEIVED_BIKE                   0x5A
#define FLAG_WATTSON_REMATCH_AVAILABLE       0x5B
#define FLAG_COLLECTED_ALL_SILVER_SYMBOLS    0x5C
#define FLAG_GOOD_LUCK_SAFARI_ZONE           0x5D // Set after talking to NPC blocking Safari Zone entrance/exit once.
#define FLAG_RECEIVED_WAILMER_PAIL           0x5E
#define FLAG_RECEIVED_POKEBLOCK_CASE         0x5F
#define FLAG_RECEIVED_SECRET_POWER           0x60
#define FLAG_MET_TEAM_AQUA_HARBOR            0x61
#define FLAG_TV_EXPLAINED                    0x62
#define FLAG_MAUVILLE_GYM_BARRIERS_STATE     0x63
#define FLAG_MOSSDEEP_GYM_SWITCH_1           0x64 // Leftover from the RS version of Mossdeep Gym, functionally unused
#define FLAG_MOSSDEEP_GYM_SWITCH_2           0x65 //
#define FLAG_MOSSDEEP_GYM_SWITCH_3           0x66 //
#define FLAG_MOSSDEEP_GYM_SWITCH_4           0x67 //

#define FLAG_UNUSED_0x068                    0x68  // Unused Flag

#define FLAG_OCEANIC_MUSEUM_MET_REPORTER     0x69
#define FLAG_RECEIVED_HM_STRENGTH            0x6A
#define FLAG_RECEIVED_HM_ROCK_SMASH          0x6B
#define FLAG_WHITEOUT_TO_LAVARIDGE           0x6C // Set after defeating Flannery, so the player can't white out from poison before receiving Go Goggles
#define FLAG_RECEIVED_HM_FLASH               0x6D
#define FLAG_RECEIVED_HM_FLY                 0x6E
#define FLAG_GROUDON_AWAKENED_MAGMA_HIDEOUT  0x6F
#define FLAG_TEAM_AQUA_ESCAPED_IN_SUBMARINE  0x70
#define FLAG_UNUSED_RS_LEGENDARY_BATTLE_DONE 0x71 // Unused Flag. Used in R/S to indicate whether player defeated or caught Groudon/Kyogre in Cave of Origin.
#define FLAG_SCOTT_CALL_BATTLE_FRONTIER      0x72 // Used in order to activate a phone call from Scott, inviting the player to the SS Tidal.
#define FLAG_RECEIVED_METEORITE              0x73
#define FLAG_ADVENTURE_STARTED               0x74 // RECEIVED Pokédex.
#define FLAG_DEFEATED_MAGMA_SPACE_CENTER     0x75 // Set when Team Magma is defeated at Mossdeep's Space Center.
#define FLAG_MET_HIDDEN_POWER_GIVER          0x76

#define FLAG_CANCEL_BATTLE_ROOM_CHALLENGE    0x77

#define FLAG_LANDMARK_MIRAGE_TOWER           0x78
#define FLAG_RECEIVED_TM_BRICK_BREAK         0x79
#define FLAG_RECEIVED_HM_SURF                0x7A
#define FLAG_RECEIVED_HM_DIVE                0x7B
#define FLAG_REGISTER_RIVAL_POKENAV          0x7C
#define FLAG_DEFEATED_RIVAL_ROUTE_104        0x7D
#define FLAG_DEFEATED_WALLY_VICTORY_ROAD     0x7E
#define FLAG_MET_PRETTY_PETAL_SHOP_OWNER     0x7F
#define FLAG_ENABLE_ROXANNE_FIRST_CALL       0x80 // Set after defeating Brawly. This will activate a call with Roxanne in order to register her.
#define FLAG_KYOGRE_ESCAPED_SEAFLOOR_CAVERN  0x81
#define FLAG_DEFEATED_RIVAL_ROUTE103         0x82
#define FLAG_RECEIVED_DOLL_LANETTE           0x83
#define FLAG_RECEIVED_POTION_OLDALE          0x84
#define FLAG_PENDING_DAYCARE_EGG             0x86
#define FLAG_THANKED_FOR_PLAYING_WITH_WALLY  0x87
#define FLAG_ENABLE_FIRST_WALLY_POKENAV_CALL 0x88 // Set after defeating Wally outside Mauville Gym. Will activate a call later to register Wally.
#define FLAG_RECEIVED_HM_CUT                 0x89
#define FLAG_SCOTT_CALL_FORTREE_GYM          0x8A // Triggers call from Scott after defeating Winona
#define FLAG_DEFEATED_EVIL_TEAM_MT_CHIMNEY   0x8B
#define FLAG_RECEIVED_6_SODA_POP             0x8C
#define FLAG_DEFEATED_SEASHORE_HOUSE         0x8D
#define FLAG_DEVON_GOODS_STOLEN              0x8E
#define FLAG_RECOVERED_DEVON_GOODS           0x8F
#define FLAG_RETURNED_DEVON_GOODS            0x90
#define FLAG_CAUGHT_LUGIA                    0x91
#define FLAG_CAUGHT_HO_OH                    0x92
#define FLAG_MR_BRINEY_SAILING_INTRO         0x93
#define FLAG_DOCK_REJECTED_DEVON_GOODS       0x94
#define FLAG_DELIVERED_DEVON_GOODS           0x95
#define FLAG_RECEIVED_CONTEST_PASS           0x96 // Unused, leftover from R/S
#define FLAG_RECEIVED_CASTFORM               0x97
#define FLAG_RECEIVED_SUPER_ROD              0x98
#define FLAG_RUSTBORO_NPC_TRADE_COMPLETED    0x99
#define FLAG_PACIFIDLOG_NPC_TRADE_COMPLETED  0x9A
#define FLAG_FORTREE_NPC_TRADE_COMPLETED     0x9B
#define FLAG_BATTLE_FRONTIER_TRADE_DONE      0x9C
#define FLAG_FORCE_MIRAGE_TOWER_VISIBLE      0x9D
#define FLAG_SOOTOPOLIS_ARCHIE_MAXIE_LEAVE   0x9E
#define FLAG_INTERACTED_WITH_DEVON_EMPLOYEE_GOODS_STOLEN 0x9F
#define FLAG_COOL_PAINTING_MADE              0xA0
#define FLAG_BEAUTY_PAINTING_MADE            0xA1
#define FLAG_CUTE_PAINTING_MADE              0xA2
#define FLAG_SMART_PAINTING_MADE             0xA3
#define FLAG_TOUGH_PAINTING_MADE             0xA4
#define FLAG_RECEIVED_TM_ROCK_TOMB           0xA5
#define FLAG_RECEIVED_TM_BULK_UP             0xA6
#define FLAG_RECEIVED_TM_SHOCK_WAVE          0xA7
#define FLAG_RECEIVED_TM_OVERHEAT            0xA8
#define FLAG_RECEIVED_TM_FACADE              0xA9
#define FLAG_RECEIVED_TM_AERIAL_ACE          0xAA
#define FLAG_RECEIVED_TM_CALM_MIND           0xAB
#define FLAG_RECEIVED_TM_WATER_PULSE         0xAC
#define FLAG_RECEIVED_TM_ATTRACT             0xAD
#define FLAG_RECEIVED_TM_SKILL_SWAP          0xAE
#define FLAG_RECEIVED_TM_REST                0xAF
#define FLAG_RECEIVED_TM_SLUDGE_BOMB         0xB0
#define FLAG_RECEIVED_TM_THUNDER_WAVE        0xB1
#define FLAG_RECEIVED_TM_THIEF               0xB2
#define FLAG_RECEIVED_TM_SUNNY_DAY           0xB3
#define FLAG_RECEIVED_TM_SPITE               0xB4
#define FLAG_RECEIVED_TM_FREEZE_DRY          0xB5
#define FLAG_RECEIVED_TM_WILL_O_WISP         0xB6
#define FLAG_RECEIVED_TM_ENDEAVOR            0xB7
#define FLAG_RECEIVED_TM_DRAINING_KISS       0xB8
#define FLAG_RECEIVED_TM_DARK_PULSE          0xB9
#define FLAG_RECEIVED_TM_ZAP_CANNON          0xBA
#define FLAG_RECEIVED_TM_CYCLONE             0xBB
#define FLAG_RECEIVED_TM_SOLAR_BLADE         0xBC
#define FLAG_RECEIVED_TM_MAGNET_RISE         0xBD
#define FLAG_RECEIVED_TM_GRASSY_TERRAIN      0xBE
#define FLAG_RECEIVED_TM_MISTY_TERRAIN       0xBF
#define FLAG_RECEIVED_TM_ELECTRIC_TERRAIN    0xC0
#define FLAG_RECEIVED_TM_PSYCHIC_TERRAIN     0xC1
#define FLAG_RECEIVED_TM_AURORA_VEIL         0xC2
#define FLAG_RECEIVED_TM_HYPER_VOICE         0xC3
#define FLAG_RECEIVED_TM_AIR_SLASH           0xC4
#define FLAG_RECEIVED_TM_BODY_PRESS          0xC5
#define FLAG_RECEIVED_TM_BODY_SLAM           0xC6
#define FLAG_RECEIVED_TM_BRAVE_BIRD          0xC7
#define FLAG_RECEIVED_TM_BREAKING_SWIPE      0xC8
#define FLAG_RECEIVED_TM_BUG_BUZZ            0xC9
#define FLAG_RECEIVED_TM_BULLET_SEED         0xCA
#define FLAG_RECEIVED_TM_CLOSE_COMBAT        0xCB
#define FLAG_RECEIVED_TM_CRUNCH              0xCC
#define FLAG_RECEIVED_TM_DAZZLING_GLEAM      0xCD
#define FLAG_RECEIVED_TM_DOUBLE_EDGE         0xCE
#define FLAG_RECEIVED_TM_EARTH_POWER         0xCF
#define FLAG_RECEIVED_TM_ENERGY_BALL         0xD0
#define FLAG_RECEIVED_TM_FIRE_FANG           0xD1
#define FLAG_RECEIVED_TM_FLAMETHROWER        0xD2
#define FLAG_RECEIVED_TM_FLASH_CANNON        0xD3
#define FLAG_RECEIVED_TM_GIGA_DRAIN          0xD4
#define FLAG_RECEIVED_TM_GRASS_KNOT          0xD5
#define FLAG_RECEIVED_TM_GUNK_SHOT           0xD6
#define FLAG_RECEIVED_TM_HAIL                0xD7
#define FLAG_RECEIVED_TM_HEAT_WAVE           0xD8
#define FLAG_RECEIVED_TM_HEAVY_SLAM          0xD9
#define FLAG_RECEIVED_TM_HURRICANE           0xDA
#define FLAG_RECEIVED_TM_HYDRO_PUMP          0xDB
#define FLAG_RECEIVED_TM_HYPER_BEAM          0xDC
#define FLAG_RECEIVED_TM_ICE_BEAM            0xDD
#define FLAG_RECEIVED_TM_ICE_FANG            0xDE
#define FLAG_RECEIVED_TM_IRON_HEAD           0xDF
#define FLAG_RECEIVED_TM_LEECH_LIFE          0xE0
#define FLAG_RECEIVED_TM_LIQUIDATION         0xE1
#define FLAG_RECEIVED_TM_LOW_KICK            0xE2
#define FLAG_RECEIVED_TM_MEGAHORN            0xE3
#define FLAG_RECEIVED_TM_MYSTICAL_FIRE       0xE4
#define FLAG_RECEIVED_TM_PLAY_ROUGH          0xE5
#define FLAG_RECEIVED_TM_POISON_JAB          0xE6
#define FLAG_RECEIVED_TM_POWER_GEM           0xE7
#define FLAG_RECEIVED_TM_PSYCHIC_FANGS       0xE8
#define FLAG_RECEIVED_TM_RAZOR_SHELL         0xE9
#define FLAG_RECEIVED_TM_ROCK_SLIDE          0xEA
#define FLAG_RECEIVED_TM_SCALD               0xEB
#define FLAG_RECEIVED_TM_SHADOW_BALL         0xEC
#define FLAG_RECEIVED_TM_SLUDGE_WAVE         0xED
#define FLAG_RECEIVED_TM_STEEL_BEAM          0xEE
#define FLAG_RECEIVED_TM_STONE_EDGE          0xEF
#define FLAG_RECEIVED_TM_STORED_POWER        0xF0
#define FLAG_RECEIVED_TM_SUPERPOWER          0xF1
#define FLAG_RECEIVED_TM_SURF                0xF2
#define FLAG_RECEIVED_TM_THUNDER_FANG        0xF3
#define FLAG_RECEIVED_TM_THUNDERBOLT         0xF4
#define FLAG_RECEIVED_TM_WATERFALL           0xF5
#define FLAG_RECEIVED_TM_WILD_CHARGE         0xF6
#define FLAG_RECEIVED_TM_X_SCISSOR           0xF7
#define FLAG_RECEIVED_TM_ZEN_HEADBUTT        0xF8

#define FLAG_DEFEATED_DEOXYS                 0xF9
#define FLAG_BATTLED_DEOXYS                  0xFA
#define FLAG_SHOWN_EON_TICKET                0xFB
#define FLAG_SHOWN_AURORA_TICKET             0xFC
#define FLAG_SHOWN_MYSTIC_TICKET             0xFD
#define FLAG_SHOWN_OLD_SEA_MAP               0xFE
#define FLAG_MOVE_TUTOR_TAUGHT_ROLLOUT       0xFF

#define TRAINER_FLAGS_START                  0x100

#include "constants/trainer_flags.h"

// Hidden items
#define FLAG_HIDDEN_ITEMS_START                                      (TRAINER_FLAGS_END + 1)
#define FLAG_HIDDEN_ITEM_LAVARIDGE_TOWN_ICE_HEAL                     (FLAG_HIDDEN_ITEMS_START + 0x00)
#define FLAG_HIDDEN_ITEM_TRICK_HOUSE_NUGGET                          (FLAG_HIDDEN_ITEMS_START + 0x01)
#define FLAG_HIDDEN_ITEM_ROUTE_111_STARDUST                          (FLAG_HIDDEN_ITEMS_START + 0x02)
#define FLAG_HIDDEN_ITEM_ROUTE_113_ETHER                             (FLAG_HIDDEN_ITEMS_START + 0x03)
#define FLAG_HIDDEN_ITEM_LILYCOVE_CITY_HEART_SCALE                   (FLAG_HIDDEN_ITEMS_START + 0x04)
#define FLAG_HIDDEN_ITEM_FALLARBOR_TOWN_NUGGET                       (FLAG_HIDDEN_ITEMS_START + 0x05)
#define FLAG_HIDDEN_ITEM_MT_PYRE_EXTERIOR_ULTRA_BALL                 (FLAG_HIDDEN_ITEMS_START + 0x06)
#define FLAG_HIDDEN_ITEM_ROUTE_115_HEART_SCALE                       (FLAG_HIDDEN_ITEMS_START + 0x07)
#define FLAG_HIDDEN_ITEM_ROUTE_119_FULL_HEAL                         (FLAG_HIDDEN_ITEMS_START + 0x08)
#define FLAG_HIDDEN_ITEM_ROUTE_120_RARE_CANDY                        (FLAG_HIDDEN_ITEMS_START + 0x09)
#define FLAG_HIDDEN_ITEM_ROUTE_121_REVIVE                            (FLAG_HIDDEN_ITEMS_START + 0x0A)
#define FLAG_HIDDEN_ITEM_ROUTE_121_ZINC                              (FLAG_HIDDEN_ITEMS_START + 0x0B)
#define FLAG_HIDDEN_ITEM_ROUTE_123_PP_UP                             (FLAG_HIDDEN_ITEMS_START + 0x0C)
#define FLAG_HIDDEN_ITEM_ROUTE_123_REVIVAL_HERB                      (FLAG_HIDDEN_ITEMS_START + 0x0D)
#define FLAG_HIDDEN_ITEM_ROUTE_125_BIG_PEARL                         (FLAG_HIDDEN_ITEMS_START + 0x0E)
#define FLAG_HIDDEN_ITEM_ROUTE_127_RARE_CANDY                        (FLAG_HIDDEN_ITEMS_START + 0x0F)
#define FLAG_HIDDEN_ITEM_ROUTE_132_PROTEIN                           (FLAG_HIDDEN_ITEMS_START + 0x10)
#define FLAG_HIDDEN_ITEM_ROUTE_133_MAX_REVIVE                        (FLAG_HIDDEN_ITEMS_START + 0x11)
#define FLAG_HIDDEN_ITEM_ROUTE_134_CARBOS                            (FLAG_HIDDEN_ITEMS_START + 0x12)
#define FLAG_HIDDEN_ITEM_ROUTE_134_STAR_PIECE                        (FLAG_HIDDEN_ITEMS_START + 0x13)
#define FLAG_HIDDEN_ITEM_ROUTE_114_ENERGY_POWDER                     (FLAG_HIDDEN_ITEMS_START + 0x14)
#define FLAG_HIDDEN_ITEM_ROUTE_115_PP_UP                             (FLAG_HIDDEN_ITEMS_START + 0x15)
#define FLAG_HIDDEN_ITEM_ARTISAN_CAVE_B1F_HP_UP                      (FLAG_HIDDEN_ITEMS_START + 0x16)
#define FLAG_HIDDEN_ITEM_ARTISAN_CAVE_1F_CARBOS                      (FLAG_HIDDEN_ITEMS_START + 0x17)
#define FLAG_HIDDEN_ITEM_MAGMA_HIDEOUT_2F_2R_MAX_ELIXIR              (FLAG_HIDDEN_ITEMS_START + 0x18)
#define FLAG_HIDDEN_ITEM_MAGMA_HIDEOUT_2F_2R_FULL_RESTORE            (FLAG_HIDDEN_ITEMS_START + 0x19)
#define FLAG_HIDDEN_ITEM_MAGMA_HIDEOUT_3F_1R_NUGGET                  (FLAG_HIDDEN_ITEMS_START + 0x1A)
#define FLAG_HIDDEN_ITEM_MAGMA_HIDEOUT_3F_2R_PP_MAX                  (FLAG_HIDDEN_ITEMS_START + 0x1B)
#define FLAG_HIDDEN_ITEM_MAGMA_HIDEOUT_4F_MAX_REVIVE                 (FLAG_HIDDEN_ITEMS_START + 0x1C)
#define FLAG_HIDDEN_ITEM_SAFARI_ZONE_NORTH_EAST_NUGGET               (FLAG_HIDDEN_ITEMS_START + 0x1D)
#define FLAG_HIDDEN_ITEM_SAFARI_ZONE_SOUTH_EAST_BIG_PEARL            (FLAG_HIDDEN_ITEMS_START + 0x1E)

#define FLAG_HIDDEN_ITEMS_END                                        FLAG_HIDDEN_ITEM_SAFARI_ZONE_SOUTH_EAST_BIG_PEARL

// Event object flags
#define FLAG_HIDE_OBJECTS_START                                      (FLAG_HIDDEN_ITEMS_END + 1)
#define FLAG_HIDE_RUSTBORO_CITY_SCIENTIST                            (FLAG_HIDE_OBJECTS_START + 0x00)
#define FLAG_HIDE_RUSTBORO_CITY_ROXANNE                              (FLAG_HIDE_OBJECTS_START + 0x01)
#define FLAG_HIDE_RUSTBORO_CITY_SCHOOL_KID                           (FLAG_HIDE_OBJECTS_START + 0x02)
#define FLAG_HIDE_RUSTBORO_CITY_RIVAL                                (FLAG_HIDE_OBJECTS_START + 0x03)
#define FLAG_HIDE_RUSTBORO_CITY_DEVON_CORP_PRESIDENT                 (FLAG_HIDE_OBJECTS_START + 0x04)
#define FLAG_HIDE_ROUTE_104_MR_BRINEY                                (FLAG_HIDE_OBJECTS_START + 0x05)
#define FLAG_HIDE_ROUTE_104_PEEKO                                   (FLAG_HIDE_OBJECTS_START + 0x06)
#define FLAG_HIDE_RUSTBORO_CITY_TRAVELING_MERCHANT                   (FLAG_HIDE_OBJECTS_START + 0x07)
#define FLAG_HIDE_RUSTBORO_CITY_WANDA                                (FLAG_HIDE_OBJECTS_START + 0x08)
#define FLAG_HIDE_RUSTBORO_CITY_WALLY                                (FLAG_HIDE_OBJECTS_START + 0x09)
#define FLAG_HIDE_RUSTBORO_CITY_POKE_BALL                            (FLAG_HIDE_OBJECTS_START + 0x0A)
#define FLAG_HIDE_RUSTBORO_CITY_DEVON_GOODS                          (FLAG_HIDE_OBJECTS_START + 0x0B)
#define FLAG_HIDE_RUSTBORO_CITY_GRUNT                                (FLAG_HIDE_OBJECTS_START + 0x0C)
#define FLAG_HIDE_ROUTE_104_DEVON_EMPLOYEE                           (FLAG_HIDE_OBJECTS_START + 0x0D)
#define FLAG_HIDE_ROUTE_104_BRINEY                                   (FLAG_HIDE_OBJECTS_START + 0x0E)
#define FLAG_HIDE_ROUTE_104_PEEKO_2                                 (FLAG_HIDE_OBJECTS_START + 0x0F)
#define FLAG_HIDE_PETALBURG_WOODS_DEVON_EMPLOYEE                     (FLAG_HIDE_OBJECTS_START + 0x10)
#define FLAG_HIDE_PETALBURG_WOODS_AQUA_GRUNT                         (FLAG_HIDE_OBJECTS_START + 0x11)
#define FLAG_HIDE_ROUTE_116_DEVON_EMPLOYEE                           (FLAG_HIDE_OBJECTS_START + 0x12)
#define FLAG_HIDE_ROUTE_116_AQUA_GRUNT                               (FLAG_HIDE_OBJECTS_START + 0x13)
#define FLAG_HIDE_ROUTE_116_MR_BRINEY                                (FLAG_HIDE_OBJECTS_START + 0x14)
#define FLAG_HIDE_ROUTE_116_PEEKO                                   (FLAG_HIDE_OBJECTS_START + 0x15)
#define FLAG_HIDE_RUSTURF_TUNNEL_WANDA                               (FLAG_HIDE_OBJECTS_START + 0x16)
#define FLAG_HIDE_RUSTURF_TUNNEL_ROCK_SMASH_GUY                      (FLAG_HIDE_OBJECTS_START + 0x17)
#define FLAG_HIDE_RUSTURF_TUNNEL_PEEKO                               (FLAG_HIDE_OBJECTS_START + 0x18)
#define FLAG_HIDE_RUSTURF_TUNNEL_AQUA_GRUNT                          (FLAG_HIDE_OBJECTS_START + 0x19)
#define FLAG_HIDE_ROUTE_116_MR_BRINEY_2                              (FLAG_HIDE_OBJECTS_START + 0x1A)
#define FLAG_HIDE_ROUTE_116_PEEKO_2                                 (FLAG_HIDE_OBJECTS_START + 0x1B)
#define FLAG_HIDE_ROUTE_116_DEVON_EMPLOYEE_2                         (FLAG_HIDE_OBJECTS_START + 0x1C)
#define FLAG_HIDE_ROUTE_116_AQUA_GRUNT_2                             (FLAG_HIDE_OBJECTS_START + 0x1D)
#define FLAG_HIDE_RUSTURF_TUNNEL_WANDA_2                             (FLAG_HIDE_OBJECTS_START + 0x1E)
#define FLAG_HIDE_RUSTURF_TUNNEL_ROCK_SMASH_GUY_2                    (FLAG_HIDE_OBJECTS_START + 0x1F)
#define FLAG_HIDE_RUSTURF_TUNNEL_PEEKO_2                             (FLAG_HIDE_OBJECTS_START + 0x20)
#define FLAG_HIDE_RUSTURF_TUNNEL_AQUA_GRUNT_2                        (FLAG_HIDE_OBJECTS_START + 0x21)
#define FLAG_HIDE_DEWFORD_TOWN_BRINEY                                (FLAG_HIDE_OBJECTS_START + 0x22)
#define FLAG_HIDE_DEWFORD_TOWN_PEEKO                                 (FLAG_HIDE_OBJECTS_START + 0x23)
#define FLAG_HIDE_DEWFORD_TOWN_WALLY                                 (FLAG_HIDE_OBJECTS_START + 0x24)
#define FLAG_HIDE_DEWFORD_TOWN_STEVEN                                (FLAG_HIDE_OBJECTS_START + 0x25)
#define FLAG_HIDE_GRANITE_CAVE_STEVEN                                (FLAG_HIDE_OBJECTS_START + 0x26)
#define FLAG_HIDE_GRANITE_CAVE_POKE_BALL                             (FLAG_HIDE_OBJECTS_START + 0x27)
#define FLAG_HIDE_ROUTE_106_BRINEY                                   (FLAG_HIDE_OBJECTS_START + 0x28)
#define FLAG_HIDE_ROUTE_106_PEEKO                                    (FLAG_HIDE_OBJECTS_START + 0x29)
#define FLAG_HIDE_SLATEPORT_CITY_TEAM_AQUA                           (FLAG_HIDE_OBJECTS_START + 0x2A)
#define FLAG_HIDE_SLATEPORT_CITY_GABBY_AND_TY                        (FLAG_HIDE_OBJECTS_START + 0x2B)
#define FLAG_HIDE_SLATEPORT_CITY_CAPT_STERN                          (FLAG_HIDE_OBJECTS_START + 0x2C)
#define FLAG_HIDE_SLATEPORT_CITY_ARCHIE                              (FLAG_HIDE_OBJECTS_START + 0x2D)
#define FLAG_HIDE_SLATEPORT_CITY_GRUNT_1                             (FLAG_HIDE_OBJECTS_START + 0x2E)
#define FLAG_HIDE_SLATEPORT_CITY_GRUNT_2                             (FLAG_HIDE_OBJECTS_START + 0x2F)
#define FLAG_HIDE_SLATEPORT_CITY_GRUNT_3                             (FLAG_HIDE_OBJECTS_START + 0x30)
#define FLAG_HIDE_ROUTE_110_TEAM_AQUA                                (FLAG_HIDE_OBJECTS_START + 0x31)
#define FLAG_HIDE_ROUTE_110_RIVAL                                    (FLAG_HIDE_OBJECTS_START + 0x32)
#define FLAG_HIDE_ROUTE_110_RIVAL_ON_BIKE                            (FLAG_HIDE_OBJECTS_START + 0x33)
#define FLAG_HIDE_ROUTE_110_BIRCH                                    (FLAG_HIDE_OBJECTS_START + 0x34)
#define FLAG_HIDE_ROUTE_103_RIVAL                                    (FLAG_HIDE_OBJECTS_START + 0x35)
#define FLAG_HIDE_ROUTE_103_TREECKO_BALL                             (FLAG_HIDE_OBJECTS_START + 0x36)
#define FLAG_HIDE_ROUTE_103_TORCHIC_BALL                             (FLAG_HIDE_OBJECTS_START + 0x37)
#define FLAG_HIDE_ROUTE_103_MUDKIP_BALL                              (FLAG_HIDE_OBJECTS_START + 0x38)
#define FLAG_HIDE_LITTLEROOT_TOWN_BIRCH                              (FLAG_HIDE_OBJECTS_START + 0x39)
#define FLAG_HIDE_LITTLEROOT_TOWN_MOM                                (FLAG_HIDE_OBJECTS_START + 0x3A)
#define FLAG_HIDE_LITTLEROOT_TOWN_RIVAL                              (FLAG_HIDE_OBJECTS_START + 0x3B)
#define FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB                         (FLAG_HIDE_OBJECTS_START + 0x3C)
#define FLAG_HIDE_LITTLEROOT_TOWN_MOVING_TRUCK                       (FLAG_HIDE_OBJECTS_START + 0x3D)
#define FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_HOUSE                      (FLAG_HIDE_OBJECTS_START + 0x3E)
#define FLAG_HIDE_LITTLEROOT_TOWN_RIVALS_HOUSE                       (FLAG_HIDE_OBJECTS_START + 0x3F)
#define FLAG_HIDE_OLDALE_TOWN_BOY                                    (FLAG_HIDE_OBJECTS_START + 0x40)
#define FLAG_HIDE_OLDALE_TOWN_GIRL                                   (FLAG_HIDE_OBJECTS_START + 0x41)
#define FLAG_HIDE_OLDALE_TOWN_MART_EMPLOYEE                          (FLAG_HIDE_OBJECTS_START + 0x42)
#define FLAG_HIDE_PETALBURG_CITY_WALLY                               (FLAG_HIDE_OBJECTS_START + 0x43)
#define FLAG_HIDE_PETALBURG_CITY_NORMAN                              (FLAG_HIDE_OBJECTS_START + 0x44)
#define FLAG_HIDE_PETALBURG_CITY_WALLYS_MOM                          (FLAG_HIDE_OBJECTS_START + 0x45)
#define FLAG_HIDE_PETALBURG_CITY_WALLYS_DAD                          (FLAG_HIDE_OBJECTS_START + 0x46)
#define FLAG_HIDE_PETALBURG_CITY_BOY                                 (FLAG_HIDE_OBJECTS_START + 0x47)
#define FLAG_HIDE_PETALBURG_CITY_GIRL                                (FLAG_HIDE_OBJECTS_START + 0x48)
#define FLAG_HIDE_PETALBURG_CITY_POKE_BALL                           (FLAG_HIDE_OBJECTS_START + 0x49)
#define FLAG_HIDE_PETALBURG_GYM_NORMAN                               (FLAG_HIDE_OBJECTS_START + 0x4A)
#define FLAG_HIDE_PETALBURG_GYM_WALLYS_DAD                           (FLAG_HIDE_OBJECTS_START + 0x4B)
#define FLAG_HIDE_PETALBURG_GYM_WALLY                                (FLAG_HIDE_OBJECTS_START + 0x4C)
#define FLAG_HIDE_PETALBURG_GYM_GYM_GUIDE                            (FLAG_HIDE_OBJECTS_START + 0x4D)
#define FLAG_HIDE_PETALBURG_GYM_DOOR_1                               (FLAG_HIDE_OBJECTS_START + 0x4E)
#define FLAG_HIDE_PETALBURG_GYM_DOOR_2                               (FLAG_HIDE_OBJECTS_START + 0x4F)
#define FLAG_HIDE_PETALBURG_GYM_DOOR_3                               (FLAG_HIDE_OBJECTS_START + 0x50)
#define FLAG_HIDE_PETALBURG_GYM_DOOR_4                               (FLAG_HIDE_OBJECTS_START + 0x51)
#define FLAG_HIDE_PETALBURG_GYM_DOOR_5                               (FLAG_HIDE_OBJECTS_START + 0x52)
#define FLAG_HIDE_PETALBURG_GYM_DOOR_6                               (FLAG_HIDE_OBJECTS_START + 0x53)
#define FLAG_HIDE_PETALBURG_GYM_DOOR_7                               (FLAG_HIDE_OBJECTS_START + 0x54)
#define FLAG_HIDE_PETALBURG_GYM_DOOR_8                               (FLAG_HIDE_OBJECTS_START + 0x55)
#define FLAG_HIDE_RUSTBORO_GYM_ROXANNE                               (FLAG_HIDE_OBJECTS_START + 0x56)
#define FLAG_HIDE_RUSTBORO_GYM_GYM_GUIDE                             (FLAG_HIDE_OBJECTS_START + 0x57)
#define FLAG_HIDE_RUSTBORO_GYM_DOOR                                  (FLAG_HIDE_OBJECTS_START + 0x58)
#define FLAG_HIDE_DEWFORD_GYM_BRAWLY                                 (FLAG_HIDE_OBJECTS_START + 0x59)
#define FLAG_HIDE_DEWFORD_GYM_GYM_GUIDE                              (FLAG_HIDE_OBJECTS_START + 0x5A)
#define FLAG_HIDE_MAUVILLE_GYM_WATTSON                               (FLAG_HIDE_OBJECTS_START + 0x5B)
#define FLAG_HIDE_MAUVILLE_GYM_GYM_GUIDE                             (FLAG_HIDE_OBJECTS_START + 0x5C)
#define FLAG_HIDE_LAVARIDGE_GYM_FLANNERY                             (FLAG_HIDE_OBJECTS_START + 0x5D)
#define FLAG_HIDE_LAVARIDGE_GYM_GYM_GUIDE                            (FLAG_HIDE_OBJECTS_START + 0x5E)
#define FLAG_HIDE_FORTREE_GYM_WINONA                                 (FLAG_HIDE_OBJECTS_START + 0x5F)
#define FLAG_HIDE_FORTREE_GYM_GYM_GUIDE                              (FLAG_HIDE_OBJECTS_START + 0x60)
#define FLAG_HIDE_MOSSDEEP_GYM_TATE_AND_LIZA                         (FLAG_HIDE_OBJECTS_START + 0x61)
#define FLAG_HIDE_MOSSDEEP_GYM_GYM_GUIDE                             (FLAG_HIDE_OBJECTS_START + 0x62)
#define FLAG_HIDE_SOOTOPOLIS_GYM_JUAN                                (FLAG_HIDE_OBJECTS_START + 0x63)
#define FLAG_HIDE_SOOTOPOLIS_GYM_GYM_GUIDE                           (FLAG_HIDE_OBJECTS_START + 0x64)
#define FLAG_HIDE_EVER_GRANDE_CHAMPION                               (FLAG_HIDE_OBJECTS_START + 0x65)
#define FLAG_HIDE_EVER_GRANDE_ELITE_FOUR_1                           (FLAG_HIDE_OBJECTS_START + 0x66)
#define FLAG_HIDE_EVER_GRANDE_ELITE_FOUR_2                           (FLAG_HIDE_OBJECTS_START + 0x67)
#define FLAG_HIDE_EVER_GRANDE_ELITE_FOUR_3                           (FLAG_HIDE_OBJECTS_START + 0x68)
#define FLAG_HIDE_EVER_GRANDE_ELITE_FOUR_4                           (FLAG_HIDE_OBJECTS_START + 0x69)
#define FLAG_HIDE_EVER_GRANDE_CHAMPION_ROOM_DOOR                     (FLAG_HIDE_OBJECTS_START + 0x6A)
#define FLAG_HIDE_BATTLE_FRONTIER_SCOTT                              (FLAG_HIDE_OBJECTS_START + 0x6B)
#define FLAG_HIDE_BATTLE_FRONTIER_BRAIN                              (FLAG_HIDE_OBJECTS_START + 0x6C)
#define FLAG_HIDE_BATTLE_FRONTIER_SYMBOL                             (FLAG_HIDE_OBJECTS_START + 0x6D)
#define FLAG_HIDE_BATTLE_FRONTIER_TOWER_RECEPTIONIST                 (FLAG_HIDE_OBJECTS_START + 0x6E)
#define FLAG_HIDE_BATTLE_FRONTIER_DOME_RECEPTIONIST                  (FLAG_HIDE_OBJECTS_START + 0x6F)
#define FLAG_HIDE_BATTLE_FRONTIER_PALACE_RECEPTIONIST                (FLAG_HIDE_OBJECTS_START + 0x70)
#define FLAG_HIDE_BATTLE_FRONTIER_ARENA_RECEPTIONIST                 (FLAG_HIDE_OBJECTS_START + 0x71)
#define FLAG_HIDE_BATTLE_FRONTIER_FACTORY_RECEPTIONIST               (FLAG_HIDE_OBJECTS_START + 0x72)
#define FLAG_HIDE_BATTLE_FRONTIER_PIKE_RECEPTIONIST                  (FLAG_HIDE_OBJECTS_START + 0x73)
#define FLAG_HIDE_BATTLE_FRONTIER_PYRAMID_RECEPTIONIST               (FLAG_HIDE_OBJECTS_START + 0x74)
#define FLAG_HIDE_BATTLE_FRONTIER_RECORD_HALL_RECEPTIONIST           (FLAG_HIDE_OBJECTS_START + 0x75)
#define FLAG_HIDE_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER_CLERK      (FLAG_HIDE_OBJECTS_START + 0x76)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_POINT_EXCHANGE_SERVICE_CLERK (FLAG_HIDE_OBJECTS_START + 0x77)
#define FLAG_HIDE_BATTLE_FRONTIER_MOVE_TUTOR                         (FLAG_HIDE_OBJECTS_START + 0x78)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER         (FLAG_HIDE_OBJECTS_START + 0x79)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_LINK_MULTI_PARTNER    (FLAG_HIDE_OBJECTS_START + 0x7A)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_OPPONENT              (FLAG_HIDE_OBJECTS_START + 0x7B)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_DOME_OPPONENT               (FLAG_HIDE_OBJECTS_START + 0x7C)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PALACE_OPPONENT             (FLAG_HIDE_OBJECTS_START + 0x7D)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_ARENA_OPPONENT              (FLAG_HIDE_OBJECTS_START + 0x7E)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_FACTORY_OPPONENT            (FLAG_HIDE_OBJECTS_START + 0x7F)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PIKE_OPPONENT               (FLAG_HIDE_OBJECTS_START + 0x80)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PYRAMID_OPPONENT            (FLAG_HIDE_OBJECTS_START + 0x81)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_BRAIN                 (FLAG_HIDE_OBJECTS_START + 0x82)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_DOME_BRAIN                  (FLAG_HIDE_OBJECTS_START + 0x83)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PALACE_BRAIN                (FLAG_HIDE_OBJECTS_START + 0x84)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_ARENA_BRAIN                 (FLAG_HIDE_OBJECTS_START + 0x85)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_FACTORY_BRAIN               (FLAG_HIDE_OBJECTS_START + 0x86)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PIKE_BRAIN                  (FLAG_HIDE_OBJECTS_START + 0x87)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PYRAMID_BRAIN               (FLAG_HIDE_OBJECTS_START + 0x88)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_SYMBOL                (FLAG_HIDE_OBJECTS_START + 0x89)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_DOME_SYMBOL                 (FLAG_HIDE_OBJECTS_START + 0x8A)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PALACE_SYMBOL               (FLAG_HIDE_OBJECTS_START + 0x8B)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_ARENA_SYMBOL                (FLAG_HIDE_OBJECTS_START + 0x8C)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_FACTORY_SYMBOL              (FLAG_HIDE_OBJECTS_START + 0x8D)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PIKE_SYMBOL                 (FLAG_HIDE_OBJECTS_START + 0x8E)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PYRAMID_SYMBOL              (FLAG_HIDE_OBJECTS_START + 0x8F)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_RECEPTIONIST_2        (FLAG_HIDE_OBJECTS_START + 0x90)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_DOME_RECEPTIONIST_2         (FLAG_HIDE_OBJECTS_START + 0x91)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PALACE_RECEPTIONIST_2       (FLAG_HIDE_OBJECTS_START + 0x92)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_ARENA_RECEPTIONIST_2        (FLAG_HIDE_OBJECTS_START + 0x93)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_FACTORY_RECEPTIONIST_2      (FLAG_HIDE_OBJECTS_START + 0x94)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PIKE_RECEPTIONIST_2         (FLAG_HIDE_OBJECTS_START + 0x95)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PYRAMID_RECEPTIONIST_2      (FLAG_HIDE_OBJECTS_START + 0x96)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_2       (FLAG_HIDE_OBJECTS_START + 0x97)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_LINK_MULTI_PARTNER_2  (FLAG_HIDE_OBJECTS_START + 0x98)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_OPPONENT_2            (FLAG_HIDE_OBJECTS_START + 0x99)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_DOME_OPPONENT_2             (FLAG_HIDE_OBJECTS_START + 0x9A)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PALACE_OPPONENT_2           (FLAG_HIDE_OBJECTS_START + 0x9B)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_ARENA_OPPONENT_2            (FLAG_HIDE_OBJECTS_START + 0x9C)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_FACTORY_OPPONENT_2          (FLAG_HIDE_OBJECTS_START + 0x9D)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PIKE_OPPONENT_2             (FLAG_HIDE_OBJECTS_START + 0x9E)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PYRAMID_OPPONENT_2          (FLAG_HIDE_OBJECTS_START + 0x9F)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_BRAIN_2               (FLAG_HIDE_OBJECTS_START + 0xA0)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_DOME_BRAIN_2                (FLAG_HIDE_OBJECTS_START + 0xA1)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PALACE_BRAIN_2              (FLAG_HIDE_OBJECTS_START + 0xA2)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_ARENA_BRAIN_2               (FLAG_HIDE_OBJECTS_START + 0xA3)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_FACTORY_BRAIN_2             (FLAG_HIDE_OBJECTS_START + 0xA4)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PIKE_BRAIN_2                (FLAG_HIDE_OBJECTS_START + 0xA5)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PYRAMID_BRAIN_2             (FLAG_HIDE_OBJECTS_START + 0xA6)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_SYMBOL_2              (FLAG_HIDE_OBJECTS_START + 0xA7)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_DOME_SYMBOL_2               (FLAG_HIDE_OBJECTS_START + 0xA8)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PALACE_SYMBOL_2             (FLAG_HIDE_OBJECTS_START + 0xA9)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_ARENA_SYMBOL_2              (FLAG_HIDE_OBJECTS_START + 0xAA)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_FACTORY_SYMBOL_2            (FLAG_HIDE_OBJECTS_START + 0xAB)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PIKE_SYMBOL_2               (FLAG_HIDE_OBJECTS_START + 0xAC)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PYRAMID_SYMBOL_2            (FLAG_HIDE_OBJECTS_START + 0xAD)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_RECEPTIONIST_3        (FLAG_HIDE_OBJECTS_START + 0xAE)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_DOME_RECEPTIONIST_3         (FLAG_HIDE_OBJECTS_START + 0xAF)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PALACE_RECEPTIONIST_3       (FLAG_HIDE_OBJECTS_START + 0xB0)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_ARENA_RECEPTIONIST_3        (FLAG_HIDE_OBJECTS_START + 0xB1)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_FACTORY_RECEPTIONIST_3      (FLAG_HIDE_OBJECTS_START + 0xB2)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PIKE_RECEPTIONIST_3         (FLAG_HIDE_OBJECTS_START + 0xB3)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PYRAMID_RECEPTIONIST_3      (FLAG_HIDE_OBJECTS_START + 0xB4)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_3       (FLAG_HIDE_OBJECTS_START + 0xB5)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_LINK_MULTI_PARTNER_3  (FLAG_HIDE_OBJECTS_START + 0xB6)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_OPPONENT_3            (FLAG_HIDE_OBJECTS_START + 0xB7)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_DOME_OPPONENT_3             (FLAG_HIDE_OBJECTS_START + 0xB8)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PALACE_OPPONENT_3           (FLAG_HIDE_OBJECTS_START + 0xB9)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_ARENA_OPPONENT_3            (FLAG_HIDE_OBJECTS_START + 0xBA)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_FACTORY_OPPONENT_3          (FLAG_HIDE_OBJECTS_START + 0xBB)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PIKE_OPPONENT_3             (FLAG_HIDE_OBJECTS_START + 0xBC)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PYRAMID_OPPONENT_3          (FLAG_HIDE_OBJECTS_START + 0xBD)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_BRAIN_3               (FLAG_HIDE_OBJECTS_START + 0xBE)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_DOME_BRAIN_3                (FLAG_HIDE_OBJECTS_START + 0xBF)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PALACE_BRAIN_3              (FLAG_HIDE_OBJECTS_START + 0xC0)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_ARENA_BRAIN_3               (FLAG_HIDE_OBJECTS_START + 0xC1)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_FACTORY_BRAIN_3             (FLAG_HIDE_OBJECTS_START + 0xC2)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PIKE_BRAIN_3                (FLAG_HIDE_OBJECTS_START + 0xC3)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PYRAMID_BRAIN_3             (FLAG_HIDE_OBJECTS_START + 0xC4)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_TOWER_SYMBOL_3              (FLAG_HIDE_OBJECTS_START + 0xC5)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_DOME_SYMBOL_3               (FLAG_HIDE_OBJECTS_START + 0xC6)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PALACE_SYMBOL_3             (FLAG_HIDE_OBJECTS_START + 0xC7)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_ARENA_SYMBOL_3              (FLAG_HIDE_OBJECTS_START + 0xC8)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_FACTORY_SYMBOL_3            (FLAG_HIDE_OBJECTS_START + 0xC9)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PIKE_SYMBOL_3               (FLAG_HIDE_OBJECTS_START + 0xCA)
#define FLAG_HIDE_BATTLE_FRONTIER_BATTLE_PYRAMID_SYMBOL_3            (FLAG_HIDE_OBJECTS_START + 0xCB)

#define FLAG_HIDE_OBJECTS_END                                        (FLAG_HIDE_OBJECTS_START + 0x1FF)

// Item ball flags
#define FLAG_ITEMBALLS_START                                         (FLAG_HIDE_OBJECTS_END + 1)
#define FLAG_ITEM_ROUTE_102_POTION                                   (FLAG_ITEMBALLS_START + 0x00)
#define FLAG_ITEM_PETALBURG_WOODS_PARALYZE_HEAL                      (FLAG_ITEMBALLS_START + 0x01)
#define FLAG_ITEM_PETALBURG_WOODS_GREAT_BALL                         (FLAG_ITEMBALLS_START + 0x02)
#define FLAG_ITEM_ROUTE_104_X_ACCURACY                               (FLAG_ITEMBALLS_START + 0x03)
#define FLAG_ITEM_ROUTE_104_POTION                                   (FLAG_ITEMBALLS_START + 0x04)
#define FLAG_ITEM_RUSTBORO_CITY_X_DEFENSE                            (FLAG_ITEMBALLS_START + 0x05)
#define FLAG_ITEM_ROUTE_116_REPEL                                    (FLAG_ITEMBALLS_START + 0x06)
#define FLAG_ITEM_ROUTE_116_X_SPECIAL                                (FLAG_ITEMBALLS_START + 0x07)
#define FLAG_ITEM_ROUTE_116_ETHER                                    (FLAG_ITEMBALLS_START + 0x08)
#define FLAG_ITEM_RUSTURF_TUNNEL_POKE_BALL                           (FLAG_ITEMBALLS_START + 0x09)
#define FLAG_ITEM_GRANITE_CAVE_1F_ESCAPE_ROPE                        (FLAG_ITEMBALLS_START + 0x0A)
#define FLAG_ITEM_GRANITE_CAVE_B1F_POKE_BALL                         (FLAG_ITEMBALLS_START + 0x0B)
#define FLAG_ITEM_GRANITE_CAVE_B2F_REPEL                             (FLAG_ITEMBALLS_START + 0x0C)
#define FLAG_ITEM_ROUTE_109_POTION                                   (FLAG_ITEMBALLS_START + 0x0D)
#define FLAG_ITEM_ROUTE_109_HEART_SCALE                              (FLAG_ITEMBALLS_START + 0x0E)
#define FLAG_ITEM_ROUTE_110_DIRE_HIT                                 (FLAG_ITEMBALLS_START + 0x0F)
#define FLAG_ITEM_ROUTE_110_RARE_CANDY                               (FLAG_ITEMBALLS_START + 0x10)
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_1_ORANGE_MAIL                   (FLAG_ITEMBALLS_START + 0x11)
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_1_HARBOR_MAIL                   (FLAG_ITEMBALLS_START + 0x12)
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_2_WAVE_MAIL                     (FLAG_ITEMBALLS_START + 0x13)
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_2_HARBOR_MAIL                   (FLAG_ITEMBALLS_START + 0x14)
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_3_SHADOW_MAIL                   (FLAG_ITEMBALLS_START + 0x15)
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_3_WOOD_MAIL                     (FLAG_ITEMBALLS_START + 0x16)
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_4_MECH_MAIL                     (FLAG_ITEMBALLS_START + 0x17)
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_4_SMOKE_BALL                    (FLAG_ITEMBALLS_START + 0x18)
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_5_TM_TAUNT                      (FLAG_ITEMBALLS_START + 0x19)
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_5_HARBOR_MAIL                   (FLAG_ITEMBALLS_START + 0x1A)
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_6_GLITTER_MAIL                  (FLAG_ITEMBALLS_START + 0x1B)
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_7_TROPIC_MAIL                   (FLAG_ITEMBALLS_START + 0x1C)
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_8_BEAD_MAIL                     (FLAG_ITEMBALLS_START + 0x1D)
#define FLAG_ITEM_JAGGED_PASS_BURN_HEAL                              (FLAG_ITEMBALLS_START + 0x1E)
#define FLAG_ITEM_AQUA_HIDEOUT_B1F_MAX_ELIXIR                        (FLAG_ITEMBALLS_START + 0x1F)
#define FLAG_ITEM_AQUA_HIDEOUT_B2F_NEST_BALL                         (FLAG_ITEMBALLS_START + 0x20)
#define FLAG_ITEM_MT_PYRE_EXTERIOR_MAX_POTION                        (FLAG_ITEMBALLS_START + 0x21)
#define FLAG_ITEM_MT_PYRE_EXTERIOR_TM_SKILL_SWAP                     (FLAG_ITEMBALLS_START + 0x22)
#define FLAG_ITEM_NEW_MAUVILLE_ULTRA_BALL                            (FLAG_ITEMBALLS_START + 0x23)
#define FLAG_ITEM_NEW_MAUVILLE_ESCAPE_ROPE                           (FLAG_ITEMBALLS_START + 0x24)
#define FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_6_LUXURY_BALL    (FLAG_ITEMBALLS_START + 0x25)
#define FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_2_SCANNER        (FLAG_ITEMBALLS_START + 0x26)
#define FLAG_ITEM_SCORCHED_SLAB_TM_SUNNY_DAY                         (FLAG_ITEMBALLS_START + 0x27)
#define FLAG_ITEM_METEOR_FALLS_B1F_2R_TM_DRAGON_CLAW                 (FLAG_ITEMBALLS_START + 0x28)
#define FLAG_ITEM_SHOAL_CAVE_ENTRANCE_BIG_PEARL                      (FLAG_ITEMBALLS_START + 0x29)
#define FLAG_ITEM_SHOAL_CAVE_INNER_ROOM_RARE_CANDY                   (FLAG_ITEMBALLS_START + 0x2A)
#define FLAG_ITEM_VICTORY_ROAD_1F_MAX_ELIXIR                         (FLAG_ITEMBALLS_START + 0x2B)
#define FLAG_ITEM_VICTORY_ROAD_1F_PP_UP                              (FLAG_ITEMBALLS_START + 0x2C)
#define FLAG_ITEM_VICTORY_ROAD_B1F_TM_PSYCHIC                        (FLAG_ITEMBALLS_START + 0x2D)
#define FLAG_ITEM_VICTORY_ROAD_B1F_FULL_RESTORE                      (FLAG_ITEMBALLS_START + 0x2E)
#define FLAG_ITEM_VICTORY_ROAD_B2F_FULL_HEAL                         (FLAG_ITEMBALLS_START + 0x2F)
#define FLAG_ITEM_MT_PYRE_6F_TM_SHADOW_BALL                          (FLAG_ITEMBALLS_START + 0x30)
#define FLAG_ITEM_SEAFLOOR_CAVERN_ROOM_9_TM_EARTHQUAKE               (FLAG_ITEMBALLS_START + 0x31)
#define FLAG_ITEM_FIERY_PATH_TM_TOXIC                                (FLAG_ITEMBALLS_START + 0x32)
#define FLAG_ITEM_ROUTE_124_RED_SHARD                                (FLAG_ITEMBALLS_START + 0x33)
#define FLAG_ITEM_ROUTE_124_BLUE_SHARD                               (FLAG_ITEMBALLS_START + 0x34)
#define FLAG_ITEM_SAFARI_ZONE_NORTH_WEST_TM_SOLAR_BEAM               (FLAG_ITEMBALLS_START + 0x35)
#define FLAG_ITEM_ABANDONED_SHIP_ROOMS_1F_HARBOR_MAIL                (FLAG_ITEMBALLS_START + 0x36)
#define FLAG_ITEM_ABANDONED_SHIP_ROOMS_B1F_ESCAPE_ROPE               (FLAG_ITEMBALLS_START + 0x37)
#define FLAG_ITEM_ABANDONED_SHIP_ROOMS_2_B1F_DIVE_BALL               (FLAG_ITEMBALLS_START + 0x38)
#define FLAG_ITEM_ABANDONED_SHIP_ROOMS_B1F_TM_ICE_BEAM               (FLAG_ITEMBALLS_START + 0x39)
#define FLAG_ITEM_ABANDONED_SHIP_ROOMS_2_1F_REVIVE                   (FLAG_ITEMBALLS_START + 0x3A)
#define FLAG_ITEM_ABANDONED_SHIP_CAPTAINS_OFFICE_STORAGE_KEY         (FLAG_ITEMBALLS_START + 0x3B)
#define FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_3_WATER_STONE    (FLAG_ITEMBALLS_START + 0x3C)
#define FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_1_TM_RAIN_DANCE  (FLAG_ITEMBALLS_START + 0x3D)
#define FLAG_ITEM_ROUTE_121_CARBOS                                   (FLAG_ITEMBALLS_START + 0x3E)
#define FLAG_ITEM_ROUTE_123_ULTRA_BALL                               (FLAG_ITEMBALLS_START + 0x3F)
#define FLAG_ITEM_ROUTE_126_GREEN_SHARD                              (FLAG_ITEMBALLS_START + 0x40)
#define FLAG_ITEM_ROUTE_119_HYPER_POTION_2                           (FLAG_ITEMBALLS_START + 0x41)
#define FLAG_ITEM_ROUTE_120_HYPER_POTION                             (FLAG_ITEMBALLS_START + 0x42)
#define FLAG_ITEM_ROUTE_120_NEST_BALL                                (FLAG_ITEMBALLS_START + 0x43)
#define FLAG_ITEM_ROUTE_123_ELIXIR                                   (FLAG_ITEMBALLS_START + 0x44)
#define FLAG_ITEM_NEW_MAUVILLE_THUNDER_STONE                         (FLAG_ITEMBALLS_START + 0x45)
#define FLAG_ITEM_FIERY_PATH_FIRE_STONE                              (FLAG_ITEMBALLS_START + 0x46)
#define FLAG_ITEM_SHOAL_CAVE_ICE_ROOM_TM_HAIL                        (FLAG_ITEMBALLS_START + 0x47)
#define FLAG_ITEM_SHOAL_CAVE_ICE_ROOM_NEVER_MELT_ICE                 (FLAG_ITEMBALLS_START + 0x48)
#define FLAG_ITEM_ROUTE_103_GUARD_SPEC                               (FLAG_ITEMBALLS_START + 0x49)
#define FLAG_ITEM_ROUTE_104_X_ACCURACY                               (FLAG_ITEMBALLS_START + 0x4A)
#define FLAG_ITEM_MAUVILLE_CITY_X_SPEED                              (FLAG_ITEMBALLS_START + 0x4B)
#define FLAG_ITEM_PETALBURG_WOODS_PARALYZE_HEAL                      (FLAG_ITEMBALLS_START + 0x4C)
#define FLAG_ITEM_ROUTE_115_GREAT_BALL                               (FLAG_ITEMBALLS_START + 0x4D)
#define FLAG_ITEM_SAFARI_ZONE_NORTH_CALCIUM                          (FLAG_ITEMBALLS_START + 0x4E)
#define FLAG_ITEM_MT_PYRE_3F_SUPER_REPEL                             (FLAG_ITEMBALLS_START + 0x4F)
#define FLAG_ITEM_ROUTE_118_HYPER_POTION                             (FLAG_ITEMBALLS_START + 0x50)
#define FLAG_ITEM_NEW_MAUVILLE_FULL_HEAL                             (FLAG_ITEMBALLS_START + 0x51)
#define FLAG_ITEM_NEW_MAUVILLE_PARALYZE_HEAL                         (FLAG_ITEMBALLS_START + 0x52)
#define FLAG_ITEM_AQUA_HIDEOUT_B1F_MASTER_BALL                       (FLAG_ITEMBALLS_START + 0x53)
#define FLAG_ITEM_OLD_MAGMA_HIDEOUT_B1F_MASTER_BALL                  (FLAG_ITEMBALLS_START + 0x54) // Unused Flag, leftover from the Ruby Magma hideout
#define FLAG_ITEM_OLD_MAGMA_HIDEOUT_B1F_MAX_ELIXIR                   (FLAG_ITEMBALLS_START + 0x55) // Unused Flag, leftover from the Ruby Magma hideout
#define FLAG_ITEM_OLD_MAGMA_HIDEOUT_B2F_NEST_BALL                    (FLAG_ITEMBALLS_START + 0x56) // Unused Flag, leftover from the Ruby Magma hideout
#define FLAG_UNUSED_0x468                                            (FLAG_ITEMBALLS_START + 0x57) // Unused Flag
#define FLAG_ITEM_MT_PYRE_2F_ULTRA_BALL                              (FLAG_ITEMBALLS_START + 0x58)
#define FLAG_ITEM_MT_PYRE_4F_SEA_INCENSE                             (FLAG_ITEMBALLS_START + 0x59)
#define FLAG_ITEM_SAFARI_ZONE_SOUTH_WEST_MAX_REVIVE                  (FLAG_ITEMBALLS_START + 0x5A)
#define FLAG_ITEM_AQUA_HIDEOUT_B1F_NUGGET                            (FLAG_ITEMBALLS_START + 0x5B)
#define FLAG_ITEM_MOSSDEEP_STEVENS_HOUSE_HM08                        (FLAG_ITEMBALLS_START + 0x5C) // Unused Flag, leftover from R/S. HM08 is given to the player directly in Emerald
#define FLAG_ITEM_ROUTE_119_NUGGET                                   (FLAG_ITEMBALLS_START + 0x5D)
#define FLAG_ITEM_ROUTE_104_POTION                                   (FLAG_ITEMBALLS_START + 0x5E)
#define FLAG_UNUSED_0x470                                            (FLAG_ITEMBALLS_START + 0x5F) // Unused Flag
#define FLAG_ITEM_ROUTE_103_PP_UP                                    (FLAG_ITEMBALLS_START + 0x60)
#define FLAG_UNUSED_0x472                                            (FLAG_ITEMBALLS_START + 0x61) // Unused Flag
#define FLAG_ITEM_ROUTE_108_STAR_PIECE                               (FLAG_ITEMBALLS_START + 0x62)
#define FLAG_ITEM_ROUTE_109_POTION                                   (FLAG_ITEMBALLS_START + 0x63)
#define FLAG_ITEM_ROUTE_110_ELIXIR                                   (FLAG_ITEMBALLS_START + 0x64)
#define FLAG_ITEM_ROUTE_111_ELIXIR                                   (FLAG_ITEMBALLS_START + 0x65)
#define FLAG_ITEM_ROUTE_113_HYPER_POTION                             (FLAG_ITEMBALLS_START + 0x66)
#define FLAG_ITEM_ROUTE_115_HEAL_POWDER                              (FLAG_ITEMBALLS_START + 0x67)
#define FLAG_UNUSED_0x479                                            (FLAG_ITEMBALLS_START + 0x68) // Unused Flag
#define FLAG_ITEM_ROUTE_116_POTION                                   (FLAG_ITEMBALLS_START + 0x69)
#define FLAG_ITEM_ROUTE_119_ELIXIR_2                                 (FLAG_ITEMBALLS_START + 0x6A)
#define FLAG_ITEM_ROUTE_120_REVIVE                                   (FLAG_ITEMBALLS_START + 0x6B)
#define FLAG_ITEM_ROUTE_121_REVIVE                                   (FLAG_ITEMBALLS_START + 0x6C)
#define FLAG_ITEM_ROUTE_121_ZINC                                     (FLAG_ITEMBALLS_START + 0x6D)
#define FLAG_ITEM_MAGMA_HIDEOUT_1F_RARE_CANDY                        (FLAG_ITEMBALLS_START + 0x6E)
#define FLAG_ITEM_ROUTE_123_PP_UP                                    (FLAG_ITEMBALLS_START + 0x6F)
#define FLAG_ITEM_ROUTE_123_REVIVAL_HERB                             (FLAG_ITEMBALLS_START + 0x70)
#define FLAG_ITEM_ROUTE_125_BIG_PEARL                                (FLAG_ITEMBALLS_START + 0x71)
#define FLAG_ITEM_ROUTE_127_RARE_CANDY                               (FLAG_ITEMBALLS_START + 0x72)
#define FLAG_ITEM_ROUTE_132_PROTEIN                                  (FLAG_ITEMBALLS_START + 0x73)
#define FLAG_ITEM_ROUTE_133_MAX_REVIVE                               (FLAG_ITEMBALLS_START + 0x74)
#define FLAG_ITEM_ROUTE_134_CARBOS                                   (FLAG_ITEMBALLS_START + 0x75)
#define FLAG_ITEM_ROUTE_134_STAR_PIECE                               (FLAG_ITEMBALLS_START + 0x76)
#define FLAG_ITEM_ROUTE_114_ENERGY_POWDER                            (FLAG_ITEMBALLS_START + 0x77)
#define FLAG_ITEM_ROUTE_115_PP_UP                                    (FLAG_ITEMBALLS_START + 0x78)
#define FLAG_ITEM_ARTISAN_CAVE_B1F_HP_UP                             (FLAG_ITEMBALLS_START + 0x79)
#define FLAG_ITEM_ARTISAN_CAVE_1F_CARBOS                             (FLAG_ITEMBALLS_START + 0x7A)
#define FLAG_ITEM_MAGMA_HIDEOUT_2F_2R_MAX_ELIXIR                     (FLAG_ITEMBALLS_START + 0x7B)
#define FLAG_ITEM_MAGMA_HIDEOUT_2F_2R_FULL_RESTORE                   (FLAG_ITEMBALLS_START + 0x7C)
#define FLAG_ITEM_MAGMA_HIDEOUT_3F_1R_NUGGET                         (FLAG_ITEMBALLS_START + 0x7D)
#define FLAG_ITEM_MAGMA_HIDEOUT_3F_2R_PP_MAX                         (FLAG_ITEMBALLS_START + 0x7E)
#define FLAG_ITEM_MAGMA_HIDEOUT_4F_MAX_REVIVE                        (FLAG_ITEMBALLS_START + 0x7F)
#define FLAG_ITEM_SAFARI_ZONE_NORTH_EAST_NUGGET                      (FLAG_ITEMBALLS_START + 0x80)
#define FLAG_ITEM_SAFARI_ZONE_SOUTH_EAST_BIG_PEARL                   (FLAG_ITEMBALLS_START + 0x81)

#define FLAG_ITEMBALLS_END                                           FLAG_ITEM_SAFARI_ZONE_SOUTH_EAST_BIG_PEARL

// System Flags
#define SYSTEM_FLAGS (FLAG_ITEMBALLS_END + 1)
#define FLAG_SYS_POKEDEX_GET                       (SYSTEM_FLAGS + 0x0)
#define FLAG_SYS_POKEMON_GET                       (SYSTEM_FLAGS + 0x1)
#define FLAG_SYS_POKENAV_GET                       (SYSTEM_FLAGS + 0x2)
#define FLAG_SYS_GAME_CLEAR                        (SYSTEM_FLAGS + 0x3)
#define FLAG_SYS_CHAT_USED                         (SYSTEM_FLAGS + 0x4)
#define FLAG_SYS_HIPSTER_MEET                      (SYSTEM_FLAGS + 0x5)
#define FLAG_BADGE01_GET                           (SYSTEM_FLAGS + 0x6)
#define FLAG_BADGE02_GET                           (SYSTEM_FLAGS + 0x7)
#define FLAG_BADGE03_GET                           (SYSTEM_FLAGS + 0x8)
#define FLAG_BADGE04_GET                           (SYSTEM_FLAGS + 0x9)
#define FLAG_BADGE05_GET                           (SYSTEM_FLAGS + 0xA)
#define FLAG_BADGE06_GET                           (SYSTEM_FLAGS + 0xB)
#define FLAG_BADGE07_GET                           (SYSTEM_FLAGS + 0xC)
#define FLAG_BADGE08_GET                           (SYSTEM_FLAGS + 0xD)
#define FLAG_SYS_POKELINK_ACTIVE                   (SYSTEM_FLAGS + 0xE)
#define FLAG_SYS_POKELINK_ENABLED                  (SYSTEM_FLAGS + 0xF)
#define FLAG_SYS_POKELINK_DISABLED                 (SYSTEM_FLAGS + 0x10)
#define FLAG_SYS_MIRAGE_ISLAND                     (SYSTEM_FLAGS + 0x11)
#define FLAG_SYS_RIBBON_GET                        (SYSTEM_FLAGS + 0x12)
#define FLAG_SYS_DAILY_MIRAGE_ISLAND               (SYSTEM_FLAGS + 0x13)
#define FLAG_SYS_USE_STRENGTH                      (SYSTEM_FLAGS + 0x14)
#define FLAG_SYS_USE_FLASH                         (SYSTEM_FLAGS + 0x15)
#define FLAG_SYS_USE_ROCK_SMASH                    (SYSTEM_FLAGS + 0x16)
#define FLAG_SYS_USE_WATERFALL                     (SYSTEM_FLAGS + 0x17)
#define FLAG_SYS_USE_DIVE                          (SYSTEM_FLAGS + 0x18)
#define FLAG_SYS_TV_START                          (SYSTEM_FLAGS + 0x19)
#define FLAG_SYS_SHOAL_TIDE                        (SYSTEM_FLAGS + 0x1A)
#define FLAG_SYS_RIBBON_GET_PARTY                  (SYSTEM_FLAGS + 0x1B)
#define FLAG_SYS_PC_LANETTE                        (SYSTEM_FLAGS + 0x1C)
#define FLAG_SYS_PC_BILL                           (SYSTEM_FLAGS + 0x1D)
#define FLAG_SYS_PC_BEBE                           (SYSTEM_FLAGS + 0x1E)
#define FLAG_SYS_PC_MARKING                        (SYSTEM_FLAGS + 0x1F)
#define FLAG_SYS_HAS_EON_TICKET                    (SYSTEM_FLAGS + 0x20)
#define FLAG_SYS_HAS_AURORA_TICKET                 (SYSTEM_FLAGS + 0x21)
#define FLAG_SYS_HAS_MYSTIC_TICKET                 (SYSTEM_FLAGS + 0x22)
#define FLAG_SYS_HAS_OLD_SEA_MAP                   (SYSTEM_FLAGS + 0x23)
#define FLAG_SYS_POKEDEX_USE                       (SYSTEM_FLAGS + 0x24)
#define FLAG_SYS_NATIONAL_DEX                      (SYSTEM_FLAGS + 0x25)
#define FLAG_SYS_CYCLING_ROAD                      (SYSTEM_FLAGS + 0x26)
#define FLAG_SYS_SAFARI_MODE                       (SYSTEM_FLAGS + 0x27)
#define FLAG_SYS_CRUISE_MODE                       (SYSTEM_FLAGS + 0x28)
#define FLAG_SYS_TOWER_SILVER                      (SYSTEM_FLAGS + 0x29)
#define FLAG_SYS_TOWER_GOLD                        (SYSTEM_FLAGS + 0x2A)
#define FLAG_SYS_DOME_SILVER                       (SYSTEM_FLAGS + 0x2B)
#define FLAG_SYS_DOME_GOLD                         (SYSTEM_FLAGS + 0x2C)
#define FLAG_SYS_PALACE_SILVER                     (SYSTEM_FLAGS + 0x2D)
#define FLAG_SYS_PALACE_GOLD                       (SYSTEM_FLAGS + 0x2E)
#define FLAG_SYS_ARENA_SILVER                      (SYSTEM_FLAGS + 0x2F)
#define FLAG_SYS_ARENA_GOLD                        (SYSTEM_FLAGS + 0x30)
#define FLAG_SYS_FACTORY_SILVER                    (SYSTEM_FLAGS + 0x31)
#define FLAG_SYS_FACTORY_GOLD                      (SYSTEM_FLAGS + 0x32)
#define FLAG_SYS_PIKE_SILVER                       (SYSTEM_FLAGS + 0x33)
#define FLAG_SYS_PIKE_GOLD                         (SYSTEM_FLAGS + 0x34)
#define FLAG_SYS_PYRAMID_SILVER                    (SYSTEM_FLAGS + 0x35)
#define FLAG_SYS_PYRAMID_GOLD                      (SYSTEM_FLAGS + 0x36)
#define FLAG_SYS_FRONTIER_PASS                     (SYSTEM_FLAGS + 0x37)
#define FLAG_SYS_TOWER_SILVER_LEGACY               (SYSTEM_FLAGS + 0x38)
#define FLAG_SYS_TOWER_GOLD_LEGACY                 (SYSTEM_FLAGS + 0x39)
#define FLAG_SYS_DOME_SILVER_LEGACY                (SYSTEM_FLAGS + 0x3A)
#define FLAG_SYS_DOME_GOLD_LEGACY                  (SYSTEM_FLAGS + 0x3B)
#define FLAG_SYS_PALACE_SILVER_LEGACY              (SYSTEM_FLAGS + 0x3C)
#define FLAG_SYS_PALACE_GOLD_LEGACY                (SYSTEM_FLAGS + 0x3D)
#define FLAG_SYS_ARENA_SILVER_LEGACY               (SYSTEM_FLAGS + 0x3E)
#define FLAG_SYS_ARENA_GOLD_LEGACY                 (SYSTEM_FLAGS + 0x3F)
#define FLAG_SYS_FACTORY_SILVER_LEGACY              (SYSTEM_FLAGS + 0x40)
#define FLAG_SYS_FACTORY_GOLD_LEGACY                (SYSTEM_FLAGS + 0x41)
#define FLAG_SYS_PIKE_SILVER_LEGACY                 (SYSTEM_FLAGS + 0x42)
#define FLAG_SYS_PIKE_GOLD_LEGACY                   (SYSTEM_FLAGS + 0x43)
#define FLAG_SYS_PYRAMID_SILVER_LEGACY              (SYSTEM_FLAGS + 0x44)
#define FLAG_SYS_PYRAMID_GOLD_LEGACY                (SYSTEM_FLAGS + 0x45)
#define FLAG_SYS_FRONTIER_PASS_LEGACY                (SYSTEM_FLAGS + 0x46)
#define FLAG_SYS_TV_LATIAS_LATIOS                    (SYSTEM_FLAGS + 0x47)
#define FLAG_LANDMARK_SKY_PILLAR                    (SYSTEM_FLAGS + 0x48)
#define FLAG_SYS_SHOAL_ITEM                         (SYSTEM_FLAGS + 0x49)
#define FLAG_SYS_B_DASH                             (SYSTEM_FLAGS + 0x4A) // RECEIVED Running Shoes
#define FLAG_SYS_CTRL_OBJ_DELETE                    (SYSTEM_FLAGS + 0x4B)
#define FLAG_SYS_RESET_RTC_ENABLE                   (SYSTEM_FLAGS + 0x4C)
#define FLAG_LANDMARK_BERRY_MASTERS_HOUSE           (SYSTEM_FLAGS + 0x4D)
#define FLAG_ENABLE_SHIP_BIRTH_ISLAND               (SYSTEM_FLAGS + 0x4E)
#define FLAG_ENABLE_SHIP_FARAWAY_ISLAND             (SYSTEM_FLAGS + 0x4F)
#define FLAG_SHOWN_BOX_WAS_FULL_MESSAGE             (SYSTEM_FLAGS + 0x50)
#define FLAG_ARRIVED_ON_FARAWAY_ISLAND              (SYSTEM_FLAGS + 0x51)
#define FLAG_ARRIVED_AT_MARINE_CAVE_EMERGE_SPOT     (SYSTEM_FLAGS + 0x52)
#define FLAG_ARRIVED_AT_TERRA_CAVE_ENTRANCE         (SYSTEM_FLAGS + 0x53)
#define FLAG_SYS_MYSTERY_GIFT_ENABLE                (SYSTEM_FLAGS + 0x54)
#define FLAG_ENTERED_MIRAGE_TOWER                   (SYSTEM_FLAGS + 0x55)
#define FLAG_LANDMARK_ALTERING_CAVE                 (SYSTEM_FLAGS + 0x56)
#define FLAG_LANDMARK_DESERT_UNDERPASS              (SYSTEM_FLAGS + 0x57)
#define FLAG_LANDMARK_ARTISAN_CAVE                  (SYSTEM_FLAGS + 0x58)
#define FLAG_ENABLE_SHIP_NAVEL_ROCK                 (SYSTEM_FLAGS + 0x59)
#define FLAG_ARRIVED_AT_NAVEL_ROCK                  (SYSTEM_FLAGS + 0x5A)
#define FLAG_LANDMARK_TRAINER_HILL                  (SYSTEM_FLAGS + 0x5B)
#define FLAG_RECEIVED_POKEDEX_FROM_BIRCH            (SYSTEM_FLAGS + 0x5C)
#define FLAG_UNUSED_0x8E5                           (SYSTEM_FLAGS + 0x5D) // Unused Flag
#define FLAG_UNUSED_0x8E6                           (SYSTEM_FLAGS + 0x5E) // Unused Flag
#define FLAG_UNUSED_0x8E7                           (SYSTEM_FLAGS + 0x5F) // Unused Flag
#define FLAG_UNUSED_0x8E8                           (SYSTEM_FLAGS + 0x60) // Unused Flag
#define FLAG_UNUSED_0x8E9                           (SYSTEM_FLAGS + 0x61) // Unused Flag
#define FLAG_UNUSED_0x8EA                           (SYSTEM_FLAGS + 0x62) // Unused Flag
#define FLAG_UNUSED_0x8EB                           (SYSTEM_FLAGS + 0x63) // Unused Flag
#define FLAG_UNUSED_0x8EC                           (SYSTEM_FLAGS + 0x64) // Unused Flag
#define FLAG_UNUSED_0x8ED                           (SYSTEM_FLAGS + 0x65) // Unused Flag
#define FLAG_UNUSED_0x8EE                           (SYSTEM_FLAGS + 0x66) // Unused Flag
#define FLAG_UNUSED_0x8EF                           (SYSTEM_FLAGS + 0x67) // Unused Flag
#define FLAG_UNUSED_0x8F0                           (SYSTEM_FLAGS + 0x68) // Unused Flag
#define FLAG_UNUSED_0x8F1                           (SYSTEM_FLAGS + 0x69) // Unused Flag
#define FLAG_UNUSED_0x8F2                           (SYSTEM_FLAGS + 0x6A) // Unused Flag
#define FLAG_UNUSED_0x8F3                           (SYSTEM_FLAGS + 0x6B) // Unused Flag
#define FLAG_UNUSED_0x8F4                           (SYSTEM_FLAGS + 0x6C) // Unused Flag
#define FLAG_UNUSED_0x8F5                           (SYSTEM_FLAGS + 0x6D) // Unused Flag
#define FLAG_UNUSED_0x8F6                           (SYSTEM_FLAGS + 0x6E) // Unused Flag
#define FLAG_UNUSED_0x8F7                           (SYSTEM_FLAGS + 0x6F) // Unused Flag
#define FLAG_UNUSED_0x8F8                           (SYSTEM_FLAGS + 0x70) // Unused Flag
#define FLAG_UNUSED_0x8F9                           (SYSTEM_FLAGS + 0x71) // Unused Flag
#define FLAG_UNUSED_0x8FA                           (SYSTEM_FLAGS + 0x72) // Unused Flag
#define FLAG_UNUSED_0x8FB                           (SYSTEM_FLAGS + 0x73) // Unused Flag
#define FLAG_UNUSED_0x8FC                           (SYSTEM_FLAGS + 0x74) // Unused Flag
#define FLAG_UNUSED_0x8FD                           (SYSTEM_FLAGS + 0x75) // Unused Flag
#define FLAG_UNUSED_0x8FE                           (SYSTEM_FLAGS + 0x76) // Unused Flag
#define FLAG_UNUSED_0x8FF                           (SYSTEM_FLAGS + 0x77) // Unused Flag
#define FLAG_UNUSED_0x900                           (SYSTEM_FLAGS + 0x78) // Unused Flag
#define FLAG_UNUSED_0x901                           (SYSTEM_FLAGS + 0x79) // Unused Flag
#define FLAG_UNUSED_0x902                           (SYSTEM_FLAGS + 0x7A) // Unused Flag
#define FLAG_UNUSED_0x903                           (SYSTEM_FLAGS + 0x7B) // Unused Flag
#define FLAG_UNUSED_0x904                           (SYSTEM_FLAGS + 0x7C) // Unused Flag
#define FLAG_UNUSED_0x905                           (SYSTEM_FLAGS + 0x7D) // Unused Flag
#define FLAG_UNUSED_0x906                           (SYSTEM_FLAGS + 0x7E) // Unused Flag
#define FLAG_UNUSED_0x907                           (SYSTEM_FLAGS + 0x7F) // Unused Flag
#define FLAG_UNUSED_0x908                           (SYSTEM_FLAGS + 0x80) // Unused Flag
#define FLAG_UNUSED_0x909                           (SYSTEM_FLAGS + 0x81) // Unused Flag
#define FLAG_UNUSED_0x90A                           (SYSTEM_FLAGS + 0x82) // Unused Flag
#define FLAG_UNUSED_0x90B                           (SYSTEM_FLAGS + 0x83) // Unused Flag
#define FLAG_UNUSED_0x90C                           (SYSTEM_FLAGS + 0x84) // Unused Flag
#define FLAG_UNUSED_0x90D                           (SYSTEM_FLAGS + 0x85) // Unused Flag
#define FLAG_UNUSED_0x90E                           (SYSTEM_FLAGS + 0x86) // Unused Flag
#define FLAG_UNUSED_0x90F                           (SYSTEM_FLAGS + 0x87) // Unused Flag
#define FLAG_UNUSED_0x910                           (SYSTEM_FLAGS + 0x88) // Unused Flag
#define FLAG_UNUSED_0x911                           (SYSTEM_FLAGS + 0x89) // Unused Flag
#define FLAG_UNUSED_0x912                           (SYSTEM_FLAGS + 0x8A) // Unused Flag
#define FLAG_UNUSED_0x913                           (SYSTEM_FLAGS + 0x8B) // Unused Flag
#define FLAG_UNUSED_0x914                           (SYSTEM_FLAGS + 0x8C) // Unused Flag
#define FLAG_UNUSED_0x915                           (SYSTEM_FLAGS + 0x8D) // Unused Flag
#define FLAG_UNUSED_0x916                           (SYSTEM_FLAGS + 0x8E) // Unused Flag
#define FLAG_UNUSED_0x917                           (SYSTEM_FLAGS + 0x8F) // Unused Flag
#define FLAG_UNUSED_0x918                           (SYSTEM_FLAGS + 0x90) // Unused Flag
#define FLAG_UNUSED_0x919                           (SYSTEM_FLAGS + 0x91) // Unused Flag
#define FLAG_UNUSED_0x91A                           (SYSTEM_FLAGS + 0x92) // Unused Flag
#define FLAG_UNUSED_0x91B                           (SYSTEM_FLAGS + 0x93) // Unused Flag
#define FLAG_UNUSED_0x91C                           (SYSTEM_FLAGS + 0x94) // Unused Flag
#define FLAG_UNUSED_0x91D                           (SYSTEM_FLAGS + 0x95) // Unused Flag
#define FLAG_UNUSED_0x91E                           (SYSTEM_FLAGS + 0x96) // Unused Flag
#define FLAG_UNUSED_0x91F                           (SYSTEM_FLAGS + 0x97) // Unused Flag

// Daily Flags
// These flags are cleared once per day
#define DAILY_FLAGS_START                           (FLAG_UNUSED_0x91F + (8 - FLAG_UNUSED_0x91F % 8))
#define FLAG_UNUSED_0x920                           (DAILY_FLAGS_START + 0x0)  // Unused Flag
#define FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY     (DAILY_FLAGS_START + 0x1)
#define FLAG_DAILY_SECRET_BASE                      (DAILY_FLAGS_START + 0x2)
#define FLAG_UNUSED_0x923                           (DAILY_FLAGS_START + 0x3)  // Unused Flag
#define FLAG_UNUSED_0x924                           (DAILY_FLAGS_START + 0x4)  // Unused Flag
#define FLAG_UNUSED_0x925                           (DAILY_FLAGS_START + 0x5)  // Unused Flag
#define FLAG_UNUSED_0x926                           (DAILY_FLAGS_START + 0x6)  // Unused Flag
#define FLAG_UNUSED_0x927                           (DAILY_FLAGS_START + 0x7)  // Unused Flag
#define FLAG_UNUSED_0x928                           (DAILY_FLAGS_START + 0x8)  // Unused Flag
#define FLAG_UNUSED_0x929                           (DAILY_FLAGS_START + 0x9)  // Unused Flag
#define FLAG_DAILY_PICKED_LOTO_TICKET               (DAILY_FLAGS_START + 0xA)
#define FLAG_DAILY_ROUTE_114_RECEIVED_BERRY         (DAILY_FLAGS_START + 0xB)
#define FLAG_DAILY_ROUTE_111_RECEIVED_BERRY         (DAILY_FLAGS_START + 0xC)
#define FLAG_DAILY_BERRY_MASTER_RECEIVED_BERRY      (DAILY_FLAGS_START + 0xD)
#define FLAG_DAILY_ROUTE_120_RECEIVED_BERRY         (DAILY_FLAGS_START + 0xE)
#define FLAG_DAILY_LILYCOVE_RECEIVED_BERRY          (DAILY_FLAGS_START + 0xF)
#define FLAG_DAILY_FLOWER_SHOP_RECEIVED_BERRY       (DAILY_FLAGS_START + 0x10)
#define FLAG_DAILY_BERRY_MASTERS_WIFE               (DAILY_FLAGS_START + 0x11)
#define FLAG_DAILY_SOOTOPOLIS_RECEIVED_BERRY        (DAILY_FLAGS_START + 0x12)
#define FLAG_UNUSED_0x933                           (DAILY_FLAGS_START + 0x13) // Unused Flag
#define FLAG_DAILY_APPRENTICE_LEAVES                (DAILY_FLAGS_START + 0x14)

#define FLAG_UNUSED_0x935                           (DAILY_FLAGS_START + 0x15) // Unused Flag
#define FLAG_UNUSED_0x936                           (DAILY_FLAGS_START + 0x16) // Unused Flag
#define FLAG_UNUSED_0x937                           (DAILY_FLAGS_START + 0x17) // Unused Flag
#define FLAG_UNUSED_0x938                           (DAILY_FLAGS_START + 0x18) // Unused Flag
#define FLAG_UNUSED_0x939                           (DAILY_FLAGS_START + 0x19) // Unused Flag
#define FLAG_UNUSED_0x93A                           (DAILY_FLAGS_START + 0x1A) // Unused Flag
#define FLAG_UNUSED_0x93B                           (DAILY_FLAGS_START + 0x1B) // Unused Flag
#define FLAG_UNUSED_0x93C                           (DAILY_FLAGS_START + 0x1C) // Unused Flag
#define FLAG_UNUSED_0x93D                           (DAILY_FLAGS_START + 0x1D) // Unused Flag
#define FLAG_UNUSED_0x93E                           (DAILY_FLAGS_START + 0x1E) // Unused Flag
#define FLAG_UNUSED_0x93F                           (DAILY_FLAGS_START + 0x1F) // Unused Flag
#define FLAG_UNUSED_0x940                           (DAILY_FLAGS_START + 0x20) // Unused Flag
#define FLAG_UNUSED_0x941                           (DAILY_FLAGS_START + 0x21) // Unused Flag
#define FLAG_UNUSED_0x942                           (DAILY_FLAGS_START + 0x22) // Unused Flag
#define FLAG_UNUSED_0x943                           (DAILY_FLAGS_START + 0x23) // Unused Flag
#define FLAG_UNUSED_0x944                           (DAILY_FLAGS_START + 0x24) // Unused Flag
#define FLAG_UNUSED_0x945                           (DAILY_FLAGS_START + 0x25) // Unused Flag
#define FLAG_UNUSED_0x946                           (DAILY_FLAGS_START + 0x26) // Unused Flag
#define FLAG_UNUSED_0x947                           (DAILY_FLAGS_START + 0x27) // Unused Flag
#define FLAG_UNUSED_0x948                           (DAILY_FLAGS_START + 0x28) // Unused Flag
#define FLAG_UNUSED_0x949                           (DAILY_FLAGS_START + 0x29) // Unused Flag
#define FLAG_UNUSED_0x94A                           (DAILY_FLAGS_START + 0x2A) // Unused Flag
#define FLAG_UNUSED_0x94B                           (DAILY_FLAGS_START + 0x2B) // Unused Flag
#define FLAG_UNUSED_0x94C                           (DAILY_FLAGS_START + 0x2C) // Unused Flag
#define FLAG_UNUSED_0x94D                           (DAILY_FLAGS_START + 0x2D) // Unused Flag
#define FLAG_UNUSED_0x94E                           (DAILY_FLAGS_START + 0x2E) // Unused Flag
#define FLAG_UNUSED_0x94F                           (DAILY_FLAGS_START + 0x2F) // Unused Flag
#define FLAG_UNUSED_0x950                           (DAILY_FLAGS_START + 0x30) // Unused Flag
#define FLAG_UNUSED_0x951                           (DAILY_FLAGS_START + 0x31) // Unused Flag
#define FLAG_UNUSED_0x952                           (DAILY_FLAGS_START + 0x32) // Unused Flag
#define FLAG_UNUSED_0x953                           (DAILY_FLAGS_START + 0x33) // Unused Flag
#define FLAG_UNUSED_0x954                           (DAILY_FLAGS_START + 0x34) // Unused Flag
#define FLAG_UNUSED_0x955                           (DAILY_FLAGS_START + 0x35) // Unused Flag
#define FLAG_UNUSED_0x956                           (DAILY_FLAGS_START + 0x36) // Unused Flag
#define FLAG_UNUSED_0x957                           (DAILY_FLAGS_START + 0x37) // Unused Flag
#define FLAG_UNUSED_0x958                           (DAILY_FLAGS_START + 0x38) // Unused Flag
#define FLAG_UNUSED_0x959                           (DAILY_FLAGS_START + 0x39) // Unused Flag
#define FLAG_UNUSED_0x95A                           (DAILY_FLAGS_START + 0x3A) // Unused Flag
#define FLAG_UNUSED_0x95B                           (DAILY_FLAGS_START + 0x3B) // Unused Flag
#define FLAG_UNUSED_0x95C                           (DAILY_FLAGS_START + 0x3C) // Unused Flag
#define FLAG_UNUSED_0x95D                           (DAILY_FLAGS_START + 0x3D) // Unused Flag
#define FLAG_UNUSED_0x95E                           (DAILY_FLAGS_START + 0x3E) // Unused Flag
#define FLAG_UNUSED_0x95F                           (DAILY_FLAGS_START + 0x3F) // Unused Flag
#define DAILY_FLAGS_END                             (FLAG_UNUSED_0x95F + (7 - FLAG_UNUSED_0x95F % 8))
#define NUM_DAILY_FLAGS                             (DAILY_FLAGS_END - DAILY_FLAGS_START + 1)

#define FLAGS_COUNT (DAILY_FLAGS_END + 1)

// Special Flags (Stored in EWRAM (sSpecialFlags), not in the SaveBlock)
#define SPECIAL_FLAGS_START                     0x4000
#define FLAG_HIDE_MAP_NAME_POPUP                (SPECIAL_FLAGS_START + 0x0)
#define FLAG_DONT_TRANSITION_MUSIC              (SPECIAL_FLAGS_START + 0x1)
#define FLAG_ENABLE_MULTI_CORRIDOR_DOOR         (SPECIAL_FLAGS_START + 0x2)
#define FLAG_SPECIAL_FLAG_UNUSED_0x4003         (SPECIAL_FLAGS_START + 0x3) // Unused Flag
#define FLAG_STORING_ITEMS_IN_PYRAMID_BAG       (SPECIAL_FLAGS_START + 0x4)
#define FLAG_SAFE_FOLLOWER_MOVEMENT             (SPECIAL_FLAGS_START + 0x5) // When set, applymovement does not put the follower inside a pokeball
                                                                            // Also, scripted movements on the player will move follower(s), too
#define SPECIAL_FLAGS_END                       (SPECIAL_FLAGS_START + 0x7F)
#define NUM_SPECIAL_FLAGS                       (SPECIAL_FLAGS_END - SPECIAL_FLAGS_START + 1)

// Temp flag aliases
#define FLAG_TEMP_SKIP_GABBY_INTERVIEW          FLAG_TEMP_1
#define FLAG_TEMP_REGICE_PUZZLE_STARTED         FLAG_TEMP_2
#define FLAG_TEMP_REGICE_PUZZLE_FAILED          FLAG_TEMP_3
#define FLAG_TEMP_HIDE_FOLLOWER                 FLAG_TEMP_E
#define FLAG_TEMP_HIDE_MIRAGE_ISLAND_BERRY_TREE FLAG_TEMP_11

// FRLG flags
#define FLAG_HIDE_BULBASAUR_BALL                           0
#define FLAG_HIDE_SQUIRTLE_BALL                            0
#define FLAG_HIDE_CHARMANDER_BALL                          0
#define FLAG_HIDE_OAK_IN_HIS_LAB                           0
#define FLAG_HIDE_OAK_IN_PALLET_TOWN                       0
#define FLAG_HIDE_RIVAL_IN_LAB                             0
#define FLAG_HIDE_PEWTER_CITY_GYM_GUIDE                    0
#define FLAG_HIDE_DOME_FOSSIL                              0
#define FLAG_HIDE_HELIX_FOSSIL                             0
#define FLAG_HIDE_NUGGET_BRIDGE_ROCKET                     0
#define FLAG_HIDE_BILL_CLEFAIRY                            0
#define FLAG_HIDE_TOWER_FUJI                               0
#define FLAG_HIDE_POKEHOUSE_FUJI                           0
#define FLAG_HIDE_LIFT_KEY                                 0
#define FLAG_HIDE_HIDEOUT_GIOVANNI                         0
#define FLAG_HIDE_TOWN_MAP                                 0
#define FLAG_HIDE_POKEDEX                                  0
#define FLAG_HIDE_CERULEAN_ROCKET                          0
#define FLAG_HIDE_CERULEAN_RIVAL                           0
#define FLAG_HIDE_SS_ANNE_RIVAL                            0
#define FLAG_HIDE_SAFFRON_ROCKETS                          0
#define FLAG_HIDE_SAFFRON_CIVILIANS                        0
#define FLAG_HIDE_SEAFOAM_1F_BOULDER_1                     0
#define FLAG_HIDE_SEAFOAM_1F_BOULDER_2                     0
#define FLAG_HIDE_SEAFOAM_B1F_BOULDER_1                    0
#define FLAG_HIDE_SEAFOAM_B1F_BOULDER_2                    0
#define FLAG_HIDE_SEAFOAM_B2F_BOULDER_1                    0
#define FLAG_HIDE_SEAFOAM_B2F_BOULDER_2                    0
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_1                    0
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_2                    0
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_3                    0
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_4                    0
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_5                    0
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_6                    0
#define FLAG_HIDE_SEAFOAM_B4F_BOULDER_1                    0
#define FLAG_HIDE_SEAFOAM_B4F_BOULDER_2                    0
#define FLAG_HIDE_SILPH_RIVAL                              0
#define FLAG_HIDE_ROUTE_22_RIVAL                           0
#define FLAG_HIDE_PEWTER_MUSEUM_GUIDE                      0
#define FLAG_HIDE_TOWER_RIVAL                              0
#define FLAG_HIDE_MOLTRES                                  0
#define FLAG_HIDE_SILPH_ROCKETS                            0
#define FLAG_HIDE_ROUTE_12_SNORLAX                         0
#define FLAG_HIDE_VIRIDIAN_GIOVANNI                        0
#define FLAG_HIDE_OLD_AMBER                                0
#define FLAG_HIDE_EEVEE_BALL                               0
#define FLAG_HIDE_VICTORY_ROAD_MOLTRES                     0
#define FLAG_HIDE_FUCHSIA_FISHING_GURU                     0
#define FLAG_HIDE_LAPRAS                                   0
#define FLAG_HIDE_SILPH_PRESIDENT                          0
#define FLAG_HIDE_CERULEAN_CAVE_MEWTWO                     0
#define FLAG_HIDE_POWER_PLANT_ZAPDOS                       0
#define FLAG_HIDE_SEAFOAM_ARTICUNO                         0
#define FLAG_HIDE_POKEMON_TOWER_MAROWAK                    0
#define FLAG_HIDE_POKEMON_TOWER_GHOST                      0
#define FLAG_HIDE_ROCKET_HIDEOUT_ELEVATOR_KEY              0
#define FLAG_HIDE_ROCKET_HIDEOUT_LIFT_KEY                  0
#define FLAG_HIDE_SILPH_SCOPE_2                            0
#define FLAG_HIDE_SILPH_CARD_KEY                           0
#define FLAG_HIDE_POKE_FLUTE                               0
#define FLAG_HIDE_SECRET_KEY                               0
#define FLAG_HIDE_BICYCLE                                  0
#define FLAG_HIDE_SAFARI_PASS                              0
#define FLAG_HIDE_GOLD_TEETH                               0
#define FLAG_HIDE_COIN_CASE                                0
#define FLAG_HIDE_SILPH_SCOPE_3                            0
#define FLAG_HIDE_ITEMFINDER                               0
#define FLAG_HIDE_TM_CASE                                  0
#define FLAG_HIDE_BERRY_POUCH                              0
#define FLAG_HIDE_FAME_CHECKER                             0
#define FLAG_HIDE_TEACHY_TV                                0
#define FLAG_HIDE_TOWN_MAP_2                               0
#define FLAG_HIDE_POKEDEX_2                                0
#define FLAG_HIDE_VS_SEEKER                                0
#define FLAG_HIDE_NATIONAL_DEX                             0
#define FLAG_HIDE_RUBY                                     0
#define FLAG_HIDE_SAPPHIRE                                 0
#define FLAG_HIDE_CELIO                                    0
#define FLAG_HIDE_LOSTELLE                                 0
#define FLAG_HIDE_HYPNO                                    0
#define FLAG_HIDE_MOLTRES_2                                0
#define FLAG_HIDE_LORELEI                                  0
#define FLAG_HIDE_ROCKET_GRUNTS                            0
#define FLAG_HIDE_GIOVANNI                                 0
#define FLAG_HIDE_ROCKET_WAREHOUSE_CARD_KEY_DOOR           0
#define FLAG_HIDE_ROCKET_WAREHOUSE_LIFT_KEY_DOOR           0
#define FLAG_HIDE_ROCKET_WAREHOUSE_SCIENTIST               0
#define FLAG_HIDE_ROCKET_WAREHOUSE_ADMIN                   0
#define FLAG_HIDE_ROCKET_WAREHOUSE_BOSS                    0
#define FLAG_HIDE_ROCKET_WAREHOUSE_RUBY                    0
#define FLAG_HIDE_ROCKET_WAREHOUSE_SAPPHIRE                0
#define FLAG_HIDE_ROCKET_WAREHOUSE_ELEVATOR                0
#define FLAG_HIDE_ROCKET_WAREHOUSE_PASSWORD_DOOR           0
#define FLAG_HIDE_ROCKET_WAREHOUSE_GIDEON                  0
#define FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE             0
#define FLAG_HIDE_ICEFALL_CAVE_LORELEI                     0
#define FLAG_HIDE_MEMORIAL_PILLAR_ITEM                     0
#define FLAG_HIDE_LOST_CAVE_ITEM                           0
#define FLAG_HIDE_RESORT_GORGEOUS_ITEM                     0
#define FLAG_HIDE_WATER_LABYRINTH_ITEM                     0
#define FLAG_HIDE_FIVE_ISLAND_MEADOW_ITEM                  0
#define FLAG_HIDE_GREEN_PATH_ITEM                          0
#define FLAG_HIDE_OUTCAST_ISLAND_ITEM                      0
#define FLAG_HIDE_TANOBY_RUINS_ITEM                        0
#define FLAG_HIDE_CANYON_ENTRANCE_ITEM                     0
#define FLAG_HIDE_SEVAULT_CANYON_ITEM                      0
#define FLAG_HIDE_TANOBY_CHAMBERS_ITEM                     0
#define FLAG_HIDE_BIRTH_ISLAND_DEOXYS                      0
#define FLAG_HIDE_NAVEL_ROCK_LUGIA                         0
#define FLAG_HIDE_NAVEL_ROCK_HO_OH                         0
#define FLAG_HIDE_FARAWAY_ISLAND_MEW                       0
#define FLAG_HIDE_TRAINER_TOWER_TRAINERS                   0
#define FLAG_HIDE_TRAINER_TOWER_OWNER                      0
#define FLAG_HIDE_UNION_ROOM_PLAYER                        0
#define FLAG_HIDE_UNION_ROOM_ATTENDANT                     0
#define FLAG_HIDE_UNION_ROOM_WIRELESS_ADAPTER              0
#define FLAG_HIDE_TRADE_CENTER_PLAYER                      0
#define FLAG_HIDE_TRADE_CENTER_PARTNER                     0
#define FLAG_HIDE_COLOSSEUM_PLAYER                         0
#define FLAG_HIDE_COLOSSEUM_PARTNER                        0
#define FLAG_HIDE_RECORD_CORNER_PLAYER                     0
#define FLAG_HIDE_RECORD_CORNER_PARTNER                    0
#define FLAG_HIDE_BERRY_CRUSH_PLAYER                       0
#define FLAG_HIDE_BERRY_CRUSH_PARTNER                      0
#define FLAG_HIDE_WIRELESS_ADAPTER_ATTENDANT               0
#define FLAG_HIDE_UNION_ROOM_CHAT_PLAYER                   0
#define FLAG_HIDE_UNION_ROOM_CHAT_PARTNER                  0
#define FLAG_HIDE_UNION_ROOM_TRADE_BOARD                   0
#define FLAG_HIDE_UNION_ROOM_TRADE_BOARD_PARTNER           0
#define FLAG_HIDE_UNION_ROOM_TRADE_BOARD_PLAYER            0
#define FLAG_HIDE_BATTLE_COLOSSEUM_PLAYER                  0
#define FLAG_HIDE_BATTLE_COLOSSEUM_PARTNER                 0
#define FLAG_HIDE_BATTLE_COLOSSEUM_OPPONENT                0
#define FLAG_HIDE_BATTLE_COLOSSEUM_OPPONENT_PARTNER        0
#define FLAG_HIDE_TRADE_CENTER_POKEMON                     0
#define FLAG_HIDE_COLOSSEUM_POKEMON                        0
#define FLAG_HIDE_RECORD_CORNER_POKEMON                    0
#define FLAG_HIDE_BERRY_CRUSH_POKEMON                      0
#define FLAG_HIDE_UNION_ROOM_POKEMON                       0
#define FLAG_HIDE_TRAINER_TOWER_POKEMON                    0
#define FLAG_HIDE_WIRELESS_ADAPTER_POKEMON                 0
#define FLAG_HIDE_UNION_ROOM_CHAT_POKEMON                  0
#define FLAG_HIDE_UNION_ROOM_TRADE_BOARD_POKEMON           0
#define FLAG_HIDE_BATTLE_COLOSSEUM_POKEMON                 0

#endif // IS_FRLG

#endif // GUARD_CONSTANTS_FLAGS_H
