MagmaHideout_2F_1R_MapScripts::
	.byte 0

MagmaHideout_2F_1R_EventScript_Grunt14::
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_14, MagmaHideout_2F_1R_Text_Grunt14Intro, MagmaHideout_2F_1R_Text_Grunt14Defeat
	msgbox MagmaHideout_2F_1R_Text_Grunt14PostBattle, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_EventScript_Grunt3::
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_3, MagmaHideout_2F_1R_Text_Grunt3Intro, MagmaHideout_2F_1R_Text_Grunt3Defeat
	msgbox MagmaHideout_2F_1R_Text_Grunt3PostBattle, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_EventScript_Grunt4::
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_4, MagmaHideout_2F_1R_Text_Grunt4Intro, MagmaHideout_2F_1R_Text_Grunt4Defeat
	msgbox MagmaHideout_2F_1R_Text_Grunt4PostBattle, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_EventScript_Grunt5::
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_5, MagmaHideout_2F_1R_Text_Grunt5Intro, MagmaHideout_2F_1R_Text_Grunt5Defeat
	msgbox MagmaHideout_2F_1R_Text_Grunt5PostBattle, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_Text_Grunt14Intro:
	.string "LEMBRANTE: Apagar uma historia\nporque ela incomoda quem manda\p"
	.string "e apenas outra forma de\nviolencia.$"

MagmaHideout_2F_1R_Text_Grunt14Defeat:
	.string "LEMBRANTE: Apagar uma historia\nporque ela incomoda quem manda\p"
	.string "e apenas outra forma de\nviolencia.$"

MagmaHideout_2F_1R_Text_Grunt14PostBattle:
	.string "LEMBRANTE: Apagar uma historia\nporque ela incomoda quem manda\p"
	.string "e apenas outra forma de\nviolencia.$"

MagmaHideout_2F_1R_Text_Grunt3Intro:
	.string "LEMBRANTE: Apagar uma historia\nporque ela incomoda quem manda\p"
	.string "e apenas outra forma de\nviolencia.$"

MagmaHideout_2F_1R_Text_Grunt3Defeat:
	.string "LEMBRANTE: Apagar uma historia\nporque ela incomoda quem manda\p"
	.string "e apenas outra forma de\nviolencia.$"

MagmaHideout_2F_1R_Text_Grunt3PostBattle:
	.string "CIRO: O futuro nao espera por\nquem vive olhando para tras.\p"
	.string "Pelo menos era nisso que eu\nacreditava.$"

MagmaHideout_2F_1R_Text_Grunt4Intro:
	.string "LEMBRANTE: Apagar uma historia\nporque ela incomoda quem manda\p"
	.string "e apenas outra forma de\nviolencia.$"

MagmaHideout_2F_1R_Text_Grunt4Defeat:
	.string "LEMBRANTE: Apagar uma historia\nporque ela incomoda quem manda\p"
	.string "e apenas outra forma de\nviolencia.$"

MagmaHideout_2F_1R_Text_Grunt4PostBattle:
	.string "LEMBRANTE: Apagar uma historia\nporque ela incomoda quem manda\p"
	.string "e apenas outra forma de\nviolencia.$"

MagmaHideout_2F_1R_Text_Grunt5Intro:
	.string "LEMBRANTE: Apagar uma historia\nporque ela incomoda quem manda\p"
	.string "e apenas outra forma de\nviolencia.$"

MagmaHideout_2F_1R_Text_Grunt5Defeat:
	.string "LEMBRANTE: Apagar uma historia\nporque ela incomoda quem manda\p"
	.string "e apenas outra forma de\nviolencia.$"

MagmaHideout_2F_1R_Text_Grunt5PostBattle:
	.string "LEMBRANTE: Apagar uma historia\nporque ela incomoda quem manda\p"
	.string "e apenas outra forma de\nviolencia.$"

