MagmaHideout_2F_1R_MapScripts::
	.byte 0

MagmaHideout_2F_1R_EventScript_Grunt14::
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_14, MagmaHideout_2F_1R_Text_Grunt14Intro, MagmaHideout_2F_1R_Text_Grunt14Defeat
	msgbox MagmaHideout_2F_1R_Text_Grunt14PostBattle, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_EventScript_Grunt3::
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_3, MagmaHideout_2F_1R_Text_Grunt3Intro, MagmaHideout_2F_1R_Text_Grunt3Defeat
	msgbox MagmaHideout_2F_1R_Text_Grunt3PostBattle, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_EventScript_Grunt4::
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_4, MagmaHideout_2F_1R_Text_Grunt4Intro, MagmaHideout_2F_1R_Text_Grunt4Defeat
	msgbox MagmaHideout_2F_1R_Text_Grunt4PostBattle, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_EventScript_Grunt5::
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_5, MagmaHideout_2F_1R_Text_Grunt5Intro, MagmaHideout_2F_1R_Text_Grunt5Defeat
	msgbox MagmaHideout_2F_1R_Text_Grunt5PostBattle, MSGBOX_AUTOCLOSE
	end

MagmaHideout_2F_1R_Text_Grunt14Intro:
	.string "REMEMBRANCER: Guardar um nome pode\n"
	.string "ser resistencia. Obrigar alguem\p"
	.string "a reviver tudo tambem pode ser\n"
	.string "violencia.$"

MagmaHideout_2F_1R_Text_Grunt14Defeat:
	.string "REMEMBRANCER: O HORIZON quer uma\n"
	.string "Arauna estavel. Eu quero uma\p"
	.string "Arauna que saiba por que suas\n"
	.string "ruinas existem.$"

MagmaHideout_2F_1R_Text_Grunt14PostBattle:
	.string "REMEMBRANCER: O HORIZON quer uma\n"
	.string "Arauna estavel. Eu quero uma\p"
	.string "Arauna que saiba por que suas\n"
	.string "ruinas existem.$"

MagmaHideout_2F_1R_Text_Grunt3Intro:
	.string "REMEMBRANCER: LUZIA diz que\n"
	.string "memoria devolvida sem permissao\p"
	.string "ainda e melhor que memoria\n"
	.string "roubada. Nem todos aqui\p"
	.string "concordam com essa parte.$"

MagmaHideout_2F_1R_Text_Grunt3Defeat:
	.string "REMEMBRANCER: Se uma historia\n"
	.string "incomoda quem manda, ela vira\p"
	.string "'ruido', depois 'trauma',\n"
	.string "depois desaparece do registro.$"

MagmaHideout_2F_1R_Text_Grunt3PostBattle:
	.string "REMEMBRANCER: Guardar um nome pode\n"
	.string "ser resistencia. Obrigar alguem\p"
	.string "a reviver tudo tambem pode ser\n"
	.string "violencia.$"

MagmaHideout_2F_1R_Text_Grunt4Intro:
	.string "REMEMBRANCER: Guardar um nome pode\n"
	.string "ser resistencia. Obrigar alguem\p"
	.string "a reviver tudo tambem pode ser\n"
	.string "violencia.$"

MagmaHideout_2F_1R_Text_Grunt4Defeat:
	.string "REMEMBRANCER: Se uma historia\n"
	.string "incomoda quem manda, ela vira\p"
	.string "'ruido', depois 'trauma',\n"
	.string "depois desaparece do registro.$"

MagmaHideout_2F_1R_Text_Grunt4PostBattle:
	.string "REMEMBRANCER: LUZIA diz que\n"
	.string "memoria devolvida sem permissao\p"
	.string "ainda e melhor que memoria\n"
	.string "roubada. Nem todos aqui\p"
	.string "concordam com essa parte.$"

MagmaHideout_2F_1R_Text_Grunt5Intro:
	.string "REMEMBRANCER: O HORIZON quer uma\n"
	.string "Arauna estavel. Eu quero uma\p"
	.string "Arauna que saiba por que suas\n"
	.string "ruinas existem.$"

MagmaHideout_2F_1R_Text_Grunt5Defeat:
	.string "REMEMBRANCER: O HORIZON quer uma\n"
	.string "Arauna estavel. Eu quero uma\p"
	.string "Arauna que saiba por que suas\n"
	.string "ruinas existem.$"

MagmaHideout_2F_1R_Text_Grunt5PostBattle:
	.string "REMEMBRANCER: Guardar um nome pode\n"
	.string "ser resistencia. Obrigar alguem\p"
	.string "a reviver tudo tambem pode ser\n"
	.string "violencia.$"

