#ifndef GUARD_CONFIG_ARAUNA_H
#define GUARD_CONFIG_ARAUNA_H

#define ARAUNA_LANGUAGE_ENGLISH 0
#define ARAUNA_LANGUAGE_PORTUGUESE 1

#ifndef ARAUNA_LANGUAGE
#define ARAUNA_LANGUAGE ARAUNA_LANGUAGE_ENGLISH
#endif

#if ARAUNA_LANGUAGE != ARAUNA_LANGUAGE_ENGLISH && ARAUNA_LANGUAGE != ARAUNA_LANGUAGE_PORTUGUESE
#error "ARAUNA_LANGUAGE must be ARAUNA_LANGUAGE_ENGLISH or ARAUNA_LANGUAGE_PORTUGUESE"
#endif

#endif // GUARD_CONFIG_ARAUNA_H
