import type { TypeId } from "./types";

export type MoveCategory = "physical" | "special" | "status";
export interface MoveDefinition { id: string; name: string; type: TypeId; category: MoveCategory; power: number | null; accuracy: number | null; pp: number; priority: number; constant?: string; }
export interface SignatureMoveDefinition extends Omit<MoveDefinition, "name" | "constant"> { namePt: string; nameEn: string; effect: string; ownerIds: number[]; rationale: string; balanceNote: string; suggestedLevel: number; }

export const MOVES = {
  MOVE_POUND: { id: "MOVE_POUND", constant: "MOVE_POUND", name: "Pound", type: "normal", category: "physical", power: 40, accuracy: 100, pp: 35, priority: 0 },
  MOVE_KARATE_CHOP: { id: "MOVE_KARATE_CHOP", constant: "MOVE_KARATE_CHOP", name: "Karate Chop", type: "fighting", category: "physical", power: 50, accuracy: 100, pp: 25, priority: 0 },
  MOVE_DOUBLE_SLAP: { id: "MOVE_DOUBLE_SLAP", constant: "MOVE_DOUBLE_SLAP", name: "Double Slap", type: "normal", category: "physical", power: 15, accuracy: 85, pp: 10, priority: 0 },
  MOVE_COMET_PUNCH: { id: "MOVE_COMET_PUNCH", constant: "MOVE_COMET_PUNCH", name: "Comet Punch", type: "normal", category: "physical", power: 18, accuracy: 85, pp: 15, priority: 0 },
  MOVE_MEGA_PUNCH: { id: "MOVE_MEGA_PUNCH", constant: "MOVE_MEGA_PUNCH", name: "Mega Punch", type: "normal", category: "physical", power: 80, accuracy: 85, pp: 20, priority: 0 },
  MOVE_PAY_DAY: { id: "MOVE_PAY_DAY", constant: "MOVE_PAY_DAY", name: "Pay Day", type: "normal", category: "physical", power: 40, accuracy: 100, pp: 20, priority: 0 },
  MOVE_FIRE_PUNCH: { id: "MOVE_FIRE_PUNCH", constant: "MOVE_FIRE_PUNCH", name: "Fire Punch", type: "fire", category: "special", power: 75, accuracy: 100, pp: 15, priority: 0 },
  MOVE_ICE_PUNCH: { id: "MOVE_ICE_PUNCH", constant: "MOVE_ICE_PUNCH", name: "Ice Punch", type: "ice", category: "special", power: 75, accuracy: 100, pp: 15, priority: 0 },
  MOVE_THUNDER_PUNCH: { id: "MOVE_THUNDER_PUNCH", constant: "MOVE_THUNDER_PUNCH", name: "Thunder Punch", type: "electric", category: "special", power: 75, accuracy: 100, pp: 15, priority: 0 },
  MOVE_SCRATCH: { id: "MOVE_SCRATCH", constant: "MOVE_SCRATCH", name: "Scratch", type: "normal", category: "physical", power: 40, accuracy: 100, pp: 35, priority: 0 },
  MOVE_VICE_GRIP: { id: "MOVE_VICE_GRIP", constant: "MOVE_VICE_GRIP", name: "Vise Grip", type: "normal", category: "physical", power: 55, accuracy: 100, pp: 30, priority: 0 },
  MOVE_GUILLOTINE: { id: "MOVE_GUILLOTINE", constant: "MOVE_GUILLOTINE", name: "Guillotine", type: "normal", category: "physical", power: 1, accuracy: 30, pp: 5, priority: 0 },
  MOVE_RAZOR_WIND: { id: "MOVE_RAZOR_WIND", constant: "MOVE_RAZOR_WIND", name: "Razor Wind", type: "normal", category: "physical", power: 80, accuracy: 100, pp: 10, priority: 0 },
  MOVE_SWORDS_DANCE: { id: "MOVE_SWORDS_DANCE", constant: "MOVE_SWORDS_DANCE", name: "Swords Dance", type: "normal", category: "status", power: null, accuracy: null, pp: 30, priority: 0 },
  MOVE_CUT: { id: "MOVE_CUT", constant: "MOVE_CUT", name: "Cut", type: "normal", category: "physical", power: 50, accuracy: 95, pp: 30, priority: 0 },
  MOVE_GUST: { id: "MOVE_GUST", constant: "MOVE_GUST", name: "Gust", type: "flying", category: "physical", power: 40, accuracy: 100, pp: 35, priority: 0 },
  MOVE_WING_ATTACK: { id: "MOVE_WING_ATTACK", constant: "MOVE_WING_ATTACK", name: "Wing Attack", type: "flying", category: "physical", power: 60, accuracy: 100, pp: 35, priority: 0 },
  MOVE_WHIRLWIND: { id: "MOVE_WHIRLWIND", constant: "MOVE_WHIRLWIND", name: "Whirlwind", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, priority: -6 },
  MOVE_FLY: { id: "MOVE_FLY", constant: "MOVE_FLY", name: "Fly", type: "flying", category: "physical", power: 70, accuracy: 95, pp: 15, priority: 0 },
  MOVE_BIND: { id: "MOVE_BIND", constant: "MOVE_BIND", name: "Bind", type: "normal", category: "physical", power: 15, accuracy: 75, pp: 20, priority: 0 },
  MOVE_SLAM: { id: "MOVE_SLAM", constant: "MOVE_SLAM", name: "Slam", type: "normal", category: "physical", power: 80, accuracy: 75, pp: 20, priority: 0 },
  MOVE_VINE_WHIP: { id: "MOVE_VINE_WHIP", constant: "MOVE_VINE_WHIP", name: "Vine Whip", type: "grass", category: "special", power: 35, accuracy: 100, pp: 10, priority: 0 },
  MOVE_STOMP: { id: "MOVE_STOMP", constant: "MOVE_STOMP", name: "Stomp", type: "normal", category: "physical", power: 65, accuracy: 100, pp: 20, priority: 0 },
  MOVE_DOUBLE_KICK: { id: "MOVE_DOUBLE_KICK", constant: "MOVE_DOUBLE_KICK", name: "Double Kick", type: "fighting", category: "physical", power: 30, accuracy: 100, pp: 30, priority: 0 },
  MOVE_MEGA_KICK: { id: "MOVE_MEGA_KICK", constant: "MOVE_MEGA_KICK", name: "Mega Kick", type: "normal", category: "physical", power: 120, accuracy: 75, pp: 5, priority: 0 },
  MOVE_JUMP_KICK: { id: "MOVE_JUMP_KICK", constant: "MOVE_JUMP_KICK", name: "Jump Kick", type: "fighting", category: "physical", power: 70, accuracy: 95, pp: 25, priority: 0 },
  MOVE_ROLLING_KICK: { id: "MOVE_ROLLING_KICK", constant: "MOVE_ROLLING_KICK", name: "Rolling Kick", type: "fighting", category: "physical", power: 60, accuracy: 85, pp: 15, priority: 0 },
  MOVE_SAND_ATTACK: { id: "MOVE_SAND_ATTACK", constant: "MOVE_SAND_ATTACK", name: "Sand Attack", type: "ground", category: "status", power: null, accuracy: 100, pp: 15, priority: 0 },
  MOVE_HEADBUTT: { id: "MOVE_HEADBUTT", constant: "MOVE_HEADBUTT", name: "Headbutt", type: "normal", category: "physical", power: 70, accuracy: 100, pp: 15, priority: 0 },
  MOVE_HORN_ATTACK: { id: "MOVE_HORN_ATTACK", constant: "MOVE_HORN_ATTACK", name: "Horn Attack", type: "normal", category: "physical", power: 65, accuracy: 100, pp: 25, priority: 0 },
  MOVE_FURY_ATTACK: { id: "MOVE_FURY_ATTACK", constant: "MOVE_FURY_ATTACK", name: "Fury Attack", type: "normal", category: "physical", power: 15, accuracy: 85, pp: 20, priority: 0 },
  MOVE_HORN_DRILL: { id: "MOVE_HORN_DRILL", constant: "MOVE_HORN_DRILL", name: "Horn Drill", type: "normal", category: "physical", power: 1, accuracy: 30, pp: 5, priority: 0 },
  MOVE_TACKLE: { id: "MOVE_TACKLE", constant: "MOVE_TACKLE", name: "Tackle", type: "normal", category: "physical", power: 35, accuracy: 95, pp: 35, priority: 0 },
  MOVE_BODY_SLAM: { id: "MOVE_BODY_SLAM", constant: "MOVE_BODY_SLAM", name: "Body Slam", type: "normal", category: "physical", power: 85, accuracy: 100, pp: 15, priority: 0 },
  MOVE_WRAP: { id: "MOVE_WRAP", constant: "MOVE_WRAP", name: "Wrap", type: "normal", category: "physical", power: 15, accuracy: 85, pp: 20, priority: 0 },
  MOVE_TAKE_DOWN: { id: "MOVE_TAKE_DOWN", constant: "MOVE_TAKE_DOWN", name: "Take Down", type: "normal", category: "physical", power: 90, accuracy: 85, pp: 20, priority: 0 },
  MOVE_THRASH: { id: "MOVE_THRASH", constant: "MOVE_THRASH", name: "Thrash", type: "normal", category: "physical", power: 90, accuracy: 100, pp: 20, priority: 0 },
  MOVE_DOUBLE_EDGE: { id: "MOVE_DOUBLE_EDGE", constant: "MOVE_DOUBLE_EDGE", name: "Double-Edge", type: "normal", category: "physical", power: 120, accuracy: 100, pp: 15, priority: 0 },
  MOVE_TAIL_WHIP: { id: "MOVE_TAIL_WHIP", constant: "MOVE_TAIL_WHIP", name: "Tail Whip", type: "normal", category: "status", power: null, accuracy: 100, pp: 30, priority: 0 },
  MOVE_POISON_STING: { id: "MOVE_POISON_STING", constant: "MOVE_POISON_STING", name: "Poison Sting", type: "poison", category: "physical", power: 15, accuracy: 100, pp: 35, priority: 0 },
  MOVE_TWINEEDLE: { id: "MOVE_TWINEEDLE", constant: "MOVE_TWINEEDLE", name: "Twineedle", type: "bug", category: "physical", power: 25, accuracy: 100, pp: 20, priority: 0 },
  MOVE_PIN_MISSILE: { id: "MOVE_PIN_MISSILE", constant: "MOVE_PIN_MISSILE", name: "Pin Missile", type: "bug", category: "physical", power: 14, accuracy: 85, pp: 20, priority: 0 },
  MOVE_LEER: { id: "MOVE_LEER", constant: "MOVE_LEER", name: "Leer", type: "normal", category: "status", power: null, accuracy: 100, pp: 30, priority: 0 },
  MOVE_BITE: { id: "MOVE_BITE", constant: "MOVE_BITE", name: "Bite", type: "dark", category: "special", power: 60, accuracy: 100, pp: 25, priority: 0 },
  MOVE_GROWL: { id: "MOVE_GROWL", constant: "MOVE_GROWL", name: "Growl", type: "normal", category: "status", power: null, accuracy: 100, pp: 40, priority: 0 },
  MOVE_ROAR: { id: "MOVE_ROAR", constant: "MOVE_ROAR", name: "Roar", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, priority: -6 },
  MOVE_SING: { id: "MOVE_SING", constant: "MOVE_SING", name: "Sing", type: "normal", category: "status", power: null, accuracy: 55, pp: 15, priority: 0 },
  MOVE_SUPERSONIC: { id: "MOVE_SUPERSONIC", constant: "MOVE_SUPERSONIC", name: "Supersonic", type: "normal", category: "status", power: null, accuracy: 55, pp: 20, priority: 0 },
  MOVE_SONIC_BOOM: { id: "MOVE_SONIC_BOOM", constant: "MOVE_SONIC_BOOM", name: "Sonic Boom", type: "normal", category: "physical", power: 1, accuracy: 90, pp: 20, priority: 0 },
  MOVE_DISABLE: { id: "MOVE_DISABLE", constant: "MOVE_DISABLE", name: "Disable", type: "normal", category: "status", power: null, accuracy: 55, pp: 20, priority: 0 },
  MOVE_ACID: { id: "MOVE_ACID", constant: "MOVE_ACID", name: "Acid", type: "poison", category: "physical", power: 40, accuracy: 100, pp: 30, priority: 0 },
  MOVE_EMBER: { id: "MOVE_EMBER", constant: "MOVE_EMBER", name: "Ember", type: "fire", category: "special", power: 40, accuracy: 100, pp: 25, priority: 0 },
  MOVE_FLAMETHROWER: { id: "MOVE_FLAMETHROWER", constant: "MOVE_FLAMETHROWER", name: "Flamethrower", type: "fire", category: "special", power: 95, accuracy: 100, pp: 15, priority: 0 },
  MOVE_MIST: { id: "MOVE_MIST", constant: "MOVE_MIST", name: "Mist", type: "ice", category: "status", power: null, accuracy: null, pp: 30, priority: 0 },
  MOVE_WATER_GUN: { id: "MOVE_WATER_GUN", constant: "MOVE_WATER_GUN", name: "Water Gun", type: "water", category: "special", power: 40, accuracy: 100, pp: 25, priority: 0 },
  MOVE_HYDRO_PUMP: { id: "MOVE_HYDRO_PUMP", constant: "MOVE_HYDRO_PUMP", name: "Hydro Pump", type: "water", category: "special", power: 120, accuracy: 80, pp: 5, priority: 0 },
  MOVE_SURF: { id: "MOVE_SURF", constant: "MOVE_SURF", name: "Surf", type: "water", category: "special", power: 95, accuracy: 100, pp: 15, priority: 0 },
  MOVE_ICE_BEAM: { id: "MOVE_ICE_BEAM", constant: "MOVE_ICE_BEAM", name: "Ice Beam", type: "ice", category: "special", power: 95, accuracy: 100, pp: 10, priority: 0 },
  MOVE_BLIZZARD: { id: "MOVE_BLIZZARD", constant: "MOVE_BLIZZARD", name: "Blizzard", type: "ice", category: "special", power: 120, accuracy: 70, pp: 5, priority: 0 },
  MOVE_PSYBEAM: { id: "MOVE_PSYBEAM", constant: "MOVE_PSYBEAM", name: "Psybeam", type: "psychic", category: "special", power: 65, accuracy: 100, pp: 20, priority: 0 },
  MOVE_BUBBLE_BEAM: { id: "MOVE_BUBBLE_BEAM", constant: "MOVE_BUBBLE_BEAM", name: "Bubble Beam", type: "water", category: "special", power: 65, accuracy: 100, pp: 20, priority: 0 },
  MOVE_AURORA_BEAM: { id: "MOVE_AURORA_BEAM", constant: "MOVE_AURORA_BEAM", name: "Aurora Beam", type: "ice", category: "special", power: 65, accuracy: 100, pp: 20, priority: 0 },
  MOVE_HYPER_BEAM: { id: "MOVE_HYPER_BEAM", constant: "MOVE_HYPER_BEAM", name: "Hyper Beam", type: "normal", category: "physical", power: 150, accuracy: 90, pp: 5, priority: 0 },
  MOVE_PECK: { id: "MOVE_PECK", constant: "MOVE_PECK", name: "Peck", type: "flying", category: "physical", power: 35, accuracy: 100, pp: 35, priority: 0 },
  MOVE_DRILL_PECK: { id: "MOVE_DRILL_PECK", constant: "MOVE_DRILL_PECK", name: "Drill Peck", type: "flying", category: "physical", power: 80, accuracy: 100, pp: 20, priority: 0 },
  MOVE_SUBMISSION: { id: "MOVE_SUBMISSION", constant: "MOVE_SUBMISSION", name: "Submission", type: "fighting", category: "physical", power: 80, accuracy: 80, pp: 25, priority: 0 },
  MOVE_LOW_KICK: { id: "MOVE_LOW_KICK", constant: "MOVE_LOW_KICK", name: "Low Kick", type: "fighting", category: "physical", power: 1, accuracy: 100, pp: 20, priority: 0 },
  MOVE_COUNTER: { id: "MOVE_COUNTER", constant: "MOVE_COUNTER", name: "Counter", type: "fighting", category: "physical", power: 1, accuracy: 100, pp: 20, priority: -5 },
  MOVE_SEISMIC_TOSS: { id: "MOVE_SEISMIC_TOSS", constant: "MOVE_SEISMIC_TOSS", name: "Seismic Toss", type: "fighting", category: "physical", power: 1, accuracy: 100, pp: 20, priority: 0 },
  MOVE_STRENGTH: { id: "MOVE_STRENGTH", constant: "MOVE_STRENGTH", name: "Strength", type: "normal", category: "physical", power: 80, accuracy: 100, pp: 15, priority: 0 },
  MOVE_ABSORB: { id: "MOVE_ABSORB", constant: "MOVE_ABSORB", name: "Absorb", type: "grass", category: "special", power: 20, accuracy: 100, pp: 20, priority: 0 },
  MOVE_MEGA_DRAIN: { id: "MOVE_MEGA_DRAIN", constant: "MOVE_MEGA_DRAIN", name: "Mega Drain", type: "grass", category: "special", power: 40, accuracy: 100, pp: 10, priority: 0 },
  MOVE_LEECH_SEED: { id: "MOVE_LEECH_SEED", constant: "MOVE_LEECH_SEED", name: "Leech Seed", type: "grass", category: "status", power: null, accuracy: 90, pp: 10, priority: 0 },
  MOVE_GROWTH: { id: "MOVE_GROWTH", constant: "MOVE_GROWTH", name: "Growth", type: "normal", category: "status", power: null, accuracy: null, pp: 40, priority: 0 },
  MOVE_RAZOR_LEAF: { id: "MOVE_RAZOR_LEAF", constant: "MOVE_RAZOR_LEAF", name: "Razor Leaf", type: "grass", category: "special", power: 55, accuracy: 95, pp: 25, priority: 0 },
  MOVE_SOLAR_BEAM: { id: "MOVE_SOLAR_BEAM", constant: "MOVE_SOLAR_BEAM", name: "Solar Beam", type: "grass", category: "special", power: 120, accuracy: 100, pp: 10, priority: 0 },
  MOVE_POISON_POWDER: { id: "MOVE_POISON_POWDER", constant: "MOVE_POISON_POWDER", name: "Poison Powder", type: "poison", category: "status", power: null, accuracy: 75, pp: 35, priority: 0 },
  MOVE_STUN_SPORE: { id: "MOVE_STUN_SPORE", constant: "MOVE_STUN_SPORE", name: "Stun Spore", type: "grass", category: "status", power: null, accuracy: 75, pp: 30, priority: 0 },
  MOVE_SLEEP_POWDER: { id: "MOVE_SLEEP_POWDER", constant: "MOVE_SLEEP_POWDER", name: "Sleep Powder", type: "grass", category: "status", power: null, accuracy: 75, pp: 15, priority: 0 },
  MOVE_PETAL_DANCE: { id: "MOVE_PETAL_DANCE", constant: "MOVE_PETAL_DANCE", name: "Petal Dance", type: "grass", category: "special", power: 70, accuracy: 100, pp: 20, priority: 0 },
  MOVE_STRING_SHOT: { id: "MOVE_STRING_SHOT", constant: "MOVE_STRING_SHOT", name: "String Shot", type: "bug", category: "status", power: null, accuracy: 95, pp: 40, priority: 0 },
  MOVE_DRAGON_RAGE: { id: "MOVE_DRAGON_RAGE", constant: "MOVE_DRAGON_RAGE", name: "Dragon Rage", type: "dragon", category: "special", power: 1, accuracy: 100, pp: 10, priority: 0 },
  MOVE_FIRE_SPIN: { id: "MOVE_FIRE_SPIN", constant: "MOVE_FIRE_SPIN", name: "Fire Spin", type: "fire", category: "special", power: 15, accuracy: 70, pp: 15, priority: 0 },
  MOVE_THUNDER_SHOCK: { id: "MOVE_THUNDER_SHOCK", constant: "MOVE_THUNDER_SHOCK", name: "Thunder Shock", type: "electric", category: "special", power: 40, accuracy: 100, pp: 30, priority: 0 },
  MOVE_THUNDERBOLT: { id: "MOVE_THUNDERBOLT", constant: "MOVE_THUNDERBOLT", name: "Thunderbolt", type: "electric", category: "special", power: 95, accuracy: 100, pp: 15, priority: 0 },
  MOVE_THUNDER_WAVE: { id: "MOVE_THUNDER_WAVE", constant: "MOVE_THUNDER_WAVE", name: "Thunder Wave", type: "electric", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_THUNDER: { id: "MOVE_THUNDER", constant: "MOVE_THUNDER", name: "Thunder", type: "electric", category: "special", power: 120, accuracy: 70, pp: 10, priority: 0 },
  MOVE_ROCK_THROW: { id: "MOVE_ROCK_THROW", constant: "MOVE_ROCK_THROW", name: "Rock Throw", type: "rock", category: "physical", power: 50, accuracy: 90, pp: 15, priority: 0 },
  MOVE_EARTHQUAKE: { id: "MOVE_EARTHQUAKE", constant: "MOVE_EARTHQUAKE", name: "Earthquake", type: "ground", category: "physical", power: 100, accuracy: 100, pp: 10, priority: 0 },
  MOVE_FISSURE: { id: "MOVE_FISSURE", constant: "MOVE_FISSURE", name: "Fissure", type: "ground", category: "physical", power: 1, accuracy: 30, pp: 5, priority: 0 },
  MOVE_DIG: { id: "MOVE_DIG", constant: "MOVE_DIG", name: "Dig", type: "ground", category: "physical", power: 60, accuracy: 100, pp: 10, priority: 0 },
  MOVE_TOXIC: { id: "MOVE_TOXIC", constant: "MOVE_TOXIC", name: "Toxic", type: "poison", category: "status", power: null, accuracy: 85, pp: 10, priority: 0 },
  MOVE_CONFUSION: { id: "MOVE_CONFUSION", constant: "MOVE_CONFUSION", name: "Confusion", type: "psychic", category: "special", power: 50, accuracy: 100, pp: 25, priority: 0 },
  MOVE_PSYCHIC: { id: "MOVE_PSYCHIC", constant: "MOVE_PSYCHIC", name: "Psychic", type: "psychic", category: "special", power: 90, accuracy: 100, pp: 10, priority: 0 },
  MOVE_HYPNOSIS: { id: "MOVE_HYPNOSIS", constant: "MOVE_HYPNOSIS", name: "Hypnosis", type: "psychic", category: "status", power: null, accuracy: 60, pp: 20, priority: 0 },
  MOVE_MEDITATE: { id: "MOVE_MEDITATE", constant: "MOVE_MEDITATE", name: "Meditate", type: "psychic", category: "status", power: null, accuracy: null, pp: 40, priority: 0 },
  MOVE_AGILITY: { id: "MOVE_AGILITY", constant: "MOVE_AGILITY", name: "Agility", type: "psychic", category: "status", power: null, accuracy: null, pp: 30, priority: 0 },
  MOVE_QUICK_ATTACK: { id: "MOVE_QUICK_ATTACK", constant: "MOVE_QUICK_ATTACK", name: "Quick Attack", type: "normal", category: "physical", power: 40, accuracy: 100, pp: 30, priority: 1 },
  MOVE_RAGE: { id: "MOVE_RAGE", constant: "MOVE_RAGE", name: "Rage", type: "normal", category: "physical", power: 20, accuracy: 100, pp: 20, priority: 0 },
  MOVE_TELEPORT: { id: "MOVE_TELEPORT", constant: "MOVE_TELEPORT", name: "Teleport", type: "psychic", category: "status", power: null, accuracy: null, pp: 20, priority: 0 },
  MOVE_NIGHT_SHADE: { id: "MOVE_NIGHT_SHADE", constant: "MOVE_NIGHT_SHADE", name: "Night Shade", type: "ghost", category: "physical", power: 1, accuracy: 100, pp: 15, priority: 0 },
  MOVE_MIMIC: { id: "MOVE_MIMIC", constant: "MOVE_MIMIC", name: "Mimic", type: "normal", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_SCREECH: { id: "MOVE_SCREECH", constant: "MOVE_SCREECH", name: "Screech", type: "normal", category: "status", power: null, accuracy: 85, pp: 40, priority: 0 },
  MOVE_DOUBLE_TEAM: { id: "MOVE_DOUBLE_TEAM", constant: "MOVE_DOUBLE_TEAM", name: "Double Team", type: "normal", category: "status", power: null, accuracy: null, pp: 15, priority: 0 },
  MOVE_RECOVER: { id: "MOVE_RECOVER", constant: "MOVE_RECOVER", name: "Recover", type: "normal", category: "status", power: null, accuracy: null, pp: 20, priority: 0 },
  MOVE_HARDEN: { id: "MOVE_HARDEN", constant: "MOVE_HARDEN", name: "Harden", type: "normal", category: "status", power: null, accuracy: null, pp: 30, priority: 0 },
  MOVE_MINIMIZE: { id: "MOVE_MINIMIZE", constant: "MOVE_MINIMIZE", name: "Minimize", type: "normal", category: "status", power: null, accuracy: null, pp: 20, priority: 0 },
  MOVE_SMOKESCREEN: { id: "MOVE_SMOKESCREEN", constant: "MOVE_SMOKESCREEN", name: "Smokescreen", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_CONFUSE_RAY: { id: "MOVE_CONFUSE_RAY", constant: "MOVE_CONFUSE_RAY", name: "Confuse Ray", type: "ghost", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_WITHDRAW: { id: "MOVE_WITHDRAW", constant: "MOVE_WITHDRAW", name: "Withdraw", type: "water", category: "status", power: null, accuracy: null, pp: 40, priority: 0 },
  MOVE_DEFENSE_CURL: { id: "MOVE_DEFENSE_CURL", constant: "MOVE_DEFENSE_CURL", name: "Defense Curl", type: "normal", category: "status", power: null, accuracy: null, pp: 40, priority: 0 },
  MOVE_BARRIER: { id: "MOVE_BARRIER", constant: "MOVE_BARRIER", name: "Barrier", type: "psychic", category: "status", power: null, accuracy: null, pp: 30, priority: 0 },
  MOVE_LIGHT_SCREEN: { id: "MOVE_LIGHT_SCREEN", constant: "MOVE_LIGHT_SCREEN", name: "Light Screen", type: "psychic", category: "status", power: null, accuracy: null, pp: 30, priority: 0 },
  MOVE_HAZE: { id: "MOVE_HAZE", constant: "MOVE_HAZE", name: "Haze", type: "ice", category: "status", power: null, accuracy: null, pp: 30, priority: 0 },
  MOVE_REFLECT: { id: "MOVE_REFLECT", constant: "MOVE_REFLECT", name: "Reflect", type: "psychic", category: "status", power: null, accuracy: null, pp: 20, priority: 0 },
  MOVE_FOCUS_ENERGY: { id: "MOVE_FOCUS_ENERGY", constant: "MOVE_FOCUS_ENERGY", name: "Focus Energy", type: "normal", category: "status", power: null, accuracy: null, pp: 30, priority: 0 },
  MOVE_BIDE: { id: "MOVE_BIDE", constant: "MOVE_BIDE", name: "Bide", type: "normal", category: "physical", power: 1, accuracy: 100, pp: 10, priority: 0 },
  MOVE_METRONOME: { id: "MOVE_METRONOME", constant: "MOVE_METRONOME", name: "Metronome", type: "normal", category: "status", power: null, accuracy: null, pp: 10, priority: 0 },
  MOVE_MIRROR_MOVE: { id: "MOVE_MIRROR_MOVE", constant: "MOVE_MIRROR_MOVE", name: "Mirror Move", type: "flying", category: "status", power: null, accuracy: null, pp: 20, priority: 0 },
  MOVE_SELF_DESTRUCT: { id: "MOVE_SELF_DESTRUCT", constant: "MOVE_SELF_DESTRUCT", name: "Self-Destruct", type: "normal", category: "physical", power: 200, accuracy: 100, pp: 5, priority: 0 },
  MOVE_EGG_BOMB: { id: "MOVE_EGG_BOMB", constant: "MOVE_EGG_BOMB", name: "Egg Bomb", type: "normal", category: "physical", power: 100, accuracy: 75, pp: 10, priority: 0 },
  MOVE_LICK: { id: "MOVE_LICK", constant: "MOVE_LICK", name: "Lick", type: "ghost", category: "physical", power: 20, accuracy: 100, pp: 30, priority: 0 },
  MOVE_SMOG: { id: "MOVE_SMOG", constant: "MOVE_SMOG", name: "Smog", type: "poison", category: "physical", power: 20, accuracy: 70, pp: 20, priority: 0 },
  MOVE_SLUDGE: { id: "MOVE_SLUDGE", constant: "MOVE_SLUDGE", name: "Sludge", type: "poison", category: "physical", power: 65, accuracy: 100, pp: 20, priority: 0 },
  MOVE_BONE_CLUB: { id: "MOVE_BONE_CLUB", constant: "MOVE_BONE_CLUB", name: "Bone Club", type: "ground", category: "physical", power: 65, accuracy: 85, pp: 20, priority: 0 },
  MOVE_FIRE_BLAST: { id: "MOVE_FIRE_BLAST", constant: "MOVE_FIRE_BLAST", name: "Fire Blast", type: "fire", category: "special", power: 120, accuracy: 85, pp: 5, priority: 0 },
  MOVE_WATERFALL: { id: "MOVE_WATERFALL", constant: "MOVE_WATERFALL", name: "Waterfall", type: "water", category: "special", power: 80, accuracy: 100, pp: 15, priority: 0 },
  MOVE_CLAMP: { id: "MOVE_CLAMP", constant: "MOVE_CLAMP", name: "Clamp", type: "water", category: "special", power: 35, accuracy: 75, pp: 10, priority: 0 },
  MOVE_SWIFT: { id: "MOVE_SWIFT", constant: "MOVE_SWIFT", name: "Swift", type: "normal", category: "physical", power: 60, accuracy: null, pp: 20, priority: 0 },
  MOVE_SKULL_BASH: { id: "MOVE_SKULL_BASH", constant: "MOVE_SKULL_BASH", name: "Skull Bash", type: "normal", category: "physical", power: 100, accuracy: 100, pp: 15, priority: 0 },
  MOVE_SPIKE_CANNON: { id: "MOVE_SPIKE_CANNON", constant: "MOVE_SPIKE_CANNON", name: "Spike Cannon", type: "normal", category: "physical", power: 20, accuracy: 100, pp: 15, priority: 0 },
  MOVE_CONSTRICT: { id: "MOVE_CONSTRICT", constant: "MOVE_CONSTRICT", name: "Constrict", type: "normal", category: "physical", power: 10, accuracy: 100, pp: 35, priority: 0 },
  MOVE_AMNESIA: { id: "MOVE_AMNESIA", constant: "MOVE_AMNESIA", name: "Amnesia", type: "psychic", category: "status", power: null, accuracy: null, pp: 20, priority: 0 },
  MOVE_KINESIS: { id: "MOVE_KINESIS", constant: "MOVE_KINESIS", name: "Kinesis", type: "psychic", category: "status", power: null, accuracy: 80, pp: 15, priority: 0 },
  MOVE_SOFT_BOILED: { id: "MOVE_SOFT_BOILED", constant: "MOVE_SOFT_BOILED", name: "Soft-Boiled", type: "normal", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_HI_JUMP_KICK: { id: "MOVE_HI_JUMP_KICK", constant: "MOVE_HI_JUMP_KICK", name: "High Jump Kick", type: "fighting", category: "physical", power: 85, accuracy: 90, pp: 20, priority: 0 },
  MOVE_GLARE: { id: "MOVE_GLARE", constant: "MOVE_GLARE", name: "Glare", type: "normal", category: "status", power: null, accuracy: 75, pp: 30, priority: 0 },
  MOVE_DREAM_EATER: { id: "MOVE_DREAM_EATER", constant: "MOVE_DREAM_EATER", name: "Dream Eater", type: "psychic", category: "special", power: 100, accuracy: 100, pp: 15, priority: 0 },
  MOVE_POISON_GAS: { id: "MOVE_POISON_GAS", constant: "MOVE_POISON_GAS", name: "Poison Gas", type: "poison", category: "status", power: null, accuracy: 55, pp: 40, priority: 0 },
  MOVE_BARRAGE: { id: "MOVE_BARRAGE", constant: "MOVE_BARRAGE", name: "Barrage", type: "normal", category: "physical", power: 15, accuracy: 85, pp: 20, priority: 0 },
  MOVE_LEECH_LIFE: { id: "MOVE_LEECH_LIFE", constant: "MOVE_LEECH_LIFE", name: "Leech Life", type: "bug", category: "physical", power: 20, accuracy: 100, pp: 15, priority: 0 },
  MOVE_LOVELY_KISS: { id: "MOVE_LOVELY_KISS", constant: "MOVE_LOVELY_KISS", name: "Lovely Kiss", type: "normal", category: "status", power: null, accuracy: 75, pp: 10, priority: 0 },
  MOVE_SKY_ATTACK: { id: "MOVE_SKY_ATTACK", constant: "MOVE_SKY_ATTACK", name: "Sky Attack", type: "flying", category: "physical", power: 140, accuracy: 90, pp: 5, priority: 0 },
  MOVE_TRANSFORM: { id: "MOVE_TRANSFORM", constant: "MOVE_TRANSFORM", name: "Transform", type: "normal", category: "status", power: null, accuracy: null, pp: 10, priority: 0 },
  MOVE_BUBBLE: { id: "MOVE_BUBBLE", constant: "MOVE_BUBBLE", name: "Bubble", type: "water", category: "special", power: 20, accuracy: 100, pp: 30, priority: 0 },
  MOVE_DIZZY_PUNCH: { id: "MOVE_DIZZY_PUNCH", constant: "MOVE_DIZZY_PUNCH", name: "Dizzy Punch", type: "normal", category: "physical", power: 70, accuracy: 100, pp: 10, priority: 0 },
  MOVE_SPORE: { id: "MOVE_SPORE", constant: "MOVE_SPORE", name: "Spore", type: "grass", category: "status", power: null, accuracy: 100, pp: 15, priority: 0 },
  MOVE_FLASH: { id: "MOVE_FLASH", constant: "MOVE_FLASH", name: "Flash", type: "normal", category: "status", power: null, accuracy: 70, pp: 20, priority: 0 },
  MOVE_PSYWAVE: { id: "MOVE_PSYWAVE", constant: "MOVE_PSYWAVE", name: "Psywave", type: "psychic", category: "special", power: 1, accuracy: 80, pp: 15, priority: 0 },
  MOVE_SPLASH: { id: "MOVE_SPLASH", constant: "MOVE_SPLASH", name: "Splash", type: "normal", category: "status", power: null, accuracy: null, pp: 40, priority: 0 },
  MOVE_ACID_ARMOR: { id: "MOVE_ACID_ARMOR", constant: "MOVE_ACID_ARMOR", name: "Acid Armor", type: "poison", category: "status", power: null, accuracy: null, pp: 40, priority: 0 },
  MOVE_CRABHAMMER: { id: "MOVE_CRABHAMMER", constant: "MOVE_CRABHAMMER", name: "Crabhammer", type: "water", category: "special", power: 90, accuracy: 85, pp: 10, priority: 0 },
  MOVE_EXPLOSION: { id: "MOVE_EXPLOSION", constant: "MOVE_EXPLOSION", name: "Explosion", type: "normal", category: "physical", power: 250, accuracy: 100, pp: 5, priority: 0 },
  MOVE_FURY_SWIPES: { id: "MOVE_FURY_SWIPES", constant: "MOVE_FURY_SWIPES", name: "Fury Swipes", type: "normal", category: "physical", power: 18, accuracy: 80, pp: 15, priority: 0 },
  MOVE_BONEMERANG: { id: "MOVE_BONEMERANG", constant: "MOVE_BONEMERANG", name: "Bonemerang", type: "ground", category: "physical", power: 50, accuracy: 90, pp: 10, priority: 0 },
  MOVE_REST: { id: "MOVE_REST", constant: "MOVE_REST", name: "Rest", type: "psychic", category: "status", power: null, accuracy: null, pp: 10, priority: 0 },
  MOVE_ROCK_SLIDE: { id: "MOVE_ROCK_SLIDE", constant: "MOVE_ROCK_SLIDE", name: "Rock Slide", type: "rock", category: "physical", power: 75, accuracy: 90, pp: 10, priority: 0 },
  MOVE_HYPER_FANG: { id: "MOVE_HYPER_FANG", constant: "MOVE_HYPER_FANG", name: "Hyper Fang", type: "normal", category: "physical", power: 80, accuracy: 90, pp: 15, priority: 0 },
  MOVE_SHARPEN: { id: "MOVE_SHARPEN", constant: "MOVE_SHARPEN", name: "Sharpen", type: "normal", category: "status", power: null, accuracy: null, pp: 30, priority: 0 },
  MOVE_CONVERSION: { id: "MOVE_CONVERSION", constant: "MOVE_CONVERSION", name: "Conversion", type: "normal", category: "status", power: null, accuracy: null, pp: 30, priority: 0 },
  MOVE_TRI_ATTACK: { id: "MOVE_TRI_ATTACK", constant: "MOVE_TRI_ATTACK", name: "Tri Attack", type: "normal", category: "physical", power: 80, accuracy: 100, pp: 10, priority: 0 },
  MOVE_SUPER_FANG: { id: "MOVE_SUPER_FANG", constant: "MOVE_SUPER_FANG", name: "Super Fang", type: "normal", category: "physical", power: 1, accuracy: 90, pp: 10, priority: 0 },
  MOVE_SLASH: { id: "MOVE_SLASH", constant: "MOVE_SLASH", name: "Slash", type: "normal", category: "physical", power: 70, accuracy: 100, pp: 20, priority: 0 },
  MOVE_SUBSTITUTE: { id: "MOVE_SUBSTITUTE", constant: "MOVE_SUBSTITUTE", name: "Substitute", type: "normal", category: "status", power: null, accuracy: null, pp: 10, priority: 0 },
  MOVE_STRUGGLE: { id: "MOVE_STRUGGLE", constant: "MOVE_STRUGGLE", name: "Struggle", type: "normal", category: "physical", power: 50, accuracy: 100, pp: 1, priority: 0 },
  MOVE_SKETCH: { id: "MOVE_SKETCH", constant: "MOVE_SKETCH", name: "Sketch", type: "normal", category: "status", power: null, accuracy: null, pp: 1, priority: 0 },
  MOVE_TRIPLE_KICK: { id: "MOVE_TRIPLE_KICK", constant: "MOVE_TRIPLE_KICK", name: "Triple Kick", type: "fighting", category: "physical", power: 10, accuracy: 90, pp: 10, priority: 0 },
  MOVE_THIEF: { id: "MOVE_THIEF", constant: "MOVE_THIEF", name: "Thief", type: "dark", category: "special", power: 40, accuracy: 100, pp: 10, priority: 0 },
  MOVE_SPIDER_WEB: { id: "MOVE_SPIDER_WEB", constant: "MOVE_SPIDER_WEB", name: "Spider Web", type: "bug", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_MIND_READER: { id: "MOVE_MIND_READER", constant: "MOVE_MIND_READER", name: "Mind Reader", type: "normal", category: "status", power: null, accuracy: 100, pp: 5, priority: 0 },
  MOVE_NIGHTMARE: { id: "MOVE_NIGHTMARE", constant: "MOVE_NIGHTMARE", name: "Nightmare", type: "ghost", category: "status", power: null, accuracy: 100, pp: 15, priority: 0 },
  MOVE_FLAME_WHEEL: { id: "MOVE_FLAME_WHEEL", constant: "MOVE_FLAME_WHEEL", name: "Flame Wheel", type: "fire", category: "special", power: 60, accuracy: 100, pp: 25, priority: 0 },
  MOVE_SNORE: { id: "MOVE_SNORE", constant: "MOVE_SNORE", name: "Snore", type: "normal", category: "physical", power: 40, accuracy: 100, pp: 15, priority: 0 },
  MOVE_CURSE: { id: "MOVE_CURSE", constant: "MOVE_CURSE", name: "Curse", type: "mystery", category: "status", power: null, accuracy: null, pp: 10, priority: 0 },
  MOVE_FLAIL: { id: "MOVE_FLAIL", constant: "MOVE_FLAIL", name: "Flail", type: "normal", category: "physical", power: 1, accuracy: 100, pp: 15, priority: 0 },
  MOVE_CONVERSION_2: { id: "MOVE_CONVERSION_2", constant: "MOVE_CONVERSION_2", name: "Conversion 2", type: "normal", category: "status", power: null, accuracy: 100, pp: 30, priority: 0 },
  MOVE_AEROBLAST: { id: "MOVE_AEROBLAST", constant: "MOVE_AEROBLAST", name: "Aeroblast", type: "flying", category: "physical", power: 100, accuracy: 95, pp: 5, priority: 0 },
  MOVE_COTTON_SPORE: { id: "MOVE_COTTON_SPORE", constant: "MOVE_COTTON_SPORE", name: "Cotton Spore", type: "grass", category: "status", power: null, accuracy: 85, pp: 40, priority: 0 },
  MOVE_REVERSAL: { id: "MOVE_REVERSAL", constant: "MOVE_REVERSAL", name: "Reversal", type: "fighting", category: "physical", power: 1, accuracy: 100, pp: 15, priority: 0 },
  MOVE_SPITE: { id: "MOVE_SPITE", constant: "MOVE_SPITE", name: "Spite", type: "ghost", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_POWDER_SNOW: { id: "MOVE_POWDER_SNOW", constant: "MOVE_POWDER_SNOW", name: "Powder Snow", type: "ice", category: "special", power: 40, accuracy: 100, pp: 25, priority: 0 },
  MOVE_PROTECT: { id: "MOVE_PROTECT", constant: "MOVE_PROTECT", name: "Protect", type: "normal", category: "status", power: null, accuracy: null, pp: 10, priority: 3 },
  MOVE_MACH_PUNCH: { id: "MOVE_MACH_PUNCH", constant: "MOVE_MACH_PUNCH", name: "Mach Punch", type: "fighting", category: "physical", power: 40, accuracy: 100, pp: 30, priority: 1 },
  MOVE_SCARY_FACE: { id: "MOVE_SCARY_FACE", constant: "MOVE_SCARY_FACE", name: "Scary Face", type: "normal", category: "status", power: null, accuracy: 90, pp: 10, priority: 0 },
  MOVE_FAINT_ATTACK: { id: "MOVE_FAINT_ATTACK", constant: "MOVE_FAINT_ATTACK", name: "Feint Attack", type: "dark", category: "special", power: 60, accuracy: null, pp: 20, priority: 0 },
  MOVE_SWEET_KISS: { id: "MOVE_SWEET_KISS", constant: "MOVE_SWEET_KISS", name: "Sweet Kiss", type: "normal", category: "status", power: null, accuracy: 75, pp: 10, priority: 0 },
  MOVE_BELLY_DRUM: { id: "MOVE_BELLY_DRUM", constant: "MOVE_BELLY_DRUM", name: "Belly Drum", type: "normal", category: "status", power: null, accuracy: null, pp: 10, priority: 0 },
  MOVE_SLUDGE_BOMB: { id: "MOVE_SLUDGE_BOMB", constant: "MOVE_SLUDGE_BOMB", name: "Sludge Bomb", type: "poison", category: "physical", power: 90, accuracy: 100, pp: 10, priority: 0 },
  MOVE_MUD_SLAP: { id: "MOVE_MUD_SLAP", constant: "MOVE_MUD_SLAP", name: "Mud-Slap", type: "ground", category: "physical", power: 20, accuracy: 100, pp: 10, priority: 0 },
  MOVE_OCTAZOOKA: { id: "MOVE_OCTAZOOKA", constant: "MOVE_OCTAZOOKA", name: "Octazooka", type: "water", category: "special", power: 65, accuracy: 85, pp: 10, priority: 0 },
  MOVE_SPIKES: { id: "MOVE_SPIKES", constant: "MOVE_SPIKES", name: "Spikes", type: "ground", category: "status", power: null, accuracy: null, pp: 20, priority: 0 },
  MOVE_ZAP_CANNON: { id: "MOVE_ZAP_CANNON", constant: "MOVE_ZAP_CANNON", name: "Zap Cannon", type: "electric", category: "special", power: 100, accuracy: 50, pp: 5, priority: 0 },
  MOVE_FORESIGHT: { id: "MOVE_FORESIGHT", constant: "MOVE_FORESIGHT", name: "Foresight", type: "normal", category: "status", power: null, accuracy: 100, pp: 40, priority: 0 },
  MOVE_DESTINY_BOND: { id: "MOVE_DESTINY_BOND", constant: "MOVE_DESTINY_BOND", name: "Destiny Bond", type: "ghost", category: "status", power: null, accuracy: null, pp: 5, priority: 0 },
  MOVE_PERISH_SONG: { id: "MOVE_PERISH_SONG", constant: "MOVE_PERISH_SONG", name: "Perish Song", type: "normal", category: "status", power: null, accuracy: null, pp: 5, priority: 0 },
  MOVE_ICY_WIND: { id: "MOVE_ICY_WIND", constant: "MOVE_ICY_WIND", name: "Icy Wind", type: "ice", category: "special", power: 55, accuracy: 95, pp: 15, priority: 0 },
  MOVE_DETECT: { id: "MOVE_DETECT", constant: "MOVE_DETECT", name: "Detect", type: "fighting", category: "status", power: null, accuracy: null, pp: 5, priority: 3 },
  MOVE_BONE_RUSH: { id: "MOVE_BONE_RUSH", constant: "MOVE_BONE_RUSH", name: "Bone Rush", type: "ground", category: "physical", power: 25, accuracy: 80, pp: 10, priority: 0 },
  MOVE_LOCK_ON: { id: "MOVE_LOCK_ON", constant: "MOVE_LOCK_ON", name: "Lock-On", type: "normal", category: "status", power: null, accuracy: 100, pp: 5, priority: 0 },
  MOVE_OUTRAGE: { id: "MOVE_OUTRAGE", constant: "MOVE_OUTRAGE", name: "Outrage", type: "dragon", category: "special", power: 90, accuracy: 100, pp: 15, priority: 0 },
  MOVE_SANDSTORM: { id: "MOVE_SANDSTORM", constant: "MOVE_SANDSTORM", name: "Sandstorm", type: "rock", category: "status", power: null, accuracy: null, pp: 10, priority: 0 },
  MOVE_GIGA_DRAIN: { id: "MOVE_GIGA_DRAIN", constant: "MOVE_GIGA_DRAIN", name: "Giga Drain", type: "grass", category: "special", power: 60, accuracy: 100, pp: 5, priority: 0 },
  MOVE_ENDURE: { id: "MOVE_ENDURE", constant: "MOVE_ENDURE", name: "Endure", type: "normal", category: "status", power: null, accuracy: null, pp: 10, priority: 3 },
  MOVE_CHARM: { id: "MOVE_CHARM", constant: "MOVE_CHARM", name: "Charm", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_ROLLOUT: { id: "MOVE_ROLLOUT", constant: "MOVE_ROLLOUT", name: "Rollout", type: "rock", category: "physical", power: 30, accuracy: 90, pp: 20, priority: 0 },
  MOVE_FALSE_SWIPE: { id: "MOVE_FALSE_SWIPE", constant: "MOVE_FALSE_SWIPE", name: "False Swipe", type: "normal", category: "physical", power: 40, accuracy: 100, pp: 40, priority: 0 },
  MOVE_SWAGGER: { id: "MOVE_SWAGGER", constant: "MOVE_SWAGGER", name: "Swagger", type: "normal", category: "status", power: null, accuracy: 90, pp: 15, priority: 0 },
  MOVE_MILK_DRINK: { id: "MOVE_MILK_DRINK", constant: "MOVE_MILK_DRINK", name: "Milk Drink", type: "normal", category: "status", power: null, accuracy: null, pp: 10, priority: 0 },
  MOVE_SPARK: { id: "MOVE_SPARK", constant: "MOVE_SPARK", name: "Spark", type: "electric", category: "special", power: 65, accuracy: 100, pp: 20, priority: 0 },
  MOVE_FURY_CUTTER: { id: "MOVE_FURY_CUTTER", constant: "MOVE_FURY_CUTTER", name: "Fury Cutter", type: "bug", category: "physical", power: 10, accuracy: 95, pp: 20, priority: 0 },
  MOVE_STEEL_WING: { id: "MOVE_STEEL_WING", constant: "MOVE_STEEL_WING", name: "Steel Wing", type: "steel", category: "physical", power: 70, accuracy: 90, pp: 25, priority: 0 },
  MOVE_MEAN_LOOK: { id: "MOVE_MEAN_LOOK", constant: "MOVE_MEAN_LOOK", name: "Mean Look", type: "normal", category: "status", power: null, accuracy: 100, pp: 5, priority: 0 },
  MOVE_ATTRACT: { id: "MOVE_ATTRACT", constant: "MOVE_ATTRACT", name: "Attract", type: "normal", category: "status", power: null, accuracy: 100, pp: 15, priority: 0 },
  MOVE_SLEEP_TALK: { id: "MOVE_SLEEP_TALK", constant: "MOVE_SLEEP_TALK", name: "Sleep Talk", type: "normal", category: "status", power: null, accuracy: null, pp: 10, priority: 0 },
  MOVE_HEAL_BELL: { id: "MOVE_HEAL_BELL", constant: "MOVE_HEAL_BELL", name: "Heal Bell", type: "normal", category: "status", power: null, accuracy: null, pp: 5, priority: 0 },
  MOVE_RETURN: { id: "MOVE_RETURN", constant: "MOVE_RETURN", name: "Return", type: "normal", category: "physical", power: 1, accuracy: 100, pp: 20, priority: 0 },
  MOVE_PRESENT: { id: "MOVE_PRESENT", constant: "MOVE_PRESENT", name: "Present", type: "normal", category: "physical", power: 1, accuracy: 90, pp: 15, priority: 0 },
  MOVE_FRUSTRATION: { id: "MOVE_FRUSTRATION", constant: "MOVE_FRUSTRATION", name: "Frustration", type: "normal", category: "physical", power: 1, accuracy: 100, pp: 20, priority: 0 },
  MOVE_SAFEGUARD: { id: "MOVE_SAFEGUARD", constant: "MOVE_SAFEGUARD", name: "Safeguard", type: "normal", category: "status", power: null, accuracy: null, pp: 25, priority: 0 },
  MOVE_PAIN_SPLIT: { id: "MOVE_PAIN_SPLIT", constant: "MOVE_PAIN_SPLIT", name: "Pain Split", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_SACRED_FIRE: { id: "MOVE_SACRED_FIRE", constant: "MOVE_SACRED_FIRE", name: "Sacred Fire", type: "fire", category: "special", power: 100, accuracy: 95, pp: 5, priority: 0 },
  MOVE_MAGNITUDE: { id: "MOVE_MAGNITUDE", constant: "MOVE_MAGNITUDE", name: "Magnitude", type: "ground", category: "physical", power: 1, accuracy: 100, pp: 30, priority: 0 },
  MOVE_DYNAMIC_PUNCH: { id: "MOVE_DYNAMIC_PUNCH", constant: "MOVE_DYNAMIC_PUNCH", name: "Dynamic Punch", type: "fighting", category: "physical", power: 100, accuracy: 50, pp: 5, priority: 0 },
  MOVE_MEGAHORN: { id: "MOVE_MEGAHORN", constant: "MOVE_MEGAHORN", name: "Megahorn", type: "bug", category: "physical", power: 120, accuracy: 85, pp: 10, priority: 0 },
  MOVE_DRAGON_BREATH: { id: "MOVE_DRAGON_BREATH", constant: "MOVE_DRAGON_BREATH", name: "Dragon Breath", type: "dragon", category: "special", power: 60, accuracy: 100, pp: 20, priority: 0 },
  MOVE_BATON_PASS: { id: "MOVE_BATON_PASS", constant: "MOVE_BATON_PASS", name: "Baton Pass", type: "normal", category: "status", power: null, accuracy: null, pp: 40, priority: 0 },
  MOVE_ENCORE: { id: "MOVE_ENCORE", constant: "MOVE_ENCORE", name: "Encore", type: "normal", category: "status", power: null, accuracy: 100, pp: 5, priority: 0 },
  MOVE_PURSUIT: { id: "MOVE_PURSUIT", constant: "MOVE_PURSUIT", name: "Pursuit", type: "dark", category: "special", power: 40, accuracy: 100, pp: 20, priority: 0 },
  MOVE_RAPID_SPIN: { id: "MOVE_RAPID_SPIN", constant: "MOVE_RAPID_SPIN", name: "Rapid Spin", type: "normal", category: "physical", power: 20, accuracy: 100, pp: 40, priority: 0 },
  MOVE_SWEET_SCENT: { id: "MOVE_SWEET_SCENT", constant: "MOVE_SWEET_SCENT", name: "Sweet Scent", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_IRON_TAIL: { id: "MOVE_IRON_TAIL", constant: "MOVE_IRON_TAIL", name: "Iron Tail", type: "steel", category: "physical", power: 100, accuracy: 75, pp: 15, priority: 0 },
  MOVE_METAL_CLAW: { id: "MOVE_METAL_CLAW", constant: "MOVE_METAL_CLAW", name: "Metal Claw", type: "steel", category: "physical", power: 50, accuracy: 95, pp: 35, priority: 0 },
  MOVE_VITAL_THROW: { id: "MOVE_VITAL_THROW", constant: "MOVE_VITAL_THROW", name: "Vital Throw", type: "fighting", category: "physical", power: 70, accuracy: 100, pp: 10, priority: -1 },
  MOVE_MORNING_SUN: { id: "MOVE_MORNING_SUN", constant: "MOVE_MORNING_SUN", name: "Morning Sun", type: "normal", category: "status", power: null, accuracy: null, pp: 5, priority: 0 },
  MOVE_SYNTHESIS: { id: "MOVE_SYNTHESIS", constant: "MOVE_SYNTHESIS", name: "Synthesis", type: "grass", category: "status", power: null, accuracy: null, pp: 5, priority: 0 },
  MOVE_MOONLIGHT: { id: "MOVE_MOONLIGHT", constant: "MOVE_MOONLIGHT", name: "Moonlight", type: "normal", category: "status", power: null, accuracy: null, pp: 5, priority: 0 },
  MOVE_HIDDEN_POWER: { id: "MOVE_HIDDEN_POWER", constant: "MOVE_HIDDEN_POWER", name: "Hidden Power", type: "normal", category: "physical", power: 1, accuracy: 100, pp: 15, priority: 0 },
  MOVE_CROSS_CHOP: { id: "MOVE_CROSS_CHOP", constant: "MOVE_CROSS_CHOP", name: "Cross Chop", type: "fighting", category: "physical", power: 100, accuracy: 80, pp: 5, priority: 0 },
  MOVE_TWISTER: { id: "MOVE_TWISTER", constant: "MOVE_TWISTER", name: "Twister", type: "dragon", category: "special", power: 40, accuracy: 100, pp: 20, priority: 0 },
  MOVE_RAIN_DANCE: { id: "MOVE_RAIN_DANCE", constant: "MOVE_RAIN_DANCE", name: "Rain Dance", type: "water", category: "status", power: null, accuracy: null, pp: 5, priority: 0 },
  MOVE_SUNNY_DAY: { id: "MOVE_SUNNY_DAY", constant: "MOVE_SUNNY_DAY", name: "Sunny Day", type: "fire", category: "status", power: null, accuracy: null, pp: 5, priority: 0 },
  MOVE_CRUNCH: { id: "MOVE_CRUNCH", constant: "MOVE_CRUNCH", name: "Crunch", type: "dark", category: "special", power: 80, accuracy: 100, pp: 15, priority: 0 },
  MOVE_MIRROR_COAT: { id: "MOVE_MIRROR_COAT", constant: "MOVE_MIRROR_COAT", name: "Mirror Coat", type: "psychic", category: "special", power: 1, accuracy: 100, pp: 20, priority: -5 },
  MOVE_PSYCH_UP: { id: "MOVE_PSYCH_UP", constant: "MOVE_PSYCH_UP", name: "Psych Up", type: "normal", category: "status", power: null, accuracy: null, pp: 10, priority: 0 },
  MOVE_EXTREME_SPEED: { id: "MOVE_EXTREME_SPEED", constant: "MOVE_EXTREME_SPEED", name: "Extreme Speed", type: "normal", category: "physical", power: 80, accuracy: 100, pp: 5, priority: 1 },
  MOVE_ANCIENT_POWER: { id: "MOVE_ANCIENT_POWER", constant: "MOVE_ANCIENT_POWER", name: "Ancient Power", type: "rock", category: "physical", power: 60, accuracy: 100, pp: 5, priority: 0 },
  MOVE_SHADOW_BALL: { id: "MOVE_SHADOW_BALL", constant: "MOVE_SHADOW_BALL", name: "Shadow Ball", type: "ghost", category: "physical", power: 80, accuracy: 100, pp: 15, priority: 0 },
  MOVE_FUTURE_SIGHT: { id: "MOVE_FUTURE_SIGHT", constant: "MOVE_FUTURE_SIGHT", name: "Future Sight", type: "psychic", category: "special", power: 80, accuracy: 90, pp: 15, priority: 0 },
  MOVE_ROCK_SMASH: { id: "MOVE_ROCK_SMASH", constant: "MOVE_ROCK_SMASH", name: "Rock Smash", type: "fighting", category: "physical", power: 20, accuracy: 100, pp: 15, priority: 0 },
  MOVE_WHIRLPOOL: { id: "MOVE_WHIRLPOOL", constant: "MOVE_WHIRLPOOL", name: "Whirlpool", type: "water", category: "special", power: 15, accuracy: 70, pp: 15, priority: 0 },
  MOVE_BEAT_UP: { id: "MOVE_BEAT_UP", constant: "MOVE_BEAT_UP", name: "Beat Up", type: "dark", category: "special", power: 10, accuracy: 100, pp: 10, priority: 0 },
  MOVE_FAKE_OUT: { id: "MOVE_FAKE_OUT", constant: "MOVE_FAKE_OUT", name: "Fake Out", type: "normal", category: "physical", power: 40, accuracy: 100, pp: 10, priority: 1 },
  MOVE_UPROAR: { id: "MOVE_UPROAR", constant: "MOVE_UPROAR", name: "Uproar", type: "normal", category: "physical", power: 50, accuracy: 100, pp: 10, priority: 0 },
  MOVE_STOCKPILE: { id: "MOVE_STOCKPILE", constant: "MOVE_STOCKPILE", name: "Stockpile", type: "normal", category: "status", power: null, accuracy: null, pp: 10, priority: 0 },
  MOVE_SPIT_UP: { id: "MOVE_SPIT_UP", constant: "MOVE_SPIT_UP", name: "Spit Up", type: "normal", category: "physical", power: 100, accuracy: 100, pp: 10, priority: 0 },
  MOVE_SWALLOW: { id: "MOVE_SWALLOW", constant: "MOVE_SWALLOW", name: "Swallow", type: "normal", category: "status", power: null, accuracy: null, pp: 10, priority: 0 },
  MOVE_HEAT_WAVE: { id: "MOVE_HEAT_WAVE", constant: "MOVE_HEAT_WAVE", name: "Heat Wave", type: "fire", category: "special", power: 100, accuracy: 90, pp: 10, priority: 0 },
  MOVE_HAIL: { id: "MOVE_HAIL", constant: "MOVE_HAIL", name: "Hail", type: "ice", category: "status", power: null, accuracy: null, pp: 10, priority: 0 },
  MOVE_TORMENT: { id: "MOVE_TORMENT", constant: "MOVE_TORMENT", name: "Torment", type: "dark", category: "status", power: null, accuracy: 100, pp: 15, priority: 0 },
  MOVE_FLATTER: { id: "MOVE_FLATTER", constant: "MOVE_FLATTER", name: "Flatter", type: "dark", category: "status", power: null, accuracy: 100, pp: 15, priority: 0 },
  MOVE_WILL_O_WISP: { id: "MOVE_WILL_O_WISP", constant: "MOVE_WILL_O_WISP", name: "Will-O-Wisp", type: "fire", category: "status", power: null, accuracy: 75, pp: 15, priority: 0 },
  MOVE_MEMENTO: { id: "MOVE_MEMENTO", constant: "MOVE_MEMENTO", name: "Memento", type: "dark", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_FACADE: { id: "MOVE_FACADE", constant: "MOVE_FACADE", name: "Facade", type: "normal", category: "physical", power: 70, accuracy: 100, pp: 20, priority: 0 },
  MOVE_FOCUS_PUNCH: { id: "MOVE_FOCUS_PUNCH", constant: "MOVE_FOCUS_PUNCH", name: "Focus Punch", type: "fighting", category: "physical", power: 150, accuracy: 100, pp: 20, priority: -3 },
  MOVE_SMELLING_SALT: { id: "MOVE_SMELLING_SALT", constant: "MOVE_SMELLING_SALT", name: "Smelling Salts", type: "normal", category: "physical", power: 60, accuracy: 100, pp: 10, priority: 0 },
  MOVE_FOLLOW_ME: { id: "MOVE_FOLLOW_ME", constant: "MOVE_FOLLOW_ME", name: "Follow Me", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, priority: 3 },
  MOVE_NATURE_POWER: { id: "MOVE_NATURE_POWER", constant: "MOVE_NATURE_POWER", name: "Nature Power", type: "normal", category: "status", power: null, accuracy: 95, pp: 20, priority: 0 },
  MOVE_CHARGE: { id: "MOVE_CHARGE", constant: "MOVE_CHARGE", name: "Charge", type: "electric", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_TAUNT: { id: "MOVE_TAUNT", constant: "MOVE_TAUNT", name: "Taunt", type: "dark", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_HELPING_HAND: { id: "MOVE_HELPING_HAND", constant: "MOVE_HELPING_HAND", name: "Helping Hand", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, priority: 5 },
  MOVE_TRICK: { id: "MOVE_TRICK", constant: "MOVE_TRICK", name: "Trick", type: "psychic", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_ROLE_PLAY: { id: "MOVE_ROLE_PLAY", constant: "MOVE_ROLE_PLAY", name: "Role Play", type: "psychic", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_WISH: { id: "MOVE_WISH", constant: "MOVE_WISH", name: "Wish", type: "normal", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_ASSIST: { id: "MOVE_ASSIST", constant: "MOVE_ASSIST", name: "Assist", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_INGRAIN: { id: "MOVE_INGRAIN", constant: "MOVE_INGRAIN", name: "Ingrain", type: "grass", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_SUPERPOWER: { id: "MOVE_SUPERPOWER", constant: "MOVE_SUPERPOWER", name: "Superpower", type: "fighting", category: "physical", power: 120, accuracy: 100, pp: 5, priority: 0 },
  MOVE_MAGIC_COAT: { id: "MOVE_MAGIC_COAT", constant: "MOVE_MAGIC_COAT", name: "Magic Coat", type: "psychic", category: "status", power: null, accuracy: 100, pp: 15, priority: 4 },
  MOVE_RECYCLE: { id: "MOVE_RECYCLE", constant: "MOVE_RECYCLE", name: "Recycle", type: "normal", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_REVENGE: { id: "MOVE_REVENGE", constant: "MOVE_REVENGE", name: "Revenge", type: "fighting", category: "physical", power: 60, accuracy: 100, pp: 10, priority: -4 },
  MOVE_BRICK_BREAK: { id: "MOVE_BRICK_BREAK", constant: "MOVE_BRICK_BREAK", name: "Brick Break", type: "fighting", category: "physical", power: 75, accuracy: 100, pp: 15, priority: 0 },
  MOVE_YAWN: { id: "MOVE_YAWN", constant: "MOVE_YAWN", name: "Yawn", type: "normal", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_KNOCK_OFF: { id: "MOVE_KNOCK_OFF", constant: "MOVE_KNOCK_OFF", name: "Knock Off", type: "dark", category: "special", power: 20, accuracy: 100, pp: 20, priority: 0 },
  MOVE_ENDEAVOR: { id: "MOVE_ENDEAVOR", constant: "MOVE_ENDEAVOR", name: "Endeavor", type: "normal", category: "physical", power: 1, accuracy: 100, pp: 5, priority: 0 },
  MOVE_ERUPTION: { id: "MOVE_ERUPTION", constant: "MOVE_ERUPTION", name: "Eruption", type: "fire", category: "special", power: 150, accuracy: 100, pp: 5, priority: 0 },
  MOVE_SKILL_SWAP: { id: "MOVE_SKILL_SWAP", constant: "MOVE_SKILL_SWAP", name: "Skill Swap", type: "psychic", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_IMPRISON: { id: "MOVE_IMPRISON", constant: "MOVE_IMPRISON", name: "Imprison", type: "psychic", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_REFRESH: { id: "MOVE_REFRESH", constant: "MOVE_REFRESH", name: "Refresh", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_GRUDGE: { id: "MOVE_GRUDGE", constant: "MOVE_GRUDGE", name: "Grudge", type: "ghost", category: "status", power: null, accuracy: 100, pp: 5, priority: 0 },
  MOVE_SNATCH: { id: "MOVE_SNATCH", constant: "MOVE_SNATCH", name: "Snatch", type: "dark", category: "status", power: null, accuracy: 100, pp: 10, priority: 4 },
  MOVE_SECRET_POWER: { id: "MOVE_SECRET_POWER", constant: "MOVE_SECRET_POWER", name: "Secret Power", type: "normal", category: "physical", power: 70, accuracy: 100, pp: 20, priority: 0 },
  MOVE_DIVE: { id: "MOVE_DIVE", constant: "MOVE_DIVE", name: "Dive", type: "water", category: "special", power: 60, accuracy: 100, pp: 10, priority: 0 },
  MOVE_ARM_THRUST: { id: "MOVE_ARM_THRUST", constant: "MOVE_ARM_THRUST", name: "Arm Thrust", type: "fighting", category: "physical", power: 15, accuracy: 100, pp: 20, priority: 0 },
  MOVE_CAMOUFLAGE: { id: "MOVE_CAMOUFLAGE", constant: "MOVE_CAMOUFLAGE", name: "Camouflage", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_TAIL_GLOW: { id: "MOVE_TAIL_GLOW", constant: "MOVE_TAIL_GLOW", name: "Tail Glow", type: "bug", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_LUSTER_PURGE: { id: "MOVE_LUSTER_PURGE", constant: "MOVE_LUSTER_PURGE", name: "Luster Purge", type: "psychic", category: "special", power: 70, accuracy: 100, pp: 5, priority: 0 },
  MOVE_MIST_BALL: { id: "MOVE_MIST_BALL", constant: "MOVE_MIST_BALL", name: "Mist Ball", type: "psychic", category: "special", power: 70, accuracy: 100, pp: 5, priority: 0 },
  MOVE_FEATHER_DANCE: { id: "MOVE_FEATHER_DANCE", constant: "MOVE_FEATHER_DANCE", name: "Feather Dance", type: "flying", category: "status", power: null, accuracy: 100, pp: 15, priority: 0 },
  MOVE_TEETER_DANCE: { id: "MOVE_TEETER_DANCE", constant: "MOVE_TEETER_DANCE", name: "Teeter Dance", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_BLAZE_KICK: { id: "MOVE_BLAZE_KICK", constant: "MOVE_BLAZE_KICK", name: "Blaze Kick", type: "fire", category: "special", power: 85, accuracy: 90, pp: 10, priority: 0 },
  MOVE_MUD_SPORT: { id: "MOVE_MUD_SPORT", constant: "MOVE_MUD_SPORT", name: "Mud Sport", type: "ground", category: "status", power: null, accuracy: 100, pp: 15, priority: 0 },
  MOVE_ICE_BALL: { id: "MOVE_ICE_BALL", constant: "MOVE_ICE_BALL", name: "Ice Ball", type: "ice", category: "special", power: 30, accuracy: 90, pp: 20, priority: 0 },
  MOVE_NEEDLE_ARM: { id: "MOVE_NEEDLE_ARM", constant: "MOVE_NEEDLE_ARM", name: "Needle Arm", type: "grass", category: "special", power: 60, accuracy: 100, pp: 15, priority: 0 },
  MOVE_SLACK_OFF: { id: "MOVE_SLACK_OFF", constant: "MOVE_SLACK_OFF", name: "Slack Off", type: "normal", category: "status", power: null, accuracy: 100, pp: 10, priority: 0 },
  MOVE_HYPER_VOICE: { id: "MOVE_HYPER_VOICE", constant: "MOVE_HYPER_VOICE", name: "Hyper Voice", type: "normal", category: "physical", power: 90, accuracy: 100, pp: 10, priority: 0 },
  MOVE_POISON_FANG: { id: "MOVE_POISON_FANG", constant: "MOVE_POISON_FANG", name: "Poison Fang", type: "poison", category: "physical", power: 50, accuracy: 100, pp: 15, priority: 0 },
  MOVE_CRUSH_CLAW: { id: "MOVE_CRUSH_CLAW", constant: "MOVE_CRUSH_CLAW", name: "Crush Claw", type: "normal", category: "physical", power: 75, accuracy: 95, pp: 10, priority: 0 },
  MOVE_BLAST_BURN: { id: "MOVE_BLAST_BURN", constant: "MOVE_BLAST_BURN", name: "Blast Burn", type: "fire", category: "special", power: 150, accuracy: 90, pp: 5, priority: 0 },
  MOVE_HYDRO_CANNON: { id: "MOVE_HYDRO_CANNON", constant: "MOVE_HYDRO_CANNON", name: "Hydro Cannon", type: "water", category: "special", power: 150, accuracy: 90, pp: 5, priority: 0 },
  MOVE_METEOR_MASH: { id: "MOVE_METEOR_MASH", constant: "MOVE_METEOR_MASH", name: "Meteor Mash", type: "steel", category: "physical", power: 100, accuracy: 85, pp: 10, priority: 0 },
  MOVE_ASTONISH: { id: "MOVE_ASTONISH", constant: "MOVE_ASTONISH", name: "Astonish", type: "ghost", category: "physical", power: 30, accuracy: 100, pp: 15, priority: 0 },
  MOVE_WEATHER_BALL: { id: "MOVE_WEATHER_BALL", constant: "MOVE_WEATHER_BALL", name: "Weather Ball", type: "normal", category: "physical", power: 50, accuracy: 100, pp: 10, priority: 0 },
  MOVE_AROMATHERAPY: { id: "MOVE_AROMATHERAPY", constant: "MOVE_AROMATHERAPY", name: "Aromatherapy", type: "grass", category: "status", power: null, accuracy: null, pp: 5, priority: 0 },
  MOVE_FAKE_TEARS: { id: "MOVE_FAKE_TEARS", constant: "MOVE_FAKE_TEARS", name: "Fake Tears", type: "dark", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_AIR_CUTTER: { id: "MOVE_AIR_CUTTER", constant: "MOVE_AIR_CUTTER", name: "Air Cutter", type: "flying", category: "physical", power: 55, accuracy: 95, pp: 25, priority: 0 },
  MOVE_OVERHEAT: { id: "MOVE_OVERHEAT", constant: "MOVE_OVERHEAT", name: "Overheat", type: "fire", category: "special", power: 140, accuracy: 90, pp: 5, priority: 0 },
  MOVE_ODOR_SLEUTH: { id: "MOVE_ODOR_SLEUTH", constant: "MOVE_ODOR_SLEUTH", name: "Odor Sleuth", type: "normal", category: "status", power: null, accuracy: 100, pp: 40, priority: 0 },
  MOVE_ROCK_TOMB: { id: "MOVE_ROCK_TOMB", constant: "MOVE_ROCK_TOMB", name: "Rock Tomb", type: "rock", category: "physical", power: 50, accuracy: 80, pp: 10, priority: 0 },
  MOVE_SILVER_WIND: { id: "MOVE_SILVER_WIND", constant: "MOVE_SILVER_WIND", name: "Silver Wind", type: "bug", category: "physical", power: 60, accuracy: 100, pp: 5, priority: 0 },
  MOVE_METAL_SOUND: { id: "MOVE_METAL_SOUND", constant: "MOVE_METAL_SOUND", name: "Metal Sound", type: "steel", category: "status", power: null, accuracy: 85, pp: 40, priority: 0 },
  MOVE_GRASS_WHISTLE: { id: "MOVE_GRASS_WHISTLE", constant: "MOVE_GRASS_WHISTLE", name: "Grass Whistle", type: "grass", category: "status", power: null, accuracy: 55, pp: 15, priority: 0 },
  MOVE_TICKLE: { id: "MOVE_TICKLE", constant: "MOVE_TICKLE", name: "Tickle", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, priority: 0 },
  MOVE_COSMIC_POWER: { id: "MOVE_COSMIC_POWER", constant: "MOVE_COSMIC_POWER", name: "Cosmic Power", type: "psychic", category: "status", power: null, accuracy: null, pp: 20, priority: 0 },
  MOVE_WATER_SPOUT: { id: "MOVE_WATER_SPOUT", constant: "MOVE_WATER_SPOUT", name: "Water Spout", type: "water", category: "special", power: 150, accuracy: 100, pp: 5, priority: 0 },
  MOVE_SIGNAL_BEAM: { id: "MOVE_SIGNAL_BEAM", constant: "MOVE_SIGNAL_BEAM", name: "Signal Beam", type: "bug", category: "physical", power: 75, accuracy: 100, pp: 15, priority: 0 },
  MOVE_SHADOW_PUNCH: { id: "MOVE_SHADOW_PUNCH", constant: "MOVE_SHADOW_PUNCH", name: "Shadow Punch", type: "ghost", category: "physical", power: 60, accuracy: null, pp: 20, priority: 0 },
  MOVE_EXTRASENSORY: { id: "MOVE_EXTRASENSORY", constant: "MOVE_EXTRASENSORY", name: "Extrasensory", type: "psychic", category: "special", power: 80, accuracy: 100, pp: 30, priority: 0 },
  MOVE_SKY_UPPERCUT: { id: "MOVE_SKY_UPPERCUT", constant: "MOVE_SKY_UPPERCUT", name: "Sky Uppercut", type: "fighting", category: "physical", power: 85, accuracy: 90, pp: 15, priority: 0 },
  MOVE_SAND_TOMB: { id: "MOVE_SAND_TOMB", constant: "MOVE_SAND_TOMB", name: "Sand Tomb", type: "ground", category: "physical", power: 15, accuracy: 70, pp: 15, priority: 0 },
  MOVE_SHEER_COLD: { id: "MOVE_SHEER_COLD", constant: "MOVE_SHEER_COLD", name: "Sheer Cold", type: "ice", category: "special", power: 1, accuracy: 30, pp: 5, priority: 0 },
  MOVE_MUDDY_WATER: { id: "MOVE_MUDDY_WATER", constant: "MOVE_MUDDY_WATER", name: "Muddy Water", type: "water", category: "special", power: 95, accuracy: 85, pp: 10, priority: 0 },
  MOVE_BULLET_SEED: { id: "MOVE_BULLET_SEED", constant: "MOVE_BULLET_SEED", name: "Bullet Seed", type: "grass", category: "special", power: 10, accuracy: 100, pp: 30, priority: 0 },
  MOVE_AERIAL_ACE: { id: "MOVE_AERIAL_ACE", constant: "MOVE_AERIAL_ACE", name: "Aerial Ace", type: "flying", category: "physical", power: 60, accuracy: null, pp: 20, priority: 0 },
  MOVE_ICICLE_SPEAR: { id: "MOVE_ICICLE_SPEAR", constant: "MOVE_ICICLE_SPEAR", name: "Icicle Spear", type: "ice", category: "special", power: 10, accuracy: 100, pp: 30, priority: 0 },
  MOVE_IRON_DEFENSE: { id: "MOVE_IRON_DEFENSE", constant: "MOVE_IRON_DEFENSE", name: "Iron Defense", type: "steel", category: "status", power: null, accuracy: null, pp: 15, priority: 0 },
  MOVE_BLOCK: { id: "MOVE_BLOCK", constant: "MOVE_BLOCK", name: "Block", type: "normal", category: "status", power: null, accuracy: 100, pp: 5, priority: 0 },
  MOVE_HOWL: { id: "MOVE_HOWL", constant: "MOVE_HOWL", name: "Howl", type: "normal", category: "status", power: null, accuracy: null, pp: 40, priority: 0 },
  MOVE_DRAGON_CLAW: { id: "MOVE_DRAGON_CLAW", constant: "MOVE_DRAGON_CLAW", name: "Dragon Claw", type: "dragon", category: "special", power: 80, accuracy: 100, pp: 15, priority: 0 },
  MOVE_FRENZY_PLANT: { id: "MOVE_FRENZY_PLANT", constant: "MOVE_FRENZY_PLANT", name: "Frenzy Plant", type: "grass", category: "special", power: 150, accuracy: 90, pp: 5, priority: 0 },
  MOVE_BULK_UP: { id: "MOVE_BULK_UP", constant: "MOVE_BULK_UP", name: "Bulk Up", type: "fighting", category: "status", power: null, accuracy: null, pp: 20, priority: 0 },
  MOVE_BOUNCE: { id: "MOVE_BOUNCE", constant: "MOVE_BOUNCE", name: "Bounce", type: "flying", category: "physical", power: 85, accuracy: 85, pp: 5, priority: 0 },
  MOVE_MUD_SHOT: { id: "MOVE_MUD_SHOT", constant: "MOVE_MUD_SHOT", name: "Mud Shot", type: "ground", category: "physical", power: 55, accuracy: 95, pp: 15, priority: 0 },
  MOVE_POISON_TAIL: { id: "MOVE_POISON_TAIL", constant: "MOVE_POISON_TAIL", name: "Poison Tail", type: "poison", category: "physical", power: 50, accuracy: 100, pp: 25, priority: 0 },
  MOVE_COVET: { id: "MOVE_COVET", constant: "MOVE_COVET", name: "Covet", type: "normal", category: "physical", power: 40, accuracy: 100, pp: 40, priority: 0 },
  MOVE_VOLT_TACKLE: { id: "MOVE_VOLT_TACKLE", constant: "MOVE_VOLT_TACKLE", name: "Volt Tackle", type: "electric", category: "special", power: 120, accuracy: 100, pp: 15, priority: 0 },
  MOVE_MAGICAL_LEAF: { id: "MOVE_MAGICAL_LEAF", constant: "MOVE_MAGICAL_LEAF", name: "Magical Leaf", type: "grass", category: "special", power: 60, accuracy: null, pp: 20, priority: 0 },
  MOVE_WATER_SPORT: { id: "MOVE_WATER_SPORT", constant: "MOVE_WATER_SPORT", name: "Water Sport", type: "water", category: "status", power: null, accuracy: 100, pp: 15, priority: 0 },
  MOVE_CALM_MIND: { id: "MOVE_CALM_MIND", constant: "MOVE_CALM_MIND", name: "Calm Mind", type: "psychic", category: "status", power: null, accuracy: null, pp: 20, priority: 0 },
  MOVE_LEAF_BLADE: { id: "MOVE_LEAF_BLADE", constant: "MOVE_LEAF_BLADE", name: "Leaf Blade", type: "grass", category: "special", power: 70, accuracy: 100, pp: 15, priority: 0 },
  MOVE_DRAGON_DANCE: { id: "MOVE_DRAGON_DANCE", constant: "MOVE_DRAGON_DANCE", name: "Dragon Dance", type: "dragon", category: "status", power: null, accuracy: null, pp: 20, priority: 0 },
  MOVE_ROCK_BLAST: { id: "MOVE_ROCK_BLAST", constant: "MOVE_ROCK_BLAST", name: "Rock Blast", type: "rock", category: "physical", power: 25, accuracy: 80, pp: 10, priority: 0 },
  MOVE_SHOCK_WAVE: { id: "MOVE_SHOCK_WAVE", constant: "MOVE_SHOCK_WAVE", name: "Shock Wave", type: "electric", category: "special", power: 60, accuracy: null, pp: 20, priority: 0 },
  MOVE_WATER_PULSE: { id: "MOVE_WATER_PULSE", constant: "MOVE_WATER_PULSE", name: "Water Pulse", type: "water", category: "special", power: 60, accuracy: 100, pp: 20, priority: 0 },
  MOVE_DOOM_DESIRE: { id: "MOVE_DOOM_DESIRE", constant: "MOVE_DOOM_DESIRE", name: "Doom Desire", type: "steel", category: "physical", power: 120, accuracy: 85, pp: 5, priority: 0 },
  MOVE_PSYCHO_BOOST: { id: "MOVE_PSYCHO_BOOST", constant: "MOVE_PSYCHO_BOOST", name: "Psycho Boost", type: "psychic", category: "special", power: 140, accuracy: 90, pp: 5, priority: 0 },
} as const satisfies Record<string, MoveDefinition>;

export type VanillaMoveId = keyof typeof MOVES;

export const SIGNATURE_MOVES = {
  VIRA_LATA_CELESTE: { id: "VIRA_LATA_CELESTE", namePt: "Vira-Lata Celeste", nameEn: "Celestial Stray", type: "fire", category: "physical", power: 90, accuracy: 100, pp: 10, priority: 0, effect: "30% de chance de causar queimadura.", ownerIds: [3], rationale: "Draguará converte lealdade em impacto dracônico sem ultrapassar o poder de um STAB final.", balanceNote: "Draguará converte lealdade em impacto dracônico sem ultrapassar o poder de um STAB final.", suggestedLevel: 46 },
  RAJADA_DO_BANHADO: { id: "RAJADA_DO_BANHADO", namePt: "Rajada do Banhado", nameEn: "Wetland Burst", type: "water", category: "special", power: 90, accuracy: 95, pp: 10, priority: 0, effect: "30% de chance de reduzir a Velocidade do alvo em 1 estágio.", ownerIds: [6], rationale: "Premia a Velocidade e o Ataque Especial de Terolibra com precisão moderada.", balanceNote: "Premia a Velocidade e o Ataque Especial de Terolibra com precisão moderada.", suggestedLevel: 46 },
  MARTELO_DE_GRANITO: { id: "MARTELO_DE_GRANITO", namePt: "Martelo de Granito", nameEn: "Granite Hammer", type: "rock", category: "physical", power: 95, accuracy: 90, pp: 10, priority: 0, effect: "30% de chance de reduzir a Defesa do alvo em 1 estágio.", ownerIds: [9], rationale: "Finalizador físico forte de Petropico, limitado por precisão.", balanceNote: "Finalizador físico forte de Petropico, limitado por precisão.", suggestedLevel: 46 },
  FOGO_FATUO_ANCESTRAL: { id: "FOGO_FATUO_ANCESTRAL", namePt: "Fogo-Fátuo Ancestral", nameEn: "Ancestral Wispfire", type: "fire", category: "special", power: 85, accuracy: 100, pp: 10, priority: 0, effect: "30% de chance de causar queimadura.", ownerIds: [16], rationale: "Identidade folclórica de Boitatá sem competir com ataques lendários.", balanceNote: "Identidade folclórica de Boitatá sem competir com ataques lendários.", suggestedLevel: 45 },
  PASSO_AO_CONTRARIO: { id: "PASSO_AO_CONTRARIO", namePt: "Passo ao Contrário", nameEn: "Backward Step", type: "grass", category: "physical", power: 80, accuracy: 100, pp: 15, priority: 1, effect: "Prioridade +1; falha se usado em turnos consecutivos.", ownerIds: [18], rationale: "Expressa os pés invertidos de Curupira; trava consecutiva contém a prioridade.", balanceNote: "Expressa os pés invertidos de Curupira; trava consecutiva contém a prioridade.", suggestedLevel: 44 },
  CANTO_DA_IARA: { id: "CANTO_DA_IARA", namePt: "Canto da Iara", nameEn: "Iara Song", type: "water", category: "special", power: 75, accuracy: 100, pp: 10, priority: 0, effect: "Causa confusão no alvo.", ownerIds: [19], rationale: "Controle confiável com poder reduzido para Iaraço.", balanceNote: "Controle confiável com poder reduzido para Iaraço.", suggestedLevel: 42 },
  REDEMOINHO_DO_SACI: { id: "REDEMOINHO_DO_SACI", namePt: "Redemoinho do Saci", nameEn: "Saci Whirlwind", type: "flying", category: "special", power: 80, accuracy: 95, pp: 10, priority: 1, effect: "Prioridade +1; reduz a própria Defesa em 1 estágio.", ownerIds: [20], rationale: "Ataque veloz temático com drawback claro.", balanceNote: "Ataque veloz temático com drawback claro.", suggestedLevel: 43 },
  ENCANTO_DO_BOTO: { id: "ENCANTO_DO_BOTO", namePt: "Encanto do Boto", nameEn: "River Enchantment", type: "psychic", category: "special", power: 85, accuracy: 100, pp: 10, priority: 0, effect: "30% de chance de causar confusão.", ownerIds: [27], rationale: "Assinatura cultural de Botogaláu com efeito padrão de confusão.", balanceNote: "Assinatura cultural de Botogaláu com efeito padrão de confusão.", suggestedLevel: 45 },
  ABRACO_DA_BOIUNA: { id: "ABRACO_DA_BOIUNA", namePt: "Abraço da Boiúna", nameEn: "Boiuna Embrace", type: "dragon", category: "physical", power: 95, accuracy: 90, pp: 10, priority: 0, effect: "Prende o alvo por 2–5 turnos.", ownerIds: [48], rationale: "Força de pseudo-lendário com precisão reduzida e trapping existente.", balanceNote: "Força de pseudo-lendário com precisão reduzida e trapping existente.", suggestedLevel: 55 },
  GALOPE_SEM_CABECA: { id: "GALOPE_SEM_CABECA", namePt: "Galope sem Cabeça", nameEn: "Headless Gallop", type: "fire", category: "physical", power: 90, accuracy: 100, pp: 10, priority: 0, effect: "Causa 1/4 do dano como recoil e tem 20% de causar queimadura.", ownerIds: [99], rationale: "Dano e risco combinam com a maldição da Mula-sem-Cabeça.", balanceNote: "Dano e risco combinam com a maldição da Mula-sem-Cabeça.", suggestedLevel: 48 },
  MARE_DA_MAE: { id: "MARE_DA_MAE", namePt: "Maré da Mãe", nameEn: "Mother Tide", type: "water", category: "special", power: 90, accuracy: 100, pp: 10, priority: 0, effect: "Cura o usuário em 25% do dano causado.", ownerIds: [108], rationale: "Sustentação moderada para Iemanjá sem usar cura total.", balanceNote: "Sustentação moderada para Iemanjá sem usar cura total.", suggestedLevel: 50 },
  FORJA_DE_OGUM: { id: "FORJA_DE_OGUM", namePt: "Forja de Ogum", nameEn: "Ogun Forge", type: "steel", category: "physical", power: 90, accuracy: 100, pp: 10, priority: 0, effect: "Aumenta a Defesa do usuário em 1 estágio após causar dano.", ownerIds: [110], rationale: "Reforça a fantasia de forja e o perfil físico de Ogum.", balanceNote: "Reforça a fantasia de forja e o perfil físico de Ogum.", suggestedLevel: 50 },
  OLHAR_DA_COBRA_GRANDE: { id: "OLHAR_DA_COBRA_GRANDE", namePt: "Olhar da Cobra-Grande", nameEn: "Great Serpent Gaze", type: "ghost", category: "status", power: null, accuracy: 90, pp: 10, priority: 0, effect: "Paralisa o alvo e impede troca por 2–5 turnos.", ownerIds: [291], rationale: "Controle temático sem dano para a entidade Cobra-Grande.", balanceNote: "Controle temático sem dano para a entidade Cobra-Grande.", suggestedLevel: 48 },
  AURORA_DE_GUARACI: { id: "AURORA_DE_GUARACI", namePt: "Aurora de Guaraci", nameEn: "Guaraci Dawn", type: "fire", category: "special", power: 100, accuracy: 90, pp: 5, priority: 0, effect: "Invoca sol forte por 5 turnos após causar dano.", ownerIds: [329], rationale: "Poder lendário equilibrado por precisão e PP baixos.", balanceNote: "Poder lendário equilibrado por precisão e PP baixos.", suggestedLevel: 60 },
  LUAR_DE_JACI: { id: "LUAR_DE_JACI", namePt: "Luar de Jaci", nameEn: "Jaci Moonlight", type: "fairy", category: "special", power: 100, accuracy: 90, pp: 5, priority: 0, effect: "30% de chance de reduzir o Ataque Especial do alvo em 1 estágio.", ownerIds: [330], rationale: "Primeiro STAB Fairy realmente novo de Jaciana, com PP e precisão contidos.", balanceNote: "Primeiro STAB Fairy realmente novo de Jaciana, com PP e precisão contidos.", suggestedLevel: 60 },
  TROVAO_DE_TUPA: { id: "TROVAO_DE_TUPA", namePt: "Trovão de Tupã", nameEn: "Tupa Thunder", type: "electric", category: "special", power: 105, accuracy: 85, pp: 5, priority: 0, effect: "30% de chance de paralisar o alvo.", ownerIds: [331], rationale: "Golpe lendário arriscado, implementável como Thunder ajustado.", balanceNote: "Golpe lendário arriscado, implementável como Thunder ajustado.", suggestedLevel: 62 },
  CORRENTEZA_SUPREMA: { id: "CORRENTEZA_SUPREMA", namePt: "Correnteza Suprema", nameEn: "Supreme Current", type: "water", category: "special", power: 100, accuracy: 95, pp: 5, priority: 0, effect: "Reduz a Velocidade do alvo em 1 estágio.", ownerIds: [332], rationale: "Controle de rio para Iaraú com PP lendário limitado.", balanceNote: "Controle de rio para Iaraú com PP lendário limitado.", suggestedLevel: 60 },
  JURAMENTO_DE_ARAUANA: { id: "JURAMENTO_DE_ARAUANA", namePt: "Juramento de Arauana", nameEn: "Arauana Oath", type: "fairy", category: "special", power: 105, accuracy: 90, pp: 5, priority: 0, effect: "Aumenta a Defesa Especial do usuário em 1 estágio após causar dano.", ownerIds: [337, 348], rationale: "Golpe titular do guardião regional, potente mas não sem risco.", balanceNote: "Golpe titular do guardião regional, potente mas não sem risco.", suggestedLevel: 65 },
  INCENDIO_PRIMORDIAL: { id: "INCENDIO_PRIMORDIAL", namePt: "Incêndio Primordial", nameEn: "Primordial Blaze", type: "fire", category: "special", power: 110, accuracy: 85, pp: 5, priority: 0, effect: "Causa 1/4 do dano como recoil e tem 30% de causar queimadura.", ownerIds: [343], rationale: "Fogaréu recebe alto teto de dano com precisão e recoil.", balanceNote: "Fogaréu recebe alto teto de dano com precisão e recoil.", suggestedLevel: 65 },
  MARULHO_ATLANTICO: { id: "MARULHO_ATLANTICO", namePt: "Marulho Atlântico", nameEn: "Atlantic Surge", type: "water", category: "physical", power: 105, accuracy: 90, pp: 5, priority: 0, effect: "30% de chance de causar flinch.", ownerIds: [344], rationale: "Aproveita o Ataque de Marulho com chance de flinch e PP baixo.", balanceNote: "Aproveita o Ataque de Marulho com chance de flinch e PP baixo.", suggestedLevel: 65 },
  ECLIPSE_DIVINO: { id: "ECLIPSE_DIVINO", namePt: "Eclipse Divino", nameEn: "Divine Eclipse", type: "fairy", category: "special", power: 110, accuracy: 85, pp: 5, priority: 0, effect: "Reduz o Ataque Especial do usuário em 1 estágio.", ownerIds: [348], rationale: "Arauanamon tem poder de ápice com drawback equivalente a Overheat.", balanceNote: "Arauanamon tem poder de ápice com drawback equivalente a Overheat.", suggestedLevel: 68 },
  ESSENCIA_PRIMORDIAL: { id: "ESSENCIA_PRIMORDIAL", namePt: "Essência Primordial", nameEn: "Primordial Essence", type: "dragon", category: "special", power: 110, accuracy: 90, pp: 5, priority: 0, effect: "Reduz Ataque e Ataque Especial do usuário em 1 estágio.", ownerIds: [386], rationale: "Arauá ganha um finalizador mítico forte, mas não repetível sem custo.", balanceNote: "Arauá ganha um finalizador mítico forte, mas não repetível sem custo.", suggestedLevel: 70 },
} as const satisfies Record<string, SignatureMoveDefinition>;

export type SignatureMoveId = keyof typeof SIGNATURE_MOVES;
export type MoveId = VanillaMoveId | SignatureMoveId;
export const ALL_MOVES: Record<string, MoveDefinition | SignatureMoveDefinition> = { ...MOVES, ...SIGNATURE_MOVES };
export function moveDisplayName(move: MoveDefinition | SignatureMoveDefinition): string { return "namePt" in move ? move.namePt : move.name; }