PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "ELIAS: Some guilt does not go away when\n"
	.string "we keep quiet. I signed off on part of\l"
	.string "the M'BOI project, then spent years\l"
	.string "calling my fear prudence.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "ELIAS: Being your father never gave me\n"
	.string "the right to choose which truth you\l"
	.string "could bear. It took me far too long to\l"
	.string "understand that.$"

