PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "ELIAS: Algumas culpas nao\ndesaparecem quando ficamos em\p"
	.string "silencio. Eu aprovei parte do\nprojeto de M'BOI. Passei anos\p"
	.string "chamando meu medo de prudencia.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "ELIAS: Algumas culpas nao\ndesaparecem quando ficamos em\p"
	.string "silencio. Eu aprovei parte do\nprojeto de M'BOI. Passei anos\p"
	.string "chamando meu medo de prudencia.$"

