AquaHideout_1F_MapScripts::
	.byte 0

@ The below two entrance guards give hints about what to do to progress the story
AquaHideout_1F_EventScript_HideoutEntranceGrunt1::
	lock
	faceplayer
	goto_if_set FLAG_GROUDON_AWAKENED_MAGMA_HIDEOUT, AquaHideout_1F_EventScript_SlateportHint1
	goto_if_set FLAG_RECEIVED_RED_OR_BLUE_ORB, AquaHideout_1F_EventScript_MagmaHideoutHint1
	msgbox AquaHideout_1F_Text_OurBossIsSnatchingSomething, MSGBOX_DEFAULT
	release
	end

AquaHideout_1F_EventScript_MagmaHideoutHint1::
	msgbox AquaHideout_1F_Text_WhereMightMagmaHideoutBe, MSGBOX_DEFAULT
	release
	end

AquaHideout_1F_EventScript_SlateportHint1::
	msgbox AquaHideout_1F_Text_BossWentToJackASubmarine, MSGBOX_DEFAULT
	release
	end

AquaHideout_1F_EventScript_HideoutEntranceGrunt2::
	lock
	faceplayer
	goto_if_set FLAG_GROUDON_AWAKENED_MAGMA_HIDEOUT, AquaHideout_1F_EventScript_SlateportHint2
	goto_if_set FLAG_RECEIVED_RED_OR_BLUE_ORB, AquaHideout_1F_EventScript_MagmaHideoutHint2
	msgbox AquaHideout_1F_Text_BossIsOnRoute122, MSGBOX_DEFAULT
	release
	end

AquaHideout_1F_EventScript_MagmaHideoutHint2::
	msgbox AquaHideout_1F_Text_TeamMagmaAtMtChimney, MSGBOX_DEFAULT
	release
	end

AquaHideout_1F_EventScript_SlateportHint2::
	msgbox AquaHideout_1F_Text_BossIsInSlateportCity, MSGBOX_DEFAULT
	release
	end

AquaHideout_1F_EventScript_Grunt1::
	trainerbattle_single TRAINER_GRUNT_AQUA_HIDEOUT_1, AquaHideout_1F_Text_Grunt1Intro, AquaHideout_1F_Text_Grunt1Defeat, AquaHideout_1F_EventScript_Grunt1Defeated
	msgbox AquaHideout_1F_Text_Grunt1PostBattle, MSGBOX_AUTOCLOSE
	end

AquaHideout_1F_EventScript_Grunt1Defeated::
	msgbox AquaHideout_1F_Text_Grunt1PostBattle, MSGBOX_DEFAULT
	release
	end

AquaHideout_1F_Text_OurBossIsSnatchingSomething:
	.string "HORIZONTE: O Arquivo preserva o\nque o tempo destruiria. Um dia\p"
	.string "voces vao agradecer por nao\nprecisarem mais sofrer para\p"
	.string "lembrar.$"

AquaHideout_1F_Text_WhereMightMagmaHideoutBe:
	.string "HORIZONTE: O Arquivo preserva o\nque o tempo destruiria. Um dia\p"
	.string "voces vao agradecer por nao\nprecisarem mais sofrer para\p"
	.string "lembrar.$"

AquaHideout_1F_Text_BossWentToJackASubmarine:
	.string "HORIZONTE: O Arquivo preserva o\nque o tempo destruiria. Um dia\p"
	.string "voces vao agradecer por nao\nprecisarem mais sofrer para\p"
	.string "lembrar.$"

AquaHideout_1F_Text_BossIsOnRoute122:
	.string "HORIZONTE: O Arquivo preserva o\nque o tempo destruiria. Um dia\p"
	.string "voces vao agradecer por nao\nprecisarem mais sofrer para\p"
	.string "lembrar.$"

AquaHideout_1F_Text_TeamMagmaAtMtChimney:
	.string "HORIZONTE: O Arquivo preserva o\nque o tempo destruiria. Um dia\p"
	.string "voces vao agradecer por nao\nprecisarem mais sofrer para\p"
	.string "lembrar.$"

AquaHideout_1F_Text_BossIsInSlateportCity:
	.string "HORIZONTE: O Arquivo preserva o\nque o tempo destruiria. Um dia\p"
	.string "voces vao agradecer por nao\nprecisarem mais sofrer para\p"
	.string "lembrar.$"

AquaHideout_1F_Text_Grunt1Intro:
	.string "HORIZONTE: O Arquivo preserva o\nque o tempo destruiria. Um dia\p"
	.string "voces vao agradecer por nao\nprecisarem mais sofrer para\p"
	.string "lembrar.$"

AquaHideout_1F_Text_Grunt1Defeat:
	.string "HORIZONTE: O Arquivo preserva o\nque o tempo destruiria. Um dia\p"
	.string "voces vao agradecer por nao\nprecisarem mais sofrer para\p"
	.string "lembrar.$"

AquaHideout_1F_Text_Grunt1PostBattle:
	.string "HORIZONTE: O Arquivo preserva o\nque o tempo destruiria. Um dia\p"
	.string "voces vao agradecer por nao\nprecisarem mais sofrer para\p"
	.string "lembrar.$"

