SeafloorCavern_Room4_MapScripts::
	.byte 0

SeafloorCavern_Room4_EventScript_Grunt3::
	trainerbattle_single TRAINER_GRUNT_SEAFLOOR_CAVERN_3, SeafloorCavern_Room4_Text_Grunt3Intro, SeafloorCavern_Room4_Text_Grunt3Defeat
	msgbox SeafloorCavern_Room4_Text_Grunt3PostBattle, MSGBOX_AUTOCLOSE
	end

SeafloorCavern_Room4_EventScript_Grunt4::
	trainerbattle_single TRAINER_GRUNT_SEAFLOOR_CAVERN_4, SeafloorCavern_Room4_Text_Grunt4Intro, SeafloorCavern_Room4_Text_Grunt4Defeat
	msgbox SeafloorCavern_Room4_Text_Grunt4PostBattle, MSGBOX_AUTOCLOSE
	end

SeafloorCavern_Room4_Text_Grunt3Intro:
	.string "Otacilio volta ao lugar onde\nperdeu a familia. Luzia chega\p"
	.string "para libertar tudo que foi\narmazenado. Os dois extremos\p"
	.string "colidem.$"

SeafloorCavern_Room4_Text_Grunt3Defeat:
	.string "Otacilio volta ao lugar onde\nperdeu a familia. Luzia chega\p"
	.string "para libertar tudo que foi\narmazenado. Os dois extremos\p"
	.string "colidem.$"

SeafloorCavern_Room4_Text_Grunt3PostBattle:
	.string "Otacilio volta ao lugar onde\nperdeu a familia. Luzia chega\p"
	.string "para libertar tudo que foi\narmazenado. Os dois extremos\p"
	.string "colidem.$"

SeafloorCavern_Room4_Text_Grunt4Intro:
	.string "Otacilio volta ao lugar onde\nperdeu a familia. Luzia chega\p"
	.string "para libertar tudo que foi\narmazenado. Os dois extremos\p"
	.string "colidem.$"

SeafloorCavern_Room4_Text_Grunt4Defeat:
	.string "Otacilio volta ao lugar onde\nperdeu a familia. Luzia chega\p"
	.string "para libertar tudo que foi\narmazenado. Os dois extremos\p"
	.string "colidem.$"

SeafloorCavern_Room4_Text_Grunt4PostBattle:
	.string "Otacilio volta ao lugar onde\nperdeu a familia. Luzia chega\p"
	.string "para libertar tudo que foi\narmazenado. Os dois extremos\p"
	.string "colidem.$"

