gText_Birch_Welcome::
	.string "Olá. Obrigado por esperar!\p"
	.string "Este é o mundo dos POKéMON.\p"
	.string "Estudo os antigos Juramentos\n"
	.string "de ARAUNA.\p"
	.string "Pode me chamar apenas de\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Isto é um POKéMON.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Em ARAUNA, pessoas e POKéMON\n"
	.string "vivem lado a lado.\p"
	.string "Erguemos cidades e cruzamos\n"
	.string "matas juntos.\p"
	.string "Enfrentamos perigos lado a lado.\p"
	.string "Mas esta terra guarda uma ferida\n"
	.string "que muitos preferem esquecer.\p"
	.string "Na NOITE SEM ESTRELAS, antigos\n"
	.string "Juramentos foram rompidos.\p"
	.string "Desde aquele dia, busco saber\n"
	.string "o que ocorreu.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "E você é?$"

gText_Birch_BoyOrGirl::
	.string "Você é um garoto?\n"
	.string "Ou uma garota?$"

gText_Birch_WhatsYourName::
	.string "Certo.\n"
	.string "Qual é seu nome?$"

gText_Birch_SoItsPlayer::
	.string "Seu nome é {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Entendi.\p"
	.string "Você é {PLAYER}.\p"
	.string "Acaba de chegar a ARAUNA.\l"
	.string "Agora faz sentido.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Tudo pronto?\p"
	.string "Sua aventura vai começar.\p"
	.string "Tenha coragem, mas escute o que\n"
	.string "ARAUNA tenta lhe dizer.\p"
	.string "Nem todo segredo deseja ser\n"
	.string "revelado.\p"
	.string "Espero você no laboratório.\n"
	.string "Ainda temos muito a descobrir.\p"
	.string "$"
