// Generated by tools/arauna/build_species.py from the approved Arauna dex.
// Edit the CSVs under docs/arauna/ and rerun rather than editing this file.

const u8 gDummyPokedexText[] = _(
    "This is a newly discovered POKéMON.\n"
    "It is currently under investigation.\n"
    "No detailed information is available\n"
    "at this time.");

const u8 gCaramelo001PokedexText[] = _(
    "Filhote de rua de pelagem cor de caramelo.\n"
    "Quando confia em seu treinador, a ponta do\n"
    "rabo acende uma chama pequena e constante\n"
    "que nunca queima quem o acaricia.");

const u8 gCaramelao002PokedexText[] = _(
    "Guardiao das feiras livres. Suas costas\n"
    "ficam salpicadas de brasas que ele controla\n"
    "como se fossem pulgas - só mordem quem tenta\n"
    "roubar.");

const u8 gDraguara003PokedexText[] = _(
    "Lendas contam que todo cachorro caramelo que\n"
    "salvou uma vida renasce como um Draguará.\n"
    "Suas chamas turquesa aquecem, mas nunca\n"
    "ferem inocentes.");

const u8 gQuero004PokedexText[] = _(
    "Nunca dorme por completo. Um olho fica\n"
    "aberto vigiando o ninho - se algo se\n"
    "aproxima, dispara o grito quero-quero! que\n"
    "ecoa por quilômetros.");

const u8 gQueribela005PokedexText[] = _(
    "Após a primeira muda, suas penas se\n"
    "transformam em membranas iridescentes de\n"
    "libélula. Paira sobre a água caçando com\n"
    "precisao cirúrgica.");

const u8 gTerolibra006PokedexText[] = _(
    "Quatro asas de libélula sustentam um corpo\n"
    "esguio de quero-quero adulto. Um único bater\n"
    "de asas cria uma rajada dágua capaz de\n"
    "partir troncos.");

const u8 gPimpau007PokedexText[] = _(
    "Fura cascas de árvore atrás de larvas com um\n"
    "bico ainda mole. Treina o dia inteiro\n"
    "batendo em tocos secos, e volta pro ninho\n"
    "com dor de cabeça.");

const u8 gBicopau008PokedexText[] = _(
    "O bico endurece até virar madeira-de-lei.\n"
    "Percute os troncos em ritmos complexos que\n"
    "outros Bicopau reconhecem como mensagens.");

const u8 gPetropico009PokedexText[] = _(
    "Seu bico se calcificou em uma cunha de\n"
    "granito. Escava cavernas em paredoes de\n"
    "pedra com pancadas que ecoam como sinos.");

const u8 gFormilim010PokedexText[] = _(
    "Nao é uma formiga - é uma colônia inteira\n"
    "andando em formato de formiga gigante. Se\n"
    "dispersa quando ameaçada.");

const u8 gSauvarco011PokedexText[] = _(
    "A rainha das saúvas. Comanda exércitos que\n"
    "desfolham árvores inteiras em uma única\n"
    "noite.");

const u8 gCapivim012PokedexText[] = _(
    "Vive em bandos beira-rio. Aceita qualquer\n"
    "outro Pokémon em suas costas - inclusive\n"
    "treinadores cansados.");

const u8 gTucanhao013PokedexText[] = _(
    "Seu bico gigante é oco e leve. Consegue\n"
    "engolir uma fruta inteira e cuspir a semente\n"
    "a 40 metros de distância - planta florestas\n"
    "sozinho.");

const u8 gSaguim014PokedexText[] = _(
    "Rouba tudo que brilha. Treinadores aprendem\n"
    "cedo a guardar as medalhas de ginásio no\n"
    "fundo da mochila.");

const u8 gMicuiras015PokedexText[] = _(
    "Ancian da tribo dos Sagüim. Enxerga o futuro\n"
    "em reflexos de rios e prevê chuvas com uma\n"
    "semana de antecedência.");

const u8 gBoitata016PokedexText[] = _(
    "Aparece após queimadas. Seu corpo é uma\n"
    "cobra feita de fogo azul que devora quem\n"
    "provoca incêndios florestais.");

const u8 gCurupim017PokedexText[] = _(
    "Seus pés apontam para trás. Confunde\n"
    "caçadores fazendo pegadas que levam pra\n"
    "dentro da mata em vez de pra fora.");

const u8 gCurupira018PokedexText[] = _(
    "O verdadeiro senhor da mata. Onde ele pisa,\n"
    "uma árvore centenária brota em uma noite.");

const u8 gIaraco019PokedexText[] = _(
    "Encanta pescadores com um canto. Quem cai no\n"
    "rio atrás dela vira parte de sua corte para\n"
    "sempre.");

const u8 gSacizinho020PokedexText[] = _(
    "Só tem uma perna. Se movimenta em\n"
    "redemoinhos e adora atrapalhar treinadores\n"
    "desatentos - apagando fogueiras ou soltando\n"
    "Pokémon capturados.");

const u8 gCactula021PokedexText[] = _(
    "Sobrevive meses sem chuva. Seus espinhos\n"
    "guardam gotas de veneno adocicado que atrai\n"
    "Pokémon-inseto.");

const u8 gMuricoco022PokedexText[] = _(
    "Enxames inteiros perseguem treinadores por\n"
    "dias. O único jeito de fugir é entrar num\n"
    "rio - e torcer para nao ter Terolibra por\n"
    "perto.");

const u8 gOncaleu023PokedexText[] = _(
    "A onça-pintada da regiao. Caça em silêncio\n"
    "absoluto - treinadores só percebem quando o\n"
    "Pokémon já está no chao.");

const u8 gTamandua024PokedexText[] = _(
    "Suas garras cortam aço. Come Formilim\n"
    "inteiros de uma lambida - mas evita\n"
    "Saúvarco: já perdeu a língua uma vez.");

const u8 gBotim025PokedexText[] = _(
    "Nasce cinza e vai ficando rosa conforme\n"
    "ganha confiança. Brinca com bolhas que ele\n"
    "mesmo sopra.");

const u8 gBotao026PokedexText[] = _(
    "Sai à noite em bandos. Diz o folclore que se\n"
    "transforma em rapaz nas festas de beira-rio.");

const u8 gBotogalau027PokedexText[] = _(
    "Chapéu branco esconde o buraco do topo da\n"
    "cabeça. Encanta moças e some no rio ao\n"
    "amanhecer.");

const u8 gTatuim028PokedexText[] = _(
    "Se enrola numa bola do tamanho de uma\n"
    "laranja. Rola morro abaixo pra fugir.");

const u8 gTatubola029PokedexText[] = _(
    "A carapaça vira aço quando ameaçado.\n"
    "Ricocheteia ataques físicos de volta.");

const u8 gTatucu030PokedexText[] = _(
    "Escava túneis de 20 metros por noite.\n"
    "Aldeias inteiras já sumiram sob suas\n"
    "galerias.");

const u8 gArarinha031PokedexText[] = _(
    "Imita qualquer som que ouve - inclusive\n"
    "gritos de treinadores caindo do barranco.");

const u8 gArara032PokedexText[] = _(
    "Penas vermelhas soltam faíscas quando bate\n"
    "as asas com força.");

const u8 gAraracanga033PokedexText[] = _(
    "Voa entre as nuvens do cerrado. Suas penas\n"
    "caídas incendeiam a grama seca.");

const u8 gJacarim034PokedexText[] = _(
    "Fica boiando com só os olhos de fora.\n"
    "Confunde treinadores com um tronco\n"
    "flutuante.");

const u8 gJacarao035PokedexText[] = _(
    "Espera horas imóvel. Quando ataca, arrasta a\n"
    "presa pro fundo em uma pirueta.");

const u8 gJacarodon036PokedexText[] = _(
    "Descendente direto dos dinossauros. Suas\n"
    "mandíbulas quebram cascos de Tatuçu.");

const u8 gPreguicim037PokedexText[] = _(
    "Se move tao devagar que musgo cresce em seu\n"
    "pelo. Serve de casa pra insetos.");

const u8 gPreguicao038PokedexText[] = _(
    "Passa 20 horas por dia dormindo. Nos sonhos,\n"
    "prevê chuvas com semanas de antecedência.");

const u8 gBichoPreguica039PokedexText[] = _(
    "Do tamanho de um elefante. Anda uma vez por\n"
    "lua e sabe onde toda árvore centenária\n"
    "brota.");

const u8 gPapaguim040PokedexText[] = _(
    "Aprende a repetir palavras em três dias.\n"
    "Aprende palavroes em uma tarde.");

const u8 gPapagaio041PokedexText[] = _(
    "Memoriza conversas inteiras e as repete pra\n"
    "pessoas erradas. Causa muita confusao.");

const u8 gPapagaiao042PokedexText[] = _(
    "Vive 200 anos. Guarda segredos de geraçoes\n"
    "de treinadores em sua memória.");

const u8 gAntinha043PokedexText[] = _(
    "Listrada como um javali pequeno. Sua tromba\n"
    "curta cheira frutas a 100 metros.");

const u8 gAnta044PokedexText[] = _(
    "Atravessa rios inteiros submersa. Come até\n"
    "40 quilos de folhas por dia.");

const u8 gAntarau045PokedexText[] = _(
    "Espírito da mata. Guia treinadores perdidos\n"
    "até a borda da floresta.");

const u8 gSucurim046PokedexText[] = _(
    "Já nasce com 2 metros. Se enrola em galhos\n"
    "esperando presas.");

const u8 gSucuri047PokedexText[] = _(
    "Sufoca a presa e engole inteira. Se torna\n"
    "Boiúna após anos absorvendo lendas do rio.");

const u8 gBoiuna048PokedexText[] = _(
    "Cobra-Grande da mitologia amazônica. Olhos\n"
    "brilham como faróis de barco em noite de\n"
    "igarapé. Diz a lenda que sua passagem forma\n"
    "novos rios.");

const u8 gBorbolim049PokedexText[] = _(
    "Come folhas de urtiga sem se envenenar.\n"
    "Guarda o veneno na pele.");

const u8 gCasulete050PokedexText[] = _(
    "Casulo iridescente que reflete o azul do\n"
    "céu. Nao se move, mas dá choque se tocado.");

const u8 gMorphalia051PokedexText[] = _(
    "Asas do tamanho de maos humanas. Suas\n"
    "escamas azuis viram poeira mágica curativa.");

const u8 gGuaracim052PokedexText[] = _(
    "Pernas desproporcionalmente longas. Corre de\n"
    "galope pelo cerrado atrás de frutas.");

const u8 gGuara053PokedexText[] = _(
    "Uiva ao entardecer. Come lobeira, uma fruta\n"
    "doce, e planta a floresta com suas fezes.");

const u8 gGuaraflama054PokedexText[] = _(
    "Aparece nas noites de lua nova. Suas patas\n"
    "deixam pegadas em brasa.");

const u8 gPeixim055PokedexText[] = _(
    "Nada devagar mamando na mae. Chora com voz\n"
    "de bebê quando se perde.");

const u8 gPeixeboi056PokedexText[] = _(
    "Herbívoro pacífico. Come até 50 quilos de\n"
    "plantas aquáticas por dia.");

const u8 gMaeDAgua057PokedexText[] = _(
    "Protetora dos rios. Diz o folclore que\n"
    "amamentou crianças perdidas.");

const u8 gMandim058PokedexText[] = _(
    "Bigodes farejam comida no lodo do fundo.\n"
    "Meio cego.");

const u8 gMandi059PokedexText[] = _(
    "Espinhos venenosos nas nadadeiras. Uma\n"
    "picada tira o sono por dias.");

const u8 gMandube060PokedexText[] = _(
    "Do tamanho de um homem. Nada no escuro\n"
    "absoluto do fundo dos rios.");

const u8 gPreguim061PokedexText[] = _(
    "Aprende a usar galhos como ferramentas ainda\n"
    "filhote. Rouba comida de acampamentos.");

const u8 gPrego062PokedexText[] = _(
    "Usa pedras pra quebrar castanhas. Ensina\n"
    "técnicas a filhotes por geraçoes.");

const u8 gPregarcanjo063PokedexText[] = _(
    "Considerado o mais inteligente dos primatas\n"
    "de Arauana. Resolve enigmas humanos.");

const u8 gAranin064PokedexText[] = _(
    "Tece teias em galhos secos. Come pequenas\n"
    "Formilim.");

const u8 gCaraninha065PokedexText[] = _(
    "Pelos urticantes causam coceira insuportável\n"
    "em contato.");

const u8 gCaranga066PokedexText[] = _(
    "Do tamanho de um prato. Presas perfuram até\n"
    "luvas de couro.");

const u8 gGatim067PokedexText[] = _(
    "Mia igual gato doméstico, mas nao deixa\n"
    "ninguém chegar perto.");

const u8 gGatoDoMato068PokedexText[] = _(
    "Caça pássaros no meio da noite. Suas pupilas\n"
    "brilham verde nas lanternas.");

const u8 gJaguatirica069PokedexText[] = _(
    "Manchas em roseta como uma onça-pintada em\n"
    "miniatura. Sobe em árvores atrás de macacos.");

const u8 gCutim070PokedexText[] = _(
    "Enterra sementes de castanha e esquece onde\n"
    "colocou. Planta a floresta sem querer.");

const u8 gCutia071PokedexText[] = _(
    "Roe qualquer coisa. Dentes crescem a vida\n"
    "inteira.");

const u8 gPaca072PokedexText[] = _(
    "Só sai de noite. Correndo assobiando pela\n"
    "mata escura.");

const u8 gFormigao073PokedexText[] = _(
    "Mordida dolorida como levar 24 horas de\n"
    "caibra. Nome popular: formiga bala.");

const u8 gMarimbondo074PokedexText[] = _(
    "Enxame agressivo. Persegue ameaças por\n"
    "quilômetros.");

const u8 gAbelhinha075PokedexText[] = _(
    "Nao tem ferrao. Faz mel doce que treinadores\n"
    "usam pra recuperar Pokémon feridos.");

const u8 gQuatim076PokedexText[] = _(
    "Bando de 15 andando pelas trilhas. Fura\n"
    "mochila atrás de biscoito.");

const u8 gQuati077PokedexText[] = _(
    "Aprende a abrir zíperes de tenda. Rouba tudo\n"
    "que brilha.");

const u8 gCoati078PokedexText[] = _(
    "Vive em cavernas escuras. Focinho\n"
    "longuíssimo pra caçar morcegos.");

const u8 gGamba079PokedexText[] = _(
    "Solta um cheiro nauseante quando ameaçado.\n"
    "Treinadores fogem antes do Pokémon.");

const u8 gCangamba080PokedexText[] = _(
    "Jato de fedor atinge 3 metros de distância.\n"
    "Dura semanas na roupa.");

const u8 gSarue081PokedexText[] = _(
    "Se finge de morto por horas quando ameaçado.\n"
    "Enganou até Onçaléu.");

const u8 gTuquinho082PokedexText[] = _(
    "Bico colorido chama fêmeas de longe. Come\n"
    "frutas silvestres.");

const u8 gAracari083PokedexText[] = _(
    "Voa em bando de 6. Todos comem da mesma\n"
    "fruta ao mesmo tempo.");

const u8 gCuricaca084PokedexText[] = _(
    "Grito estridente ao amanhecer. Toda fazenda\n"
    "de Arauana odeia esse Pokémon.");

const u8 gSapim085PokedexText[] = _(
    "Nada em cardumes. Vira Sapao quando as patas\n"
    "crescem.");

const u8 gSapao086PokedexText[] = _(
    "Glândulas atrás dos olhos soltam veneno\n"
    "branco. Nunca lamba um Sapao.");

const u8 gCururu087PokedexText[] = _(
    "Do tamanho de uma bola de futebol. Come\n"
    "Muriçoco aos milhares.");

const u8 gTeiuzim088PokedexText[] = _(
    "Corre em duas patas quando assustado. Rabo\n"
    "destaca pra despistar predadores.");

const u8 gTeiu089PokedexText[] = _(
    "Come tudo: frutas, ovos, pequenos animais.\n"
    "Come até serpentes venenosas.");

const u8 gCamaleao090PokedexText[] = _(
    "Muda de cor pra combinar com o ambiente.\n"
    "Também muda de humor de segundo em segundo.");

const u8 gMorcim091PokedexText[] = _(
    "Dorme de cabeça pra baixo agarrado no teto\n"
    "da caverna.");

const u8 gMorcego092PokedexText[] = _(
    "Enxerga com som. Voa no escuro absoluto sem\n"
    "bater em nada.");

const u8 gVampiro093PokedexText[] = _(
    "Suga sangue de mamíferos adormecidos. Deixa\n"
    "o dono anêmico se convive muito tempo.");

const u8 gPiuiuim094PokedexText[] = _(
    "Fica em uma perna só a maior parte do tempo.\n"
    "Cai se um vento forte pega.");

const u8 gTuiuiu095PokedexText[] = _(
    "Ave símbolo do Pantanal. Bico enorme pesca\n"
    "peixes com uma bicada só.");

const u8 gColhereiro096PokedexText[] = _(
    "Rosa por comer crustáceos. Bico em formato\n"
    "de colher.");

const u8 gMulinha097PokedexText[] = _(
    "Filhote inocente. Nada indica o que vai\n"
    "virar quando crescer.");

const u8 gMula098PokedexText[] = _(
    "Cavalga mais rápido que um cavalo. Zurro\n"
    "assustador.");

const u8 gMulaSemCabeca099PokedexText[] = _(
    "Solta fogo do pescoço no lugar da cabeça.\n"
    "Aparece nas sextas-feiras.");

const u8 gCorcovado100PokedexText[] = _(
    "Espírito de uma montanha inteira. Costas\n"
    "cobertas de mata que respira.");

const u8 gCervalo101PokedexText[] = _(
    "Chifres pontudos ainda em desenvolvimento.\n"
    "Salta arbustos com facilidade.");

const u8 gCatingueiro102PokedexText[] = _(
    "Chifres se ramificam com a idade. Come\n"
    "cactos sem se machucar.");

const u8 gSucuapara103PokedexText[] = _(
    "Chifres tao grandes que precisam levantar a\n"
    "cabeça pra passar pela mata.");

const u8 gCabocim104PokedexText[] = _(
    "Espírito das águas em forma humanoide. Nada\n"
    "como um peixe.");

const u8 gCaboclo105PokedexText[] = _(
    "Puxa canoas pra fundo quando pescadores\n"
    "desrespeitam o rio.");

const u8 gCangaco106PokedexText[] = _(
    "Ave que rouba dos ricos e distribui pros\n"
    "pobres - segundo os sertanejos.");

const u8 gXango107PokedexText[] = _(
    "Domina raios e trovoes. Machado bipene solta\n"
    "faíscas ao golpear.");

const u8 gIemanja108PokedexText[] = _(
    "Deusa dos oceanos. Filhas peixes seguem-na\n"
    "em cortejo.");

const u8 gOxum109PokedexText[] = _(
    "Rainha das águas doces. Cabelo de ouro\n"
    "molhado escorre pra sempre.");

const u8 gOgum110PokedexText[] = _(
    "Ferreiro divino. Forjou espadas que cortam a\n"
    "alma dos malfeitores.");

const u8 gCavalim111PokedexText[] = _(
    "Crina longa esvoaça no vento. Aprende a\n"
    "galopar em uma semana.");

const u8 gCavalgado112PokedexText[] = _(
    "Corre 60 km/h por horas. Domesticado por\n"
    "gaúchos de Arauana.");

const u8 gZebuim113PokedexText[] = _(
    "Corcova enorme já visível no filhote. Ainda\n"
    "inseguro nas patas.");

const u8 gZebu114PokedexText[] = _(
    "Corcova gigante. Aguenta calor extremo do\n"
    "cerrado sem se cansar.");

const u8 gOvelhinha115PokedexText[] = _(
    "Lan grossa protege do frio serrano.\n"
    "Docilíssima.");

const u8 gCabrita116PokedexText[] = _(
    "Sobe morros impossíveis. Come galhos secos.");

const u8 gChocalhao117PokedexText[] = _(
    "Chocalho no rabo ainda pequeno. Aprende a\n"
    "tocar aos poucos.");

const u8 gCascavelim118PokedexText[] = _(
    "Veneno neurotóxico já plenamente ativo.\n"
    "Chocalho intimida predadores.");

const u8 gCascavao119PokedexText[] = _(
    "Uma mordida paralisa até Onçaléu. Chocalho\n"
    "ouve-se a 100 metros.");

const u8 gJararaca120PokedexText[] = _(
    "Camufla-se em folhas caídas. Nao avisa antes\n"
    "de morder.");

const u8 gPirarim121PokedexText[] = _(
    "Nasce com 30 cm. Cresce um metro por ano em\n"
    "rio bem alimentado.");

const u8 gPirarucu122PokedexText[] = _(
    "Até 3 metros de comprimento. Respira ar da\n"
    "superfície como um mamífero.");

const u8 gPiranha123PokedexText[] = _(
    "Ataca em cardume. Descarnam uma vaca em\n"
    "minutos.");

const u8 gTambaqui124PokedexText[] = _(
    "Come frutas que caem dos igapós. Dentes\n"
    "triturando sementes.");

const u8 gAruana125PokedexText[] = _(
    "Salta 2 metros fora dágua pra pegar insetos\n"
    "em galhos.");

const u8 gPoraque126PokedexText[] = _(
    "Solta choque de 600 volts. Paralisa qualquer\n"
    "coisa que toque a água.");

const u8 gCurimbata127PokedexText[] = _(
    "Nada em cardumes gigantes. Migra rio acima\n"
    "na piracema.");

const u8 gTraira128PokedexText[] = _(
    "Espera imóvel entre folhas submersas. Dentes\n"
    "afiados travam a presa.");

const u8 gDourado129PokedexText[] = _(
    "Salta em cachoeiras rio acima. Escamas\n"
    "douradas brilham como moedas.");

const u8 gTucunare130PokedexText[] = _(
    "Mancha ocelada na cauda espanta predadores.\n"
    "Ataca qualquer coisa que entre no\n"
    "território.");

const u8 gPacu131PokedexText[] = _(
    "Dentes humanos triturando castanhas.\n"
    "Confunde treinadores nadando.");

const u8 gMatrinxa132PokedexText[] = _(
    "Cardumes escuros deslizam pelas corredeiras.\n"
    "Pesca esportiva popular.");

const u8 gPiau133PokedexText[] = _(
    "Listras douradas laterais. Come tudo que cai\n"
    "na água.");

const u8 gCascudo134PokedexText[] = _(
    "Placas duras cobrem o corpo. Roi lodo dos\n"
    "aquários.");

const u8 gAcara135PokedexText[] = _(
    "Formato de disco colorido. Cria os filhotes\n"
    "no próprio muco da pele.");

const u8 gVagalumim136PokedexText[] = _(
    "Bumbum acende só quando fica com medo.\n"
    "Ilumina caminhos na mata.");

const u8 gVagalume137PokedexText[] = _(
    "Piscadas em código atraem fêmeas. Ilumina 5\n"
    "metros ao redor.");

const u8 gCigarrinho138PokedexText[] = _(
    "Vive 7 anos debaixo da terra antes de virar\n"
    "Cigarrao.");

const u8 gCigarrao139PokedexText[] = _(
    "Canto de 100 decibéis. Sinal do verao em\n"
    "Arauana.");

const u8 gLouvadinha140PokedexText[] = _(
    "Foices ainda pequenas mas afiadas. Come\n"
    "formigas.");

const u8 gLouvadeus141PokedexText[] = _(
    "Reza antes de decapitar a presa. Fêmea come\n"
    "o macho após acasalar.");

const u8 gEscorpim142PokedexText[] = _(
    "Ferrao translúcido no rabo. Uma picada tira\n"
    "o sono da noite.");

const u8 gEscorpiao143PokedexText[] = _(
    "Pinças esmagam besouros. Ferrao paralisa até\n"
    "um Cavalgado.");

const u8 gCaramulao144PokedexText[] = _(
    "Concha espiralada com padrao folclórico.\n"
    "Come alface das margens.");

const u8 gPiolhao145PokedexText[] = _(
    "Se enrola em bola quando ameaçado. Solta\n"
    "cheiro de amêndoa amarga.");

const u8 gBarata146PokedexText[] = _(
    "Sobrevive a qualquer coisa. Radiaçao,\n"
    "veneno, chinelo.");

const u8 gGrilim147PokedexText[] = _(
    "Salta 30 vezes o próprio tamanho. Toca\n"
    "música com as pernas.");

const u8 gGrilao148PokedexText[] = _(
    "Canto ininterrupto à noite. Anuncia chuva.");

const u8 gAranhao149PokedexText[] = _(
    "Levanta as patas dianteiras antes de atacar.\n"
    "Veneno neurotóxico grave.");

const u8 gVespao150PokedexText[] = _(
    "Caça aranhas do tamanho de maos e as arrasta\n"
    "pro ninho.");

const u8 gMarimbondao151PokedexText[] = _(
    "Ferroada dolorosa por horas. Faz ninho de\n"
    "barro em telhados.");

const u8 gTraca152PokedexText[] = _(
    "Come móveis por dentro. Só se percebe quando\n"
    "desmorona.");

const u8 gCorupiao153PokedexText[] = _(
    "Vive 30 anos botando ovos sem parar.\n"
    "Cupinzeiro cresce em torno dela.");

const u8 gCupinzim154PokedexText[] = _(
    "Mandíbulas gigantes protegem a rainha. Nao\n"
    "come - só briga.");

const u8 gFormigaoPreto155PokedexText[] = _(
    "Corre em fila indiana por quilômetros.\n"
    "Devora tudo no caminho.");

const u8 gBeijaFlor156PokedexText[] = _(
    "Bate as asas 80 vezes por segundo. Voa pra\n"
    "trás e de cabeça pra baixo.");

const u8 gSabia157PokedexText[] = _(
    "Canto conhecido como o mais bonito do\n"
    "Brasil. Anuncia a primavera.");

const u8 gBemTeVi158PokedexText[] = _(
    "Grita o próprio nome. Delator de tudo que\n"
    "acontece no quintal.");

const u8 gUrutau159PokedexText[] = _(
    "Se disfarça de galho seco. Canto lamentoso à\n"
    "noite assusta viajantes.");

const u8 gCarcara160PokedexText[] = _(
    "Come cobras, ratos e até cordeiros pequenos.\n"
    "Símbolo do sertao.");

const u8 gGaviao161PokedexText[] = _(
    "Maior ave de rapina das Américas. Come\n"
    "macacos e preguiças.");

const u8 gUrubu162PokedexText[] = _(
    "Come qualquer carne podre. Faz limpeza dos\n"
    "campos.");

const u8 gCorurupim163PokedexText[] = _(
    "Olhos giram 270 graus. Vê no escuro total.");

const u8 gCoruja164PokedexText[] = _(
    "Vive em buracos no chao do cerrado. Voa em\n"
    "silêncio absoluto.");

const u8 gJaburu165PokedexText[] = _(
    "Voa em bandos de centenas. Pesca peixes com\n"
    "bico de espada.");

const u8 gEma166PokedexText[] = _(
    "Maior ave do Brasil. Corre 60 km/h em fuga.");

const u8 gSeriema167PokedexText[] = _(
    "Bate cobras venenosas contra o chao até\n"
    "matar. Só depois come.");

const u8 gAnu168PokedexText[] = _(
    "Vive em bandos ruidosos. Come carrapatos das\n"
    "costas de vacas.");

const u8 gTrincaFerro169PokedexText[] = _(
    "Canto tao forte que treinadores premiam pelo\n"
    "timbre em concursos.");

const u8 gCurio170PokedexText[] = _(
    "Canto elaborado com trinados. Ave mais\n"
    "valiosa em disputas de canto.");

const u8 gSanhaco171PokedexText[] = _(
    "Azul cintilante brilha no sol. Come frutas\n"
    "em quintais.");

const u8 gPapaFormiga172PokedexText[] = _(
    "Come exclusivamente formigas correiçao.\n"
    "Segue enxames por dias.");

const u8 gChoca173PokedexText[] = _(
    "Vive na sombra baixa. Assusta borboletas com\n"
    "bater de asas.");

const u8 gBacurau174PokedexText[] = _(
    "Voa rasante caçando insetos. Boca gigante\n"
    "abre no ar.");

const u8 gJoaoDeBarro175PokedexText[] = _(
    "Constrói ninho de barro em forma de forno.\n"
    "Vira símbolo em pátios rurais.");

const u8 gSementim176PokedexText[] = _(
    "Semente-de-jequitibá que aprendeu a andar em\n"
    "duas raízes.");

const u8 gMuda177PokedexText[] = _(
    "Broto de árvore com folhinhas de sol.\n"
    "Rega-se sozinha nas chuvas.");

const u8 gJequitiba178PokedexText[] = _(
    "Árvore centenária ambulante. Passa mais\n"
    "tempo parada do que andando.");

const u8 gBromelinha179PokedexText[] = _(
    "Copo natural que junta água da chuva. Sapos\n"
    "vivem dentro.");

const u8 gOrquidina180PokedexText[] = _(
    "Pétalas iridescentes. Aroma atrai\n"
    "polinizadores por quilômetros.");

const u8 gVitoriaregia181PokedexText[] = _(
    "Folha do tamanho de uma cama de casal.\n"
    "Aguenta uma criança em pé.");

const u8 gIpe182PokedexText[] = _(
    "Perde as folhas e floresce amarelo no\n"
    "inverno seco.");

const u8 gCipo183PokedexText[] = _(
    "Se enrosca em árvores e sufoca. Longuíssimo\n"
    "- dá volta em morros.");

const u8 gPalmito184PokedexText[] = _(
    "Coraçao da palmeira é iguaria disputada. Se\n"
    "defende com espinhos no tronco.");

const u8 gBabacu185PokedexText[] = _(
    "Coco duríssimo. Só Petropico consegue\n"
    "quebrar.");

const u8 gBuriti186PokedexText[] = _(
    "Cresce onde tem água doce escondida.\n"
    "Sinaliza oásis no cerrado.");

const u8 gCajuzim187PokedexText[] = _(
    "Fruta que anda. Castanha na cabeça balança\n"
    "como topete.");

const u8 gCajueiro188PokedexText[] = _(
    "Assa a própria castanha ao sol da caatinga.\n"
    "Aroma inebriante.");

const u8 gAcai189PokedexText[] = _(
    "Cacho roxo escuro no topo. Energético\n"
    "natural pros Pokémon lutadores.");

const u8 gCacauim190PokedexText[] = _(
    "Fruto amarelo com sementes doces. Vira\n"
    "Chocolat na fermentaçao.");

const u8 gCacaueiro191PokedexText[] = _(
    "Vagens roxas quando maduras. Origem do\n"
    "chocolate de Arauana.");

const u8 gGuarana192PokedexText[] = _(
    "Semente pretíssima parece um olho. Energia\n"
    "natural pura.");

const u8 gMate193PokedexText[] = _(
    "Folhas amargas viram chimarrao. Companheiro\n"
    "dos gaúchos de Arauana.");

const u8 gMilho194PokedexText[] = _(
    "Espigas coloridas amarela, vermelha, roxa.\n"
    "Alimento das aldeias.");

const u8 gMandioca195PokedexText[] = _(
    "Raiz alongada parece perna. Enterra a si\n"
    "mesma pra dormir.");

const u8 gPedrinha196PokedexText[] = _(
    "Pedra rolada por milênios. Perfeitamente\n"
    "lisa.");

const u8 gRochao197PokedexText[] = _(
    "Rocha ambulante que ronca ao rolar. Faz\n"
    "tremer o chao.");

const u8 gCristalim198PokedexText[] = _(
    "Cristal transparente. Cresce um centímetro\n"
    "por ano em cavernas úmidas.");

const u8 gAmetista199PokedexText[] = _(
    "Geodo roxo brilhante. Refrata o sol em\n"
    "arco-íris.");

const u8 gOurico200PokedexText[] = _(
    "Pepita ambulante. Bandidos perseguem por\n"
    "Arauana inteira.");

const u8 gFerrolho201PokedexText[] = _(
    "Rocha pesadíssima. Ficha em pé só se plantar\n"
    "as raízes.");

const u8 gDiamantina202PokedexText[] = _(
    "Pedra preciosíssima. Reflete arco-íris em\n"
    "qualquer luz.");

const u8 gBauxito203PokedexText[] = _(
    "Cor terracota. Se descama em placas\n"
    "metálicas.");

const u8 gManganim204PokedexText[] = _(
    "Preto brilhante. Absorve luz ao redor.");

const u8 gSalitre205PokedexText[] = _(
    "Cristaliza sozinho em salinas. Doce e amargo\n"
    "ao mesmo tempo.");

const u8 gEnxofrino206PokedexText[] = _(
    "Cheiro de ovo podre. Cresce em fumarolas.");

const u8 gArgilim207PokedexText[] = _(
    "Se molda em qualquer forma. Vira Boneco\n"
    "quando um humano brinca.");

const u8 gBoneco208PokedexText[] = _(
    "Argila animada por brincadeiras de criança.\n"
    "Guarda memórias afetivas.");

const u8 gEstalactite209PokedexText[] = _(
    "Cresce uma gota por século. Se ofende se\n"
    "chamada de estalagmite.");

const u8 gEstalagmite210PokedexText[] = _(
    "Cresce apontando pra cima. Nao gosta de\n"
    "estalactites.");

const u8 gFossil211PokedexText[] = _(
    "Osso de dinossauro que voltou a andar.\n"
    "Ninguém sabe como.");

const u8 gMeteorito212PokedexText[] = _(
    "Caiu do céu há milênios. Ainda quente ao\n"
    "toque.");

const u8 gVulcanite213PokedexText[] = _(
    "Formada em erupçao antiga. Guarda calor por\n"
    "séculos.");

const u8 gMarmim214PokedexText[] = _(
    "Escultura clássica ganhou vida por magia.\n"
    "Elegantíssimo.");

const u8 gGranito215PokedexText[] = _(
    "Rachaduras naturais formam rostos zangados.");

const u8 gCaranguim216PokedexText[] = _(
    "Bebê caranguejo saltitante. Pinça já\n"
    "mordisca dedos.");

const u8 gGuaiamum217PokedexText[] = _(
    "Vive em tocas no manguezal. Sai à noite em\n"
    "bandos.");

const u8 gSiri218PokedexText[] = _(
    "Nada de lado. Pinças azuis brilhantes.");

const u8 gCamarao219PokedexText[] = _(
    "Nada em bandos rosados. Delícia grelhada -\n"
    "segundo turistas.");

const u8 gPolvim220PokedexText[] = _(
    "Muda de cor pra combinar com o fundo do mar.\n"
    "Solta tinta.");

const u8 gPolvao221PokedexText[] = _(
    "8 braços resolvem quebra-cabeças. Abre potes\n"
    "com tampa.");

const u8 gAguaviva222PokedexText[] = _(
    "Tentáculos urticantes de metros. Flutua com\n"
    "as correntes.");

const u8 gCavalimMarinho223PokedexText[] = _(
    "Macho engravida e cuida dos filhotes. Nada\n"
    "em pé.");

const u8 gTartaruguim224PokedexText[] = _(
    "Nasce na praia e corre pro mar por instinto.\n"
    "Frágil demais.");

const u8 gTartaruga225PokedexText[] = _(
    "Vive 100 anos. Volta à praia onde nasceu pra\n"
    "desovar.");

const u8 gGolfinho226PokedexText[] = _(
    "Salta em piruetas. Se comunica em cliques\n"
    "agudos.");

const u8 gBaleia227PokedexText[] = _(
    "Canta cançoes que percorrem oceanos. Migra\n"
    "sazonalmente.");

const u8 gTubarim228PokedexText[] = _(
    "Já nasce nadando e caçando. Sem infância.");

const u8 gTubarao229PokedexText[] = _(
    "Rei do mar. Dentes serrilhados regeneram\n"
    "infinitamente.");

const u8 gArraia230PokedexText[] = _(
    "Se camufla no fundo. Choque paralisa\n"
    "banhistas descuidados.");

const u8 gPeixeEspada231PokedexText[] = _(
    "Rostro em forma de espada. Perfura cascos de\n"
    "barco.");

const u8 gPargo232PokedexText[] = _(
    "Escamas vermelhas brilham no sol. Cardume\n"
    "gigante nos recifes.");

const u8 gPescadao233PokedexText[] = _(
    "Antena com isca luminosa engana peixes\n"
    "menores.");

const u8 gLoirinha234PokedexText[] = _(
    "Aparece em espelhos de escolas à noite.\n"
    "Chama seu nome.");

const u8 gCuca235PokedexText[] = _(
    "Rouba crianças que nao dormem. Nem sempre é\n"
    "real.");

const u8 gBichoPapao236PokedexText[] = _(
    "Vive embaixo de camas. Só assusta crianças\n"
    "desobedientes.");

const u8 gLobisomem237PokedexText[] = _(
    "Sétimo filho homem em lua cheia. Uivo faz\n"
    "caes fugirem.");

const u8 gCorpoSeco238PokedexText[] = _(
    "Alma tao ruim que nem a terra aceita. Vaga\n"
    "eternamente.");

const u8 gMaoPeluda239PokedexText[] = _(
    "Mao gigante peluda sai debaixo da cama. Pega\n"
    "os pés.");

const u8 gPernaCabeluda240PokedexText[] = _(
    "Perna cabeluda anda sozinha à noite.\n"
    "Persegue solitários.");

const u8 gComadre241PokedexText[] = _(
    "Espírito de mulher que morreu no parto.\n"
    "Sequestra bebês.");

const u8 gAnhanga242PokedexText[] = _(
    "Protetor dos animais. Amaldiçoa caçadores\n"
    "gulosos.");

const u8 gJurupari243PokedexText[] = _(
    "Deus tupi da noite. Só homens podem ver o\n"
    "rosto.");

const u8 gTupa244PokedexText[] = _(
    "Deus supremo tupi-guarani. Solta relâmpagos\n"
    "com um piscar.");

const u8 gJaci245PokedexText[] = _(
    "Deusa da lua. Cabelo prateado brilha nas\n"
    "noites de lua cheia.");

const u8 gGuaraci246PokedexText[] = _(
    "Deus do sol. Coroa dourada ilumina Arauana\n"
    "inteira.");

const u8 gRuda247PokedexText[] = _(
    "Deus do amor. Flecha de flor faz coraçoes se\n"
    "encontrarem.");

const u8 gAlua248PokedexText[] = _(
    "Espírito da bebida fermentada. Alegra festas\n"
    "em pajelanças.");

const u8 gJenipapo249PokedexText[] = _(
    "Tinta preta que dura semanas na pele. Pinta\n"
    "padroes de bênçao.");

const u8 gUrucum250PokedexText[] = _(
    "Tinta vermelha ancestral. Repele insetos.");

const u8 gCaipora251PokedexText[] = _(
    "Monta em porco-do-mato. Protege a caça -\n"
    "persegue caçadores que exageram.");

const u8 gAnhangaPita252PokedexText[] = _(
    "Forma vermelha do Anhangá quando enfurecido.");

const u8 gYaraPinda253PokedexText[] = _(
    "Yara em forma de pescadora. Ensina jovens a\n"
    "respeitar o rio.");

const u8 gPisadeira254PokedexText[] = _(
    "Pisa no peito de quem dorme de barriga\n"
    "cheia. Paralisia.");

const u8 gZumbi255PokedexText[] = _(
    "Espírito líder de quilombo. Inspira coragem\n"
    "em quem luta pela liberdade.");

const u8 gIemanjaPequena256PokedexText[] = _(
    "Forma jovem da deusa Iemanjá. Rege marés\n"
    "menores.");

const u8 gOssanha257PokedexText[] = _(
    "Domina o poder das folhas medicinais. Cura\n"
    "Pokémon envenenados.");

const u8 gOxala258PokedexText[] = _(
    "Espírito criador. Vestido de branco, benze\n"
    "quem se aproxima.");

const u8 gSaciamigo259PokedexText[] = _(
    "Filhote de Saci. Ainda nao domina os\n"
    "redemoinhos.");

const u8 gSaciperere260PokedexText[] = _(
    "Chapéu vermelho, cachimbo, uma perna. Solto\n"
    "pelo folclore inteiro.");

const u8 gCurupiraAnciao261PokedexText[] = _(
    "Curupira anciao cabeludo. Sabe onde toda\n"
    "árvore ancestral cresce.");

const u8 gCaiporaFemea262PokedexText[] = _(
    "Forma feminina do Caipora. Ainda mais rígida\n"
    "com caçadores gulosos.");

const u8 gPombaGira263PokedexText[] = _(
    "Espírito feminino sedutor. Ri alto nas\n"
    "encruzilhadas.");

const u8 gExu264PokedexText[] = _(
    "Guardiao das encruzilhadas. Nada passa sem\n"
    "seu aval.");

const u8 gPretoVelho265PokedexText[] = _(
    "Espírito ancestral. Fuma cachimbo e dá\n"
    "conselhos milenares.");

const u8 gCabocloGuerreiro266PokedexText[] = _(
    "Guerreiro indígena espectral. Cocar de penas\n"
    "coloridas.");

const u8 gMarinheiro267PokedexText[] = _(
    "Espírito de marujo afogado. Conta histórias\n"
    "de tempestades.");

const u8 gBaiano268PokedexText[] = _(
    "Espírito festeiro. Toca berimbau sem parar.");

const u8 gCangaceiro269PokedexText[] = _(
    "Espírito de Lampiao. Chapéu de couro\n"
    "tachonado.");

const u8 gBeata270PokedexText[] = _(
    "Espírito de Padre Cícero. Benze com terço de\n"
    "mandacaru.");

const u8 gMeninoDeus271PokedexText[] = _(
    "Espírito de criança inocente. Aparece em\n"
    "folias de reis.");

const u8 gReiMomo272PokedexText[] = _(
    "Rei do carnaval. Trono de purpurina.");

const u8 gBumbaMeuBoi273PokedexText[] = _(
    "Espírito do boi de folia. Ressuscita em cada\n"
    "apresentaçao.");

const u8 gReisado274PokedexText[] = _(
    "Espírito folia de reis. Sanfona toca\n"
    "sozinha.");

const u8 gFrevinho275PokedexText[] = _(
    "Espírito do frevo pernambucano. Dança\n"
    "acrobática sem parar.");

const u8 gMaracatu276PokedexText[] = _(
    "Cortejo real espectral. Coroa dourada e\n"
    "vestes bordadas.");

const u8 gCongada277PokedexText[] = _(
    "Espírito guerreiro em cortejo. Bastoes batem\n"
    "em ritmo.");

const u8 gFoliao278PokedexText[] = _(
    "Espírito que percorre festas. Nunca cansa de\n"
    "dançar.");

const u8 gOncuma279PokedexText[] = _(
    "Onça-preta lendária. Deusa das florestas\n"
    "noturnas.");

const u8 gSucuriacu280PokedexText[] = _(
    "Sucuri de 10 metros. Engole capivaras\n"
    "inteiras.");

const u8 gPirarumba281PokedexText[] = _(
    "Pirarucu-rei. 5 metros e escamas de\n"
    "armadura.");

const u8 gDraguaraAlfa282PokedexText[] = _(
    "Draguará alfa da matilha lendária. Fogo\n"
    "turquesa esverdeado.");

const u8 gTerolibraRainha283PokedexText[] = _(
    "Rainha enorme dos Terolibra. Comanda\n"
    "enxames.");

const u8 gPetropicoAnciao284PokedexText[] = _(
    "Petropico centenário. Bico esculpiu chapadas\n"
    "inteiras.");

const u8 gBoitataPuro285PokedexText[] = _(
    "Boitatá primordial. Fogo azul que devora\n"
    "bosques inteiros.");

const u8 gIaraMae286PokedexText[] = _(
    "Iara mae de todas. Canto ouvido só uma vez\n"
    "por vida.");

const u8 gCurupiraRei287PokedexText[] = _(
    "Curupira rei da floresta. Cabelos de fogo\n"
    "cor de urucum.");

const u8 gSaciRei288PokedexText[] = _(
    "Saci-Pererê ancestral. Chapéu vermelho\n"
    "lendário.");

const u8 gAnhangau289PokedexText[] = _(
    "Anhangá supremo. Veados brancos o seguem.");

const u8 gMuiraKyta290PokedexText[] = _(
    "Amor amazônico convertido em árvore.");

const u8 gCobraNorato291PokedexText[] = _(
    "Homem-serpente. Boiuna vira homem nas\n"
    "festas.");

const u8 gMapinguari292PokedexText[] = _(
    "Preguiça-gigante primordial. Boca no peito,\n"
    "cheiro de morte.");

const u8 gIpupiara293PokedexText[] = _(
    "Homem-peixe canibal. Terror dos pescadores\n"
    "antigos.");

const u8 gUirapuru294PokedexText[] = _(
    "Ave lendária. Canto silencia toda a mata\n"
    "quando canta.");

const u8 gMuiraquita295PokedexText[] = _(
    "Amuleto verde-jade das Icamiabas. Traz sorte\n"
    "em batalhas.");

const u8 gAmazona296PokedexText[] = _(
    "Guerreira sem seio esquerdo pra atirar arco.\n"
    "Rainha de tribo lendária.");

const u8 gCorcovadoAnciao297PokedexText[] = _(
    "Corcovado antigo. Costa cheia de árvores\n"
    "primárias.");

const u8 gCristo298PokedexText[] = _(
    "Espírito de maos abertas. Abençoa quem vê o\n"
    "nascer do sol.");

const u8 gRatao299PokedexText[] = _(
    "Vive em esgotos. Come qualquer coisa.");

const u8 gPombim300PokedexText[] = _(
    "Fura sacos de lixo. Cocô arruína estátuas.");

const u8 gPombao301PokedexText[] = _(
    "Pomba enorme. Domina praças inteiras.");

const u8 gBaratao302PokedexText[] = _(
    "Barata voadora do apocalipse. Voa em direçao\n"
    "a pessoas gritando.");

const u8 gMosquim303PokedexText[] = _(
    "Rajadinho listrado. Transmite doenças.");

const u8 gCaoBravo304PokedexText[] = _(
    "Contraparte selvagem do Caramelo. Vive em\n"
    "bando defendendo território.");

const u8 gGatoPreto305PokedexText[] = _(
    "Diz que dá azar cruzar caminho. Diz.");

const u8 gPerereca306PokedexText[] = _(
    "Aparece em vasos sanitários. Salta na cara\n"
    "de quem senta.");

const u8 gLagartixa307PokedexText[] = _(
    "Come mosquitos. Rabo cai e continua se\n"
    "mexendo.");

const u8 gTracaPapel308PokedexText[] = _(
    "Come papel antigo. Absorve o conhecimento\n"
    "dos livros.");

const u8 gPoeirao309PokedexText[] = _(
    "Bola de poeira ambulante. Aumenta em salas\n"
    "fechadas.");

const u8 gFerrugem310PokedexText[] = _(
    "Come metal de dentro. Pontes desabam sem\n"
    "aviso.");

const u8 gFumacento311PokedexText[] = _(
    "Nuvem de fumaça de ônibus. Escurece céus\n"
    "urbanos.");

const u8 gOleoso312PokedexText[] = _(
    "Mancha de vazamento. Mata Pokémon marinhos.");

const u8 gLixao313PokedexText[] = _(
    "Pilha viva de lixo urbano. Vira Chorume\n"
    "quando chove.");

const u8 gChorume314PokedexText[] = _(
    "Líquido preto que sai do lixao. Envenena\n"
    "tudo por onde passa.");

const u8 gBituca315PokedexText[] = _(
    "Ainda queima quando jogada. Causa incêndios\n"
    "em pastos.");

const u8 gLatinha316PokedexText[] = _(
    "Vive procurando outra Latinha pra brigar.\n"
    "Recompensa quem recicla.");

const u8 gSacolim317PokedexText[] = _(
    "Voa com o vento. Enrosca em árvores por\n"
    "décadas.");

const u8 gGarrafao318PokedexText[] = _(
    "Vive boiando em rios. Desce até o mar.");

const u8 gNetzero319PokedexText[] = _(
    "Ave feita de plástico do estômago. Símbolo\n"
    "da poluiçao.");

const u8 gPilhoso320PokedexText[] = _(
    "Vaza ácido corrosivo. Nao deve ser tocada.");

const u8 gCabofio321PokedexText[] = _(
    "Fios elétricos emaranhados. Curto-circuito\n"
    "ambulante.");

const u8 gBugao322PokedexText[] = _(
    "Bug urbano gigante. Aparece em cozinhas mal\n"
    "cuidadas.");

const u8 gAluminio323PokedexText[] = _(
    "Papel alumínio dobrado voa como pipa.");

const u8 gConcretim324PokedexText[] = _(
    "Pedaço de calçada quebrada. Tropeça pessoas.");

const u8 gBueiro325PokedexText[] = _(
    "Espírito das águas residuais. Sobe em\n"
    "enchentes.");

const u8 gSinal326PokedexText[] = _(
    "Semáforo que muda de cor sem motivo. Causa\n"
    "confusao no trânsito.");

const u8 gPoste327PokedexText[] = _(
    "Poste de luz que anda. Ilumina ruas escuras.");

const u8 gGrafiteiro328PokedexText[] = _(
    "Espírito da arte urbana. Muda de forma\n"
    "conforme o desenho.");

const u8 gGuaraciana329PokedexText[] = _(
    "Consorte de Guaraci. Brilha ao amanhecer.");

const u8 gJaciana330PokedexText[] = _(
    "Consorte de Jaci. Brilha à meia-noite.");

const u8 gTupanau331PokedexText[] = _(
    "Tupan em forma primordial. Um trovao só\n"
    "destrói montes.");

const u8 gIarau332PokedexText[] = _(
    "Iara em forma suprema. Rio inteiro obedece\n"
    "ao canto.");

const u8 gKuarahy333PokedexText[] = _(
    "Sol dos primeiros dias. Deu vida ao\n"
    "continente.");

const u8 gYasy334PokedexText[] = _(
    "Lua dos primeiros dias. Rege marés e sonhos.");

const u8 gRudarauna335PokedexText[] = _(
    "Amor primordial. Une casais destinados.");

const u8 gPerybe336PokedexText[] = _(
    "Espírito da bacia amazônica inteira. Um só\n"
    "corpo, milhares de afluentes.");

const u8 gArauanau337PokedexText[] = _(
    "Guardiao supremo da regiao. Só aparece\n"
    "quando Arauana está em perigo.");

const u8 gVerdejante338PokedexText[] = _(
    "Espírito da mata atlântica primordial. Brota\n"
    "das cinzas de queimadas.");

const u8 gChuvao339PokedexText[] = _(
    "Espírito da chuva de dezembro. Encharca\n"
    "Arauana em três dias.");

const u8 gSolzao340PokedexText[] = _(
    "Espírito da estiagem. Queima os campos por\n"
    "meses.");

const u8 gVentania341PokedexText[] = _(
    "Vento sul que traz frio no inverno. Assobia\n"
    "melodias mortais.");

const u8 gTerraao342PokedexText[] = _(
    "Terra fértil ambulante. Onde pisa, brota\n"
    "lavoura.");

const u8 gFogareu343PokedexText[] = _(
    "Fogo primordial que aqueceu Arauana no\n"
    "início.");

const u8 gMarulho344PokedexText[] = _(
    "Espírito do oceano Atlântico. Ondas obedecem\n"
    "seu compasso.");

const u8 gAlvorecer345PokedexText[] = _(
    "Espírito do amanhecer. Cor rosa dourada\n"
    "preenche o céu.");

const u8 gPoente346PokedexText[] = _(
    "Espírito do pôr do sol. Cores queimadas em\n"
    "fim de tarde.");

const u8 gEstrelinha347PokedexText[] = _(
    "Estrela cadente que fez ninho. Faz desejos\n"
    "se realizarem.");

const u8 gArauanamon348PokedexText[] = _(
    "Encarnaçao de toda a regiao de Arauana. Só\n"
    "existe um.");

const u8 gAracua349PokedexText[] = _(
    "Grita ao amanhecer alertando o bando. Serve\n"
    "de despertador da mata.");

const u8 gBugio350PokedexText[] = _(
    "Uiva ao alvorecer. Marca território a\n"
    "quilômetros.");

const u8 gTuim351PokedexText[] = _(
    "Menor papagaio do Brasil. Voa em bandos\n"
    "verdes ruidosos.");

const u8 gPeriquitao352PokedexText[] = _(
    "Papagaio esperdo. Imita vozes humanas para\n"
    "enganar predadores.");

const u8 gArarunao353PokedexText[] = _(
    "Arara azul de bico curvo. Casais permanecem\n"
    "juntos por toda a vida.");

const u8 gPreazinho354PokedexText[] = _(
    "Roedor tímido de olhos redondos. Vive em\n"
    "tocas nos campos.");

const u8 gCapivarao355PokedexText[] = _(
    "O maior roedor do mundo. Serve de assento\n"
    "pra aves e macacos.");

const u8 gTamandui356PokedexText[] = _(
    "Filhote monta nas costas da mae até crescer.\n"
    "Lambe formigas o dia inteiro.");

const u8 gTamandua357PokedexText[] = _(
    "Língua pegajosa de 60cm. Cheira formigueiro\n"
    "a quilômetros.");

const u8 gTamanduao358PokedexText[] = _(
    "Garras dianteiras enormes. Espanta onças de\n"
    "pé em pé.");

const u8 gPreguicinha359PokedexText[] = _(
    "Move-se tao devagar que musgo cresce no\n"
    "pelo.");

const u8 gPreguicoso360PokedexText[] = _(
    "Dorme 20 horas por dia. Sonhos alteram o\n"
    "clima ao redor.");

const u8 gBeijaFlor361PokedexText[] = _(
    "Bate as asas 80 vezes por segundo. Bebe\n"
    "néctar em pleno voo.");

const u8 gBeijaLuz362PokedexText[] = _(
    "Penas refletem luz solar em espectros\n"
    "iridescentes.");

const u8 gBeijaSol363PokedexText[] = _(
    "Núcleo do peito guarda uma centelha do\n"
    "próprio sol.");

const u8 gSarara364PokedexText[] = _(
    "Cabelos loiros cacheados. Traz sorte a quem\n"
    "pesca perto.");

const u8 gCambota365PokedexText[] = _(
    "Ginga sem parar. Chuta enquanto dança.");

const u8 gBerimbau366PokedexText[] = _(
    "Cabaça viva que toca sozinha. Impoe o ritmo\n"
    "da roda.");

const u8 gAtabaque367PokedexText[] = _(
    "Cada batida faz o chao tremer. Marca o\n"
    "compasso do candomblé.");

const u8 gPandeirim368PokedexText[] = _(
    "Rodopia sozinho tocando samba.");

const u8 gSanfoninha369PokedexText[] = _(
    "Sopra melodias que fazem quem escuta chorar\n"
    "de saudade.");

const u8 gVioleiro370PokedexText[] = _(
    "Viola caipira ambulante. Canta modas de\n"
    "causos antigos.");

const u8 gZabumba371PokedexText[] = _(
    "Tambor grave que puxa o forró. Faz coraçoes\n"
    "baterem em compasso.");

const u8 gCordelim372PokedexText[] = _(
    "Panfleto de cordel que se lê sozinho em voz\n"
    "alta.");

const u8 gRendeira373PokedexText[] = _(
    "Tece rendas invisíveis que capturam sonhos\n"
    "ruins.");

const u8 gEscamoso374PokedexText[] = _(
    "Pele coberta de escamas afiadas. Pescadores\n"
    "respeitam.");

const u8 gPiranhita375PokedexText[] = _(
    "Nada em cardumes de dezenas. Come vaca\n"
    "inteira em minutos.");

const u8 gBoitata376PokedexText[] = _(
    "Cobra de fogo que castiga quem queima a\n"
    "mata. Olhos brasas.");

const u8 gPiraruacu377PokedexText[] = _(
    "Pirarucu ancestral. Um único golpe de cauda\n"
    "esvazia um lago.");

const u8 gMataMata378PokedexText[] = _(
    "Cágado antigo. Casco esconde uma floresta em\n"
    "miniatura.");

const u8 gSolaris379PokedexText[] = _(
    "Corpo é uma esfera solar viva. Apaga\n"
    "estrelas ao surgir.");

const u8 gSelene380PokedexText[] = _(
    "Corpo é uma lua crescente prateada. Domina\n"
    "marés e sonhos.");

const u8 gZumbiRei381PokedexText[] = _(
    "Rei de Palmares reencarnado. Símbolo da\n"
    "liberdade.");

const u8 gIemanja382PokedexText[] = _(
    "Rainha do mar. Recebe oferendas em\n"
    "fevereiro.");

const u8 gOxumara383PokedexText[] = _(
    "Serpente arco-íris. Une céu e terra em ponte\n"
    "colorida.");

const u8 gCurupixel384PokedexText[] = _(
    "Filhote de Curupira em forma primordial. Só\n"
    "aparece a crianças puras.");

const u8 gSacinho385PokedexText[] = _(
    "Saci recém-nascido. Redemoinhos onde passa.");

const u8 gAraua386PokedexText[] = _(
    "O primeiro Pokémon de Arauana. Contém a\n"
    "essência de toda a regiao.");
