// Generated by tools/arauna/build_species.py from the approved Arauna dex.
// Edit the CSVs under docs/arauna/ and rerun rather than editing this file.

const u8 gDummyPokedexText[] = _(
    "This is a newly discovered POKéMON.\n"
    "It is currently under investigation.\n"
    "No detailed information is available\n"
    "at this time.");

const u8 gCaramelo001PokedexText[] = _(
    "A stray pup the colour of caramel. Once it\n"
    "trusts its trainer, the tip of its tail\n"
    "lights a small steady flame that never burns\n"
    "a friendly hand."
);

const u8 gCaramelao002PokedexText[] = _(
    "Guardian of the open-air markets. Embers\n"
    "speckle its back, and it keeps them like\n"
    "fleas that bite only thieves."
);

const u8 gDraguara003PokedexText[] = _(
    "Legend says every stray that saved a life\n"
    "comes back as a Draguará. Its turquoise fire\n"
    "warms but never harms the innocent."
);

const u8 gQuero004PokedexText[] = _(
    "It never sleeps all the way. One eye stays\n"
    "open over the nest, and its quero-quero cry\n"
    "carries for kilometres."
);

const u8 gQueribela005PokedexText[] = _(
    "After its first moult the feathers become\n"
    "iridescent dragonfly membranes. It hovers\n"
    "over water and hunts with surgical aim."
);

const u8 gTerolibra006PokedexText[] = _(
    "Four dragonfly wings carry a lean adult\n"
    "body. One wingbeat throws a jet of water\n"
    "strong enough to split a trunk."
);

const u8 gPimpau007PokedexText[] = _(
    "It drills bark for grubs with a beak still\n"
    "soft. It drills dry stumps all day and goes\n"
    "home with a headache."
);

const u8 gBicopau008PokedexText[] = _(
    "The beak hardens into ironwood. It drums\n"
    "trunks in complex rhythms other Bicopau read\n"
    "as messages."
);

const u8 gPetropico009PokedexText[] = _(
    "Its beak has calcified into a granite wedge.\n"
    "It carves caves out of rock faces with blows\n"
    "that ring like bells."
);

const u8 gFormilim010PokedexText[] = _(
    "Not one ant: a whole colony walking in the\n"
    "shape of a giant one. It scatters when\n"
    "threatened."
);

const u8 gSauvarco011PokedexText[] = _(
    "Queen of the leafcutters. Her armies can\n"
    "strip a whole tree bare in a single night."
);

const u8 gCapivim012PokedexText[] = _(
    "It lives in riverside troops and lets\n"
    "anything ride on its back, tired trainers\n"
    "included."
);

const u8 gTucanhao013PokedexText[] = _(
    "Its huge beak is hollow and light. It\n"
    "swallows a fruit whole and spits the seed 40\n"
    "metres, planting forests alone."
);

const u8 gSaguim014PokedexText[] = _(
    "It steals anything that shines. Trainers\n"
    "learn early to keep their badges at the\n"
    "bottom of the bag."
);

const u8 gMicuiras015PokedexText[] = _(
    "Elder of the Sagüim troop. It reads the\n"
    "future in river reflections and calls rain a\n"
    "week ahead."
);

const u8 gBoitata016PokedexText[] = _(
    "It appears after a burn. Its body is a snake\n"
    "of blue fire that devours whoever sets the\n"
    "forest alight."
);

const u8 gCurupim017PokedexText[] = _(
    "Its feet point backwards. Hunters follow its\n"
    "tracks deeper into the woods instead of out."
);

const u8 gCurupira018PokedexText[] = _(
    "The true lord of the forest. Where it\n"
    "treads, a hundred-year tree rises in one\n"
    "night."
);

const u8 gIaraco019PokedexText[] = _(
    "It charms fishermen with a song. Whoever\n"
    "follows her into the river joins her court\n"
    "forever."
);

const u8 gSacizinho020PokedexText[] = _(
    "It has only one leg. It travels in\n"
    "whirlwinds and loves to pester careless\n"
    "trainers, dousing fires and freeing caught\n"
    "Pokémon."
);

const u8 gCactula021PokedexText[] = _(
    "It survives months without rain. Its spines\n"
    "hold drops of sweet venom that draw in Bug\n"
    "Pokémon."
);

const u8 gMuricoco022PokedexText[] = _(
    "Whole swarms follow trainers for days. The\n"
    "only escape is a river, and hoping no\n"
    "Terolibra lives in it."
);

const u8 gOncaleu023PokedexText[] = _(
    "The jaguar of the region. It hunts in total\n"
    "silence, and trainers notice only once they\n"
    "are on the ground."
);

const u8 gTamandua024PokedexText[] = _(
    "Its claws cut steel. It eats whole Formilim\n"
    "in one lick, but avoids Saúvarco: it lost\n"
    "its tongue once."
);

const u8 gBotim025PokedexText[] = _(
    "Born grey, it turns pink as its confidence\n"
    "grows. It plays with bubbles it blows\n"
    "itself."
);

const u8 gBotao026PokedexText[] = _(
    "It comes out at night in groups. Folklore\n"
    "says it turns into a young man at riverside\n"
    "parties."
);

const u8 gBotogalau027PokedexText[] = _(
    "A white hat hides the hole in the top of its\n"
    "head. It charms girls and vanishes into the\n"
    "river at dawn."
);

const u8 gTatuim028PokedexText[] = _(
    "It curls into a ball the size of an orange\n"
    "and rolls downhill to escape."
);

const u8 gTatubola029PokedexText[] = _(
    "Its shell turns to steel when threatened,\n"
    "bouncing physical attacks straight back."
);

const u8 gTatucu030PokedexText[] = _(
    "It digs twenty metres of tunnel a night.\n"
    "Whole villages have sunk into its galleries."
);

const u8 gArarinha031PokedexText[] = _(
    "It mimics any sound it hears, including\n"
    "trainers yelling as they fall down the bank."
);

const u8 gArara032PokedexText[] = _(
    "Its red feathers throw sparks when it beats\n"
    "its wings hard."
);

const u8 gAraracanga033PokedexText[] = _(
    "It flies among the clouds of the cerrado.\n"
    "The feathers it drops set the dry grass\n"
    "alight."
);

const u8 gJacarim034PokedexText[] = _(
    "It floats with only its eyes above water,\n"
    "and passes for a drifting log."
);

const u8 gJacarao035PokedexText[] = _(
    "It waits still for hours. When it strikes,\n"
    "it drags its prey under in a single roll."
);

const u8 gJacarodon036PokedexText[] = _(
    "A direct descendant of the dinosaurs. Its\n"
    "jaws crack a Tatuçu's shell."
);

const u8 gPreguicim037PokedexText[] = _(
    "It moves so slowly that moss grows in its\n"
    "fur. Insects live there."
);

const u8 gPreguicao038PokedexText[] = _(
    "It sleeps twenty hours a day. In its dreams\n"
    "it sees rain weeks ahead."
);

const u8 gBichoPreguica039PokedexText[] = _(
    "The size of an elephant. It walks once a\n"
    "moon and knows where every old tree will\n"
    "rise."
);

const u8 gPapaguim040PokedexText[] = _(
    "It learns to repeat words in three days. It\n"
    "learns swearing in an afternoon."
);

const u8 gPapagaio041PokedexText[] = _(
    "It memorises whole conversations and repeats\n"
    "them to the wrong people. It causes trouble."
);

const u8 gPapagaiao042PokedexText[] = _(
    "It lives 200 years, holding the secrets of\n"
    "generations of trainers in its memory."
);

const u8 gAntinha043PokedexText[] = _(
    "Striped like a small boar. Its short snout\n"
    "smells fruit a hundred metres off."
);

const u8 gAnta044PokedexText[] = _(
    "It crosses whole rivers underwater and eats\n"
    "forty kilos of leaves a day."
);

const u8 gAntarau045PokedexText[] = _(
    "A spirit of the forest. It guides lost\n"
    "trainers back to the edge of the trees."
);

const u8 gSucurim046PokedexText[] = _(
    "It is already two metres long at birth. It\n"
    "coils in branches and waits for prey."
);

const u8 gSucuri047PokedexText[] = _(
    "It smothers its prey and swallows it whole.\n"
    "Years of river legend turn it into Boiuna."
);

const u8 gBoiuna048PokedexText[] = _(
    "The Cobra-Grande of Amazon myth. Its eyes\n"
    "shine like boat lamps on the creek at night,\n"
    "and legend says its passing carves new\n"
    "rivers."
);

const u8 gBorbolim049PokedexText[] = _(
    "It eats nettle leaves without being\n"
    "poisoned, and stores the venom in its skin."
);

const u8 gCasulete050PokedexText[] = _(
    "An iridescent cocoon that mirrors the blue\n"
    "sky. It cannot move, but it shocks anything\n"
    "that touches it."
);

const u8 gMorphalia051PokedexText[] = _(
    "Wings the size of human hands. Its blue\n"
    "scales become healing magic dust."
);

const u8 gGuaracim052PokedexText[] = _(
    "Its legs are far too long. It gallops across\n"
    "the cerrado after fruit."
);

const u8 gGuara053PokedexText[] = _(
    "It howls at dusk. It eats the sweet lobeira\n"
    "fruit and plants the forest with its\n"
    "droppings."
);

const u8 gGuaraflama054PokedexText[] = _(
    "It appears on new moon nights. Its paws\n"
    "leave footprints of live coals."
);

const u8 gPeixim055PokedexText[] = _(
    "It swims slowly, nursing from its mother,\n"
    "and cries like a baby when it gets lost."
);

const u8 gPeixeboi056PokedexText[] = _(
    "A peaceable herbivore. It eats fifty kilos\n"
    "of water plants a day."
);

const u8 gMaeDAgua057PokedexText[] = _(
    "Protector of the rivers. Folklore says she\n"
    "nursed lost children."
);

const u8 gMandim058PokedexText[] = _(
    "Its whiskers find food in the mud below. It\n"
    "is nearly blind."
);

const u8 gMandi059PokedexText[] = _(
    "Venomous spines in its fins. One sting costs\n"
    "days of sleep."
);

const u8 gMandube060PokedexText[] = _(
    "The size of a man. It swims in the total\n"
    "dark of the river bottom."
);

const u8 gPreguim061PokedexText[] = _(
    "It uses sticks as tools while still young,\n"
    "and robs camps of food."
);

const u8 gPrego062PokedexText[] = _(
    "It cracks nuts with stones, and has taught\n"
    "the technique to its young for generations."
);

const u8 gPregarcanjo063PokedexText[] = _(
    "Held to be the cleverest primate in Arauana.\n"
    "It solves human riddles."
);

const u8 gAranin064PokedexText[] = _(
    "It spins webs in dry branches and eats small\n"
    "Formilim."
);

const u8 gCaraninha065PokedexText[] = _(
    "Its stinging hairs raise an unbearable itch\n"
    "on contact."
);

const u8 gCaranga066PokedexText[] = _(
    "The size of a dinner plate. Its fangs go\n"
    "through leather gloves."
);

const u8 gGatim067PokedexText[] = _(
    "It meows like a house cat, but lets nobody\n"
    "close."
);

const u8 gGatoDoMato068PokedexText[] = _(
    "It hunts birds at midnight. Its pupils flash\n"
    "green in torchlight."
);

const u8 gJaguatirica069PokedexText[] = _(
    "Rosette spots, like a jaguar in miniature.\n"
    "It climbs trees after monkeys."
);

const u8 gCutim070PokedexText[] = _(
    "It buries nuts and forgets where. It plants\n"
    "the forest by accident."
);

const u8 gCutia071PokedexText[] = _(
    "It gnaws anything. Its teeth grow for its\n"
    "whole life."
);

const u8 gPaca072PokedexText[] = _(
    "It comes out only at night, running and\n"
    "whistling through the dark woods."
);

const u8 gFormigao073PokedexText[] = _(
    "Its bite hurts like a full day of cramp.\n"
    "Locals call it the bullet ant."
);

const u8 gMarimbondo074PokedexText[] = _(
    "An aggressive swarm. It chases a threat for\n"
    "kilometres."
);

const u8 gAbelhinha075PokedexText[] = _(
    "It has no sting. Its sweet honey is used to\n"
    "revive hurt Pokémon."
);

const u8 gQuatim076PokedexText[] = _(
    "Bands of fifteen walk the trails, going\n"
    "through packs after biscuits."
);

const u8 gQuati077PokedexText[] = _(
    "It has learned to open tent zips, and steals\n"
    "anything that shines."
);

const u8 gCoati078PokedexText[] = _(
    "It lives in dark caves. Its very long snout\n"
    "is made for hunting bats."
);

const u8 gGamba079PokedexText[] = _(
    "It lets out a sickening smell when\n"
    "threatened. Trainers flee before it does."
);

const u8 gCangamba080PokedexText[] = _(
    "Its stink jet reaches three metres and lasts\n"
    "weeks in your clothes."
);

const u8 gSarue081PokedexText[] = _(
    "It plays dead for hours when threatened. It\n"
    "has even fooled Onçaléu."
);

const u8 gTuquinho082PokedexText[] = _(
    "Its bright bill calls females from far off.\n"
    "It eats wild fruit."
);

const u8 gAracari083PokedexText[] = _(
    "It flies in sixes. All of them eat from the\n"
    "same fruit at once."
);

const u8 gCuricaca084PokedexText[] = _(
    "A shrill cry at daybreak. Every farm in\n"
    "Arauana hates this Pokémon."
);

const u8 gSapim085PokedexText[] = _(
    "It swims in shoals, and becomes Sapao once\n"
    "its legs come in."
);

const u8 gSapao086PokedexText[] = _(
    "Glands behind its eyes weep white poison.\n"
    "Never lick a Sapao."
);

const u8 gCururu087PokedexText[] = _(
    "The size of a football. It eats Muriçoco by\n"
    "the thousand."
);

const u8 gTeiuzim088PokedexText[] = _(
    "It runs on two legs when startled. Its tail\n"
    "detaches to throw off predators."
);

const u8 gTeiu089PokedexText[] = _(
    "It eats everything: fruit, eggs, small\n"
    "animals, even venomous snakes."
);

const u8 gCamaleao090PokedexText[] = _(
    "It changes colour to match its surroundings,\n"
    "and its mood by the second."
);

const u8 gMorcim091PokedexText[] = _(
    "It sleeps upside down, gripping the roof of\n"
    "the cave."
);

const u8 gMorcego092PokedexText[] = _(
    "It sees with sound, flying in absolute dark\n"
    "without touching anything."
);

const u8 gVampiro093PokedexText[] = _(
    "It drinks the blood of sleeping mammals.\n"
    "Long company leaves its owner anaemic."
);

const u8 gPiuiuim094PokedexText[] = _(
    "It stands on one leg most of the time, and\n"
    "topples if a hard wind catches it."
);

const u8 gTuiuiu095PokedexText[] = _(
    "The bird of the Pantanal. Its huge bill\n"
    "takes a fish in one stab."
);

const u8 gColhereiro096PokedexText[] = _(
    "Pink from eating shellfish. Its bill is\n"
    "shaped like a spoon."
);

const u8 gMulinha097PokedexText[] = _(
    "An innocent foal. Nothing about it hints at\n"
    "what it becomes."
);

const u8 gMula098PokedexText[] = _(
    "It rides faster than a horse. Its bray is\n"
    "terrifying."
);

const u8 gMulaSemCabeca099PokedexText[] = _(
    "Fire pours from its neck where the head\n"
    "should be. It comes on Fridays."
);

const u8 gCorcovado100PokedexText[] = _(
    "The spirit of an entire mountain. Its back\n"
    "is covered in forest, and it breathes."
);

const u8 gCervalo101PokedexText[] = _(
    "Its pointed horns are still coming in. It\n"
    "clears bushes easily."
);

const u8 gCatingueiro102PokedexText[] = _(
    "Its horns branch with age. It eats cactus\n"
    "without hurting itself."
);

const u8 gSucuapara103PokedexText[] = _(
    "Horns so wide it has to raise its head to\n"
    "get through the woods."
);

const u8 gCabocim104PokedexText[] = _(
    "A water spirit in human shape. It swims like\n"
    "a fish."
);

const u8 gCaboclo105PokedexText[] = _(
    "It drags canoes under when fishermen\n"
    "disrespect the river."
);

const u8 gCangaco106PokedexText[] = _(
    "A bird that robs the rich and gives to the\n"
    "poor, so the backlanders say."
);

const u8 gXango107PokedexText[] = _(
    "Master of lightning and thunder. Its\n"
    "twin-headed axe throws sparks when it\n"
    "strikes."
);

const u8 gIemanja108PokedexText[] = _(
    "Goddess of the oceans. Her daughters, the\n"
    "fish, follow her in procession."
);

const u8 gOxum109PokedexText[] = _(
    "Queen of fresh water. Her hair of wet gold\n"
    "runs and never dries."
);

const u8 gOgum110PokedexText[] = _(
    "The divine blacksmith. He forged blades that\n"
    "cut the souls of wrongdoers."
);

const u8 gCavalim111PokedexText[] = _(
    "Its long mane streams in the wind. It learns\n"
    "to gallop in a week."
);

const u8 gCavalgado112PokedexText[] = _(
    "It runs at sixty an hour for hours. The\n"
    "gauchos of Arauana tamed it."
);

const u8 gZebuim113PokedexText[] = _(
    "Its huge hump already shows in the foal. It\n"
    "is still unsure on its feet."
);

const u8 gZebu114PokedexText[] = _(
    "A giant hump. It takes the worst heat of the\n"
    "cerrado without tiring."
);

const u8 gOvelhinha115PokedexText[] = _(
    "Thick wool against the highland cold.\n"
    "Utterly gentle."
);

const u8 gCabrita116PokedexText[] = _(
    "It climbs impossible slopes and eats dry\n"
    "branches."
);

const u8 gChocalhao117PokedexText[] = _(
    "The rattle on its tail is still small. It is\n"
    "learning to play it."
);

const u8 gCascavelim118PokedexText[] = _(
    "Its neurotoxin is fully active. The rattle\n"
    "warns predators off."
);

const u8 gCascavao119PokedexText[] = _(
    "One bite paralyses even Onçaléu. Its rattle\n"
    "carries a hundred metres."
);

const u8 gJararaca120PokedexText[] = _(
    "It hides among fallen leaves. It gives no\n"
    "warning before it bites."
);

const u8 gPirarim121PokedexText[] = _(
    "Thirty centimetres at birth. It grows a\n"
    "metre a year in a well-fed river."
);

const u8 gPirarucu122PokedexText[] = _(
    "Up to three metres long. It breathes surface\n"
    "air like a mammal."
);

const u8 gPiranha123PokedexText[] = _(
    "It attacks in shoals. They strip a cow in\n"
    "minutes."
);

const u8 gTambaqui124PokedexText[] = _(
    "It eats fruit falling into the flooded\n"
    "forest. Its teeth grind the seeds."
);

const u8 gAruana125PokedexText[] = _(
    "It leaps two metres clear of the water to\n"
    "take insects off branches."
);

const u8 gPoraque126PokedexText[] = _(
    "It puts out a six hundred volt shock,\n"
    "paralysing anything touching the water."
);

const u8 gCurimbata127PokedexText[] = _(
    "It swims in enormous shoals, running upriver\n"
    "at spawning time."
);

const u8 gTraira128PokedexText[] = _(
    "It waits still among sunken leaves. Its\n"
    "sharp teeth lock onto prey."
);

const u8 gDourado129PokedexText[] = _(
    "It leaps up waterfalls. Its golden scales\n"
    "shine like coins."
);

const u8 gTucunare130PokedexText[] = _(
    "The eyespot on its tail scares predators\n"
    "off. It attacks anything entering its water."
);

const u8 gPacu131PokedexText[] = _(
    "Human-looking teeth grinding nuts. Swimmers\n"
    "mistake it for one of their own."
);

const u8 gMatrinxa132PokedexText[] = _(
    "Dark shoals slip through the rapids. A\n"
    "favourite of sport anglers."
);

const u8 gPiau133PokedexText[] = _(
    "Gold stripes down its flanks. It eats\n"
    "whatever falls in the water."
);

const u8 gCascudo134PokedexText[] = _(
    "Hard plates cover its body. It scrapes the\n"
    "algae off aquarium glass."
);

const u8 gAcara135PokedexText[] = _(
    "A bright disc of a fish. It raises its young\n"
    "on the mucus of its own skin."
);

const u8 gVagalumim136PokedexText[] = _(
    "Its tail lights only when it is frightened,\n"
    "showing the way through the woods."
);

const u8 gVagalume137PokedexText[] = _(
    "It blinks in code to draw females, lighting\n"
    "five metres around it."
);

const u8 gCigarrinho138PokedexText[] = _(
    "It lives seven years underground before it\n"
    "becomes Cigarrao."
);

const u8 gCigarrao139PokedexText[] = _(
    "A hundred-decibel song. The sign of summer\n"
    "in Arauana."
);

const u8 gLouvadinha140PokedexText[] = _(
    "Its scythes are small but already sharp. It\n"
    "eats ants."
);

const u8 gLouvadeus141PokedexText[] = _(
    "It prays before beheading its prey. The\n"
    "female eats the male after mating."
);

const u8 gEscorpim142PokedexText[] = _(
    "A see-through sting in its tail. One jab\n"
    "costs a night's sleep."
);

const u8 gEscorpiao143PokedexText[] = _(
    "Its claws crush beetles. Its sting can\n"
    "paralyse even a Cavalgado."
);

const u8 gCaramulao144PokedexText[] = _(
    "A spiral shell with a folk pattern on it. It\n"
    "eats lettuce along the banks."
);

const u8 gPiolhao145PokedexText[] = _(
    "It curls into a ball when threatened, giving\n"
    "off a smell of bitter almond."
);

const u8 gBarata146PokedexText[] = _(
    "It survives anything. Radiation, poison, a\n"
    "flip-flop."
);

const u8 gGrilim147PokedexText[] = _(
    "It leaps thirty times its own length, and\n"
    "plays music with its legs."
);

const u8 gGrilao148PokedexText[] = _(
    "It sings without pause all night. It\n"
    "announces rain."
);

const u8 gAranhao149PokedexText[] = _(
    "It raises its front legs before it strikes.\n"
    "Its neurotoxin is serious."
);

const u8 gVespao150PokedexText[] = _(
    "It hunts spiders the size of hands and drags\n"
    "them back to the nest."
);

const u8 gMarimbondao151PokedexText[] = _(
    "A sting that hurts for hours. It builds mud\n"
    "nests on rooftops."
);

const u8 gTraca152PokedexText[] = _(
    "It eats furniture from the inside. Nobody\n"
    "notices until it collapses."
);

const u8 gCorupiao153PokedexText[] = _(
    "She lives thirty years laying without pause.\n"
    "The mound grows around her."
);

const u8 gCupinzim154PokedexText[] = _(
    "Giant jaws guard the queen. It does not eat,\n"
    "only fight."
);

const u8 gFormigaoPreto155PokedexText[] = _(
    "It marches in single file for kilometres,\n"
    "devouring everything on the way."
);

const u8 gBeijaFlor156PokedexText[] = _(
    "Its wings beat eighty times a second. It\n"
    "flies backwards and upside down."
);

const u8 gSabia157PokedexText[] = _(
    "Its song is held the most beautiful in\n"
    "Brazil. It announces the spring."
);

const u8 gBemTeVi158PokedexText[] = _(
    "It shouts its own name, telling the whole\n"
    "yard what everyone did."
);

const u8 gUrutau159PokedexText[] = _(
    "It disguises itself as a dead branch. Its\n"
    "mournful night song frightens travellers."
);

const u8 gCarcara160PokedexText[] = _(
    "It eats snakes, rats and even small lambs.\n"
    "The emblem of the backlands."
);

const u8 gGaviao161PokedexText[] = _(
    "The largest bird of prey in the Americas. It\n"
    "takes monkeys and sloths."
);

const u8 gUrubu162PokedexText[] = _(
    "It eats any rotting meat, and keeps the\n"
    "fields clean."
);

const u8 gCorurupim163PokedexText[] = _(
    "Its eyes turn 270 degrees. It sees in total\n"
    "dark."
);

const u8 gCoruja164PokedexText[] = _(
    "It lives in burrows in the cerrado floor and\n"
    "flies in complete silence."
);

const u8 gJaburu165PokedexText[] = _(
    "It flies in flocks of hundreds, spearing\n"
    "fish with a bill like a sword."
);

const u8 gEma166PokedexText[] = _(
    "The largest bird in Brazil. It runs at sixty\n"
    "an hour to escape."
);

const u8 gSeriema167PokedexText[] = _(
    "It beats venomous snakes on the ground until\n"
    "they die, and only then eats."
);

const u8 gAnu168PokedexText[] = _(
    "It lives in noisy flocks, picking ticks off\n"
    "the backs of cattle."
);

const u8 gTrincaFerro169PokedexText[] = _(
    "A song so strong that trainers award prizes\n"
    "for its tone at contests."
);

const u8 gCurio170PokedexText[] = _(
    "An elaborate song full of trills. The most\n"
    "prized bird in singing contests."
);

const u8 gSanhaco171PokedexText[] = _(
    "A glittering blue that catches the sun. It\n"
    "eats fruit in back gardens."
);

const u8 gPapaFormiga172PokedexText[] = _(
    "It eats nothing but army ants, following the\n"
    "swarms for days."
);

const u8 gChoca173PokedexText[] = _(
    "It lives in the low shade, startling\n"
    "butterflies with a beat of its wings."
);

const u8 gBacurau174PokedexText[] = _(
    "It skims low after insects, its huge mouth\n"
    "opening in mid-air."
);

const u8 gJoaoDeBarro175PokedexText[] = _(
    "It builds a clay nest shaped like an oven,\n"
    "an emblem of country yards."
);

const u8 gSementim176PokedexText[] = _(
    "A jequitibá seed that learned to walk on two\n"
    "roots."
);

const u8 gMuda177PokedexText[] = _(
    "A sapling with little sun-catching leaves.\n"
    "The rain waters it for free."
);

const u8 gJequitiba178PokedexText[] = _(
    "A hundred-year tree that walks. It stands\n"
    "still far more than it moves."
);

const u8 gBromelinha179PokedexText[] = _(
    "A natural cup that gathers rainwater. Frogs\n"
    "live inside it."
);

const u8 gOrquidina180PokedexText[] = _(
    "Iridescent petals. Its scent draws\n"
    "pollinators from kilometres away."
);

const u8 gVitoriaregia181PokedexText[] = _(
    "A leaf the size of a double bed. It holds a\n"
    "standing child."
);

const u8 gIpe182PokedexText[] = _(
    "It drops its leaves and flowers yellow in\n"
    "the dry winter."
);

const u8 gCipo183PokedexText[] = _(
    "It winds around trees and strangles them. So\n"
    "long it can ring a hill."
);

const u8 gPalmito184PokedexText[] = _(
    "Its palm heart is a prized delicacy, so it\n"
    "defends itself with a spined trunk."
);

const u8 gBabacu185PokedexText[] = _(
    "A coconut of terrible hardness. Only\n"
    "Petropico can crack it."
);

const u8 gBuriti186PokedexText[] = _(
    "It grows where fresh water hides, marking\n"
    "oases in the cerrado."
);

const u8 gCajuzim187PokedexText[] = _(
    "A fruit that walks. The nut on its head bobs\n"
    "like a quiff."
);

const u8 gCajueiro188PokedexText[] = _(
    "It roasts its own nut in the caatinga sun.\n"
    "The smell is intoxicating."
);

const u8 gAcai189PokedexText[] = _(
    "A dark purple cluster on top. Natural fuel\n"
    "for Fighting Pokémon."
);

const u8 gCacauim190PokedexText[] = _(
    "A yellow fruit with sweet seeds. Fermenting\n"
    "turns it into Chocolat."
);

const u8 gCacaueiro191PokedexText[] = _(
    "Purple pods when ripe. The origin of Arauana\n"
    "chocolate."
);

const u8 gGuarana192PokedexText[] = _(
    "A seed so black it looks like an eye. Pure\n"
    "natural energy."
);

const u8 gMate193PokedexText[] = _(
    "Its bitter leaves make chimarrao, companion\n"
    "of the Arauana gauchos."
);

const u8 gMilho194PokedexText[] = _(
    "Ears in yellow, red and purple. The food of\n"
    "the villages."
);

const u8 gMandioca195PokedexText[] = _(
    "A long root shaped like a leg. It buries\n"
    "itself to sleep."
);

const u8 gPedrinha196PokedexText[] = _(
    "A stone rolled for millennia. Perfectly\n"
    "smooth."
);

const u8 gRochao197PokedexText[] = _(
    "A walking rock that rumbles as it rolls,\n"
    "shaking the ground."
);

const u8 gCristalim198PokedexText[] = _(
    "A clear crystal. It grows a centimetre a\n"
    "year in damp caves."
);

const u8 gAmetista199PokedexText[] = _(
    "A bright purple geode. It breaks the sun\n"
    "into rainbows."
);

const u8 gOurico200PokedexText[] = _(
    "A walking nugget. Bandits chase it across\n"
    "the whole of Arauana."
);

const u8 gFerrolho201PokedexText[] = _(
    "A rock of terrible weight. It only stands if\n"
    "it puts down roots."
);

const u8 gDiamantina202PokedexText[] = _(
    "A gem of the highest order. It throws\n"
    "rainbows in any light."
);

const u8 gBauxito203PokedexText[] = _(
    "Terracotta coloured. It flakes away in metal\n"
    "sheets."
);

const u8 gManganim204PokedexText[] = _(
    "A shining black. It swallows the light\n"
    "around it."
);

const u8 gSalitre205PokedexText[] = _(
    "It crystallises by itself in salt flats.\n"
    "Sweet and bitter at once."
);

const u8 gEnxofrino206PokedexText[] = _(
    "It smells of rotten egg. It grows in\n"
    "volcanic vents."
);

const u8 gArgilim207PokedexText[] = _(
    "It moulds into any shape, and becomes Boneco\n"
    "when a child plays with it."
);

const u8 gBoneco208PokedexText[] = _(
    "Clay brought to life by a child's game. It\n"
    "keeps the memories fondly."
);

const u8 gEstalactite209PokedexText[] = _(
    "It grows a drop a century, and takes offence\n"
    "at being called a stalagmite."
);

const u8 gEstalagmite210PokedexText[] = _(
    "It grows pointing upward, and does not care\n"
    "for stalactites."
);

const u8 gFossil211PokedexText[] = _(
    "A dinosaur bone that started walking again.\n"
    "Nobody knows how."
);

const u8 gMeteorito212PokedexText[] = _(
    "It fell out of the sky millennia ago, and is\n"
    "still warm to the touch."
);

const u8 gVulcanite213PokedexText[] = _(
    "Formed in an ancient eruption. It holds its\n"
    "heat for centuries."
);

const u8 gMarmim214PokedexText[] = _(
    "A classical sculpture brought to life by\n"
    "magic. Utterly elegant."
);

const u8 gGranito215PokedexText[] = _(
    "Its natural cracks make the shapes of angry\n"
    "faces."
);

const u8 gCaranguim216PokedexText[] = _(
    "A hopping baby crab. Its claw already nips\n"
    "fingers."
);

const u8 gGuaiamum217PokedexText[] = _(
    "It lives in mangrove burrows and comes out\n"
    "at night in groups."
);

const u8 gSiri218PokedexText[] = _(
    "It swims sideways. Its claws are a brilliant\n"
    "blue."
);

const u8 gCamarao219PokedexText[] = _(
    "It swims in pink shoals. Delicious grilled,\n"
    "so the tourists say."
);

const u8 gPolvim220PokedexText[] = _(
    "It changes colour to match the sea floor,\n"
    "and squirts ink."
);

const u8 gPolvao221PokedexText[] = _(
    "Eight arms that solve puzzles. It opens jars\n"
    "with lids."
);

const u8 gAguaviva222PokedexText[] = _(
    "Stinging tentacles metres long. It drifts\n"
    "with the current."
);

const u8 gCavalimMarinho223PokedexText[] = _(
    "The male carries and raises the young. It\n"
    "swims upright."
);

const u8 gTartaruguim224PokedexText[] = _(
    "It hatches on the beach and runs for the sea\n"
    "on instinct. Terribly fragile."
);

const u8 gTartaruga225PokedexText[] = _(
    "It lives a hundred years, returning to lay\n"
    "on the beach where it hatched."
);

const u8 gGolfinho226PokedexText[] = _(
    "It leaps in pirouettes and talks in high\n"
    "clicks."
);

const u8 gBaleia227PokedexText[] = _(
    "It sings songs that cross oceans, and\n"
    "migrates with the seasons."
);

const u8 gTubarim228PokedexText[] = _(
    "It is born already swimming and hunting. It\n"
    "has no childhood."
);

const u8 gTubarao229PokedexText[] = _(
    "King of the sea. Its serrated teeth grow\n"
    "back forever."
);

const u8 gArraia230PokedexText[] = _(
    "It hides on the bottom. Its shock paralyses\n"
    "careless bathers."
);

const u8 gPeixeEspada231PokedexText[] = _(
    "A bill shaped like a sword. It runs through\n"
    "the hulls of boats."
);

const u8 gPargo232PokedexText[] = _(
    "Red scales flashing in the sun. Huge shoals\n"
    "over the reefs."
);

const u8 gPescadao233PokedexText[] = _(
    "A lit lure on its antenna fools smaller\n"
    "fish."
);

const u8 gLoirinha234PokedexText[] = _(
    "It appears in school mirrors at night,\n"
    "calling its own name."
);

const u8 gCuca235PokedexText[] = _(
    "It takes children who will not sleep. It is\n"
    "not always real."
);

const u8 gBichoPapao236PokedexText[] = _(
    "It lives under beds, and frightens only\n"
    "disobedient children."
);

const u8 gLobisomem237PokedexText[] = _(
    "The seventh son under a full moon. Its howl\n"
    "sends dogs running."
);

const u8 gCorpoSeco238PokedexText[] = _(
    "A soul so bad the earth will not have it. It\n"
    "wanders forever."
);

const u8 gMaoPeluda239PokedexText[] = _(
    "A giant hairy hand comes out from under the\n"
    "bed and takes your feet."
);

const u8 gPernaCabeluda240PokedexText[] = _(
    "A hairy leg walks alone at night, following\n"
    "anyone out on their own."
);

const u8 gComadre241PokedexText[] = _(
    "The spirit of a woman who died in\n"
    "childbirth. She takes babies."
);

const u8 gAnhanga242PokedexText[] = _(
    "Protector of animals. It curses hunters who\n"
    "take more than their share."
);

const u8 gJurupari243PokedexText[] = _(
    "The Tupi god of night. Only men may see his\n"
    "face."
);

const u8 gTupa244PokedexText[] = _(
    "The supreme Tupi-Guarani god. He looses\n"
    "lightning with a blink."
);

const u8 gJaci245PokedexText[] = _(
    "Goddess of the moon. Her silver hair shines\n"
    "on full-moon nights."
);

const u8 gGuaraci246PokedexText[] = _(
    "God of the sun. His golden crown lights the\n"
    "whole of Arauana."
);

const u8 gRuda247PokedexText[] = _(
    "God of love. His flower arrow brings two\n"
    "hearts together."
);

const u8 gAlua248PokedexText[] = _(
    "Spirit of fermented drink. It brightens the\n"
    "feasts of the healers."
);

const u8 gJenipapo249PokedexText[] = _(
    "Black paint that lasts weeks on the skin. It\n"
    "draws patterns of blessing."
);

const u8 gUrucum250PokedexText[] = _(
    "An ancestral red paint. It keeps insects\n"
    "away."
);

const u8 gCaipora251PokedexText[] = _(
    "It rides a wild boar. It guards the game and\n"
    "hunts down greedy hunters."
);

const u8 gAnhangaPita252PokedexText[] = _(
    "The red form Anhangá takes when it is\n"
    "enraged."
);

const u8 gYaraPinda253PokedexText[] = _(
    "Yara as a fisherwoman. She teaches the young\n"
    "to respect the river."
);

const u8 gPisadeira254PokedexText[] = _(
    "It stands on the chest of anyone who sleeps\n"
    "on a full stomach. Paralysis."
);

const u8 gZumbi255PokedexText[] = _(
    "The spirit that led a quilombo. It puts\n"
    "courage in whoever fights to be free."
);

const u8 gIemanjaPequena256PokedexText[] = _(
    "The young form of the goddess Iemanjá. She\n"
    "rules the smaller tides."
);

const u8 gOssanha257PokedexText[] = _(
    "It commands the power of healing leaves, and\n"
    "cures poisoned Pokémon."
);

const u8 gOxala258PokedexText[] = _(
    "The creator spirit. Dressed in white, it\n"
    "blesses whoever comes near."
);

const u8 gSaciamigo259PokedexText[] = _(
    "A young Saci. It has not mastered the\n"
    "whirlwinds yet."
);

const u8 gSaciperere260PokedexText[] = _(
    "Red cap, pipe, one leg. Loose through the\n"
    "whole of folklore."
);

const u8 gCurupiraAnciao261PokedexText[] = _(
    "A long-haired elder Curupira. It knows where\n"
    "every ancient tree grows."
);

const u8 gCaiporaFemea262PokedexText[] = _(
    "The female form of Caipora, and harder still\n"
    "on greedy hunters."
);

const u8 gPombaGira263PokedexText[] = _(
    "A seductive female spirit. She laughs loudly\n"
    "at the crossroads."
);

const u8 gExu264PokedexText[] = _(
    "Guardian of the crossroads. Nothing passes\n"
    "without his leave."
);

const u8 gPretoVelho265PokedexText[] = _(
    "An ancestral spirit. It smokes a pipe and\n"
    "gives thousand-year-old advice."
);

const u8 gCabocloGuerreiro266PokedexText[] = _(
    "A spectral indigenous warrior in a headdress\n"
    "of bright feathers."
);

const u8 gMarinheiro267PokedexText[] = _(
    "The spirit of a drowned sailor. It tells\n"
    "stories of storms."
);

const u8 gBaiano268PokedexText[] = _(
    "A festive spirit. It plays the berimbau\n"
    "without stopping."
);

const u8 gCangaceiro269PokedexText[] = _(
    "The spirit of Lampiao, in a studded leather\n"
    "hat."
);

const u8 gBeata270PokedexText[] = _(
    "The spirit of Padre Cicero. It blesses with\n"
    "a rosary of cactus beads."
);

const u8 gMeninoDeus271PokedexText[] = _(
    "The spirit of an innocent child. It appears\n"
    "in the Kings' revels."
);

const u8 gReiMomo272PokedexText[] = _(
    "King of carnival, on a throne of glitter."
);

const u8 gBumbaMeuBoi273PokedexText[] = _(
    "The spirit of the festival ox. It rises\n"
    "again at every performance."
);

const u8 gReisado274PokedexText[] = _(
    "A spirit of the Kings' revel. Its accordion\n"
    "plays by itself."
);

const u8 gFrevinho275PokedexText[] = _(
    "The spirit of the Pernambuco frevo. It\n"
    "dances acrobatically without pause."
);

const u8 gMaracatu276PokedexText[] = _(
    "A spectral royal procession, in a gold crown\n"
    "and embroidered robes."
);

const u8 gCongada277PokedexText[] = _(
    "A warrior spirit in procession. Its staves\n"
    "beat in rhythm."
);

const u8 gFoliao278PokedexText[] = _(
    "A spirit that goes from feast to feast. It\n"
    "never tires of dancing."
);

const u8 gOncuma279PokedexText[] = _(
    "The legendary black jaguar. Goddess of the\n"
    "night forests."
);

const u8 gSucuriacu280PokedexText[] = _(
    "A ten-metre anaconda. It swallows capybaras\n"
    "whole."
);

const u8 gPirarumba281PokedexText[] = _(
    "The king pirarucu. Five metres, with scales\n"
    "like armour."
);

const u8 gDraguaraAlfa282PokedexText[] = _(
    "The alpha Draguará of the legendary pack.\n"
    "Its fire burns green-turquoise."
);

const u8 gTerolibraRainha283PokedexText[] = _(
    "The enormous Terolibra queen. She commands\n"
    "the swarms."
);

const u8 gPetropicoAnciao284PokedexText[] = _(
    "A hundred-year-old Petropico. Its beak\n"
    "carved whole plateaus."
);

const u8 gBoitataPuro285PokedexText[] = _(
    "The first Boitatá. Blue fire that devours\n"
    "entire woods."
);

const u8 gIaraMae286PokedexText[] = _(
    "Iara, mother of them all. Her song is heard\n"
    "once in a lifetime."
);

const u8 gCurupiraRei287PokedexText[] = _(
    "The Curupira king of the forest. His hair is\n"
    "fire the colour of urucum."
);

const u8 gSaciRei288PokedexText[] = _(
    "The ancestral Saci-Pererê, in the legendary\n"
    "red cap."
);

const u8 gAnhangau289PokedexText[] = _(
    "The supreme Anhangá. White deer walk behind\n"
    "it."
);

const u8 gMuiraKyta290PokedexText[] = _(
    "An Amazonian love turned into a tree."
);

const u8 gCobraNorato291PokedexText[] = _(
    "The snake-man. Boiuna takes human shape at\n"
    "the feasts."
);

const u8 gMapinguari292PokedexText[] = _(
    "The primordial giant sloth. A mouth in its\n"
    "chest, and the smell of death."
);

const u8 gIpupiara293PokedexText[] = _(
    "A cannibal fish-man. The terror of the old\n"
    "fishermen."
);

const u8 gUirapuru294PokedexText[] = _(
    "A legendary bird. The whole forest falls\n"
    "silent when it sings."
);

const u8 gMuiraquita295PokedexText[] = _(
    "The jade-green amulet of the Icamiabas. It\n"
    "brings luck in battle."
);

const u8 gAmazona296PokedexText[] = _(
    "A warrior without her left breast, the\n"
    "better to draw a bow. Queen of a legendary\n"
    "tribe."
);

const u8 gCorcovadoAnciao297PokedexText[] = _(
    "An ancient Corcovado. Its back is covered in\n"
    "old-growth forest."
);

const u8 gCristo298PokedexText[] = _(
    "A spirit with open hands. It blesses whoever\n"
    "sees the sun rise."
);

const u8 gRatao299PokedexText[] = _(
    "It lives in the sewers and eats anything at\n"
    "all."
);

const u8 gPombim300PokedexText[] = _(
    "It rips open rubbish bags. Its droppings\n"
    "ruin statues."
);

const u8 gPombao301PokedexText[] = _(
    "An enormous pigeon. It rules whole town\n"
    "squares."
);

const u8 gBaratao302PokedexText[] = _(
    "The flying cockroach of the apocalypse. It\n"
    "flies straight at screaming people."
);

const u8 gMosquim303PokedexText[] = _(
    "A streaked brown rat. It carries disease."
);

const u8 gCaoBravo304PokedexText[] = _(
    "The wild counterpart of Caramelo. It runs in\n"
    "packs and defends its ground."
);

const u8 gGatoPreto305PokedexText[] = _(
    "They say it is bad luck if it crosses your\n"
    "path. They say."
);

const u8 gPerereca306PokedexText[] = _(
    "It turns up in toilet bowls and jumps at the\n"
    "face of whoever sits down."
);

const u8 gLagartixa307PokedexText[] = _(
    "It eats mosquitoes. Its tail drops off and\n"
    "keeps moving."
);

const u8 gTracaPapel308PokedexText[] = _(
    "It eats old paper, taking in the knowledge\n"
    "of the books."
);

const u8 gPoeirao309PokedexText[] = _(
    "A walking ball of dust. It grows in shut\n"
    "rooms."
);

const u8 gFerrugem310PokedexText[] = _(
    "It eats metal from the inside. Bridges fall\n"
    "without warning."
);

const u8 gFumacento311PokedexText[] = _(
    "A cloud of bus exhaust. It darkens city\n"
    "skies."
);

const u8 gOleoso312PokedexText[] = _(
    "An oil slick given shape. It kills sea\n"
    "Pokémon."
);

const u8 gLixao313PokedexText[] = _(
    "A living heap of city rubbish. Rain turns it\n"
    "into Chorume."
);

const u8 gChorume314PokedexText[] = _(
    "The black liquid that seeps from the dump.\n"
    "It poisons all it touches."
);

const u8 gBituca315PokedexText[] = _(
    "Still burning when thrown away. It starts\n"
    "fires in the pastures."
);

const u8 gLatinha316PokedexText[] = _(
    "It roams looking for another Latinha to\n"
    "fight. It rewards whoever recycles."
);

const u8 gSacolim317PokedexText[] = _(
    "It rides the wind, and catches in trees for\n"
    "decades."
);

const u8 gGarrafao318PokedexText[] = _(
    "It drifts down the rivers all the way to the\n"
    "sea."
);

const u8 gNetzero319PokedexText[] = _(
    "A bird made of the plastic in its own\n"
    "stomach. The emblem of pollution."
);

const u8 gPilhoso320PokedexText[] = _(
    "It leaks a corrosive acid. It should not be\n"
    "handled."
);

const u8 gCabofio321PokedexText[] = _(
    "A tangle of live wires. A walking short\n"
    "circuit."
);

const u8 gBugao322PokedexText[] = _(
    "A giant city bug. It shows up in badly kept\n"
    "kitchens."
);

const u8 gAluminio323PokedexText[] = _(
    "Folded kitchen foil that flies like a kite."
);

const u8 gConcretim324PokedexText[] = _(
    "A piece of broken pavement. It trips people."
);

const u8 gBueiro325PokedexText[] = _(
    "The spirit of waste water. It rises in the\n"
    "floods."
);

const u8 gSinal326PokedexText[] = _(
    "A traffic light that changes for no reason,\n"
    "snarling up the junction."
);

const u8 gPoste327PokedexText[] = _(
    "A lamp post that walks, lighting the dark\n"
    "streets."
);

const u8 gGrafiteiro328PokedexText[] = _(
    "The spirit of street art. It changes shape\n"
    "with the drawing."
);

const u8 gGuaraciana329PokedexText[] = _(
    "Consort of Guaraci. It shines at daybreak."
);

const u8 gJaciana330PokedexText[] = _(
    "Consort of Jaci. It shines at midnight."
);

const u8 gTupanau331PokedexText[] = _(
    "Tupan in his first form. A single\n"
    "thunderclap levels hills."
);

const u8 gIarau332PokedexText[] = _(
    "Iara at her greatest. A whole river obeys\n"
    "her song."
);

const u8 gKuarahy333PokedexText[] = _(
    "The sun of the first days. It gave the\n"
    "continent life."
);

const u8 gYasy334PokedexText[] = _(
    "The moon of the first days. It rules tides\n"
    "and dreams."
);

const u8 gRudarauna335PokedexText[] = _(
    "Love in its first form. It binds the couples\n"
    "that were meant to be."
);

const u8 gPerybe336PokedexText[] = _(
    "The spirit of the whole Amazon basin. One\n"
    "body, a thousand tributaries."
);

const u8 gArauanau337PokedexText[] = _(
    "Supreme guardian of the region. It appears\n"
    "only when Arauana is in danger."
);

const u8 gVerdejante338PokedexText[] = _(
    "The spirit of the first Atlantic forest. It\n"
    "sprouts from the ash of burnings."
);

const u8 gChuvao339PokedexText[] = _(
    "The spirit of the December rain. It soaks\n"
    "Arauana in three days."
);

const u8 gSolzao340PokedexText[] = _(
    "The spirit of the drought. It burns the\n"
    "fields for months."
);

const u8 gVentania341PokedexText[] = _(
    "The south wind that brings the winter cold,\n"
    "whistling deadly tunes."
);

const u8 gTerraao342PokedexText[] = _(
    "Walking fertile earth. Where it steps, a\n"
    "crop comes up."
);

const u8 gFogareu343PokedexText[] = _(
    "The first fire, which warmed Arauana at the\n"
    "beginning."
);

const u8 gMarulho344PokedexText[] = _(
    "The spirit of the Atlantic. The waves keep\n"
    "his time."
);

const u8 gAlvorecer345PokedexText[] = _(
    "The spirit of daybreak. A rose and gold that\n"
    "fills the sky."
);

const u8 gPoente346PokedexText[] = _(
    "The spirit of sunset, and its burnt colours\n"
    "at the end of the day."
);

const u8 gEstrelinha347PokedexText[] = _(
    "A shooting star that made a nest. It grants\n"
    "wishes."
);

const u8 gArauanamon348PokedexText[] = _(
    "The whole region of Arauana made flesh.\n"
    "There is only one."
);

const u8 gAracua349PokedexText[] = _(
    "It shouts at dawn to warn the troop. The\n"
    "alarm clock of the forest."
);

const u8 gBugio350PokedexText[] = _(
    "It howls at first light. It marks its ground\n"
    "for kilometres."
);

const u8 gTuim351PokedexText[] = _(
    "The smallest parrot in Brazil. It flies in\n"
    "loud green flocks."
);

const u8 gPeriquitao352PokedexText[] = _(
    "A clever parrot. It mimics human voices to\n"
    "fool predators."
);

const u8 gArarunao353PokedexText[] = _(
    "A blue macaw with a hooked bill. Pairs stay\n"
    "together for life."
);

const u8 gPreazinho354PokedexText[] = _(
    "A shy round-eyed rodent. It lives in burrows\n"
    "out in the fields."
);

const u8 gCapivarao355PokedexText[] = _(
    "The largest rodent in the world. Birds and\n"
    "monkeys use it as a seat."
);

const u8 gTamandui356PokedexText[] = _(
    "The young rides on its mother's back until\n"
    "grown. It licks ants all day."
);

const u8 gTamandua357PokedexText[] = _(
    "A sticky tongue sixty centimetres long. It\n"
    "smells an ant nest kilometres off."
);

const u8 gTamanduao358PokedexText[] = _(
    "Enormous front claws. It sees off jaguars\n"
    "standing upright."
);

const u8 gPreguicinha359PokedexText[] = _(
    "It moves so slowly that moss grows in its\n"
    "fur."
);

const u8 gPreguicoso360PokedexText[] = _(
    "It sleeps twenty hours a day. Its dreams\n"
    "change the weather around it."
);

const u8 gBeijaFlor361PokedexText[] = _(
    "Its wings beat eighty times a second. It\n"
    "drinks nectar in mid-air."
);

const u8 gBeijaLuz362PokedexText[] = _(
    "Its feathers throw sunlight back in\n"
    "iridescent bands."
);

const u8 gBeijaSol363PokedexText[] = _(
    "The core in its chest holds a spark of the\n"
    "sun itself."
);

const u8 gSarara364PokedexText[] = _(
    "Curly blonde hair. It brings luck to anyone\n"
    "fishing nearby."
);

const u8 gCambota365PokedexText[] = _(
    "It sways without stopping, and kicks while\n"
    "it dances."
);

const u8 gBerimbau366PokedexText[] = _(
    "A living gourd that plays itself. It sets\n"
    "the rhythm of the circle."
);

const u8 gAtabaque367PokedexText[] = _(
    "Every beat shakes the ground. It keeps the\n"
    "time of the candomblé."
);

const u8 gPandeirim368PokedexText[] = _(
    "It spins on its own, playing samba."
);

const u8 gSanfoninha369PokedexText[] = _(
    "It blows tunes that make the listener weep\n"
    "with longing."
);

const u8 gVioleiro370PokedexText[] = _(
    "A walking country guitar. It sings the old\n"
    "tales in verse."
);

const u8 gZabumba371PokedexText[] = _(
    "A deep drum that pulls the forró along. It\n"
    "sets hearts beating in time."
);

const u8 gCordelim372PokedexText[] = _(
    "A cordel pamphlet that reads itself aloud."
);

const u8 gRendeira373PokedexText[] = _(
    "It weaves invisible lace that catches bad\n"
    "dreams."
);

const u8 gEscamoso374PokedexText[] = _(
    "Its skin is covered in sharp scales.\n"
    "Fishermen treat it with respect."
);

const u8 gPiranhita375PokedexText[] = _(
    "It swims in shoals of dozens. They eat a\n"
    "whole cow in minutes."
);

const u8 gBoitata376PokedexText[] = _(
    "A snake of fire that punishes whoever burns\n"
    "the forest. Its eyes are coals."
);

const u8 gPiraruacu377PokedexText[] = _(
    "The ancestral pirarucu. One stroke of its\n"
    "tail empties a lake."
);

const u8 gMataMata378PokedexText[] = _(
    "An ancient turtle. Its shell hides a forest\n"
    "in miniature."
);

const u8 gSolaris379PokedexText[] = _(
    "Its body is a living sphere of sun. Stars go\n"
    "out when it rises."
);

const u8 gSelene380PokedexText[] = _(
    "Its body is a silver crescent moon. It rules\n"
    "tides and dreams."
);

const u8 gZumbiRei381PokedexText[] = _(
    "The king of Palmares returned. The emblem of\n"
    "freedom."
);

const u8 gIemanja382PokedexText[] = _(
    "Queen of the sea. She receives her offerings\n"
    "in February."
);

const u8 gOxumara383PokedexText[] = _(
    "The rainbow serpent. It bridges earth and\n"
    "sky in colour."
);

const u8 gCurupixel384PokedexText[] = _(
    "A young Curupira in its first form. It shows\n"
    "itself only to pure children."
);

const u8 gSacinho385PokedexText[] = _(
    "A newborn Saci. Whirlwinds follow wherever\n"
    "it goes."
);

const u8 gAraua386PokedexText[] = _(
    "The first Pokémon of Arauana. It holds the\n"
    "essence of the whole region."
);
