gText_Birch_Welcome::
	.string "Hello. Thank you for waiting!\p"
	.string "Welcome to the world of POKéMON.\p"
	.string "I study the ancient Oaths of\n"
	.string "ARAUNA.\p"
	.string "For now, you may call me\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a POKéMON.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "In ARAUNA, people and POKéMON\n"
	.string "live side by side.\p"
	.string "We cross wild lands and build\n"
	.string "our cities together.\p"
	.string "We face danger side by side.\p"
	.string "But this land bears an old wound\n"
	.string "many would rather forget.\p"
	.string "On the STARLESS NIGHT, ancient\n"
	.string "Oaths were broken.\p"
	.string "Since that day, I have searched\n"
	.string "for the truth.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "I understand.\p"
	.string "You're {PLAYER}.\p"
	.string "You just arrived in ARAUNA.\l"
	.string "Now it makes sense.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Are you ready?\p"
	.string "Your adventure begins now.\p"
	.string "Be brave, but listen to what\n"
	.string "ARAUNA is trying to tell you.\p"
	.string "Not every secret wants to be\n"
	.string "revealed.\p"
	.string "I'll be waiting in my lab.\n"
	.string "We still have much to discover.\p"
	.string "$"
