#!/usr/bin/env python3
"""Build exact-color, draw-only connection aliases without changing map grids.

The two primary sheets have identical pixels. Reusing their static tiles and
unused secondary palette entries avoids the full Fortree bank and leaves Cut,
encounters and all MapGrid APIs on their original metatile IDs.
"""
import collections
import json
import re
import shutil
import struct
from pathlib import Path

from PIL import Image
from bancos_nativos import resolve_bank, bank_words
from connection_cache import rectangle
from render_native_map import Renderer, words

ROOT = Path(__file__).resolve().parents[2]
CONFIG = {
    'Route119': ('Route118', 'gTileset_AraunaMataMeioV3', 'AraunaRoute119BorderV1', 'InitTilesetAnim_Fortree'),
    'Route118': ('Route119', 'gTileset_Arauna118MataUmida', 'AraunaRoute118BorderV1', 'InitTilesetAnim_Mauville'),
}

def dump(path, node):
    path.write_text(json.dumps(node, indent=2, ensure_ascii=False) + '\n')

def marked(path, content):
    start, end = '// ARAUNA_BORDER_VISUALS_BEGIN', '// ARAUNA_BORDER_VISUALS_END'
    text = path.read_text()
    block = start + '\n' + content + end + '\n'
    if start in text:
        text = re.sub(re.escape(start) + r'.*?' + re.escape(end) + r'\n?', lambda _: block, text, flags=re.S)
    else:
        text += '\n' + block
    path.write_text(text)

def main():
    node = json.loads((ROOT/'data/layouts/layouts.json').read_text())
    layouts = {l['id']: l for l in node['layouts']}
    maps = {m['id']: m for p in (ROOT/'data/maps').glob('*/map.json') for m in [json.loads(p.read_text())]}
    results = {}
    declarations = collections.defaultdict(str)
    tables = '// Generated by build_border_visuals_119_118.py.\n'
    for name, (neighbor, original, symbol, callback) in CONFIG.items():
        m = json.loads((ROOT/f'data/maps/{name}/map.json').read_text())
        n = json.loads((ROOT/f'data/maps/{neighbor}/map.json').read_text())
        cur, source = layouts[m['layout']], layouts[n['layout']]
        source_symbol = CONFIG[neighbor][1]
        old = resolve_bank(ROOT, original)
        primary = resolve_bank(ROOT, cur['primary_tileset'])
        source_primary = resolve_bank(ROOT, source['primary_tileset'])
        receiver = Renderer(primary, old)
        donor = Renderer(source_primary, resolve_bank(ROOT, source_symbol))
        assert receiver.primary_tiles[0].tobytes() == donor.primary_tiles[0].tobytes(), 'Primary pixel sheets differ'
        # Protect every ID shown in the map and every incoming cache, including
        # the other neighbors. No assumptions about a metatile being "unused".
        live = {v & 1023 for field in ('blockdata_filepath', 'border_filepath') for v in words(ROOT/cur[field])}
        for c in m.get('connections') or []:
            if c['direction'] in ('dive', 'emerge'):
                continue
            other = layouts[maps[c['map']]['layout']]
            grid = words(ROOT/other['blockdata_filepath'])
            live.update(grid[y*other['width']+x] & 1023 for x,y in rectangle(cur['width'],cur['height'],other['width'],other['height'],c['offset'],c['direction']))
        colors = collections.defaultdict(set)
        for mid in live:
            for e in bank_words(receiver, mid):
                tile = receiver._tile(e & 1023)
                if tile is None:
                    # Animated source slots cannot be repurposed for aliases.
                    colors[e >> 12].update(range(1,16))
                else:
                    colors[e >> 12].update(set(tile.getdata()) - {0})
        c = next(c for c in m['connections'] if c['map'] == n['id'])
        grid = words(ROOT/source['blockdata_filepath'])
        points = rectangle(cur['width'],cur['height'],source['width'],source['height'],c['offset'],c['direction'])
        counts = collections.Counter(grid[y*source['width']+x] & 1023 for x,y in points)
        needed = sorted(mid for mid in counts if receiver.metatile(mid).tobytes() != donor.metatile(mid).tobytes())
        path = ROOT/'data/tilesets/secondary'/('arauna_route119_border_v1' if name=='Route119' else 'arauna_route118_border_v1')
        if path.exists():
            shutil.rmtree(path)
        shutil.copytree(old, path, ignore=shutil.ignore_patterns('*.4bpp','*.4bpp.lz','*.gbapal'))
        palettes = [list(p) for p in receiver.palettes]
        meta, attrs = words(old/'metatiles.bin'), words(old/'metatile_attributes.bin')
        sheet = Image.open(path/'tiles.png');sheet.load()
        primary_pixels = {receiver._tile(i).tobytes():i for i in range(432)}
        compacted = 0
        # This scoped Fortree copy has no secondary animation. Referencing an
        # identical static primary tile is lossless for every defined metatile.
        if name == 'Route119':
            for i,e in enumerate(meta):
                if (e & 1023) >= 512:
                    t = receiver._tile(e & 1023)
                    if t is not None and t.tobytes() in primary_pixels:
                        meta[i] = (e & ~1023) | primary_pixels[t.tobytes()]
                        compacted += 1
        used_tiles = {(e & 1023)-512 for e in meta if (e & 1023)>=512}
        used_tiles.update((e & 1023)-512 for e in receiver.primary_metatiles if (e & 1023)>=512)
        # Do not touch door slots or Mauville's animated secondary slots.
        animated = set(range(96,160)) if name == 'Route118' else set()
        free_tiles = sorted(set(range(1,min(496,sheet.width*sheet.height//64))) - used_tiles - animated)
        new_tiles = {}
        reserved = set(live)
        # Also preserve all named secondary IDs referenced by code/scripts.
        labels = dict((k,int(v,16)) for k,v in re.findall(r'#define (METATILE_\w+)\s+(0x[0-9A-Fa-f]+)', (ROOT/'include/constants/metatile_labels.h').read_text()))
        references = ''.join(p.read_text(errors='ignore') for base,pattern in [('src','*.c'),('data/scripts','*.inc'),(f'data/maps/{name}','*.inc')] for p in (ROOT/base).glob(pattern))
        reserved.update(labels[k] for k in set(re.findall(r'METATILE_\w+',references)) if k in labels)
        aliases = {}
        changes = set()
        for mid in needed:
            # Allocate render-only aliases outside all native/cache/script IDs.
            alias = next(i for i in range(512,1024) if i not in reserved)
            reserved.add(alias)
            entries = []
            for e in bank_words(donor, mid):
                tile = e & 1023
                assert tile < 432, f'Animated/secondary donor tile {tile}: requires an explicit VRAM plan'
                pixels = set(donor._tile(tile).getdata()) - {0}
                pal = donor.palettes[e >> 12]
                candidates = []
                # Keep pixel indices and reuse the unchanged primary sheet.
                # Palette indices are assigned only when provably unused.
                for q in range(13):
                    if all(pal[ix] == palettes[q][ix] or (q >= 6 and ix not in colors[q]) for ix in pixels):
                        modified = sum(pal[ix] != palettes[q][ix] for ix in pixels)
                        candidates.append((modified, q))
                target_tile = tile
                if candidates:
                    _, q = min(candidates)
                    mapping = {ix:ix for ix in pixels}
                    additions = {ix:pal[ix] for ix in pixels if palettes[q][ix] != pal[ix]}
                else:
                    plans = []
                    for q in range(6,13):
                        available = set(range(1,16))-colors[q]
                        mapping = {};additions = {}
                        for ix in sorted(pixels):
                            exact = next((j for j in range(1,16) if palettes[q][j] == pal[ix]),None)
                            if exact is None:
                                if not available:break
                                exact = ix if ix in available else min(available)
                                available.remove(exact);additions[exact] = pal[ix]
                            mapping[ix] = exact
                        if len(mapping) == len(pixels):
                            plans.append((len(additions),q,mapping,additions))
                    assert plans, f'No exact palette for {name} metatile {mid:#x} tile {tile}'
                    _,q,mapping,additions = min(plans,key=lambda p:(p[0],p[1]))
                    original_pixels = donor._tile(tile).tobytes()
                    remapped = bytes(mapping.get(ix,0) for ix in original_pixels)
                    if remapped in primary_pixels:
                        target_tile = primary_pixels[remapped]
                    else:
                        if remapped not in new_tiles:
                            assert free_tiles, 'No safe static hardware tile slot'
                            slot = free_tiles.pop(0);new_tiles[remapped] = slot
                            data = Image.frombytes('P',(8,8),remapped)
                            sheet.paste(data,((slot%(sheet.width//8))*8,(slot//(sheet.width//8))*8))
                        target_tile = 512+new_tiles[remapped]
                for ix,color in additions.items():
                    palettes[q][ix] = color;changes.add(q)
                colors[q].update(mapping.values())
                entries.append((e & 0x0c00) | target_tile | q << 12)
            local = alias-512
            while len(attrs) <= local:
                attrs.append(0);meta.extend([0]*8)
            meta[local*8:local*8+8] = entries
            attrs[local] = bank_words(donor, mid, True)
            aliases[mid] = alias
        (path/'metatiles.bin').write_bytes(struct.pack('<%dH'%len(meta),*meta))
        (path/'metatile_attributes.bin').write_bytes(struct.pack('<%dH'%len(attrs),*attrs))
        sheet.save(path/'tiles.png')
        for q in sorted(changes):
            (path/f'palettes/{q:02}.pal').write_bytes(('JASC-PAL\r\n0100\r\n16\r\n'+''.join('%d %d %d\r\n'%v for v in palettes[q])).encode())
        cur['secondary_tileset'] = 'gTileset_'+symbol
        slug = path.relative_to(ROOT).as_posix()
        declarations['graphics.h'] += f'const u32 gTilesetTiles_{symbol}[] = INCGFX_U32("{slug}/tiles.png", ".4bpp.lz");\nconst u16 gTilesetPalettes_{symbol}[][16] =\n{{\n'+''.join(f'    INCGFX_U16("{slug}/palettes/{i:02}.pal", ".gbapal"),\n' for i in range(16))+'};\n'
        declarations['metatiles.h'] += f'const u16 gMetatiles_{symbol}[] = INCBIN_U16("{slug}/metatiles.bin");\nconst u16 gMetatileAttributes_{symbol}[] = INCBIN_U16("{slug}/metatile_attributes.bin");\n'
        declarations['headers.h'] += f'const struct Tileset gTileset_{symbol} =\n{{\n    .isCompressed = TRUE,\n    .isSecondary = TRUE,\n    .tiles = gTilesetTiles_{symbol},\n    .palettes = gTilesetPalettes_{symbol},\n    .metatiles = gMetatiles_{symbol},\n    .metatileAttributes = gMetatileAttributes_{symbol},\n    .callback = {callback},\n}};\n'
        tables += f'static const struct BorderVisualAlias s{name}BorderAliases[] =\n{{\n'+''.join(f'    {{0x{a:03X}, 0x{b:03X}}},\n' for a,b in aliases.items())+'};\n'
        results[name] = {'neighbor':neighbor, 'cache_cells':len(points), 'different_rgb_before':sum(counts[mid] for mid in needed), 'aliases':{str(a):b for a,b in aliases.items()}, 'palettes_modified':sorted(changes), 'new_hardware_tiles':len(new_tiles), 'new_hardware_slots':sorted(new_tiles.values()), 'compacted_static_entries':compacted, 'map_grid_untouched':True}
    for name, content in declarations.items():
        marked(ROOT/'src/data/tilesets'/name, content)
    (ROOT/'src/data/arauna_border_visuals.h').write_text(tables)
    dump(ROOT/'data/layouts/layouts.json', node)
    dump(ROOT/'review/border_visuals_119_118_build.json', results)
    print(json.dumps(results, indent=2))

if __name__ == '__main__':
    main()
