#!/usr/bin/env python3
"""Transplant exact-color border metatiles to private banks; native grids intact."""
import argparse,collections,json,re,subprocess,ctypes,tempfile,random,copy
from pathlib import Path
from PIL import Image
from native_visuals_v2 import ROOT,Pair,dump,marked,declarations
from render_native_map import Renderer as RawRenderer,words,indexed_tiles
def normalize(r):
 r.palettes=[[tuple(c>>3<<3 for c in rgb) for rgb in pal] for pal in r.palettes];return r
def Renderer(*args):return normalize(RawRenderer(*args))
from bancos_nativos import resolve_bank,bank_words
from connection_cache import rectangle
BASE='591aeb24973622bda8d12cce60b3560cef938c00'
PAIRS=[('Route124','Route126'),('Route110','MauvilleCity'),('Route110','SlateportCity'),('EverGrandeCity','Route128'),('Route103','Route110'),('PetalburgCity','Route104'),('Route104','RustboroCity'),('MauvilleCity','Route111'),('MauvilleCity','Route117'),('MauvilleCity','Route118'),('RustboroCity','Route115'),('LavaridgeTown','Route112'),('PetalburgCity','Route102'),('Route102','OldaleTown'),('Route103','OldaleTown'),('Route104','Route105'),('Route119','Route118')]
NAMES=list(dict.fromkeys(n for pair in PAIRS for n in pair));CODES={n:1000+i for i,n in enumerate(NAMES)}
def symbol(n,kind):return 'AraunaBorder'+n+('Base' if kind==0 else 'Art')+'SulV1'
def animation_pixels(repo,t):
 for start,count,slug in ((432,30,'water'),(464,10,'sand_water_edge'),(480,10,'land_water_edge'),(496,6,'waterfall'),(508,4,'flower')):
  if start<=t<start+count:
   pixels=set()
   for p in (repo/'data/tilesets/primary/general/anim'/slug).glob('*.png'):
    im,row,_=indexed_tiles(p);j=t-start;pixels.update(im.crop((j%row*8,j//row*8,j%row*8+8,j//row*8+8)).tobytes())
   return pixels-{0}
 return set(range(1,16))
def choose_palette(pair,locked,pal,pixels,dynamic):
 plans=[]
 for q in range(13):
  if all(pair.pals[q][ix]==pal[ix] or ix not in locked[q] for ix in pixels):plans.append((sum(pair.pals[q][ix]!=pal[ix] for ix in pixels),q,{ix:ix for ix in pixels},{ix:pal[ix] for ix in pixels if pair.pals[q][ix]!=pal[ix]}))
 if not dynamic:
  for q in range(13):
   available=set(range(1,16))-locked[q];mapping={};add={}
   for ix in sorted(pixels):
    match=next((j for j in range(1,16) if (add.get(j,pair.pals[q][j]))==pal[ix]),None)
    if match is None:
     if not available:break
     match=min(available);available.remove(match);add[match]=pal[ix]
    else:available.discard(match)
    mapping[ix]=match
   if len(mapping)==len(pixels):plans.append((len(add),q,mapping,add))
 assert plans,('No exact palette capacity',len(pixels),[len(locked[q]) for q in range(13)],len({pair.pals[q][j] for q in range(13) for j in locked[q]}),pal,pixels)
 _,q,mapping,add=min(plans,key=lambda p:(p[0],p[1]))
 for ix,color in add.items():pair.pals[q][ix]=color
 locked[q].update(mapping.values());return q,mapping
def private_alias(pair,native,entries,attribute):
 key=attribute,tuple(entries)
 if key in pair.alias_cache:return pair.alias_cache[key]
 mid=next((i for i in list(range(512,1024))+list(range(1,512)) if i not in pair.reserved),None);assert mid is not None,'No safe native metatile ID'
 pair.reserved.add(mid);kind=int(mid>=512);local=mid%512
 while len(pair.attrs[kind])<=local:pair.attrs[kind].append(0);pair.meta[kind].extend([0]*8)
 pair.attrs[kind][local]=attribute;pair.meta[kind][local*8:local*8+8]=entries;pair.alias_cache[key]=mid;return mid

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--source',type=Path,required=True);a=ap.parse_args();base=a.source.resolve()
 oldnode=json.loads((base/'data/layouts/layouts.json').read_text());old={l['id']:l for l in oldnode['layouts']};node=json.loads((ROOT/'data/layouts/layouts.json').read_text());new={l['id']:l for l in node['layouts']};maps={m['name']:m for p in (base/'data/maps').glob('*/map.json') for m in [json.loads(p.read_text())]};byid={m['id']:m for m in maps.values()};report={'base_commit':BASE,'maps':{},'regions':[]};decl=collections.defaultdict(str);tables='// Generated by build_sul_borders_v1.py.\n';regions=[]
 for n in NAMES:
  print('Packing borders',n,flush=True)
  m=maps[n];l=old[m['layout']];pair=Pair(base,l,repack=True);normalize(pair.reader);pair.pals=[list(p) for p in pair.reader.palettes];neighbors=[byid[c['map']]['name'] for c in m['connections'] or [] if c['direction'] in ('up','down','left','right')];pair.reserve(base,[n]+neighbors,old,maps);live={v&1023 for field in ('blockdata_filepath','border_filepath') for v in words(base/l[field])}
  for c in m['connections'] or []:
   if c['direction'] not in ('up','down','left','right'):continue
   if any(n in uv and byid[c['map']]['name'] in uv for uv in PAIRS):continue
   o=old[byid[c['map']]['layout']];g=words(base/o['blockdata_filepath']);live.update(g[y*o['width']+x]&1023 for x,y in rectangle(l['width'],l['height'],o['width'],o['height'],c['offset'],c['direction']))
  labels={k:int(v,16) for hp in (base/'include/constants').glob('*metatile*.h') for k,v in re.findall(r'#define (METATILE_\w+)\s+(0x[\da-fA-F]+)',hp.read_text())}
  scripts=''.join(p.read_text() for p in (base/'data/maps'/n).glob('*.inc'))
  live.update(labels[k] for k in re.findall(r'METATILE_\w+',scripts) if k in labels)
  engine=''.join(p.read_text() for p in (base/'src').glob('*.c'))
  native_ids={v&1023 for v in words(base/l['blockdata_filepath'])}
  for family in ('MuddySlope','BlueCave','RedCave','YellowCave','SecretBase_Tree','SecretBase_Vine','SandPit'):
   family_ids={value for label,value in labels.items() if label.startswith('METATILE_General_'+family)}
   if family_ids & native_ids:live.update(family_ids)
  art=json.loads((ROOT/'review/sul_pampa_v1/art_build.json').read_text());art_record=art['maps'].get(n)
  if art_record:live.update(art_record['cut_outputs'].values());live.update(art_record['engine_created_ids'])
  pair.reserved.update(live)

  # Cut can create floor/tree variants not already present in the grid.
  for label in ('General_Grass','General_Grass_TreeLeft','General_Grass_TreeRight','General_Grass_TreeUp','AraunaInicio_Campo'):
   value=labels.get('METATILE_'+label)
   if value is not None and (value<512 or n=='Route103'):live.add(value)
  # Protect all script and engine references, as well as the visible caches.
  locked=collections.defaultdict(set)
  # Build exact-color palettes for the live native map/cache first. This
  # removes unused recoloration-bank colors, without quantizing any pixel.
  own_source=pair.reader;pair.tiles={i:raw for i,raw in pair.tiles.items() if i in pair.dynamic};pair.tiles[0]=bytes(64);pair.tile_cache={bytes(64):0};pair.free=[i for i in list(range(1,432))+list(range(512,992)) if i not in pair.dynamic];pair.touched=set();pair.pals=[[own_source.palettes[q][0]]+[(0,0,0)]*15 for q in range(13)];own_animated={}
  # Door animation tables use fixed palette numbers rather than metatile
  # palette words. Keep those rows and pixel indices exactly as the base.
  doors=(base/'src/field_door.c').read_text();door_pals={k:set(map(int,re.findall(r'\d+',v))) for k,v in re.findall(r'static const u8 (sDoorAnimPalettes_\w+)\[\] = \{([^}]+)',doors)}
  native_grid=words(base/l['blockdata_filepath']);door_ids={native_grid[int(e['y'])*l['width']+int(e['x'])]&1023 for e in m['warp_events']}
  protected_door_rows=set()
  for label,palette_name in re.findall(r'\{(METATILE_\w+),[^\n]+?, (sDoorAnimPalettes_\w+)\}',doors):
   if labels.get(label) in door_ids:protected_door_rows.update(door_pals[palette_name])
  for q in protected_door_rows:
   assert q<13;pair.pals[q]=list(own_source.palettes[q]);locked[q].update(range(1,16))
  for mid in sorted(live):
   for e in bank_words(own_source,mid):
    t=e&1023
    if t in pair.dynamic:
     key=(tuple(own_source.palettes[e>>12]),t)
     if key not in own_animated:own_animated[key]=choose_palette(pair,locked,own_source.palettes[e>>12],animation_pixels(base,t) if t<512 else set(range(1,16)),True)
  # Animated graphics keep hardware IDs and pixel indices. Reserve their
  # exact palette entries before packing static imported colors.
  animated={}
  for u,v in PAIRS:
   if n not in (u,v):continue
   other=v if n==u else u;sm=maps[other];sl=old[sm['layout']];sr=Renderer(*[resolve_bank(base,sl[k]) for k in ('primary_tileset','secondary_tileset')]);co=next(c for c in m['connections'] if c['map']==sm['id']);sg=words(base/sl['blockdata_filepath'])
   for mid in sorted({sg[y*sl['width']+x]&1023 for x,y in rectangle(l['width'],l['height'],sl['width'],sl['height'],co['offset'],co['direction'])}):
    for e in bank_words(sr,mid):
     t=e&1023
     if 432<=t<512:
      key=(tuple(sr.palettes[e>>12]),t)
      if key not in animated:animated[key]=choose_palette(pair,locked,sr.palettes[e>>12],animation_pixels(base,t),True)
  requirements={}
  sources=[(own_source,live)]
  for u,v in PAIRS:
   if n not in (u,v):continue
   other=v if n==u else u;sm=maps[other];sl=old[sm['layout']];sr=Renderer(*[resolve_bank(base,sl[k]) for k in ('primary_tileset','secondary_tileset')]);co=next(c for c in m['connections'] if c['map']==sm['id']);sg=words(base/sl['blockdata_filepath']);sources.append((sr,{sg[y*sl['width']+x]&1023 for x,y in rectangle(l['width'],l['height'],sl['width'],sl['height'],co['offset'],co['direction'])}))
  for source,ids in sources:
   for mid in sorted(ids):
    for e in bank_words(source,mid):
     t=e&1023
     if (source is own_source and t in pair.dynamic) or 432<=t<512:continue
     image=source._tile(t);assert image is not None
     key=tuple(source.palettes[e>>12]),image.tobytes();requirements[key]=set(image.tobytes())-{0}
  initial_pals=copy.deepcopy(pair.pals);initial_locked=copy.deepcopy(locked)
  plan_path=ROOT/'art/sul_pampa_v1'/('palette_plan_'+n+'.json')
  if plan_path.exists():
   pair.pals=[[tuple(c) for c in row] for row in json.loads(plan_path.read_text())];locked=copy.deepcopy(initial_locked)
   for q,ixs in initial_locked.items():
    for ix in ixs:assert pair.pals[q][ix]==initial_pals[q][ix],(n,'animation/door color plan')
   staticplans={}
   for key,pixels in requirements.items():
    colors={key[0][ix] for ix in pixels};q=next((q for q in range(13) if colors<=set(pair.pals[q][1:])),None);assert q is not None,(n,'palette plan missing colors',colors)
    mapping={ix:next(j for j in range(1,16) if pair.pals[q][j]==key[0][ix]) for ix in pixels};staticplans[key]=q,mapping;locked[q].update(mapping.values())
  else:
   for attempt in range(256):
    pair.pals=copy.deepcopy(initial_pals);locked=copy.deepcopy(initial_locked);keys=list(requirements);random.Random(attempt).shuffle(keys);keys.sort(key=lambda k:-len(requirements[k]));staticplans={}
    try:
     for key in keys:staticplans[key]=choose_palette(pair,locked,key[0],requirements[key],False)
     break
    except AssertionError:continue
   else:
    debug={'map':n,'initial_palettes':initial_pals,'locked':{q:sorted(v) for q,v in initial_locked.items()},'color_groups':[sorted({key[0][ix] for ix in pixels}) for key,pixels in requirements.items()]};dump(ROOT/'art/sul_pampa_v1'/('packing_input_'+n+'.json'),debug)
    raise AssertionError((n,'Exact palette packing exhausted; compute offline palette plan'))
  for mid in sorted(live):
   entries=[]
   for e in bank_words(own_source,mid):
    t=e&1023;pal=own_source.palettes[e>>12];image=own_source._tile(t)
    if t in pair.dynamic:q,mapping=own_animated[(tuple(pal),t)];target=t
    else:
     assert image is not None,(n,mid,t)
     q,mapping=staticplans[(tuple(pal),image.tobytes())]
     target=pair.tile(Image.frombytes('L',(8,8),bytes(mapping.get(ix,0) for ix in image.tobytes())))
    entries.append((e&0xc00)|target|q<<12)
   pair.meta[mid>=512][mid%512*8:mid%512*8+8]=entries
  ownedregions=[]
  for u,v in PAIRS:
   if n not in (u,v):continue
   other=v if n==u else u;s=maps[other];o=old[s['layout']];source=Renderer(*[resolve_bank(base,o[k]) for k in ('primary_tileset','secondary_tileset')]);c=next(c for c in m['connections'] if c['map']==s['id']);points=rectangle(l['width'],l['height'],o['width'],o['height'],c['offset'],c['direction']);g=words(base/o['blockdata_filepath']);ids=sorted({g[y*o['width']+x]&1023 for x,y in points});aliases={}
   for mid in ids:
    entries=[]
    for e in bank_words(source,mid):
     t=e&1023;image=source._tile(t);dynamic=432<=t<512
     assert image is not None,(n,other,t)
     pal=source.palettes[e>>12]
     q,mapping=animated[(tuple(pal),t)] if dynamic else staticplans[(tuple(pal),image.tobytes())]
     target=t if dynamic else pair.tile(Image.frombytes('L',(8,8),bytes(mapping.get(ix,0) for ix in image.tobytes())))
     entries.append((e&0xc00)|target|q<<12)
    aliases[mid]=private_alias(pair,mid,entries,bank_words(source,mid,True))
   # Destination coordinates exactly match the four engine Fill* routines.
   if c['direction']=='up':x0=max(0,c['offset']+7);y0=0;rw=max(x for x,y in points)-min(x for x,y in points)+1;rh=7
   elif c['direction']=='down':x0=max(0,c['offset']+7);y0=l['height']+7;rw=max(x for x,y in points)-min(x for x,y in points)+1;rh=7
   elif c['direction']=='left':x0=0;y0=max(0,c['offset']+7);rw=7;rh=max(y for x,y in points)-min(y for x,y in points)+1
   else:x0=l['width']+7;y0=max(0,c['offset']+7);rw=8;rh=max(y for x,y in points)-min(y for x,y in points)+1
   array=f'sSul_{n}_{other}';tables+=f'static const struct BorderVisualAlias {array}[] =\n{{\n'+''.join(f'    {{0x{a:03X}, 0x{b:03X}}},\n' for a,b in aliases.items())+'};\n';r={'receiver':n,'source':other,'direction':c['direction'],'offset':c['offset'],'rectangle':[x0,y0,x0+rw,y0+rh],'source_rectangle':[min(x for x,y in points),min(y for x,y in points),max(x for x,y in points)+1,max(y for x,y in points)+1],'cells':len(points),'aliases':{str(k):v for k,v in aliases.items()},'array':array};regions.append((symbol(n,1),r));report['regions'].append(r);ownedregions.append(r)
  slug=re.sub(r'([a-z])([A-Z])',r'\1_\2',n).lower();paths=[ROOT/'data/tilesets'/kind/f'arauna_border_{slug}_sul_v1' for kind in ('primary','secondary')];symbols=[symbol(n,k) for k in range(2)];pair.write(paths)
  for field,s in zip(('primary_tileset','secondary_tileset'),symbols):new[m['layout']][field]='gTileset_'+s
  for field,text in declarations(paths,symbols,pair.callbacks).items():decl[field]+=text
  report['maps'][n]={'code':CODES[n],'paths':[str(p.relative_to(ROOT)) for p in paths],'symbols':symbols,'protected_door_palette_rows':sorted(protected_door_rows),'runtime_visual_ids':sorted(live),'original_callbacks':pair.callbacks,'new_static_slots':sorted(pair.touched),'alias_count':len(pair.alias_cache),'native_map_and_cache_IDs_reserved':len(pair.reserved),'live_colors_preserved':{str(q):len(v) for q,v in locked.items()}}
 tables+='struct SulBorderRegion { const struct Tileset *bank; s32 x1,y1,x2,y2; const struct BorderVisualAlias *aliases; u32 count; };\nstatic const struct SulBorderRegion sSulBorderRegions[] =\n{\n'
 for sym,r in regions:
  x1,y1,x2,y2=r['rectangle'];tables+=f'    {{&gTileset_{sym}, {x1},{y1},{x2},{y2}, {r["array"]}, ARRAY_COUNT({r["array"]})}},\n'
 tables+='};\n';(ROOT/'src/data/arauna_border_sul_v1.h').write_text(tables)
 for field,text in decl.items():marked(ROOT/'src/data/tilesets'/field,'BORDER_SUL_V1',text)
 c=(ROOT/'src/arauna_border_visuals.c').read_text();externs=''.join(f'extern const struct Tileset gTileset_{symbol(n,1)};\n' for n in NAMES);c=c.replace('struct BorderVisualAlias',externs+'\nstruct BorderVisualAlias',1);c=c.replace('#include "data/arauna_border_priority_v2.h"','#include "data/arauna_border_priority_v2.h"\n#include "data/arauna_border_sul_v1.h"')
 needle='|| layout->secondaryTileset == &gTileset_AraunaBorderRoute110ArtV2'
 c=c.replace(needle,needle+'\n'+''.join(f'        || layout->secondaryTileset == &gTileset_{symbol(n,1)}\n' for n in NAMES).rstrip())
 needle='    for (i = 0; i < ARRAY_COUNT(sPriorityBorderRegions); i++)'
 dispatch='    for (i = 0; i < ARRAY_COUNT(sSulBorderRegions); i++)\n    {\n        const struct SulBorderRegion *region = &sSulBorderRegions[i];\n        u32 j;\n        if (layout->secondaryTileset != region->bank || x < region->x1 || x >= region->x2 || y < region->y1 || y >= region->y2)\n            continue;\n        for (j = 0; j < region->count; j++)\n            if (region->aliases[j].nativeId == nativeId)\n                return region->aliases[j].visualId;\n    }\n'
 assert needle in c;c=c.replace(needle,dispatch+needle);(ROOT/'src/arauna_border_visuals.c').write_text(c)
 cut=(ROOT/'src/fldeff_cut.c').read_text();ex=''.join(f'extern const struct Tileset gTileset_{symbol(n,0)};\n' for n in list(art['maps'])+['OldaleTown']);cut=cut.replace('#include "global.h"','#include "global.h"\n// SUL_CUT_EXTERNS_BEGIN\n'+ex+'// SUL_CUT_EXTERNS_END')
 cut=cut.replace('|| gMapHeader.mapLayout->primaryTileset == &gTileset_AraunaBorderRoute103BaseV2)', '|| gMapHeader.mapLayout->primaryTileset == &gTileset_AraunaBorderRoute103BaseV2\n      || gMapHeader.mapLayout->primaryTileset == &gTileset_'+symbol('OldaleTown',0)+')')
 dispatch=''
 for n,d in art['maps'].items():
  if not d['cut_outputs']:continue
  dispatch+=f'    if (gMapHeader.mapLayout->primaryTileset == &gTileset_{symbol(n,0)})\n    {{\n        switch (MapGridGetMetatileIdAt(x, y))\n        {{\n'
  for k,v in d['cut_outputs'].items():dispatch+=f'        case {k}: MapGridSetMetatileIdAt(x, y, {v}); return;\n'
  dispatch+='        default: break;\n        }\n    }\n'
 needle='    switch (MapGridGetMetatileIdAt(x, y))';assert needle in cut;cut=cut.replace(needle,dispatch+needle,1);(ROOT/'src/fldeff_cut.c').write_text(cut)
 # Intermediate art outputs are reproducible inputs, not duplicate linked ROM banks.
 for field in ('graphics.h','metatiles.h','headers.h'):
  p=ROOT/'src/data/tilesets'/field;p.write_text(re.sub(r'\n*// SUL_PAMPA_V1_BEGIN\n.*?// SUL_PAMPA_V1_END\n','\n',p.read_text(),flags=re.S))
 dump(ROOT/'data/layouts/layouts.json',node);dump(ROOT/'review/sul_pampa_v1/borders_build.json',report);print('Built',len(NAMES),'private pairs and',len(regions),'border regions')
if __name__=='__main__':main()
