#!/usr/bin/env python3
"""Deterministic, camera-only Terra/Marine artwork over the installed checkpoints."""
from __future__ import annotations
import argparse, collections, hashlib, json, re, subprocess
from pathlib import Path
from PIL import Image, ImageDraw
from native_visuals_v2 import Pair, binary, declarations, dump, marked, ROOT
from render_native_map import words
from script_metatile_dependencies import collect

BASE = 'bcd93e980e55a0f5a649baa7d6b8d154b464be23'
NAMES = ('TerraCave_Entrance', 'TerraCave_End', 'MarineCave_Entrance', 'MarineCave_End')
OUT = ROOT / 'review/cavernas_03a'
WATER = {0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x17, 0x19}
ROCK = {
 'terra': [(0,0,0),(16,24,32),(24,32,40),(32,40,48),(48,56,64),(64,72,80),(80,88,96),(104,112,120),(128,136,136),(152,160,160),(56,40,32),(88,56,32),(120,72,40),(160,96,48),(192,128,64),(224,168,88)],
 'marine': [(0,0,0),(16,32,40),(24,48,56),(40,64,72),(56,80,88),(72,96,104),(96,120,128),(120,144,144),(144,168,168),(184,200,192),(32,72,80),(40,104,112),(56,136,144),(88,168,168),(144,208,200),(216,232,216)]}
FLOOR = {
 'terra': [(0,0,0),(48,48,48),(64,64,56),(80,80,72),(96,96,80),(112,104,88),(128,120,104),(144,136,112),(160,152,128),(176,168,144),(112,88,64),(136,104,72),(160,128,88),(184,152,104),(208,184,128),(232,216,168)],
 'marine': [(0,0,0),(56,80,88),(72,96,104),(88,112,120),(104,128,128),(120,144,144),(136,160,152),(152,176,168),(176,192,176),(200,208,184),(80,120,128),(104,152,152),(136,184,176),(168,208,192),(208,224,208),(232,240,216)]}

def quantize(im, pal, opaque=False):
    out = Image.new('L', im.size)
    out.putdata([min(range(1,16), key=lambda j: sum((a-b)**2 for a,b in zip(rgb[:3],pal[j]))) if opaque or rgb[3] else 0 for rgb in im.convert('RGBA').getdata()])
    return out

def pieces(family):
    atlas = Image.open(ROOT/'art/cavernas_03a/minerais_atlas.png').convert('RGBA')
    raw = []
    offset = 0 if family == 'terra' else 2
    for row in range(offset,offset+2):
        for col in range(4):
            im=atlas.crop((round(col*atlas.width/4),round(row*atlas.height/4),round((col+1)*atlas.width/4),round((row+1)*atlas.height/4)))
            im.putdata([(r,g,b,0 if r>180 and b>180 and g<90 else 255) for r,g,b,a in im.getdata()])
            raw.append(im.crop(im.getbbox()))
    face=raw[0].resize((48,32),Image.Resampling.NEAREST)
    cap=raw[1].resize((32,32),Image.Resampling.NEAREST)
    result={'upper':face.crop((16,0,32,16)), 'lower':face.crop((16,16,32,32)),
            'single':face.crop((16,0,32,32)).resize((16,16),Image.Resampling.NEAREST),
            'cap':cap.crop((8,0,24,16)),
            'left':raw[2].resize((16,32),Image.Resampling.NEAREST).crop((0,8,16,24)),
            'right':raw[3].resize((16,32),Image.Resampling.NEAREST).crop((0,8,16,24)),
            'outcrop':raw[5].resize((16,16),Image.Resampling.NEAREST),
            'vein':raw[6].resize((16,16),Image.Resampling.NEAREST)}
    result={k:quantize(v,ROCK[family],k=='cap') for k,v in result.items()}
    # Sparse 1–2px clusters keep walking ground legible at native scale.
    for variant in range(3):
        im=Image.new('L',(16,16),6);d=ImageDraw.Draw(im)
        for x,y in ((2,3),(11,2),(7,11),(13,13)):
            xx=(x+variant*3)%15; yy=(y+variant*5)%15
            d.line((xx,yy,min(xx+2,15),yy),fill=5 if variant!=2 else 7)
            if variant==1:d.point((xx,yy+1 if yy<15 else yy),fill=8)
        result[f'floor{variant}']=im
    return result

def main():
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--base',type=Path,required=True);args=ap.parse_args();base=args.base.resolve()
    assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=base,text=True).strip()==BASE
    node=json.loads((base/'data/layouts/layouts.json').read_text());layouts={l['id']:l for l in node['layouts']}
    maps={m['name']:m for p in (base/'data/maps').glob('*/map.json') for m in [json.loads(p.read_text())]}
    labels={k:int(v,16) for k,v in re.findall(r'#define (METATILE_\w+)\s+(0x[\da-fA-F]+)',(base/'include/constants/metatile_labels.h').read_text())}
    # Refuse unrelated local changes before writing any shared registry.
    for rel in ('data/layouts/layouts.json','src/data/arauna_cave_visuals_v2.h','src/data/tilesets/graphics.h','src/data/tilesets/metatiles.h','src/data/tilesets/headers.h'):
        current=(ROOT/rel).read_text();original=(base/rel).read_text()
        if rel=='data/layouts/layouts.json':
            a=json.loads(current);b=json.loads(original)
            for l in a['layouts']:
                if l['id'] in {maps[n]['layout'] for n in NAMES}:l['secondary_tileset']='gTileset_Cave'
            assert a==b,('unrelated layout change',rel)
        elif rel.endswith('arauna_cave_visuals_v2.h'):
            assert current==original or current.startswith('/* Generated by build_cavernas_03a.py'),rel
        else:
            current=re.sub(r'\n*// CAVERNAS_03A_BEGIN\n.*?// CAVERNAS_03A_END\n','\n',current,flags=re.S)
            assert current.rstrip()==original.rstrip(),('unrelated registry change',rel)
    report={'base_commit':BASE,'maps':{},'banks':{},'native_grids_unchanged':True,'art_sha256':hashlib.sha256((ROOT/'art/cavernas_03a/minerais_atlas.png').read_bytes()).hexdigest()}
    tables=[];decl={k:'' for k in ('graphics.h','metatiles.h','headers.h')}
    for family,group in [('terra',NAMES[:2]),('marine',NAMES[2:])]:
        pair=Pair(base,layouts[maps[group[0]]['layout']]);pair.dynamic.update(range(928,932))
        pair.free=[i for i in pair.free if i>=512 and i not in pair.dynamic]
        # A cached tile must not also be a future allocation slot. Otherwise a
        # later piece could overwrite a blank/identical tile already referenced.
        pair.tile_cache={raw:i for i,raw in pair.tiles.items() if i>=512 and i not in pair.dynamic and i not in pair.free}
        assert pair.reader._tile(0).tobytes()==bytes(64)
        pair.tile_cache[bytes(64)]=0
        pair.reserve(base,group,layouts,maps)
        for n in group:pair.reserved.update(collect(base,n,labels)[0])
        pair.pals[7]=ROCK[family];pair.pals[9]=FLOOR[family]
        pair.pals[12]=[tuple((v//16)*8 for v in rgb) for rgb in ROCK[family]]
        pair.pals[11]=[(0,0,0),(24,32,40),(40,48,48),(64,72,64),(88,96,80),(120,120,96),(160,152,120),(200,184,144),(224,216,184),(240,232,208),(40,80,88),(64,120,128),(96,160,168),(152,208,208),(192,112,48),(240,176,72)]
        art=pieces(family);counter=collections.Counter()
        original_meta=[list(a) for a in pair.meta]
        def entries(mid):return original_meta[mid>=512][mid%512*8:mid%512*8+8]
        def behavior(mid):return pair.attrs[mid>=512][mid%512]&255
        # 863 is the static staging lava under the legendary. 864–866 are
        # opaque rocky ledges above lava; their walkable tops must remain land.
        def lava(mid):return mid==863 or (mid not in (864,865,866) and any(928<=e&1023<932 for e in entries(mid)))
        def water(mid):return behavior(mid) in WATER or lava(mid)
        for name in group:
            l=layouts[maps[name]['layout']];g=words(base/l['blockdata_filepath']);w,h=l['width'],l['height'];visual=[];roles=[]
            at=lambda x,y:g[y*w+x] if 0<=x<w and 0<=y<h else None
            solid=lambda x,y:at(x,y) is not None and bool(at(x,y)&0xc00) and not water(at(x,y)&1023)
            liquid=lambda x,y:at(x,y) is not None and water(at(x,y)&1023)
            warps={(e['x'],e['y']) for e in maps[name]['warp_events']}
            for j,v in enumerate(g):
                x,y=j%w,j//w;mid=v&1023;bottom=art[f'floor{(x//3+y//3)%3}'];top=None;pal=9;role='floor'
                if water(mid):
                    is_lava=lava(mid)
                    # Preserve the static encounter staging tiles and all live
                    # animation slots: 863 stays static, the pool stays animated.
                    out=entries(mid) if mid==863 else ([928|8<<12,929|8<<12,930|8<<12,931|8<<12]+[0]*4) if is_lava else entries(334 if behavior(mid) in (0x11,0x12) else 368)
                    overlay=Image.new('L',(16,16),0);d=ImageDraw.Draw(overlay)
                    for dx,dy,rect,line in [(0,-1,(0,0,15,1),(0,2,15,2)),(1,0,(14,0,15,15),(13,0,13,15)),(0,1,(0,14,15,15),(0,13,15,13)),(-1,0,(0,0,1,15),(2,0,2,15))]:
                        if at(x+dx,y+dy) is not None and not liquid(x+dx,y+dy):
                            d.rectangle(rect,fill=3 if is_lava else 6);d.line(line,fill=15 if is_lava else 13)
                    out=out[:4]+pair.entries(overlay,11);role='lava_static' if mid==863 else 'lava' if is_lava else ('dive_water' if behavior(mid) in (0x11,0x12) else 'water')
                elif mid==515:
                    out=pair.entries(bottom,9)+pair.entries(art['outcrop'],7);role='boulder'
                elif mid==516:
                    # Keep the stair silhouette, remapped to the local mineral palette.
                    bottom=quantize(pair.reader.metatile(mid),FLOOR[family],True);out=pair.entries(bottom,9)+[0]*4;role='stairs'
                elif behavior(mid) in (0x60,0x61):
                    gate=Image.new('L',(16,16),1);d=ImageDraw.Draw(gate);d.rectangle((1,0,14,3),fill=5);d.rectangle((0,3,2,15),fill=4);d.rectangle((13,3,15,15),fill=4);d.line((3,15,12,15),fill=8)
                    out=pair.entries(gate,7)+[0]*4;role='gate'
                elif solid(x,y):
                    if not solid(x,y+1):piece='lower' if solid(x,y-1) else 'single'
                    elif not solid(x,y+2):piece='upper'
                    elif not solid(x-1,y):piece='left'
                    elif not solid(x+1,y):piece='right'
                    else:piece='cap'
                    # Large interior masses read as dark bedrock; veins belong to edges.
                    if piece=='cap' and all(solid(x+dx,y+dy) for dx,dy in ((-2,0),(2,0),(0,-2),(0,2))):
                        under=Image.new('L',(16,16),2);dd=ImageDraw.Draw(under)
                        dd.line((2,5,6,5),fill=3);dd.line((6,5,8,7),fill=3);dd.line((10,12,14,12),fill=3)
                        out=pair.entries(under,12)+[0]*4;role='bedrock'
                    else:
                        under=Image.new('L',(16,16),3 if piece=='cap' else 5)
                        out=pair.entries(under,7)+pair.entries(art[piece],12 if piece=='cap' else 7);role='rock_'+piece
                else:
                    overlay=Image.new('L',(16,16),0);d=ImageDraw.Draw(overlay)
                    for dx,dy,rect in [(0,-1,(0,0,15,1)),(1,0,(14,0,15,15)),(0,1,(0,14,15,15)),(-1,0,(0,0,1,15))]:
                        if liquid(x+dx,y+dy):d.rectangle(rect,fill=14 if family=='terra' else 10)
                    if solid(x,y-1):d.line((0,0,15,0),fill=2)
                    if (x,y) in warps:
                        d.ellipse((3,10,12,14),fill=8);d.line((5,12,10,12),fill=9);role='exit_floor'
                    out=pair.entries(bottom,pal)+pair.entries(overlay,11)
                alias=pair.alias(mid,out);visual.append(alias);roles.append(role);counter[role]+=1
            idx=node['layouts'].index(l);tables.append((name,idx,visual));binary(OUT/'visual_grids'/f'{name}.bin',visual)
            report['maps'][name]={'layout_index':idx,'cells':len(g),'visual_alias_cells':sum((v&1023)!=a for v,a in zip(g,visual)),'roles':dict(collections.Counter(roles)),'role_grid':roles,'secondary':'gTileset_Arauna'+family.title()+'Cave03A'}
            l['secondary_tileset']=report['maps'][name]['secondary']
        # The unchanged border words must draw the same dark mass as the outer cells.
        for mid in set(words(base/layouts[maps[group[0]]['layout']]['border_filepath'])):
            pair.put(mid,Image.new('L',(16,16),2),12)
        path=ROOT/f'data/tilesets/secondary/arauna_{family}_cave_03a';pair.write([pair.paths[0],path],kinds=(1,))
        symbol='Arauna'+family.title()+'Cave03A';d=declarations([ROOT/pair.paths[0].relative_to(base),path],['General',symbol],pair.callbacks)
        # declarations() returns both banks; use only the private secondary section.
        for k,body in d.items():decl[k]+=body[body.index('const '+('u32 gTilesetTiles_' if k=='graphics.h' else 'u16 gMetatiles_' if k=='metatiles.h' else 'struct Tileset gTileset_')+symbol):]
        report['banks'][family]={'path':path.relative_to(ROOT).as_posix(),'symbol':symbol,'alias_count':len(pair.alias_cache),'new_static_graphics_slots':sorted(pair.touched),'reserved_animation_slots':[432,511,928,931,992,1023],'callbacks':pair.callbacks,'roles':dict(counter),'original_native_used_ids':sorted({v&1023 for n in group for v in words(base/layouts[maps[n]['layout']]['blockdata_filepath'])}),'border_ids':[753]}
    for k,body in decl.items():marked(ROOT/'src/data/tilesets'/k,'CAVERNAS_03A',body)
    dump(ROOT/'data/layouts/layouts.json',node)
    header=(base/'src/data/arauna_cave_visuals_v2.h').read_text()
    definitions=''.join(f'static const u16 sVisual_{n}[] = INCBIN_U16("review/cavernas_03a/visual_grids/{n}.bin");\n' for n,idx,g in tables)
    header=header.replace('static const struct CaveVisualGrid sCaveVisualGrids[] =',definitions+'static const struct CaveVisualGrid sCaveVisualGrids[] =')
    pos=header.rfind('};');header=header[:pos]+''.join(f'    {{{idx}, sVisual_{n}}}, // {n} checkpoint 03A\n' for n,idx,g in tables)+header[pos:]
    header='/* Generated by build_cavernas_03a.py; existing V2 entries preserved. */\n'+header
    (ROOT/'src/data/arauna_cave_visuals_v2.h').write_text(header)
    dump(OUT/'build.json',report)
    print(json.dumps({'maps':len(tables),'banks':{f:{k:v for k,v in b.items() if k in ('alias_count','new_static_graphics_slots')} for f,b in report['banks'].items()}},indent=2))

if __name__=='__main__':main()
