/* Generated by build_grutas_v2.py. Camera IDs only. */
static const u16 sVisual_VictoryRoad_1F[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/VictoryRoad_1F.bin");
static const u16 sVisual_VictoryRoad_B1F[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/VictoryRoad_B1F.bin");
static const u16 sVisual_VictoryRoad_B2F[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/VictoryRoad_B2F.bin");
static const u16 sVisual_SeafloorCavern_Entrance[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Entrance.bin");
static const u16 sVisual_SeafloorCavern_Room1[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room1.bin");
static const u16 sVisual_SeafloorCavern_Room2[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room2.bin");
static const u16 sVisual_SeafloorCavern_Room3[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room3.bin");
static const u16 sVisual_SeafloorCavern_Room4[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room4.bin");
static const u16 sVisual_SeafloorCavern_Room5[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room5.bin");
static const u16 sVisual_SeafloorCavern_Room6[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room6.bin");
static const u16 sVisual_SeafloorCavern_Room7[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room7.bin");
static const u16 sVisual_SeafloorCavern_Room8[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room8.bin");
static const u16 sVisual_SeafloorCavern_Room9[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room9.bin");
static const u16 sVisual_Route114_LanettesHouse[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/Route114_LanettesHouse.bin");
static const struct CaveVisualGrid sCaveVisualGrids[] =
{
    {162, sVisual_VictoryRoad_1F}, // VictoryRoad_1F
    {284, sVisual_VictoryRoad_B1F}, // VictoryRoad_B1F
    {285, sVisual_VictoryRoad_B2F}, // VictoryRoad_B2F
    {146, sVisual_SeafloorCavern_Entrance}, // SeafloorCavern_Entrance
    {147, sVisual_SeafloorCavern_Room1}, // SeafloorCavern_Room1
    {148, sVisual_SeafloorCavern_Room2}, // SeafloorCavern_Room2
    {149, sVisual_SeafloorCavern_Room3}, // SeafloorCavern_Room3
    {150, sVisual_SeafloorCavern_Room4}, // SeafloorCavern_Room4
    {151, sVisual_SeafloorCavern_Room5}, // SeafloorCavern_Room5
    {152, sVisual_SeafloorCavern_Room6}, // SeafloorCavern_Room6
    {153, sVisual_SeafloorCavern_Room7}, // SeafloorCavern_Room7
    {154, sVisual_SeafloorCavern_Room8}, // SeafloorCavern_Room8
    {155, sVisual_SeafloorCavern_Room9}, // SeafloorCavern_Room9
    {120, sVisual_Route114_LanettesHouse}, // Route114_LanettesHouse
};
