/* Generated by build_campanha_grutas_v1.py. */
extern const struct Tileset gTileset_AraunaGrutasSeafloorBaseV1;
extern const struct Tileset gTileset_AraunaGrutasSeafloorRochaV1;
extern const struct Tileset gTileset_AraunaGrutasSeafloorCorrentesV1;
extern const struct Tileset gTileset_AraunaGrutasVictoryBaseV1;
extern const struct Tileset gTileset_AraunaGrutasVictoryRochaV1;
extern const struct Tileset gTileset_AraunaRotaTunelV1;
static u16 AraunaGrutas_NormalizeSavedBlock(u16 block)
{
    u16 mid = block & 0x03FF;
    const struct Tileset *bank = mid < 512 ? gMapHeader.mapLayout->primaryTileset : gMapHeader.mapLayout->secondaryTileset;
    if (bank == &gTileset_AraunaRotaTunelV1 && !(block & 0x0C00) && mid == 0x279)
        return (block & 0xFC00) | 0x303;
    if (!(block & 0x0C00))
        return block;
    if (bank == &gTileset_AraunaGrutasSeafloorRochaV1)
    {
        switch (mid)
        {
        case 529: return (block & 0xFC00) | 583;
        case 547: return (block & 0xFC00) | 545;
        case 753: return (block & 0xFC00) | 580;
        case 788: return (block & 0xFC00) | 514;
        default: break;
        }
    }
    if (bank == &gTileset_AraunaGrutasSeafloorCorrentesV1)
    {
        switch (mid)
        {
        case 633: return (block & 0xFC00) | 701;
        case 638: return (block & 0xFC00) | 715;
        default: break;
        }
    }
    if (bank == &gTileset_AraunaGrutasVictoryRochaV1)
    {
        switch (mid)
        {
        case 529: return (block & 0xFC00) | 583;
        case 547: return (block & 0xFC00) | 545;
        default: break;
        }
    }
    return block;
}
