/* Generated by build_cavernas_03a.py; existing V2 entries preserved. */
/* Generated by build_grutas_v2.py. Camera IDs only. */
static const u16 sVisual_VictoryRoad_1F[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/VictoryRoad_1F.bin");
static const u16 sVisual_VictoryRoad_B1F[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/VictoryRoad_B1F.bin");
static const u16 sVisual_VictoryRoad_B2F[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/VictoryRoad_B2F.bin");
static const u16 sVisual_SeafloorCavern_Entrance[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Entrance.bin");
static const u16 sVisual_SeafloorCavern_Room1[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room1.bin");
static const u16 sVisual_SeafloorCavern_Room2[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room2.bin");
static const u16 sVisual_SeafloorCavern_Room3[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room3.bin");
static const u16 sVisual_SeafloorCavern_Room4[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room4.bin");
static const u16 sVisual_SeafloorCavern_Room5[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room5.bin");
static const u16 sVisual_SeafloorCavern_Room6[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room6.bin");
static const u16 sVisual_SeafloorCavern_Room7[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room7.bin");
static const u16 sVisual_SeafloorCavern_Room8[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room8.bin");
static const u16 sVisual_SeafloorCavern_Room9[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/SeafloorCavern_Room9.bin");
static const u16 sVisual_Route114_LanettesHouse[] = INCBIN_U16("review/grutas_bordas_v2/visual_grids/Route114_LanettesHouse.bin");
static const u16 sVisual_TerraCave_Entrance[] = INCBIN_U16("review/cavernas_03a/visual_grids/TerraCave_Entrance.bin");
static const u16 sVisual_TerraCave_End[] = INCBIN_U16("review/cavernas_03a/visual_grids/TerraCave_End.bin");
static const u16 sVisual_MarineCave_Entrance[] = INCBIN_U16("review/cavernas_03a/visual_grids/MarineCave_Entrance.bin");
static const u16 sVisual_MarineCave_End[] = INCBIN_U16("review/cavernas_03a/visual_grids/MarineCave_End.bin");
static const u16 sVisual_SealedChamber_OuterRoom[] = INCBIN_U16("review/cavernas_03c/03b_v11_visual_grids/SealedChamber_OuterRoom.bin");
static const u16 sVisual_SealedChamber_InnerRoom[] = INCBIN_U16("review/cavernas_03c/03b_v11_visual_grids/SealedChamber_InnerRoom.bin");
static const u16 sVisual_AncientTomb[] = INCBIN_U16("review/cavernas_03c/03b_v11_visual_grids/AncientTomb.bin");
static const u16 sVisual_IslandCave[] = INCBIN_U16("review/cavernas_03c/03b_v11_visual_grids/IslandCave.bin");
static const u16 sVisual_AlteringCave[] = INCBIN_U16("review/cavernas_03c/visual_grids/AlteringCave.bin");
static const u16 sVisual_ArtisanCave_B1F[] = INCBIN_U16("review/cavernas_03c/visual_grids/ArtisanCave_B1F.bin");
static const u16 sVisual_ArtisanCave_1F[] = INCBIN_U16("review/cavernas_03c/visual_grids/ArtisanCave_1F.bin");
static const u16 sVisual_Underwater_Route105[] = INCBIN_U16("review/dive_04/visual_grids/Underwater_Route105.bin");
static const u16 sVisual_Underwater_Route124[] = INCBIN_U16("review/dive_04/visual_grids/Underwater_Route124.bin");
static const u16 sVisual_Underwater_Route126[] = INCBIN_U16("review/dive_04/visual_grids/Underwater_Route126.bin");
static const u16 sVisual_Underwater_SootopolisCity[] = INCBIN_U16("review/dive_04/visual_grids/Underwater_SootopolisCity.bin");
static const u16 sVisual_Underwater_Route125[] = INCBIN_U16("review/dive_04/visual_grids/Underwater_Route125.bin");
static const u16 sVisual_Underwater_MarineCave[] = INCBIN_U16("review/dive_04/visual_grids/Underwater_MarineCave.bin");
static const u16 sVisual_Underwater_Route127[] = INCBIN_U16("review/dive_04/visual_grids/Underwater_Route127.bin");
static const u16 sVisual_Underwater_Route128[] = INCBIN_U16("review/dive_04/visual_grids/Underwater_Route128.bin");
static const u16 sVisual_Underwater_Route129[] = INCBIN_U16("review/dive_04/visual_grids/Underwater_Route129.bin");
static const u16 sVisual_Underwater_Route134[] = INCBIN_U16("review/dive_04/visual_grids/Underwater_Route134.bin");
static const u16 sVisual_Underwater_SealedChamber[] = INCBIN_U16("review/dive_04/visual_grids/Underwater_SealedChamber.bin");
static const u16 sVisual_Underwater_SeafloorCavern[] = INCBIN_U16("review/dive_04/visual_grids/Underwater_SeafloorCavern.bin");
static const struct CaveVisualGrid sCaveVisualGrids[] =
{
    {162, sVisual_VictoryRoad_1F}, // VictoryRoad_1F
    {284, sVisual_VictoryRoad_B1F}, // VictoryRoad_B1F
    {285, sVisual_VictoryRoad_B2F}, // VictoryRoad_B2F
    {146, sVisual_SeafloorCavern_Entrance}, // SeafloorCavern_Entrance
    {147, sVisual_SeafloorCavern_Room1}, // SeafloorCavern_Room1
    {148, sVisual_SeafloorCavern_Room2}, // SeafloorCavern_Room2
    {149, sVisual_SeafloorCavern_Room3}, // SeafloorCavern_Room3
    {150, sVisual_SeafloorCavern_Room4}, // SeafloorCavern_Room4
    {151, sVisual_SeafloorCavern_Room5}, // SeafloorCavern_Room5
    {152, sVisual_SeafloorCavern_Room6}, // SeafloorCavern_Room6
    {153, sVisual_SeafloorCavern_Room7}, // SeafloorCavern_Room7
    {154, sVisual_SeafloorCavern_Room8}, // SeafloorCavern_Room8
    {155, sVisual_SeafloorCavern_Room9}, // SeafloorCavern_Room9
    {120, sVisual_Route114_LanettesHouse}, // Route114_LanettesHouse
    {407, sVisual_TerraCave_Entrance}, // TerraCave_Entrance checkpoint 03A
    {408, sVisual_TerraCave_End}, // TerraCave_End checkpoint 03A
    {406, sVisual_MarineCave_Entrance}, // MarineCave_Entrance checkpoint 03A
    {412, sVisual_MarineCave_End}, // MarineCave_End checkpoint 03A
    {283, sVisual_SealedChamber_OuterRoom}, // SealedChamber_OuterRoom checkpoint 03B
    {303, sVisual_SealedChamber_InnerRoom}, // SealedChamber_InnerRoom checkpoint 03B
    {280, sVisual_AncientTomb}, // AncientTomb checkpoint 03B
    {279, sVisual_IslandCave}, // IslandCave checkpoint 03B
    {419, sVisual_AlteringCave}, // AlteringCave checkpoint 03C
    {399, sVisual_ArtisanCave_B1F}, // ArtisanCave_B1F checkpoint 03C
    {400, sVisual_ArtisanCave_1F}, // ArtisanCave_1F checkpoint 03C
    {409, sVisual_Underwater_Route105}, // Dive checkpoint 04
    {273, sVisual_Underwater_Route124}, // Dive checkpoint 04
    {50, sVisual_Underwater_Route126}, // Dive checkpoint 04
    {129, sVisual_Underwater_SootopolisCity}, // Dive checkpoint 04
    {410, sVisual_Underwater_Route125}, // Dive checkpoint 04
    {405, sVisual_Underwater_MarineCave}, // Dive checkpoint 04
    {51, sVisual_Underwater_Route127}, // Dive checkpoint 04
    {52, sVisual_Underwater_Route128}, // Dive checkpoint 04
    {411, sVisual_Underwater_Route129}, // Dive checkpoint 04
    {281, sVisual_Underwater_Route134}, // Dive checkpoint 04
    {282, sVisual_Underwater_SealedChamber}, // Dive checkpoint 04
    {145, sVisual_Underwater_SeafloorCavern}, // Dive checkpoint 04
};
